Repository JohnSnowLabs/spark-nlp, pull requests merged in 2018-02, with the labels that each got.

#117 Fixed NERCRF not working when not using word embeddings
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ApproachWithWordEmbeddings.scala
Labels: bug-fix

#116 Improved pyspark ExternalResource API easier to use
  python/example/crf-ner/ner.ipynb
  python/example/dictionary-sentiment/sentiment.ipynb
  python/example/entities-extractor/extractor.ipynb
  python/example/logreg-assertion/assertion.ipynb
  python/example/vivekn-sentiment/sentiment.ipynb
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
Labels: enhancement

#104 Pretrained models
  build.sbt
  python/example/model-downloader/ModelDownloaderExample.ipynb
  python/pretrained/en/models.py
  python/pretrained/en/pipelines.py
  python/sparknlp/annotator.py
  python/sparknlp/base.py
  python/sparknlp/internal.py
  python/sparknlp/pretrained.py
  src/main/resources/application.conf
  src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
  src/main/scala/com/johnsnowlabs/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/pretrained/ResourceMetadata.scala
  src/main/scala/com/johnsnowlabs/pretrained/S3ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/pretrained/TrainingModels.scala
  src/main/scala/com/johnsnowlabs/pretrained/en/Models.scala
  src/main/scala/com/johnsnowlabs/pretrained/en/Pipelines.scala
  src/main/scala/com/johnsnowlabs/util/Build.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
  src/main/scala/com/johnsnowlabs/util/PipelineModels.scala
  src/main/scala/com/johnsnowlabs/util/Version.scala
  src/main/scala/com/johnsnowlabs/util/ZipArchiveUtil.scala
  src/test/scala/com/johnsnowlabs/ml/crf/CoNLL2003CrfTest.scala
  src/test/scala/com/johnsnowlabs/pretrained/ModelDownloadSpec.scala
  src/test/scala/com/johnsnowlabs/pretrained/PipelineDownloadSpec.scala
  src/test/scala/com/johnsnowlabs/pretrained/ResourceDownloaderSpec.scala
  src/test/scala/com/johnsnowlabs/pretrained/S3TestResources.scala
  src/test/scala/com/johnsnowlabs/util/TrainingModelsScript.scala
  src/test/scala/com/johnsnowlabs/util/VersionSpec.scala
Labels: New Feature
