Repository JohnSnowLabs/spark-nlp, pull requests merged in 2019-06, with the labels that each got.

#530 Fixed kryo and cluster nerdl support
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/PretrainedPipeline.scala
Labels: bug-fix

#544 Added Google Colab notebook setup in README
  README.md
Labels: documentation

#554 Adding support for NerDLApproach evaluation during training
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
Labels: enhancement
