Repository JohnSnowLabs/spark-nlp, pull requests merged in 2019-12, with the labels that each got.

#702 Date matcher fix flexible dates
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
Labels: enhancement

#709 minor edits to quickstart
  docs/en/quickstart.md
Labels: documentation, enhancement

#718 Fixed a fake group match scenario
  src/main/scala/com/johnsnowlabs/nlp/util/regex/RuleFactory.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
Labels: bug-fix

#716 minor readme spelling fixes
  README.md
Labels: documentation, enhancement

#719 Move import to top level to avoid import fail
  python/sparknlp/functions.py
Labels: bug-fix

#705 Delimiter param for NGramGenerator
  docs/en/annotators.md
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/NGramGenerator.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/NGramGeneratorTestSpec.scala
Labels: enhancement, new-feature

#708 SkipOOV parameter for ChunkEmbeddings
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
Labels: enhancement, new-feature

#711 Introducing minLength and maxLength features in Tokenizer
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: enhancement, new-feature

#712 Introducing minLength and maxLength features in SentenceDetector
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/SentenceDetectorParams.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetector.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticDetectionBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetectorBoundsSpec.scala
Labels: enhancement, new-feature

#717 Text Matcher Trie on Fit
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
Labels: enhancement

#720 Upgrade TensorFlow 1.12.0 to 1.13.1
  build.sbt
  python/tensorflow/bert/create_bert.ipynb
  python/tensorflow/lib/bert/CONTRIBUTING.md
  python/tensorflow/lib/bert/LICENSE
  python/tensorflow/lib/bert/README.md
  python/tensorflow/lib/bert/__init__.py
  python/tensorflow/lib/bert/create_pretraining_data.py
  python/tensorflow/lib/bert/extract_features.py
  python/tensorflow/lib/bert/modeling.py
  python/tensorflow/lib/bert/modeling_test.py
  python/tensorflow/lib/bert/multilingual.md
  python/tensorflow/lib/bert/optimization.py
  python/tensorflow/lib/bert/optimization_test.py
  python/tensorflow/lib/bert/requirements.txt
  python/tensorflow/lib/bert/run_classifier.py
  python/tensorflow/lib/bert/run_pretraining.py
  python/tensorflow/lib/bert/run_squad.py
  python/tensorflow/lib/bert/sample_text.txt
  python/tensorflow/lib/bert/tokenization.py
  python/tensorflow/lib/bert/tokenization_test.py
  python/tensorflow/lib/ner/dataset_encoder.py
  python/tensorflow/lib/ner/embeddings_resolver.py
  python/tensorflow/lib/ner/ner_model.py
  python/tensorflow/lib/ner/ner_model_saver.py
  python/tensorflow/lib/ner/sentence_grouper.py
  python/tensorflow/ner/create_models.ipynb
  src/main/resources/ner-dl/linux/_lstm_ops.so
  src/main/resources/ner-dl/linux/_sparse_feature_cross_op.so
  src/main/resources/ner-dl/mac/_lstm_ops.so
  src/main/resources/ner-dl/mac/_sparse_feature_cross_op.so
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
Labels: enhancement

#722 Introducing UniversalSentenceEncoder annotator for sentence embeddings by using TF Hub Models
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSerializeModel.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowUSE.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
  src/test/resources/embeddings/sentence_embeddings_use.csv
  src/test/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoderTestSpec.scala
Labels: new-feature

#714 [WIP, BREAKING]Reusable rocksdb redesign
  python/sparknlp/annotator.py
  python/sparknlp/common.py
  python/sparknlp/embeddings.py
  python/sparknlp/internal.py
  python/sparknlp/pretrained.py
  python/sparknlp/storage.py
  src/main/resources/application.conf
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/FeatureGenerator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLPythonReader.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsFormat.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsHelper.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/EmbeddingsReadable.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/HasEmbeddingsProperties.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/HasWordEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RocksDbIndexer.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsFormat.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsIndexer.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsLoader.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsReader.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsRetriever.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsWriter.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/PretrainedPipeline.scala
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLL2003NerReader.scala
  src/main/scala/com/johnsnowlabs/storage/HasStorage.scala
  src/main/scala/com/johnsnowlabs/storage/HasStorageModel.scala
  src/main/scala/com/johnsnowlabs/storage/RocksDBConnection.scala
  src/main/scala/com/johnsnowlabs/storage/StorageFormat.scala
  src/main/scala/com/johnsnowlabs/storage/StorageHelper.scala
  src/main/scala/com/johnsnowlabs/storage/StorageLoader.scala
  src/main/scala/com/johnsnowlabs/storage/StorageReadable.scala
  src/main/scala/com/johnsnowlabs/storage/StorageReader.scala
  src/main/scala/com/johnsnowlabs/storage/StorageWriter.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
  src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java
  src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerCrfCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/benchmarks/spark/NerCrfCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
  src/test/scala/com/johnsnowlabs/nlp/FinisherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerPerfTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfCustomCase.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLReader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsTestSpec.scala
Labels: new-feature
