Repository JohnSnowLabs/spark-nlp, pull requests merged in 2019-11, with the labels that each got.

#671 Fix missing EmbeddingsFinisher in Scala and Python
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/EmbeddingsFinisher.scala
  src/main/scala/com/johnsnowlabs/nlp/base.scala
Labels: bug-fix

#672 Reverted embeddings move to copy due to crc issue
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
Labels: bug-fix

#673 Fix IndexOutOfBoundsException in SentenceEmbeddings
  src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/EmbeddingsFinisherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala
Labels: bug-fix

#675 232 release candidate
  CHANGELOG
  README.md
  build.sbt
  python/run-tests.py
  python/setup.py
  python/sparknlp/__init__.py
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/nlp/EmbeddingsFinisher.scala
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/base.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ClusterWordEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
  src/main/scala/com/johnsnowlabs/util/Build.scala
  src/test/scala/com/johnsnowlabs/nlp/EmbeddingsFinisherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala
Labels: bug-fix, enhancement

#677 Make ChunkEmbeddings output to be compatible with SentenceEmbeddings
  src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
  src/main/scala/com/johnsnowlabs/nlp/AnnotatorType.scala
  src/main/scala/com/johnsnowlabs/nlp/EmbeddingsFinisher.scala
  src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
Labels: bug-fix

#683 Fixed two typos. closes #682
  docs/en/models.md
  docs/en/quickstart.md
Labels: documentation

#681 Keep original index for the sentence-token columns pair
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/EmbeddingsWithSentence.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceWithEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/TokenizedWithSentence.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala
Labels: bug-fix

#680 Text matcher overlapping
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
Labels: enhancement

#697 Chunk embeddings ref fix
  build.sbt
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
Labels: enhancement
