Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-05, with the labels that each got.

#884 Introducing new outputLogsPath for NerDLApproach and ClassifierDLApproach
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/Logging.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
  src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
Labels: enhancement, new-feature

#890 Annotator log file Fix for DBFS
  src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
Labels: bug-fix, enhancement

#888 Introducing new SentimentDL annotator
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSentiment.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLModel.scala
Labels: new-feature

#886 Add PubTator Reader (and fix CoNLLGenerator)
  docs/en/training.md
  src/main/scala/com/johnsnowlabs/nlp/training/PubTator.scala
  src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala
  src/test/resources/corpus_pubtator_sample.txt
  src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/util/PubTatorTestSpec.scala
Labels: enhancement, new-feature

#872 Docs licensed update
  docs/Gemfile.lock
  docs/_data/navigation.yml
  docs/_includes/article-footer.html
  docs/en/annotators.md
  docs/en/auxiliary.md
  docs/en/concepts.md
  docs/en/evaluation.md
  docs/en/licensed_annotators.md
  docs/en/licensed_install.md
  docs/en/licensed_models.md
  docs/en/licensed_release_notes.md
  docs/en/ocr.md
  docs/en/ocr_pipeline_components.md
  docs/en/training.md
  docs/en/transformers.md
Labels: documentation

#880 add whl generation instruction to the dev section
  docs/en/developers.md
Labels: documentation

#889 Introducing a new Context Spell Checker annotator
  python/sparknlp/__init__.py
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSpell.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/RecursiveTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/RecursiveTokenizerModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/HasTransducerFeatures.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/WeightedLevenshtein.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/parser/SpecialTokensParser.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/resources/dist.psv
  src/test/resources/distance.psv
  src/test/resources/test.txt
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
Labels: new-feature

#893 Lemmatizer should not crash in case of bad input
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
Labels: bug-fix, enhancement

#894 Add default pretrained model to ContextSpellCheckerModel
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
Labels: enhancement

#897 add python ans scala tests for XlnetEmbeddings
  python/run-tests.py
  python/test/annotators.py
  src/test/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddingsTestSpec.scala
Labels: enhancement

#899 Spellchecker dl tests
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/SpellCheckersPerfTest.scala
Labels: enhancement

#900 Added tests for the SentimentDLTestSpec for python
  python/run-tests.py
  python/test/annotators.py
Labels: enhancement

#901 add new PubTator reader to python
  python/sparknlp/training.py
Labels: new-feature

#902 Updated documentation for new features in the 2.5.0 release
  docs/en/annotators.md
  docs/en/licensed_annotators.md
  docs/en/transformers.md
Labels: documentation

#907 Ocr documentation update130
  docs/en/ocr.md
  docs/en/ocr_install.md
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
  docs/en/ocr_structures.md
Labels: documentation
