Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-07, with the labels that each got.

#961 Context spell checker fix
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
Labels: bug-fix

#969 Add pretrained support to StopWordsCleaner annotator
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/StopWordsCleaner.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/StopWordsCleanerTestSpec.scala
Labels: new-feature

#967 Fix ModuleNotFoundError in LanguageDetectorDL pipelines
  python/sparknlp/__init__.py
Labels: bug-fix

#968 Add missing dll for SentencePiece used by Albert and Xlnet
  src/main/resources/sentencepiece/sentencepiece_jni.dll
Labels: bug-fix

#957 Add support for Apache Spark 2.3.x
  .ci/DockerfileSpark24
  .travis.yml
  build.sbt
  python/sparknlp/__init__.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java
  src/test/scala/com/johnsnowlabs/nlp/AnnotatorBaseTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
  src/test/scala/com/johnsnowlabs/nlp/ContentProvider.scala
  src/test/scala/com/johnsnowlabs/nlp/DataBuilder.scala
  src/test/scala/com/johnsnowlabs/nlp/EmbeddingsFinisherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/FinisherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/FunctionsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ChunkTokenizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/LemmatizerBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/LemmatizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/NGramGeneratorTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/NormalizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/StemmerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyModelTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproachBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/PragmaticSentimentTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/CloudTestResources.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala
  src/test/scala/com/johnsnowlabs/util/VersionSpec.scala
Labels: new-feature, on-hold

#972 Introducing RegexTokenizer annotator
  .github/workflows/scala.yml
  docs/en/release_notes.md
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: new-feature

#976 Spark OCR 1.5.0 release update
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
Labels: documentation

#975 Fix a bug in RegexTokenizer on Python side
  python/sparknlp/annotator.py
Labels: bug-fix

#978 Fix StopWordsCleaner exception in Python when pretrained() is used
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
Labels: bug-fix

#984 Update articles.md
  docs/articles.md
Labels: documentation
