Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-04, with the labels that each got.

#834 Fix java.io.UTFDataFormatException in cluster-mode and some Databricks runtime versions
  src/main/scala/com/johnsnowlabs/nlp/serialization/Feature.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
Labels: bug-fix

#829 Fix ClassifierDL in Python
  python/sparknlp/__init__.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
Labels: bug-fix, enhancement

#839 Update README.md
  README.md
  docs/articles.md
  docs/en/models.md
  docs/en/pipelines.md
  docs/index.md
Labels: documentation

#845 Revert reset index
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/doc_improvement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  docs/en/annotators.md
  src/main/scala/com/johnsnowlabs/nlp/annotators/NormalizerModel.scala
Labels: bug-fix, enhancement

#835 splitPattern alternative for Tokenizers
  src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: enhancement

#838 Splitpattern and splitchars patch
  python/sparknlp/annotator.py
  python/sparknlp/functions.py
  python/tensorflow/ner/create_models.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: enhancement

#849 OCR 1.2.0 release doc update
  docs/_data/navigation.yml
  docs/assets/images/ocr/showImage.png
  docs/en/ocr.md
  docs/en/ocr_install.md
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
  docs/en/ocr_structures.md
Labels: documentation

#866 docs changes in licensed
  docs/en/install.md
  docs/en/licensed_annotators.md
  docs/en/licensed_install.md
  docs/en/licensed_models.md
  docs/en/quickstart.md
Labels: documentation

#848 Introducing AlbertEmbeddings annotator
  src/main/resources/sentencepiece/libsentencepiece_jni.dylib
  src/main/resources/sentencepiece/libsentencepiece_jni.so
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/NativeLibLoader.java
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencePieceException.java
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencePieceJNI.java
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencePieceProcessor.java
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencePieceWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
Labels: new-feature

#852 Updated test case for pipelineWithoutNormalize
  src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
Labels: enhancement

#855 Refactor + Test CoNLLGenerator
  src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala
  src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala
Labels: enhancement, new-feature

#859 Simple tokenizer small improvements
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/SimpleTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/SimpleTokenizerModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/TokenParser.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: enhancement

#864 Removing unused param in NerDLModel
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
Labels: enhancement

#867 Token assembler should preserve the new lines from DocumentAssembler
  python/sparknlp/base.py
  src/main/scala/com/johnsnowlabs/nlp/TokenAssembler.scala
  src/test/scala/com/johnsnowlabs/nlp/TokenAssemblerTestSpec.scala
Labels: enhancement, new-feature

#875 Add AlbertEmbeddings to Python
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala
Labels: new-feature
