Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-12, with the labels that each got.

#1217 [skip ci] 2020-11-30-pos_ud_padt_ar
  README.md
  docs/_posts/HashamUlHaq/2020-11-30-pos_ud_padt_ar.md
Labels: new model

#1222 [skip ci] 2020-12-01-urduvec_140M_300d_ur
  docs/_posts/HashamUlHaq/2020-12-01-urduvec_140M_300d_ur.md
Labels: new model

#1223 [skip ci] 2020-12-01-uner_mk_140M_300d_ur
  docs/_posts/HashamUlHaq/2020-12-01-uner_mk_140M_300d_ur.md
Labels: new model

#1224 [skip ci] 2020-12-01-sentimentdl_urduvec_imdb_ur
  docs/_posts/HashamUlHaq/2020-12-01-sentimentdl_urduvec_imdb_ur.md
Labels: new model

#1231 Upgrade to the latest Apache Spark 2.4.x release
  build.sbt
Labels: enhancement

#1233 Merge latest models to Models hub
  docs/_posts/HashamUlHaq/2020-11-28-lemma_ar.md
  docs/_posts/HashamUlHaq/2020-11-28-lemma_et.md
  docs/_posts/HashamUlHaq/2020-11-28-lemma_fa.md
  docs/_posts/HashamUlHaq/2020-11-28-lemma_ur.md
  docs/_posts/HashamUlHaq/2020-11-30-pos_ud_edt_et.md
  docs/_posts/HashamUlHaq/2020-11-30-pos_ud_padt_ar.md
  docs/_posts/HashamUlHaq/2020-11-30-pos_ud_perdt_fa.md
  docs/_posts/HashamUlHaq/2020-11-30-pos_ud_udtb_ur.md
  docs/_posts/HashamUlHaq/2020-12-01-sentimentdl_urduvec_imdb_ur.md
  docs/_posts/HashamUlHaq/2020-12-01-uner_mk_140M_300d_ur.md
  docs/_posts/HashamUlHaq/2020-12-01-urduvec_140M_300d_ur.md
Labels: new model

#1236 [skip ci] 2020-12-05-persian_w2v_cc_300d_fa
  docs/_posts/HashamUlHaq/2020-12-05-persian_w2v_cc_300d_fa.md
Labels: new model

#1235 [skip ci] 2020-12-05-arabic_w2v_cc_300d_ar
  docs/_posts/HashamUlHaq/2020-12-05-arabic_w2v_cc_300d_ar.md
Labels: new model

#1184 Introducing a new DocumentNormalizer annotator
  docs/en/annotators.md
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentNormalizer.scala
  src/test/resources/doc-normalizer/html-docs/sample0.html
  src/test/resources/doc-normalizer/html-docs/sample1.html
  src/test/resources/doc-normalizer/html-docs/sample2.html
  src/test/resources/doc-normalizer/json-docs/sample0.json
  src/test/resources/doc-normalizer/xml-docs/C-CDAsample.xml
  src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentNormalizerBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentNormalizerTestSpec.scala
Labels: new-feature

#1237 [skip ci] 2020-12-05-aner_cc_300d_ar
  docs/_posts/HashamUlHaq/2020-12-05-aner_cc_300d_ar.md
Labels: new model

#1238 [skip ci] 2020-12-05-ld_wiki_tatoeba_cnn_21_xx
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_21_xx.md
Labels: new model

#1239 Models hub
  docs/_posts/HashamUlHaq/2020-12-05-aner_cc_300d_ar.md
  docs/_posts/HashamUlHaq/2020-12-05-arabic_w2v_cc_300d_ar.md
  docs/_posts/HashamUlHaq/2020-12-05-persian_w2v_cc_300d_fa.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_21_xx.md
Labels: new model

#1240 [skip ci] 2020-12-05-detect_language_21_xx
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_21_xx.md
Labels: new model

#1241 [skip ci] 2020-12-05-ld_tatoeba_bigru_21_xx
  docs/_posts/maziyarpanahi/2020-12-05-ld_tatoeba_bigru_21_xx.md
Labels: new model

#1242 [skip ci] 2020-12-05-ld_tatoeba_cnn_99_xx
  docs/_posts/maziyarpanahi/2020-12-05-ld_tatoeba_cnn_99_xx.md
Labels: new model

#1243 [skip ci] 2020-12-05-ld_wiki_cnn_231_xx
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_cnn_231_xx.md
Labels: new model

#1244 [skip ci] 2020-12-05-ld_wiki_tatoeba_cnn_43_xx
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_43_xx.md
Labels: new model

#1245 [skip ci] 2020-12-05-ld_wiki_tatoeba_cnn_95_xx
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_95_xx.md
Labels: new model

#1246 [skip ci] 2020-12-05-ld_wiki_tatoeba_cnn_220_xx
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_220_xx.md
Labels: new model

#1247 [skip ci] 2020-12-05-ld_wiki_tatoeba_cnn_375_xx
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_375_xx.md
Labels: new model

#1248 [skip ci] 2020-12-05-detect_language_43_xx
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_43_xx.md
Labels: new model

#1249 [skip ci] 2020-12-05-detect_language_95_xx
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_95_xx.md
Labels: new model

#1250 [skip ci] 2020-12-05-detect_language_99_xx
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_99_xx.md
Labels: new model

#1251 [skip ci] 2020-12-05-detect_language_220_xx
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_220_xx.md
Labels: new model

#1252 [skip ci] 2020-12-05-detect_language_231_xx
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_231_xx.md
Labels: new model

#1253 [skip ci] 2020-12-05-detect_language_375_xx
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_375_xx.md
Labels: new model

#1254 [skip ci] 2020-12-05-detect_language_bigru_21_xx
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_bigru_21_xx.md
Labels: new model

#1255 Models hub
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_21_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_220_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_231_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_375_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_43_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_95_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_99_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_bigru_21_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_tatoeba_bigru_21_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_tatoeba_cnn_99_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_cnn_231_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_220_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_375_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_43_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_95_xx.md
Labels: models_hub

#1256 [skip ci] 2020-12-05-onto_bert_base_cased_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_bert_base_cased_en.md
Labels: new model

#1258 [skip ci] 2020-12-05-onto_bert_large_cased_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_bert_large_cased_en.md
Labels: new model

#1259 [skip ci] 2020-12-05-onto_electra_small_uncased_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_electra_small_uncased_en.md
Labels: new model

#1260 [skip ci] 2020-12-05-onto_electra_large_uncased_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_electra_large_uncased_en.md
Labels: new model

#1261 [skip ci] 2020-12-05-onto_electra_small_uncased_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_electra_small_uncased_en.md
Labels: new model

#1262 [skip ci] 2020-12-05-onto_small_bert_L2_128_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L2_128_en.md
Labels: new model

#1263 [skip ci] 2020-12-05-onto_small_bert_L4_256_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L4_256_en.md
Labels: new model

#1264 [skip ci] 2020-12-05-onto_small_bert_L4_512_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L4_512_en.md
Labels: new model

#1265 [skip ci] 2020-12-05-onto_small_bert_L8_512_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L8_512_en.md
Labels: new model

#1268 [skip ci] 2020-12-05-onto_electra_small_uncased_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_electra_small_uncased_en.md
Labels: new model

#1269 [skip ci] 2020-12-05-onto_electra_base_uncased_en
  docs/_posts/maziyarpanahi/2020-12-05-onto_electra_base_uncased_en.md
Labels: new model

#1232 Fix the known issues in ClassifierDL, SentimentDL, and MultiClassifierDL
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
Labels: bug-fix, enhancement

#1275 [skip ci] 2020-12-07-personer_cc_300d_fa
  docs/_posts/HashamUlHaq/2020-12-07-personer_cc_300d_fa.md
Labels: new model

#1277 Models hub
  docs/_posts/HashamUlHaq/2020-12-07-personer_cc_300d_fa.md
Labels: models_hub

#1285 [skip ci] 2020-12-08-tfhub_use_multi_xx
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_multi_xx.md
Labels: new model

#1284 [skip ci] 2020-12-08-ner_posology_greedy_en
  docs/_posts/HashamUlHaq/2020-12-08-ner_posology_greedy_en.md
Labels: new model

#1283 [skip ci] 2020-12-08-ner_drugs_greedy_en
  docs/_posts/HashamUlHaq/2020-12-08-ner_drugs_greedy_en.md
Labels: new model

#1288 [skip ci] 2020-12-08-tfhub_use_multi_lg_xx
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_multi_lg_xx.md
Labels: new model

#1289 [skip ci] 2020-12-08-tfhub_use_xling_en_de_xx
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_de_xx.md
Labels: new model

#1290 [skip ci] 2020-12-08-tfhub_use_xling_en_es_xx
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_es_xx.md
Labels: new model

#1291 [skip ci] 2020-12-08-tfhub_use_xling_en_fr_xx
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_fr_xx.md
Labels: new model

#1292 [skip ci] 2020-12-08-tfhub_use_xling_many_xx
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_many_xx.md
Labels: new model

#1273 Introducing new UniversalSentenceEncoder multi-lingual models
  .github/workflows/build_and_test.yml
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  src/main/resources/sp-process/linux/_sentencepiece_processor_ops.so
  src/main/resources/sp-process/mac/_sentencepiece_processor_ops.so
  src/main/resources/sp-process/win/_sentencepiece_processor_ops.so
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSerializeModel.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/LoadSentencepiece.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoderTestSpec.scala
Labels: new model, new-feature

#1274 Fix bug in bert sentence embeddings resulting in multiple annotations per sentence
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
Labels: bug-fix

#1279 Adding Option handler to avoid null pointer exception in doc assembler
  src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
  src/test/resources/doc-assembler/corrupted_data.parquet/part-00000-598cfbc8-e67a-49ec-aca1-fec28b0cb436-c000.snappy.parquet
  src/test/scala/com/johnsnowlabs/nlp/DocumentAssemblerTestSpec.scala
Labels: bug-fix, enhancement

#1296 [skip ci] 2020-12-09-onto_recognize_entities_bert_base_en
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_base_en.md
Labels: new model

#1297 [skip ci] 2020-12-09-onto_recognize_entities_bert_large_en
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_large_en.md
Labels: new model

#1298 [skip ci] 2020-12-09-onto_recognize_entities_bert_medium_en
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_medium_en.md
Labels: new model

#1299 [skip ci] 2020-12-09-onto_recognize_entities_bert_mini_en
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_mini_en.md
Labels: new model

#1300 [skip ci] 2020-12-09-onto_recognize_entities_bert_small_en
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_small_en.md
Labels: new model

#1301 [skip ci] 2020-12-09-onto_recognize_entities_bert_tiny_en
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_tiny_en.md
Labels: new model

#1302 [skip ci] 2020-12-09-onto_recognize_entities_electra_base_en
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_electra_base_en.md
Labels: new model

#1303 [skip ci] 2020-12-09-onto_recognize_entities_electra_small_en
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_electra_small_en.md
Labels: new model

#1304 [skip ci] 2020-12-09-hebrew_cc_300d_he
  docs/_posts/HashamUlHaq/2020-12-09-hebrew_cc_300d_he.md
Labels: new model

#1305 Models hub [skip ci]
  docs/_posts/HashamUlHaq/2020-12-09-hebrew_cc_300d_he.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_base_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_large_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_medium_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_mini_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_small_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_tiny_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_electra_base_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_electra_small_en.md
Labels: models_hub, new model

#1306 [skip ci] 2020-12-09-hebrewner_cc_300d_he
  docs/_posts/HashamUlHaq/2020-12-09-hebrewner_cc_300d_he.md
Labels: new model

#1307 [skip ci] 2020-12-09-pos_ud_htb_he
  docs/_posts/HashamUlHaq/2020-12-09-pos_ud_htb_he.md
Labels: new model

#1308 [skip ci] 2020-12-09-lemma_he
  docs/_posts/HashamUlHaq/2020-12-09-lemma_he.md
Labels: new model

#1310 [skip ci] 2020-12-09-onto_recognize_entities_electra_large_en
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_electra_large_en.md
Labels: new model

#1157 Adds Word Segmenter annotator and refactor POS Tagger annotator
  python/run-tests.py
  python/sparknlp/__init__.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/TaggedWord.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproachDistributed.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronPredictionUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronTrainingUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ws/TagsType.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ws/WordSegmenterApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ws/WordSegmenterModel.scala
  src/test/resources/word-segmenter/chinese_ground_truth.utf8
  src/test/resources/word-segmenter/chinese_test.utf8
  src/test/resources/word-segmenter/chinese_train.utf8
  src/test/resources/word-segmenter/japanese_train.utf8
  src/test/resources/word-segmenter/korean_train.utf8
  src/test/scala/com/johnsnowlabs/benchmarks/annotators/ws/Metrics.scala
  src/test/scala/com/johnsnowlabs/benchmarks/annotators/ws/WordSegmenterBenchmark.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/WordSegmenterModelTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/WordSegmenterTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/DistributedPos.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproachBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproachTestSpec.scala
Labels: new-feature

#1319 265 release candidate
  CHANGELOG
  README.md
  build.sbt
  docs/en/concepts.md
  docs/en/install.md
  python/setup.py
  python/sparknlp/__init__.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/util/Build.scala
  src/test/resources/doc-assembler/corrupted_data.parquet/part-00000-598cfbc8-e67a-49ec-aca1-fec28b0cb436-c000.snappy.parquet
  src/test/scala/com/johnsnowlabs/nlp/DocumentAssemblerTestSpec.scala
Labels: bug-fix

#1331 [skip ci] 2020-12-21-google_t5_small_ssm_nq_en
  docs/_posts/vankov/2020-12-21-google_t5_small_ssm_nq_en.md
Labels: new model

#1332 [skip ci] 2020-12-21-t5_small_en
  docs/_posts/vankov/2020-12-21-t5_small_en.md
Labels: new model

#1336 Introducing T5Transformer for predicting Seq2Seq tasks by T5 models released by Google
  python/run-tests.py
  python/run_t5_tests.py
  python/sparknlp/__init__.py
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  python/test/t5.py
  python/test/util.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/nlp/seq2seq/T5Transformer.scala
  src/test/scala/com/johnsnowlabs/nlp/seq2seq/T5TestSpec.scala
Labels: new-feature

#1334 Introducing MarianTransformer to use MarianNMT models for Fast Neural Machine Translation
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencePieceWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala
Labels: new-feature

#1313 Feature/lemmatizer conllu support
  python/run-tests.py
  python/sparknlp/training.py
  python/test/annotators.py
  python/test/util.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/Lemmatizer.scala
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLLHelper.scala
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLLU.scala
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLLUCols.scala
  src/main/scala/com/johnsnowlabs/util/TrainingHelper.scala
  src/test/resources/conllu/en.test.conllu
  src/test/resources/conllu/en.test.lemma.conllu
  src/test/scala/com/johnsnowlabs/nlp/AssertAnnotations.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/LemmatizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/training/CoNLLUTestSpec.scala
Labels: enhancement, new-feature

#1344 [skip ci] 2020-12-28-opus_mt_en_it_xx
  docs/_posts/maziyarpanahi/2020-12-28-opus_mt_en_it_xx.md
Labels: new model

#1346 [skip ci] 2020-12-28-opus_mt_en_fr_xx
  docs/_posts/maziyarpanahi/2020-12-28-opus_mt_en_fr_xx.md
Labels: new model

#1348 [skip ci] 2020-12-28-opus_mt_en_es_xx
  docs/_posts/maziyarpanahi/2020-12-28-opus_mt_en_es_xx.md
Labels: new model

#1350 [skip ci] 2020-12-28-opus_mt_swc_en_xx
  docs/_posts/maziyarpanahi/2020-12-28-opus_mt_swc_en_xx.md
Labels: new model

#1367 [skip ci] 2020-12-28-opus_mt_en_umb_xx
  docs/_posts/maziyarpanahi/2020-12-28-opus_mt_en_umb_xx.md
Labels: new model

#1692 [skip ci] 2020-12-29-ner_aspect_based_sentiment_en
  docs/_posts/HashamUlHaq/2020-12-29-ner_aspect_based_sentiment_en.md
Labels: new model

#1701 [skip ci] 2020-12-29-opus_mt_tl_en_xx
  docs/_posts/maziyarpanahi/2020-12-29-opus_mt_tl_en_xx.md
Labels: new model

#1693 [skip ci] 2020-12-29-opus_mt_bzs_en_xx
  docs/_posts/maziyarpanahi/2020-12-29-opus_mt_bzs_en_xx.md
Labels: new model

#1694 [skip ci] 2020-12-29-opus_mt_en_et_xx
  docs/_posts/maziyarpanahi/2020-12-29-opus_mt_en_et_xx.md
Labels: new model

#1695 [skip ci] 2020-12-29-opus_mt_en_sk_xx
  docs/_posts/maziyarpanahi/2020-12-29-opus_mt_en_sk_xx.md
Labels: new model

#1696 [skip ci] 2020-12-29-opus_mt_en_to_xx
  docs/_posts/maziyarpanahi/2020-12-29-opus_mt_en_to_xx.md
Labels: new model

#1697 [skip ci] 2020-12-29-opus_mt_en_ur_xx
  docs/_posts/maziyarpanahi/2020-12-29-opus_mt_en_ur_xx.md
Labels: new model

#1698 [skip ci] 2020-12-29-opus_mt_lue_en_xx
  docs/_posts/maziyarpanahi/2020-12-29-opus_mt_lue_en_xx.md
Labels: new model

#1699 [skip ci] 2020-12-29-opus_mt_niu_en_xx
  docs/_posts/maziyarpanahi/2020-12-29-opus_mt_niu_en_xx.md
Labels: new model

#1700 [skip ci] 2020-12-29-opus_mt_ti_en_xx
  docs/_posts/maziyarpanahi/2020-12-29-opus_mt_ti_en_xx.md
Labels: new model

#1703 [skip ci] 2020-12-29-opus_mt_en_lu_xx
  docs/_posts/maziyarpanahi/2020-12-29-opus_mt_en_lu_xx.md
Labels: new model
