Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-01, with the labels that each got.

#731 Upgrade TensorFlow 1.13.1 to 1.15.0 with contrib
  build.sbt
  python/sparknlp/annotator.py
  python/tensorflow/lib/ner/ner_model.py
  python/tensorflow/ner/create_models.ipynb
  python/tensorflow/ner/create_models.py
  src/main/resources/ner-dl/blstm-noncontrib_10_100_128_100.pb
  src/main/resources/ner-dl/blstm-noncontrib_10_1024_128_100.pb
  src/main/resources/ner-dl/blstm-noncontrib_10_200_128_100.pb
  src/main/resources/ner-dl/blstm-noncontrib_10_300_128_100.pb
  src/main/resources/ner-dl/blstm-noncontrib_10_768_128_100.pb
  src/main/resources/ner-dl/blstm-noncontrib_25_300_128_100.pb
  src/main/resources/ner-dl/blstm_10_100_128_100.pb
  src/main/resources/ner-dl/blstm_10_100_128_120.pb
  src/main/resources/ner-dl/blstm_10_1024_128_100.pb
  src/main/resources/ner-dl/blstm_10_1024_128_120.pb
  src/main/resources/ner-dl/blstm_10_200_128_100.pb
  src/main/resources/ner-dl/blstm_10_300_128_100.pb
  src/main/resources/ner-dl/blstm_10_300_128_120.pb
  src/main/resources/ner-dl/blstm_10_768_128_100.pb
  src/main/resources/ner-dl/blstm_10_768_128_120.pb
  src/main/resources/ner-dl/blstm_20_100_128_120.pb
  src/main/resources/ner-dl/blstm_20_300_128_120.pb
  src/main/resources/ner-dl/blstm_25_300_128_100.pb
  src/main/resources/ner-dl/blstm_30_100_128_600.pb
  src/main/resources/ner-dl/blstm_30_1024_128_600.pb
  src/main/resources/ner-dl/blstm_30_300_128_600.pb
  src/main/resources/ner-dl/blstm_30_768_128_600.pb
  src/main/resources/ner-dl/linux/_lstm_ops.so
  src/main/resources/ner-dl/linux/_sparse_feature_cross_op.so
  src/main/resources/ner-dl/mac/_lstm_ops.so
  src/main/resources/ner-dl/mac/_sparse_feature_cross_op.so
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/LoadsContrib.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/org/tensorflow/NativeLibrary.java
  src/test/resources/graph/blstm_10_100_128_120.pb
  src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerPerfTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala
Labels: enhancement, new-feature

#753 BertEmbeddings should load TF Saved Models
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
Labels: enhancement, new-feature

#754 Get the chunk metadata by its name rather than by its index
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
Labels: bug-fix

#759 Tokenizer split chars review
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: bug-fix

#763 Introducing ElmoEmbeddings annotator
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowElmo.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ElmoEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ElmoEmbeddingsTestSpec.scala
Labels: new-feature
