Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-08, with the labels that each got.

#993 added new video links
  docs/videos.md
Labels: documentation

#992 Annotator docs updates
  docs/en/annotators.md
Labels: documentation

#990 Fix max sequence length issue in AlbertEmbeddings and BertEmbeddings
  docs/articles.md
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnet.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala
Labels: bug-fix, enhancement

#1004 Adding DeIdentifcation code sample
  docs/en/licensed_annotators.md
Labels: documentation

#997 Fix sbt version issue in the second sbt project and make Travis native
  .travis.yml
  src/main/scala/com/johnsnowlabs/util/Build.scala
Labels: bug-fix

#999 OutputHelper#writeAppend: Create file if not exists before trying to append to it
  src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
Labels: bug-fix

#1001 Make sure the SentimentDL and ClassifierDL are at least binary
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
Labels: enhancement

#1013 added parameter to enable/disable list detection in SentenceDetector
  docs/_data/navigation.yml
  docs/en/examples.md
  docs/en/licensed_annotators.md
  docs/en/licensed_install.md
  docs/en/licensed_release_notes.md
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/SentenceDetectorParams.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticContentFormatter.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticMethod.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticDetectionBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetectorBoundsSpec.scala
Labels: enhancement

#1020 fixed in Tokenizer for exceptions and sentences
  src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: bug-fix
