Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-06, with the labels that each got.

#913 Spell fixes
  src/main/resources/spell_nlm/nlm_300_2_1450_43700.pb
  src/main/resources/spell_nlm/nlm_300_2_1500_43700.pb
  src/main/resources/spell_nlm/nlm_300_2_1600_50000.pb
  src/main/resources/spell_nlm/nlm_300_2_1650_56650.pb
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
Labels: bug-fix, enhancement

#914 Spell correction
  docs/en/concepts.md
Labels: documentation

#915 Text matcher entity metadata 252
  docs/en/licensed_models.md
  python/sparknlp/annotator.py
  python/tensorflow/ner/create_models.ipynb
  src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala
Labels: enhancement, new-feature

#919 Fixed multi language selection tabs
  docs/en/evaluation.md
Labels: documentation

#925 fixed databricks setGraph Path issue.
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
Labels: bug-fix

#927 Fix bugs in includeConfidence and BasicTokenizer/BertEmbeddings
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/wordpiece/BasicTokenizer.scala
Labels: bug-fix

#921 WIP: Introducing new LanguageDetectorDL annotator to identify languages
  python/sparknlp/__init__.py
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowLD.scala
  src/main/scala/com/johnsnowlabs/nlp/AnnotatorType.scala
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ld/dl/LanguageDetectorDL.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/resources/language-detector/multilingual_sample.txt
  src/test/scala/com/johnsnowlabs/nlp/annotators/ld/dl/LanguageDetectorDLTestSpec.scala
Labels: new-feature

#932 Improve RocksDB connection
  src/main/scala/com/johnsnowlabs/storage/RocksDBConnection.scala
  src/main/scala/com/johnsnowlabs/storage/StorageBatchWriter.scala
  src/main/scala/com/johnsnowlabs/storage/StorageWriter.scala
Labels: enhancement

#934 changed param name to avoid collision
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/TokenParser.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
Labels: enhancement

#936 add NerConverter to the docs
  docs/en/annotators.md
Labels: documentation

#946 253 text matcher from tokens
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/TextMatcherModel.scala
  src/test/resources/entity-extractor/test-phrases-par.txt
  src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala
Labels: enhancement

#949 fix symbols check in decodeViterbi
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
Labels: bug-fix

#951 253 conllgenerator python wrapper
  python/sparknlp/internal.py
  python/sparknlp/util.py
Labels: enhancement

#954 fixed multi language selection tabs on "general concepts" docs page
  docs/en/concepts.md
Labels: documentation
