Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-09, with the labels that each got.

#1024 Introducing YakeModel annotator for Unsupervised keyword extraction
  docs/licensed/api/lib/jquery.js
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/AnnotatorType.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/YakeModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/YakeParams.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/util/Token.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/util/Utilities.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/keyword/yake/YakeTestSpec.scala
Labels: new-feature

#1029 Ocr documentation update 160
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
  docs/en/ocr_structures.md
Labels: documentation

#1038 Update typo install.md
  docs/en/install.md
Labels: documentation

#1039 Fix typo
  docs/en/concepts.md
Labels: documentation

#1041 Update licensed_release_notes.md
  docs/en/licensed_release_notes.md
Labels: documentation

#1036 Fix lower accuracy in ClassifierDL introduced in 2.6.0 release
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
Labels: bug-fix

#1052 docs update
  docs/_layouts/landing.html
  docs/en/concepts.md
  docs/learn.md
Labels: documentation

#1055 Create PR 2.6.0-healthcare-docs-dfdde5b984e7e9b0c528e0bbfec1db277824fa65-111
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/assertion/logreg/ReadablePretrainedAssertionLogReg.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/disambiguation/logic/embeddings/EmbeddingsExtractor.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/disambiguation/logic/embeddings/PoolingLogic.html
Labels: documentation

#1058 Create PR 2.6.0-healthcare-docs-dfdde5b984e7e9b0c528e0bbfec1db277824fa65-112
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/classification/ReadablePretrainedDocumentLogRegClassifierModel.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/deid/ReadablePretrainedDeId.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/disambiguation/logic/embeddings/EmbeddingsExtractor.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/disambiguation/logic/embeddings/PoolingLogic.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/generic_classifier/ReadablePretrainedGenericClassifier.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/generic_classifier/ReadsGenericClassifierGraph.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/resolution/ReadablePretrainedChunkEntityResolver.html
  docs/licensed/api/com/johnsnowlabs/nlp/eval/resolution/EvalEntityResolver.html
Labels: documentation

#1059 Website updates
  docs/_includes/scripts/custom.js
  docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
  docs/_posts/2020-01-30-assertion_dl_en.md
  docs/_posts/2020-01-30-assertion_ml_en.md
  docs/_posts/2020-01-30-ner_bionlp_en.md
  docs/_posts/2020-01-30-ner_clinical_en.md
  docs/_posts/2020-03-19-explain_document_dl.md
  docs/_posts/2020-03-25-ner_drugs_en.md
  docs/_posts/2020-03-25-ner_events_clinical_en.md
  docs/_posts/2020-03-26-ner_healthcare_en.md
  docs/_posts/2020-04-15-ner_posology_en.md
  docs/_posts/2020-04-22-ner_anatomy_en.md
  docs/_posts/2020-04-22-ner_cellular_en.md
  docs/_posts/2020-04-22-ner_jsl_en.md
  docs/_posts/2020-04-22-ner_jsl_enriched_en.md
  docs/_posts/2020-04-22-ner_posology_large_en.md
  docs/_posts/2020-04-22-ner_posology_small_en.md
  docs/_posts/2020-04-22-ner_risk_factors_en.md
  docs/_posts/2020-05-21-assertion_dl_large_en.md
  docs/_posts/2020-05-23-ner_clinical_large_en.md
  docs/_posts/2020-08-09-re_clinical_en.md
  docs/_posts/2020-08-19-explain_clinical_doc_carp_en.md
  docs/_posts/2020-08-19-explain_clinical_doc_era_en.md
  docs/_sass/custom.scss
  docs/en/licensed_install.md
  docs/en/ocr.md
Labels: documentation

#1045 Add MultiClassifierDL unit test in Scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLTestSpec.scala
Labels: enhancement

#1056 Better error handling in SentimentDLApproach
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
Labels: bug-fix

#1062 Fix loadSavedModel for BertSentenceEmbeddings in Python
  python/sparknlp/internal.py
Labels: bug-fix

#1066 Website updates
  docs/_layouts/landing.html
  docs/_posts/2020-08-19-explain_clinical_doc_carp_en.md
  docs/_posts/2020-09-21-ner_chemprot_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_gene_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_go_clinical_en.md
  docs/_sass/custom.scss
  docs/assets/images/2020.png
  docs/assets/images/Detect_Key_Phrases.svg
  docs/assets/images/Detect_Key_Phrases_f.svg
  docs/assets/images/Detect_Toxic_Comments.svg
  docs/assets/images/Detect_Toxic_Comments_f.svg
  docs/assets/images/Detect_chemical_compounds_and_genes.svg
  docs/assets/images/Detect_chemical_compounds_and_genes_f.svg
  docs/assets/images/Detect_demographics_and_vital_signs_using_rules.svg
  docs/assets/images/Detect_demographics_and_vital_signs_using_rules_f.svg
  docs/assets/images/Detect_genes_and_human_phenotypes.svg
  docs/assets/images/Detect_genes_and_human_phenotypes_f.svg
  docs/assets/images/Detect_normalized_genes_and_human_phenotypes.svg
  docs/assets/images/Detect_normalized_genes_and_human_phenotypes_f.svg
  docs/assets/images/Detect_similar_sentences.svg
  docs/assets/images/Detect_similar_sentences_f.svg
  docs/assets/images/main-bg1.jpg
  docs/demo.md
  docs/en/licensed_install.md
  docs/en/ocr.md
  docs/index.md
  docs/learn.md
Labels: documentation

#1067 icons
  docs/assets/images/chat_symbols.svg
  docs/assets/images/ocr/ocr.png
  docs/assets/images/one_node_to_many.svg
  docs/assets/images/open_source.svg
Labels: documentation

#1074 template updates
  example/model_template.md
  example/pipeline_template.md
Labels: documentation

#1075 tags removal + Data source text updated
  docs/_posts/2020-03-17-ner_diseases_en.md
  docs/_posts/2020-04-17-spellcheck_clinical_en.md
  docs/_posts/2020-04-21-chunkresolve_icd10cm_clinical_en.md
  docs/_posts/2020-04-21-chunkresolve_icd10pcs_clinical_en.md
  docs/_posts/2020-04-21-chunkresolve_icdo_clinical_en.md
  docs/_posts/2020-05-07-assertion_i2b2_en.md
  docs/_posts/2020-05-10-wikiner_6B_100_pl.md
  docs/_posts/2020-05-10-wikiner_6B_100_pt.md
  docs/_posts/2020-05-10-wikiner_6B_300_pl.md
  docs/_posts/2020-05-10-wikiner_6B_300_pt.md
  docs/_posts/2020-05-10-wikiner_840B_300_pl.md
  docs/_posts/2020-05-10-wikiner_840B_300_pt.md
  docs/_posts/2020-05-16-chunkresolve_loinc_clinical_en.md
  docs/_posts/2020-05-19-deidentify_rb_no_regex_en.md
  docs/_posts/2020-06-20-chunkresolve_snomed_findings_clinical_en.md
  docs/_posts/2020-06-24-chunkresolve_rxnorm_xsmall_clinical_en.md
  docs/_posts/2020-07-08-ner_deid_enriched_en.md
  docs/_posts/2020-07-08-ner_diag_proc_es.md
  docs/_posts/2020-07-08-ner_neoplasms_es.md
  docs/_posts/2020-07-14-stopwords_eo.md
  docs/_posts/2020-07-22-ner_deid_large_en.md
  docs/_posts/2020-07-27-chunkresolve_rxnorm_cd_clinical_en.md
  docs/_posts/2020-07-27-chunkresolve_rxnorm_sbd_clinical_en.md
  docs/_posts/2020-07-27-chunkresolve_rxnorm_scd_clinical_en.md
  docs/_posts/2020-08-04-deidentify_large_en.md
  docs/_posts/2020-08-18-ner_events_clinical_en.md
Labels: documentation

#1071 Introducing a new SentenceDetectorDL
  docs/_layouts/landing.html
  docs/_posts/2020-08-19-explain_clinical_doc_carp_en.md
  docs/_posts/2020-09-21-ner_chemprot_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_gene_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_go_clinical_en.md
  docs/_sass/custom.scss
  docs/assets/images/2020.png
  docs/assets/images/Detect_Key_Phrases.svg
  docs/assets/images/Detect_Key_Phrases_f.svg
  docs/assets/images/Detect_Toxic_Comments.svg
  docs/assets/images/Detect_Toxic_Comments_f.svg
  docs/assets/images/Detect_chemical_compounds_and_genes.svg
  docs/assets/images/Detect_chemical_compounds_and_genes_f.svg
  docs/assets/images/Detect_demographics_and_vital_signs_using_rules.svg
  docs/assets/images/Detect_demographics_and_vital_signs_using_rules_f.svg
  docs/assets/images/Detect_genes_and_human_phenotypes.svg
  docs/assets/images/Detect_genes_and_human_phenotypes_f.svg
  docs/assets/images/Detect_normalized_genes_and_human_phenotypes.svg
  docs/assets/images/Detect_normalized_genes_and_human_phenotypes_f.svg
  docs/assets/images/Detect_similar_sentences.svg
  docs/assets/images/Detect_similar_sentences_f.svg
  docs/assets/images/chat_symbols.svg
  docs/assets/images/main-bg1.jpg
  docs/assets/images/ocr/ocr.png
  docs/assets/images/one_node_to_many.svg
  docs/assets/images/open_source.svg
  docs/demo.md
  docs/en/licensed_install.md
  docs/en/ocr.md
  docs/index.md
  docs/learn.md
  python/sparknlp/__init__.py
  python/sparknlp/annotator.py
  src/main/resources/sentence_detector_dl/cnn.pb
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSentenceDetectorDL.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLEncoder.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLModel.scala
  src/test/resources/sentence_detector_dl/sample.txt
  src/test/resources/sentence_detector_dl/test.txt
  src/test/resources/sentence_detector_dl/train.txt
  src/test/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLSpec.scala
Labels: new-feature

#1076 Databricks install instructions + streamlit apps links for some models
  docs/_posts/2020-03-17-ner_posology_en.md
  docs/_posts/2020-04-15-ner_posology_en.md
  docs/_posts/2020-04-21-ner_posology_large_en.md
  docs/_posts/2020-04-21-ner_posology_small_en.md
  docs/_posts/2020-04-22-ner_anatomy_en.md
  docs/_posts/2020-04-22-ner_cancer_genetics_en.md
  docs/_posts/2020-04-22-ner_posology_large_en.md
  docs/_posts/2020-04-22-ner_posology_small_en.md
  docs/_posts/2020-04-22-ner_risk_factors_en.md
  docs/en/install.md
Labels: documentation
