Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-11, with the labels that each got.

#1135 [skip travis] Update 2020-09-21-ner_human_phenotype_gene_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_gene_clinical_en.md
Labels: documentation

#1139 duplicates removal
  docs/_posts/2020-01-28-assertion_dl_en.md
  docs/_posts/2020-01-28-assertion_ml_en.md
  docs/_posts/2020-01-28-ner_bionlp_en.md
  docs/_posts/2020-01-30-assertion_dl_en.md
  docs/_posts/2020-01-30-assertion_ml_en.md
  docs/_posts/2020-01-30-ner_bionlp_en.md
  docs/_posts/2020-03-04-ner_deid_large_en.md
  docs/_posts/2020-03-17-ner_drugs_en.md
  docs/_posts/2020-03-25-ner_drugs_en.md
  docs/_posts/2020-04-21-ner_posology_large_en.md
  docs/_posts/2020-04-21-ner_posology_small_en.md
  docs/_posts/2020-04-21-ner_risk_factors_en.md
  docs/_posts/2020-04-22-ner_posology_large_en.md
  docs/_posts/2020-04-22-ner_posology_small_en.md
  docs/_posts/2020-04-22-ner_risk_factors_en.md
  docs/_posts/2020-05-21-ner_clinical_large_en.md
  docs/_posts/2020-05-21-ner_large_clinical_en.md
  docs/_posts/2020-07-19-deidentify_large_en.md
  docs/_posts/2020-07-22-ner_deid_large_en.md
  docs/_posts/2020-08-04-deidentify_large_en.md
  docs/_posts/2020-08-09-re_clinical_en.md
  docs/_posts/2020-08-18-ner_events_clinical_en.md
  docs/_posts/2020-08-18-re_temporal_events_clinical_en.md
  docs/_posts/2020-08-18-re_temporal_events_enriched_clinical_en.md
  docs/_posts/2020-08-19-explain_clinical_doc_era_en.md
  docs/_posts/2020-08-27-re_human_phenotype_gene_clinical_en.md
  docs/_posts/2020-09-06-ner_healthcare_de.md
  docs/_posts/2020-09-07-ner_legal_de.md
  docs/_posts/2020-09-21-ner_human_phenotype_gene_clinical_en.md
  docs/_posts/2020-09-28-ner_healthcare_de.md
  docs/_posts/2020-09-28-ner_legal_de.md
  docs/_posts/2020-09-28-re_temporal_events_clinical_en.md
  docs/_posts/2020-09-28-re_temporal_events_enriched_clinical_en.md
  docs/_posts/2020-09-30-explain_clinical_doc_era_en.md
  docs/_posts/2020-09-30-ner_events_clinical_en.md
  docs/_posts/2020-09-30-re_human_phenotype_gene_clinical_en.md
Labels: documentation

#1140 2020-11-05_ner_clinical_en
  docs/_posts/diatrambitas/2020-11-05_ner_clinical_en.md
Labels: new model

#1147 [skip travis] emotion models fix
  docs/_posts/2020-04-22-ner_anatomy_en.md
  docs/_posts/2020-07-03-classifierdl_use_emotion_en.md
  docs/_posts/2020-07-03-classifierdl_use_fakenews_en.md
  docs/_posts/2020-07-03-classifierdl_use_sarcasm_en.md
  docs/_posts/2020-07-03-classifierdl_use_spam_en.md
Labels: documentation

#1148 [skip travis] emotions models fixes
  docs/_posts/2020-07-03-classifierdl_use_cyberbullying_en.md
  docs/_posts/2020-07-03-classifierdl_use_emotion_en.md
  docs/_posts/2020-07-03-classifierdl_use_fakenews_en.md
  docs/_posts/2020-07-03-classifierdl_use_sarcasm_en.md
  docs/_posts/2020-07-03-classifierdl_use_spam_en.md
Labels: documentation

#1167 [skip travis] Website updates
  docs/_data/navigation.yml
  docs/assets/images/assertion viz.png
  docs/assets/images/dependency tree viz.png
  docs/assets/images/ner viz.png
  docs/assets/images/relations viz.png
  docs/assets/images/resolution viz.png
  docs/en/display.md
Labels: documentation

#1169 [skip travis] Models description updates
  docs/Gemfile.lock
  docs/_posts/2020-04-22-ner_cellular_en.md
  docs/_posts/2020-04-22-ner_jsl_en.md
  docs/_posts/2020-04-22-ner_jsl_enriched_en.md
  docs/_posts/2020-04-22-ner_posology_large_en.md
  docs/_posts/2020-04-22-ner_risk_factors_en.md
  docs/_posts/2020-04-28-chunkresolve_icd10cm_diseases_clinical_en.md
  docs/_posts/2020-05-21-ner_large_clinical_en.md
  docs/_posts/2020-05-23-ner_clinical_large_en.md
  docs/_posts/2020-06-20-chunkresolve_snomed_findings_clinical_en.md
  docs/_posts/2020-07-03-classifierdl_use_sarcasm_en.md
  docs/_posts/2020-07-08-ner_deid_enriched_en.md
  docs/_posts/2020-07-22-ner_deid_large_en.md
  docs/_posts/2020-07-27-chunkresolve_rxnorm_sbd_clinical_en.md
  docs/_posts/2020-07-27-chunkresolve_rxnorm_scd_clinical_en.md
  docs/_posts/2020-08-18-ner_events_clinical_en.md
  docs/_posts/2020-08-19-explain_clinical_doc_carp_en.md
  docs/_posts/2020-08-19-explain_clinical_doc_cra_en.md
  docs/_posts/2020-09-06-chunkresolve_ICD10GM_de.md
  docs/_posts/2020-09-21-ner_chemprot_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_gene_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_go_clinical_en.md
  docs/_posts/2020-09-24-re_clinical_en.md
  docs/_posts/2020-09-28-ner_healthcare_de.md
  docs/_posts/2020-09-28-ner_legal_de.md
  docs/_posts/2020-09-28-re_temporal_events_clinical_en.md
  docs/_posts/2020-09-28-re_temporal_events_enriched_clinical_en.md
  docs/_posts/2020-09-30-explain_clinical_doc_era_en.md
  docs/_posts/2020-09-30-ner_events_clinical_en.md
  docs/_posts/2020-11-04-ner_anatomy_coarse_biobert_en.md
  docs/_posts/2020-11-04-ner_anatomy_coarse_en.md
Labels: documentation

#1171 [skip travis] anatomy models updates
  docs/_posts/2020-04-22-ner_anatomy_en.md
  docs/_posts/2020-11-04-ner_anatomy_coarse_biobert_en.md
  docs/_posts/2020-11-04-ner_anatomy_coarse_en.md
Labels: documentation

#1172 [skip travis] website updates
  docs/_data/navigation.yml
  docs/assets/images/resolution viz.png
  docs/en/auxiliary.md
  docs/en/training.md
Labels: documentation

#1177 Spark OCR 1.8.0 documentation update
  docs/en/ocr_install.md
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
  docs/en/ocr_structures.md
Labels: documentation

#1141 Bug fix - load from local folder with no access to the cache folder
  .github/workflows/build_and_test.yml
  src/main/scala/com/johnsnowlabs/nlp/HasPretrained.scala
Labels: bug-fix

#1145 Fix java.lang.NullPointerException in DocumentAssembler
  src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
Labels: bug-fix

#1162 Fix dynamic padding in Bert and Add support for BERT models with different input types
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddingsTestSpec.scala
Labels: bug-fix

#1187 264 release candidate
  .github/workflows/build_and_test.yml
  CHANGELOG
  README.md
  build.sbt
  docs/en/concepts.md
  docs/en/install.md
  python/setup.py
  python/sparknlp/__init__.py
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
  src/main/scala/com/johnsnowlabs/nlp/HasPretrained.scala
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/util/Build.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddingsTestSpec.scala
Labels: bug-fix

#1192 Models hub [skip ci]
  docs/_posts/2020-07-03-classifierdl_use_sarcasm_en.md
  docs/_posts/2020-09-30-classifierdl_biobert_ade.md
  docs/_posts/2020-11-04-ner_anatomy_coarse_biobert_en.md
  docs/_posts/2020-11-04-ner_anatomy_coarse_en.md
  docs/_posts/2020-11-12-classifierdl_pico_biobert_en.md
  docs/_posts/murat-gunay/2020-11-10-turkish_ner_840B_300_tr.md
  docs/_posts/murat-gunay/2020-11-10-turkish_ner_bert_tr.md
Labels: documentation

#1194 uk fix [skip ci]
  docs/_posts/2020-05-05-pos_ud_iu_uk.md
Labels: documentation

#1195 spanish pos update [skip ci]
  docs/_posts/2020-05-04-pos_ud_tal_sv.md
Labels: documentation

#1146 enabled test data to be refreshed on every iteration
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
Labels: enhancement

#1176 Fix Python dataType Annotation
  python/sparknlp/annotation.py
Labels: bug-fix

#1202 Release Notes Docs update for 2.7.1
  docs/en/licensed_release_notes.md
Labels: documentation

#1209 Indentation fix on models hub posts [skip ci]
  docs/_posts/2020-11-27-sbiobert_base_cased_mli_en.md
  docs/_posts/2020-11-27-sbiobertresolve_cpt_en.md
  docs/_posts/2020-11-27-sbiobertresolve_icd10cm_en.md
  docs/_posts/2020-11-27-sbiobertresolve_icd10pcs_en.md
  docs/_posts/2020-11-27-sbiobertresolve_icdo_en.md
  docs/_posts/2020-11-27-sbiobertresolve_rxnorm_en.md
  docs/_posts/2020-11-27-sbiobertresolve_snomed_auxConcepts_en.md
  docs/_posts/2020-11-27-sbiobertresolve_snomed_auxConcepts_int_en.md
  docs/_posts/2020-11-27-sbiobertresolve_snomed_findings_en.md
  docs/_posts/2020-11-27-sbiobertresolve_snomed_findings_int_en.md
  docs/_posts/2020-11-27-sbluebert_base_uncased_mli_en.md
Labels: documentation

#1208 271 docs licensed
  docs/en/licensed_release_notes.md
Labels: documentation

#1216 Fixed typos in README file
  README.md
Labels: documentation
