Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-10, with the labels that each got.

#1079 Fix BERT loadSavedModel
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
Labels: enhancement

#1064 262 release candidate
  CHANGELOG
  README.md
  build.sbt
  docs/_layouts/landing.html
  docs/_posts/2020-09-13-sentence_detector_dl_en.md
  docs/_posts/2020-09-14-sentence_detector_dl_xx.md
  docs/_posts/2020-09-15-biobert_pubmed_base_cased_en.md
  docs/_posts/2020-09-16-biobert_pubmed_large_cased_en.md
  docs/_posts/2020-09-19-biobert_clinical_base_cased.md
  docs/_posts/2020-09-19-biobert_discharge_base_cased.md
  docs/_posts/2020-09-19-biobert_pmc_base_cased.md
  docs/_posts/2020-09-19-biobert_pubmed_base_cased.md
  docs/_posts/2020-09-19-biobert_pubmed_large_cased.md
  docs/_posts/2020-09-19-biobert_pubmed_pmc_base_cased.md
  docs/_posts/2020-09-19-sent-biobert_clinical_base_cased.md
  docs/_posts/2020-09-19-sent_biobert_discharge_base_cased.md
  docs/_posts/2020-09-19-sent_biobert_pmc_base_cased.md
  docs/_posts/2020-09-19-sent_biobert_pubmed_base_cased.md
  docs/_posts/2020-09-19-sent_biobert_pubmed_large_cased.md
  docs/_posts/2020-09-19-sent_biobert_pubmed_pmc_base_cased.md
  docs/_posts/2020-09-23-labse.md
  docs/en/annotators.md
  docs/en/concepts.md
  docs/en/install.md
  docs/en/licensed_install.md
  docs/en/models.md
  python/run-tests.py
  python/setup.py
  python/sparknlp/__init__.py
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  python/test/annotators.py
  src/main/resources/sentence_detector_dl/cnn.pb
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSentenceDetectorDL.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetector.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLEncoder.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLModel.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/util/Build.scala
  src/test/resources/sentence_detector_dl/sample.txt
  src/test/resources/sentence_detector_dl/test.txt
  src/test/resources/sentence_detector_dl/train.txt
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLSpec.scala
Labels: bug-fix, documentation, enhancement, models_hub, new-feature

#1087 Website updates
  docs/_posts/2020-09-06-w2v_cc_300d_de.md
  docs/_posts/2020-09-28-re_temporal_events_enriched_clinical_en.md
  docs/_posts/2020-09-30-classifierdl_biobert_ade.md
  docs/_posts/2020-09-30-explain_clinical_doc_era_en.md
  docs/_posts/2020-09-30-ner_events_clinical_en.md
  docs/_posts/2020-09-30-re_human_phenotype_gene_clinical_en
  docs/_sass/custom.scss
  docs/learn.md
Labels: documentation

#1088 Update licensed_release_notes.md
  docs/en/licensed_release_notes.md
Labels: documentation

#1081 Fix SentenceDetectorDL Unsupported Model error
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLSpec.scala
Labels: bug-fix

#1084 Fixed race condition in LruMap
  src/main/scala/com/johnsnowlabs/nlp/util/LruMap.scala
Labels: bug-fix

#1094 Code sample update for DeepSentenceDetector
  docs/_posts/2020-09-13-sentence_detector_dl_healthcare_en.md
Labels: documentation

#1098 Fix BERT max sequence length calculation
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
Labels: bug-fix

#1104 Website updates
  docs/_posts/2020-04-21-ner_anatomy_en.md
  docs/_posts/2020-04-21-ner_cellular_en.md
  docs/_posts/2020-04-21-ner_jsl_en.md
  docs/_posts/2020-04-21-ner_jsl_enriched_en.md
  docs/_posts/2020-04-21-ner_posology_large_en.md
  docs/_posts/2020-04-21-ner_posology_small_en.md
  docs/_posts/2020-04-21-ner_risk_factors_en.md
  docs/_posts/2020-04-22-ner_anatomy_en.md
  docs/_posts/2020-04-22-ner_cancer_genetics_en.md
  docs/_posts/2020-04-22-ner_jsl_en.md
  docs/_posts/2020-04-22-ner_posology_large_en.md
  docs/_posts/2020-04-22-ner_posology_small_en.md
  docs/_posts/2020-04-22-ner_risk_factors_en.md
  docs/_posts/2020-04-28-chunkresolve_icd10cm_diseases_clinical_en.md
  docs/_posts/2020-04-28-chunkresolve_icd10cm_injuries_clinical_en.md
  docs/_posts/2020-04-28-chunkresolve_icd10cm_musculoskeletal_clinical_en.md
  docs/_posts/2020-04-28-chunkresolve_icd10cm_neoplasms_clinical_en.md
  docs/_posts/2020-04-28-chunkresolve_icd10cm_poison_ext_clinical_en.md
  docs/_posts/2020-04-28-chunkresolve_icd10cm_puerile_clinical_en.md
  docs/_posts/2020-05-03-classifierdl_use_trec50_en.md
  docs/_posts/2020-05-03-classifierdl_use_trec6_en.md
  docs/_posts/2020-05-07-assertion_i2b2_en.md
  docs/_posts/2020-05-10-ner_clinical_large_en.md
  docs/_posts/2020-05-16-chunkresolve_loinc_clinical_en.md
  docs/_posts/2020-05-19-deidentify_rb_no_regex_en.md
  docs/_posts/2020-05-21-ner_large_clinical_en.md
  docs/_posts/2020-05-23-ner_clinical_large_en.md
  docs/_posts/2020-07-03-classifierdl_use_cyberbullying_en.md
  docs/_posts/2020-07-03-classifierdl_use_emotion_en.md
  docs/_posts/2020-07-03-classifierdl_use_fakenews_en.md
  docs/_posts/2020-07-03-classifierdl_use_sarcasm_en.md
  docs/_posts/2020-07-03-classifierdl_use_spam_en.md
  docs/_posts/2020-09-06-ner_healthcare_de.md
  docs/_posts/2020-09-06-w2v_cc_300d_de.md
  docs/_posts/2020-09-07-ner_legal_de.md
  docs/_posts/2020-09-13-sentence_detector_dl_en.md
  docs/_posts/2020-09-13-sentence_detector_dl_healthcare_en.md
  docs/_posts/2020-09-14-sentence_detector_dl_xx.md
  docs/_posts/2020-09-16-chunkresolve_athena_conditions_healthcare_en.md
  docs/_posts/2020-09-23-assertion_dl_healthcare_en.md
  docs/_posts/2020-09-28-re_temporal_events_clinical_en.md
  docs/_posts/2020-09-28-re_temporal_events_enriched_clinical_en.md
  docs/_posts/2020-09-30-explain_clinical_doc_era_en.md
Labels: documentation

#1092 Added option to explode sentences from SentenceDetectorDL
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLModel.scala
Labels: new-feature, on-hold

#1103 Fix threshold in YakeModel on Python side
  python/sparknlp/annotator.py
Labels: bug-fix

#1090 263 release candidate
  CHANGELOG
  README.md
  build.sbt
  docs/en/concepts.md
  docs/en/graph.md
  docs/en/install.md
  python/run-tests.py
  python/setup.py
  python/sparknlp/__init__.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/DatasetHelpers.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/AveragedPerceptron.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/util/Utilities.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/util/LruMap.scala
  src/main/scala/com/johnsnowlabs/util/Build.scala
  src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLSpec.scala
Labels: bug-fix, enhancement, new-feature

#1122 Create PR 2.7.0-healthcare-docs-a8fc8634d788f85c365bd3cb720eaa17406bb2e4-2
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/assertion/logreg/ReadablePretrainedAssertionLogReg.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/disambiguation/logic/embeddings/EmbeddingsExtractor.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/generic_classifier/ReadablePretrainedGenericClassifier.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/generic_classifier/ReadsGenericClassifierGraph.html
Labels: documentation
