Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-02, with the labels that each got.

#727 Ocr 2.0 documentation
  docs/Gemfile.lock
  docs/_data/navigation.yml
  docs/assets/images/ocr/binarized.png
  docs/assets/images/ocr/corrected.png
  docs/assets/images/ocr/rotated.png
  docs/assets/images/ocr/text_with_noise.png
  docs/en/ocr_transformers.md
Labels: documentation

#747 Docs update developers section
  docs/assets/images/activate_env.png
  docs/assets/images/add_config.png
  docs/assets/images/add_python.png
  docs/assets/images/compile_jar.png
  docs/assets/images/idea_choose_repo.png
  docs/assets/images/idea_first_screen.png
  docs/assets/images/idea_init.png
  docs/assets/images/individual_test.png
  docs/assets/images/java_version.png
  docs/assets/images/platform_settings.png
  docs/assets/images/pop_up_build.png
  docs/assets/images/project_settings.png
  docs/assets/images/project_structure.png
  docs/assets/images/python_libs_add.png
  docs/assets/images/python_libs_attached.png
  docs/assets/images/python_libs_select.png
  docs/assets/images/python_module_add.png
  docs/assets/images/python_module_pop_up.png
  docs/assets/images/python_plugin.png
  docs/assets/images/python_spark_home.png
  docs/assets/images/python_test_add.png
  docs/assets/images/python_test_config.png
  docs/assets/images/sbt_task.png
  docs/assets/images/sbt_task_run.png
  docs/assets/images/settings_build.png
  docs/assets/images/spark_submit.png
  docs/en/developers.md
Labels: documentation

#785 Fixed typo in landing.html
  docs/_layouts/landing.html
Labels: documentation

#775 Chunk embeddings groupBy fix: it was sentence, not chunk
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
Labels: bug-fix

#783 Fix NorvigSweetingModel missing sentence ID in its metadata
  src/main/scala/com/johnsnowlabs/nlp/annotators/NGramGenerator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/NGramGeneratorTestSpec.scala
Labels: bug-fix

#784 Fix UniversalSentenceEncoder crashing with empty sentences
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoderTestSpec.scala
Labels: bug-fix

#788 New licensed annotators
  docs/en/licensed_annotators.md
Labels: documentation

#786 241 Release Candidate
  CHANGELOG
  README.md
  build.sbt
  docs/_includes/article-footer.html
  docs/_includes/scripts/programmingLanguageSwitcherJavaScalaPython.js
  docs/_layouts/landing.html
  docs/en/annotators.md
  docs/en/auxiliary.md
  docs/en/concepts.md
  docs/en/evaluation.md
  docs/en/licensed_annotators.md
  docs/en/licensed_models.md
  docs/en/models.md
  docs/en/training.md
  docs/en/transformers.md
  python/setup.py
  python/sparknlp/__init__.py
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/NGramGenerator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ElmoEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
  src/main/scala/com/johnsnowlabs/util/Build.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/NGramGeneratorTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoderTestSpec.scala
Labels: bug-fix, new-feature

#793 Fix UniversalSentenceEncoder and ElmoEmbeddings failing to be downloaded in Python
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
Labels: bug-fix
