Repository JohnSnowLabs/spark-nlp, pull requests merged in 2020-03, with the labels that each got.

#802 Fix ElmoEmbeddings.Pretrained() in Python
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
Labels: bug-fix

#794 Add gpu support in Spark NLP start function
  python/sparknlp/__init__.py
  python/test/annotators.py
  python/test/util.py
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
Labels: new-feature

#810 Fixed return and wrote raise for the tensorflow version exception
  python/tensorflow/ner/create_models.py
Labels: enhancement

#805 Chunkembeddings preserve ner chunk index
  src/main/scala/com/johnsnowlabs/nlp/annotators/NGramGenerator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/NGramGeneratorTestSpec.scala
Labels: bug-fix

#801 242 Release Candidate
  README.md
  build.sbt
  docs/Gemfile.lock
  docs/_data/navigation.yml
  docs/_layouts/landing.html
  docs/en/concepts.md
  docs/en/install.md
  docs/en/ocr.md
  docs/en/ocr_release_notes.md
  docs/en/quickstart.md
  python/setup.py
  python/sparknlp/__init__.py
  python/tensorflow/ner/create_models.py
  python/test/annotators.py
  python/test/util.py
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/NGramGenerator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
  src/main/scala/com/johnsnowlabs/util/Build.scala
  src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java
  src/test/scala/com/johnsnowlabs/nlp/annotators/NGramGeneratorTestSpec.scala
Labels: bug-fix, documentation, new-feature

#816 small updates of the OCR documentation
  docs/en/ocr.md
Labels: documentation

#821 Fix broken TokenAssembler
  src/main/scala/com/johnsnowlabs/nlp/TokenAssembler.scala
  src/test/scala/com/johnsnowlabs/nlp/TokenAssemblerTestSpec.scala
Labels: bug-fix

#809 Feature/normalizer reset index
  src/main/scala/com/johnsnowlabs/nlp/annotators/NormalizerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/NormalizerBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/NormalizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
Labels: bug-fix

#825 Add param to NerConverter and avoid exception when the tagging is not IOB style
  build.sbt
  python/setup.py
  python/sparknlp/__init__.py
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/TokenAssembler.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
  src/main/scala/com/johnsnowlabs/util/Build.scala
  src/test/scala/com/johnsnowlabs/nlp/TokenAssemblerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverterTest.scala
Labels: bug-fix, new-feature

#826 Introducing ClassifierDL annotator for training multi-class text classification
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
  src/test/resources/classifier/sentiment.csv
Labels: new-feature
