Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-09, with the labels that each got.

#6047 2021-09-01-sent_bert_muril_xx
  docs/_posts/Digaari/2021-09-01-sent_bert_muril_xx.md
Labels: new model

#6045 Docs: Added Rest of Transformer use case examples
  docs/en/transformer_entries/AlbertEmbeddings.md
  docs/en/transformer_entries/ElmoEmbeddings.md
  docs/en/transformer_entries/XlnetEmbeddings.md
Labels: enhancement, documentation

#6048 Models hub
  docs/_posts/Digaari/2021-08-29-bert_muril_xx.md
  docs/_posts/Digaari/2021-08-30-bert_pubmed_en.md
  docs/_posts/Digaari/2021-08-30-bert_pubmed_squad2_en.md
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_en.md
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_mnli_en.md
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_qnli_en.md
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_qqp_en.md
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_squad2_en.md
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_sst2_en.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_bs.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_gu.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_id.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_kn.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_ml.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_mr.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_ne.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_pa.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_ru.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_sd.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_so.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_ta.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_te.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_uk.md
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_yi.md
  docs/_posts/Digaari/2021-08-31-sent_bert_pubmed_en.md
  docs/_posts/Digaari/2021-08-31-sent_bert_pubmed_squad2_en.md
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_en.md
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_mnli_en.md
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_qnli_en.md
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_qqp_en.md
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_squad2_en.md
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_sst2_en.md
  docs/_posts/Digaari/2021-09-01-sent_bert_muril_xx.md
  docs/_posts/HashamUlHaq/2021-08-11-sentence_detector_dl_healthcare_en.md
  docs/_posts/HashamUlHaq/2021-08-13-ner_jsl_slim_en.md
  docs/_posts/maziyarpanahi/2021-08-31-ner_conll_albert_base_uncased_en.md
  docs/_posts/maziyarpanahi/2021-08-31-ner_conll_albert_large_uncased_en.md
  docs/_posts/maziyarpanahi/2021-08-31-ner_conll_elmo_en.md
  docs/_posts/maziyarpanahi/2021-08-31-ner_conll_xlnet_base_cased_en.md
  docs/_posts/muhammetsnts/2021-08-12-sbiobertresolve_rxnorm_disposition_en.md
  docs/_posts/muhammetsnts/2021-08-13-ner_jsl_greedy_biobert_en.md
  docs/_posts/muhammetsnts/2021-08-26-sbertresolve_icd10cm_slim_billable_hcc_med_en.md
  docs/_posts/muhammetsnts/2021-08-26-sbiobertresolve_icd10cm_slim_billable_hcc_en.md
  docs/_posts/muhammetsnts/2021-08-28-bert_token_classifier_ner_clinical_en.md
  docs/_posts/muhammetsnts/2021-08-28-bert_token_classifier_ner_jsl_en.md
  docs/_posts/muhammetsnts/2021-08-28-sbertresolve_rxnorm_disposition_en.md
  docs/_posts/muhammetsnts/2021-08-28-sbertresolve_snomed_conditions_en.md
  docs/_posts/murat-gunay/2021-08-13-classifierdl_bert_news_pipeline_de.md
  docs/_posts/murat-gunay/2021-08-13-classifierdl_berturk_cyberbullying_pipeline_tr.md
  docs/_posts/murat-gunay/2021-08-13-classifierdl_electra_questionpair_en.md
  docs/_posts/murat-gunay/2021-08-25-classifierdl_electra_questionpair_pipeline_en.md
  docs/_posts/murat-gunay/2021-08-27-classifierdl_bert_news_pipeline_tr.md
Labels: models_hub, new model

#6049 2021-09-01-sent_roberta_base_en
  docs/_posts/maziyarpanahi/2021-09-01-sent_roberta_base_en.md
Labels: new model

#6050 2021-09-01-sent_roberta_large_en
  docs/_posts/maziyarpanahi/2021-09-01-sent_roberta_large_en.md
Labels: new model

#6051 2021-09-01-sent_distilroberta_base_en
  docs/_posts/maziyarpanahi/2021-09-01-sent_distilroberta_base_en.md
Labels: new model

#6053 2021-09-01-sent_xlm_roberta_base_xx
  docs/_posts/maziyarpanahi/2021-09-01-sent_xlm_roberta_base_xx.md
Labels: new model

#6056 2021-09-01-ner_posology_experimental_en
  docs/_posts/HashamUlHaq/2021-09-01-ner_posology_experimental_en.md
Labels: new model

#6062 2021-09-03-ner_deid_subentity_augmented_en
  docs/_posts/murat-gunay/2021-09-03-ner_deid_subentity_augmented_en.md
Labels: new model

#6064 2021-09-05-ner_jsl_biobert_en
  docs/_posts/HashamUlHaq/2021-09-05-ner_jsl_biobert_en.md
Labels: new model

#6073 Detect PHI for Deidentification error
  docs/_posts/HashamUlHaq/2021-06-30-ner_deid_subentity_augmented_en.md
Labels: documentation, models_hub

#6067 2021-09-06-sent_bert_base_uncased_legal_en
  docs/_posts/Digaari/2021-09-06-sent_bert_base_uncased_legal_en.md
Labels: new model

#6068 2021-09-06-sent_bert_base_uncased_el
  docs/_posts/Digaari/2021-09-06-sent_bert_base_uncased_el.md
Labels: new model

#6069 2021-09-06-sent_bert_base_cased_sv
  docs/_posts/Digaari/2021-09-06-sent_bert_base_cased_sv.md
Labels: new model

#6070 2021-09-06-sent_bert_base_cased_nl
  docs/_posts/Digaari/2021-09-06-sent_bert_base_cased_nl.md
Labels: new model

#6071 2021-09-06-sent_bert_base_uncased_es
  docs/_posts/Digaari/2021-09-06-sent_bert_base_uncased_es.md
Labels: new model

#6072 2021-09-06-sent_bert_base_cased_es
  docs/_posts/Digaari/2021-09-06-sent_bert_base_cased_es.md
Labels: new model

#6081 2021-09-07-bert_base_cased_nl
  docs/_posts/Digaari/2021-09-07-bert_base_cased_nl.md
Labels: new model

#6080 2021-09-07-bert_base_uncased_legal_en
  docs/_posts/Digaari/2021-09-07-bert_base_uncased_legal_en.md
Labels: new model

#6079 2021-09-07-bert_base_uncased_el
  docs/_posts/Digaari/2021-09-07-bert_base_uncased_el.md
Labels: new model

#6078 2021-09-07-bert_base_cased_sv
  docs/_posts/Digaari/2021-09-07-bert_base_cased_sv.md
Labels: new model

#6077 2021-09-07-bert_base_uncased_es
  docs/_posts/Digaari/2021-09-07-bert_base_uncased_es.md
Labels: new model

#6076 2021-09-07-bert_base_cased_es
  docs/_posts/Digaari/2021-09-07-bert_base_cased_es.md
Labels: new model

#6084 2021-09-08-classifierdl_bert_sentiment_fr
  docs/_posts/murat-gunay/2021-09-08-classifierdl_bert_sentiment_fr.md
Labels: new model

#6063 2021-09-04-ocr_table_detection_general_model_en
  docs/_posts/xyutech/2021-09-04-ocr_table_detection_general_model_en.md
Labels: new model

#6089 2021-09-09-bert_token_classifier_ner_btc_en
  docs/_posts/murat-gunay/2021-09-09-bert_token_classifier_ner_btc_en.md
Labels: new model

#6088 2021-09-09-japanese_cc_300d_ja
  docs/_posts/DevinTDHa/2021-09-09-japanese_cc_300d_ja.md
Labels: new model

#6087 2021-09-09-ner_ud_gsd_cc_300d_ja
  docs/_posts/DevinTDHa/2021-09-09-ner_ud_gsd_cc_300d_ja.md
Labels: new model

#6086 2021-09-09-classifierdl_bert_sentiment_de
  docs/_posts/murat-gunay/2021-09-09-classifierdl_bert_sentiment_de.md
Labels: new model

#6093 2021-09-10-redl_bodypart_procedure_test_biobert_en_3.0.3_2.4_en
  docs/_posts/albertoandreottiATgmail/2021-09-10-redl_bodypart_procedure_test_biobert_en_3.0.3_2.4_en.md
Labels: new model

#6057 Fix default language for XlmRoBertaSentenceEmbeddings pretrained model
  python/sparknlp/annotator.py
Labels: bug-fix, on-hold

#6060 Fix Sentence Embeddings issue
  src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala
Labels: bug-fix

#6065 Change KEYWORD to CHUNK output type in YakeModel
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/AnnotatorType.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/YakeModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/YakeParams.scala
Labels: enhancement

#6082 Docs: Moved some annotators to transformers page, added new ones
  docs/en/annotators.md
  docs/en/transformer_entries/BertForTokenClassification.md
  docs/en/transformer_entries/DistilBertForTokenClassification.md
  docs/en/transformer_entries/RoBertaSentenceEmbeddings.md
  docs/en/transformer_entries/XlmRoBertaSentenceEmbeddings.md
  python/sparknlp/annotator.py
Labels: enhancement, documentation, on-hold

#6083 Avoid exceptions due to corrupt merges in Longformer tokenizer
  src/main/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddings.scala
Labels: enhancement

#6097 2021-09-13-bert_base_cased_ro
  docs/_posts/HashamUlHaq/2021-09-13-bert_base_cased_ro.md
Labels: new model

#6101 Fix graph extraction light pipeline
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/GraphFinisher.scala
  src/main/scala/com/johnsnowlabs/nlp/HasInputAnnotationCols.scala
  src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/GraphExtraction.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
  src/main/scala/com/johnsnowlabs/nlp/util/GraphBuilder.scala
  src/test/scala/com/johnsnowlabs/nlp/GraphFinisherTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionFixture.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionTest.scala
  src/test/scala/com/johnsnowlabs/nlp/util/GraphBuilderTest.scala
Labels: enhancement, bug-fix

#6104 NLP products page
  docs/_layouts/nlp_products.html
  docs/en/nlp_server/nlp_server.md
Labels: documentation

#6092 2021-09-10-bert_token_classifier_ner_ud_gsd_ja
  docs/_posts/DevinTDHa/2021-09-10-bert_token_classifier_ner_ud_gsd_ja.md
Labels: new model

#6106 2021-09-15-ner_healthcare_de
  docs/_posts/muhammetsnts/2021-09-15-ner_healthcare_de.md
Labels: new model

#6100 2021-09-13-bert_token_classifier_ner_deid_en
  docs/_posts/murat-gunay/2021-09-13-bert_token_classifier_ner_deid_en.md
Labels: new model

#6107 2021-09-15-ner_ud_gsd_xlm_roberta_base_ja
  docs/_posts/DevinTDHa/2021-09-15-ner_ud_gsd_xlm_roberta_base_ja.md
Labels: new model

#6111 2021-09-15-spellcheck_drug_norvig_en
  docs/_posts/muhammetsnts/2021-09-15-spellcheck_drug_norvig_en.md
Labels: new model

#6112 2021-09-15-sent_bert_base_cased_de
  docs/_posts/HashamUlHaq/2021-09-15-sent_bert_base_cased_de.md
Labels: new model

#6121 2021-09-16-sbertresolve_icd10gm_de
  docs/_posts/muhammetsnts/2021-09-16-sbertresolve_icd10gm_de.md
Labels: new model

#6123 2021-09-16-sbertresolve_snomed_de
  docs/_posts/muhammetsnts/2021-09-16-sbertresolve_snomed_de.md
Labels: new model

#6122 2021-09-16-bert_token_classifier_ner_jsl_en
  docs/_posts/murat-gunay/2021-09-16-bert_token_classifier_ner_jsl_en.md
Labels: new model

#6119 2021-09-16-ner_ud_gsd_bert_base_japanese_ja
  docs/_posts/DevinTDHa/2021-09-16-ner_ud_gsd_bert_base_japanese_ja.md
Labels: new model

#6118 2021-09-16-bert_base_japanese_ja
  docs/_posts/DevinTDHa/2021-09-16-bert_base_japanese_ja.md
Labels: new model

#6130 Saving Spark NLP models 50x-60x times
  src/main/scala/com/johnsnowlabs/util/Benchmark.scala
  src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala
  src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
  src/main/scala/com/johnsnowlabs/util/FileHelper.scala
  src/main/scala/com/johnsnowlabs/util/PipelineModels.scala
  src/main/scala/com/johnsnowlabs/util/TrainingHelper.scala
  src/main/scala/com/johnsnowlabs/util/Version.scala
  src/main/scala/com/johnsnowlabs/util/ZipArchiveUtil.scala
  src/main/scala/com/johnsnowlabs/util/spark/MapAccumulator.scala
Labels: new-feature

#6131 2021-09-20-wordseg_large_zh
  docs/_posts/dcecchini/2021-09-20-wordseg_large_zh.md
Labels: new model

#6132 2021-09-20-wordseg_large_zh
  docs/_posts/dcecchini/2021-09-20-wordseg_large_zh.md
Labels: new model

#6133 2021-09-20-bert_token_classifier_ner_drugs_en
  docs/_posts/murat-gunay/2021-09-20-bert_token_classifier_ner_drugs_en.md
Labels: new model

#6134 330 Docs update
  docs/en/annotators.md
  docs/en/training_entries/conllu.md
  docs/en/transformer_entries/AlbertForTokenClassification.md
  docs/en/transformer_entries/DistilBertEmbeddings.md
  docs/en/transformer_entries/LongformerEmbeddings.md
  docs/en/transformer_entries/LongformerForTokenClassification.md
  docs/en/transformer_entries/RoBertaEmbeddings.md
  docs/en/transformer_entries/RoBertaForTokenClassification.md
  docs/en/transformer_entries/RoBertaSentenceEmbeddings.md
  docs/en/transformer_entries/XlmRoBertaEmbeddings.md
  docs/en/transformer_entries/XlmRoBertaForTokenClassification.md
  docs/en/transformer_entries/XlmRoBertaSentenceEmbeddings.md
  docs/en/transformer_entries/XlnetForTokenClassification.md
  python/sparknlp/annotator.py
  python/sparknlp/training.py
Labels: enhancement, documentation

#6142 2021-09-22-wordseg_best_th
  docs/_posts/dcecchini/2021-09-22-wordseg_best_th.md
Labels: new model

#6143 Models hub
  docs/_posts/DevinTDHa/2021-09-16-bert_base_japanese_ja.md
  docs/_posts/DevinTDHa/2021-09-16-ner_ud_gsd_bert_base_japanese_ja.md
  docs/_posts/dcecchini/2021-09-20-wordseg_large_zh.md
  docs/_posts/dcecchini/2021-09-22-wordseg_best_th.md
  docs/_posts/muhammetsnts/2021-09-16-sbertresolve_icd10gm_de.md
  docs/_posts/muhammetsnts/2021-09-16-sbertresolve_snomed_de.md
  docs/_posts/murat-gunay/2021-09-16-bert_token_classifier_ner_jsl_en.md
  docs/_posts/murat-gunay/2021-09-20-bert_token_classifier_ner_drugs_en.md
Labels: models_hub, new model

#6138 Fix wrong param types in Python for ContextSpellCheckerApproach
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
Labels: bug-fix

#6149 Docs/product installations
  docs/_data/navigation.yml
  docs/_layouts/nlp_products.html
  docs/assets/images/annotation_lab/2.1.0/API access.png
  docs/assets/images/annotation_lab/2.1.0/list_of_projects.png
  docs/assets/images/annotation_lab/2.1.0/swagger.png
  docs/assets/images/nlp_server/AWS_s1.png
  docs/assets/images/nlp_server/AWS_s2.png
  docs/assets/images/nlp_server/AWS_s3.png
  docs/assets/images/nlp_server/AWS_s4.png
  docs/assets/images/nlp_server/AWS_s5.png
  docs/assets/images/nlp_server/EC2_0.png
  docs/assets/images/nlp_server/EC2_s1.png
  docs/assets/images/nlp_server/EC2_s2.png
  docs/assets/images/nlp_server/EC2_s3.png
  docs/assets/images/nlp_server/EC2_s4.png
  docs/assets/images/nlp_server/EC2_s5.png
  docs/assets/images/nlp_server/EC2_s6.png
  docs/assets/images/nlp_server/EC2_s7.png
  docs/en/alab/api.md
  docs/en/alab/install.md
  docs/en/alab/quickstart.md
  docs/en/nlp_server/installation.md
  docs/en/nlp_server/nlp_server.md
Labels: documentation

#6150 2021-09-23-ner_profiling_biobert_en
  docs/_posts/muhammetsnts/2021-09-23-ner_profiling_biobert_en.md
Labels: new model

#6158 2021-09-24-ner_profiling_clinical_en
  docs/_posts/muhammetsnts/2021-09-24-ner_profiling_clinical_en.md
Labels: new model

#6156 2021-09-24-bert_token_classifier_ner_jsl_slim_en
  docs/_posts/murat-gunay/2021-09-24-bert_token_classifier_ner_jsl_slim_en.md
Labels: new model

#6161 2021-09-26-albert_base_token_classifier_conll03_en
  docs/_posts/maziyarpanahi/2021-09-26-albert_base_token_classifier_conll03_en.md
Labels: new model

#6162 2021-09-26-albert_large_token_classifier_conll03_en
  docs/_posts/maziyarpanahi/2021-09-26-albert_large_token_classifier_conll03_en.md
Labels: new model

#6163 2021-09-26-albert_xlarge_token_classifier_conll03_en
  docs/_posts/maziyarpanahi/2021-09-26-albert_xlarge_token_classifier_conll03_en.md
Labels: new model

#6164 2021-09-26-distilroberta_base_token_classifier_ontonotes_en
  docs/_posts/maziyarpanahi/2021-09-26-distilroberta_base_token_classifier_ontonotes_en.md
Labels: new model

#6165 2021-09-26-roberta_base_token_classifier_ontonotes_en
  docs/_posts/maziyarpanahi/2021-09-26-roberta_base_token_classifier_ontonotes_en.md
Labels: new model

#6166 2021-09-26-roberta_large_token_classifier_ontonotes_en
  docs/_posts/maziyarpanahi/2021-09-26-roberta_large_token_classifier_ontonotes_en.md
Labels: new model

#6167 2021-09-26-roberta_base_token_classifier_conll03_en
  docs/_posts/maziyarpanahi/2021-09-26-roberta_base_token_classifier_conll03_en.md
Labels: new model

#6168 2021-09-26-roberta_large_token_classifier_conll03_en
  docs/_posts/maziyarpanahi/2021-09-26-roberta_large_token_classifier_conll03_en.md
Labels: new model

#6171 2021-09-28-classifierdl_bertwiki_finance_sentiment_en
  docs/_posts/murat-gunay/2021-09-28-classifierdl_bertwiki_finance_sentiment_en.md
Labels: new model

#6172 2021-09-28-classifierdl_bert_sentiment_es
  docs/_posts/murat-gunay/2021-09-28-classifierdl_bert_sentiment_es.md
Labels: new model

#6174 2021-09-28-nerdl_fewnerd_subentity_100d_pipeline_en
  docs/_posts/murat-gunay/2021-09-28-nerdl_fewnerd_subentity_100d_pipeline_en.md
Labels: new model

#6175 2021-09-28-xlnet_base_token_classifier_conll03_en
  docs/_posts/maziyarpanahi/2021-09-28-xlnet_base_token_classifier_conll03_en.md
Labels: new model

#6176 2021-09-28-xlnet_large_token_classifier_conll03_en
  docs/_posts/maziyarpanahi/2021-09-28-xlnet_large_token_classifier_conll03_en.md
Labels: new model

#6177 2021-09-28-classifierdl_bert_sentiment_pipeline_de
  docs/_posts/murat-gunay/2021-09-28-classifierdl_bert_sentiment_pipeline_de.md
Labels: new model

#6178 2021-09-28-roberta_token_classifier_zwnj_base_ner_fa
  docs/_posts/maziyarpanahi/2021-09-28-roberta_token_classifier_zwnj_base_ner_fa.md
Labels: new model

#6179 2021-09-28-xlm_roberta_token_classifier_ner_40_lang_xx
  docs/_posts/maziyarpanahi/2021-09-28-xlm_roberta_token_classifier_ner_40_lang_xx.md
Labels: new model

#6181 Update ResourceDownloader.showPublicPipelines interface and README.md
  README.md
  python/README.md
  python/sparknlp/internal.py
  python/sparknlp/pretrained.py
  python/test/pretrained.py
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala
Labels: enhancement

#6160 Use chunk to read and write TF Variables
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/io/ChunkBytes.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
  src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddingsTestSpec.scala
Labels: enhancement, new-feature

#6186 2021-09-29-xlm_roberta_large_xx
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_large_xx.md
Labels: new model

#6187 2021-09-29-xlm_roberta_base_finetuned_amharic_am
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_base_finetuned_amharic_am.md
Labels: new model

#6188 2021-09-29-xlm_roberta_base_finetuned_hausa_ha
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_base_finetuned_hausa_ha.md
Labels: new model

#6189 2021-09-29-xlm_roberta_base_finetuned_igbo_ig
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_base_finetuned_igbo_ig.md
Labels: new model

#6190 2021-09-29-xlm_roberta_base_finetuned_kinyarwanda_rw
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_base_finetuned_kinyarwanda_rw.md
Labels: new model

#6191 2021-09-29-xlm_roberta_base_finetuned_luganda_lg
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_base_finetuned_luganda_lg.md
Labels: new model

#6180 2021-09-28-classifierdl_bert_sentiment_pipeline_fr
  docs/_posts/murat-gunay/2021-09-28-classifierdl_bert_sentiment_pipeline_fr.md
Labels: new model

#6192 2021-09-29-sbiobertresolve_hcpcs_en
  docs/_posts/muhammetsnts/2021-09-29-sbiobertresolve_hcpcs_en.md
Labels: new model

#6193 Models hub
  docs/_posts/maziyarpanahi/2021-09-26-albert_base_token_classifier_conll03_en.md
  docs/_posts/maziyarpanahi/2021-09-26-albert_large_token_classifier_conll03_en.md
  docs/_posts/maziyarpanahi/2021-09-26-albert_xlarge_token_classifier_conll03_en.md
  docs/_posts/maziyarpanahi/2021-09-26-distilroberta_base_token_classifier_ontonotes_en.md
  docs/_posts/maziyarpanahi/2021-09-26-roberta_base_token_classifier_conll03_en.md
  docs/_posts/maziyarpanahi/2021-09-26-roberta_base_token_classifier_ontonotes_en.md
  docs/_posts/maziyarpanahi/2021-09-26-roberta_large_token_classifier_conll03_en.md
  docs/_posts/maziyarpanahi/2021-09-26-roberta_large_token_classifier_ontonotes_en.md
  docs/_posts/maziyarpanahi/2021-09-28-roberta_token_classifier_zwnj_base_ner_fa.md
  docs/_posts/maziyarpanahi/2021-09-28-xlm_roberta_token_classifier_ner_40_lang_xx.md
  docs/_posts/maziyarpanahi/2021-09-28-xlnet_base_token_classifier_conll03_en.md
  docs/_posts/maziyarpanahi/2021-09-28-xlnet_large_token_classifier_conll03_en.md
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_base_finetuned_amharic_am.md
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_base_finetuned_hausa_ha.md
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_base_finetuned_igbo_ig.md
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_base_finetuned_kinyarwanda_rw.md
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_base_finetuned_luganda_lg.md
  docs/_posts/maziyarpanahi/2021-09-29-xlm_roberta_large_xx.md
  docs/_posts/muhammetsnts/2021-09-23-ner_profiling_biobert_en.md
  docs/_posts/muhammetsnts/2021-09-24-ner_profiling_clinical_en.md
  docs/_posts/muhammetsnts/2021-09-29-sbiobertresolve_hcpcs_en.md
  docs/_posts/murat-gunay/2021-09-24-bert_token_classifier_ner_jsl_slim_en.md
  docs/_posts/murat-gunay/2021-09-28-classifierdl_bert_sentiment_es.md
  docs/_posts/murat-gunay/2021-09-28-classifierdl_bert_sentiment_pipeline_de.md
  docs/_posts/murat-gunay/2021-09-28-classifierdl_bert_sentiment_pipeline_fr.md
  docs/_posts/murat-gunay/2021-09-28-classifierdl_bertwiki_finance_sentiment_en.md
  docs/_posts/murat-gunay/2021-09-28-nerdl_fewnerd_subentity_100d_pipeline_en.md
Labels: models_hub, new model

#6197 2021-09-29-sbiobertresolve_icd10cm_generalised_en
  docs/_posts/HashamUlHaq/2021-09-29-sbiobertresolve_icd10cm_generalised_en.md
Labels: new model

#6203 2021-09-30-bert_token_classifier_ner_ade_en
  docs/_posts/murat-gunay/2021-09-30-bert_token_classifier_ner_ade_en.md
Labels: new model
