Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-12, with the labels that each got.

#6527 2021-11-29-classifierdl_bert_sentiment_pipeline_es
  docs/_posts/murat-gunay/2021-11-29-classifierdl_bert_sentiment_pipeline_es.md
Labels: new model

#6544 Add new getClasses function to retrieve labels from pretrained models
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlnetForTokenClassification.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForSequenceClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForTokenClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForSequenceClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForSequenceClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForTokenClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForSequenceClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForTokenClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForTokenClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlnetForTokenClassificationTestSpec.scala
Labels: new-feature, DON'T MERGE

#6523 GPT-2 transformer implementation
  python/sparknlp/internal.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowGPT2.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2Transformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2Tokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2TestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2TokenizerTestSpec.scala
Labels: new-feature, DON'T MERGE

#6548 2021-12-02-xlm_roberta_base_token_classifier_ner_tr
  docs/_posts/murat-gunay/2021-12-02-xlm_roberta_base_token_classifier_ner_tr.md
Labels: new model

#6553 2021-12-03-gpt2_distilled_en
  docs/_posts/vankov/2021-12-03-gpt2_distilled_en.md
Labels: new model

#6552 2021-12-03-gpt2_medium_en
  docs/_posts/vankov/2021-12-03-gpt2_medium_en.md
Labels: new model

#6551 2021-12-03-gpt2_en
  docs/_posts/vankov/2021-12-03-gpt2_en.md
Labels: new model

#6559 2021-12-03-gpt_large_en
  docs/_posts/vankov/2021-12-03-gpt_large_en.md
Labels: new model

#6556 Feature/date matcher input formats
  docs/_includes/demomenu.html
  docs/demos/analyze_financial_models.md
  docs/demos/analyze_medical_text_german.md
  docs/demos/analyze_medical_text_spanish.md
  docs/demos/medical_risk_scoring.md
  docs/demos/recognize_clinical_entities.md
  docs/en/licensed_release_notes.md
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcher.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherMultiLanguageTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcherMultiLanguageTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcherTestSpec.scala
Labels: enhancement, new-feature

#6564 2021-12-04-electra_medal_acronym_en
  docs/_posts/Ahmetemintek/2021-12-04-electra_medal_acronym_en.md
Labels: new model

#6566 Introducing Distributed and Trainable Word2Vec annotators
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/Word2VecApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/Word2VecModel.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/Word2VecTestSpec.scala
Labels: new-feature, new model

#6562 Fix Keyword/Yake module naming in Scala
  python/run-tests.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword/yake/YakeKeywordExtraction.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword/yake/YakeParams.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword/yake/util/Token.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword/yake/util/Utilities.scala
Labels: enhancement

#6567 Use the best model while training NerDLApproach annotator
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
Labels: new-feature

#6555 2021-12-03-nerdl_fewnerd_100d_pipeline_en
  docs/_posts/murat-gunay/2021-12-03-nerdl_fewnerd_100d_pipeline_en.md
Labels: new model

#6558 2021-12-03-xlm_roberta_large_token_classification_ner_id
  docs/_posts/murat-gunay/2021-12-03-xlm_roberta_large_token_classification_ner_id.md
Labels: new model

#6569 2021-12-06-xlm_roberta_large_token_classifier_masakhaner_xx
  docs/_posts/murat-gunay/2021-12-06-xlm_roberta_large_token_classifier_masakhaner_xx.md
Labels: new model

#6573 2021-12-06-sbiobertresolve_umls_drug_substance_en
  docs/_posts/HashamUlHaq/2021-12-06-sbiobertresolve_umls_drug_substance_en.md
Labels: new model

#6547 Updated OCR docs for 3.9.1
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
Labels: documentation

#6579 Add release notes for NLP Server 0.4.0
  docs/_data/navigation.yml
  docs/en/nlp_server/release_notes.md
Labels: documentation

#6580 Feature/pabla nlp server release notes
  docs/en/nlp_server/release_notes.md
Labels: documentation

#6581 Docs/alab2.4.0
  docs/assets/images/annotation_lab/2.3.0/large_taxonomy.png
  docs/en/alab/release_notes.md
Labels: documentation

#6577 2021-12-07-roberta_token_classifier_bne_capitel_ner_es
  docs/_posts/murat-gunay/2021-12-07-roberta_token_classifier_bne_capitel_ner_es.md
Labels: new model

#6578 2021-12-07-bert_token_classifier_chinese_ner_zh
  docs/_posts/murat-gunay/2021-12-07-bert_token_classifier_chinese_ner_zh.md
Labels: new model

#6585 2021-12-08-bert_token_classifier_dutch_udlassy_ner_nl
  docs/_posts/murat-gunay/2021-12-08-bert_token_classifier_dutch_udlassy_ner_nl.md
Labels: new model

#6591 2021-12-09-text_detection_v1_en
  docs/_posts/kolia1985/2021-12-09-text_detection_v1_en.md
Labels: new model

#6589 2021-12-08-indic_transformers_te_distilbert_spark_nlp_te
  docs/_posts/gadde5300/2021-12-08-indic_transformers_te_distilbert_spark_nlp_te.md
Labels: new model

#6596 2021-12-09-bert_token_classifier_scandi_ner_xx
  docs/_posts/murat-gunay/2021-12-09-bert_token_classifier_scandi_ner_xx.md
Labels: new model

#6599 Deprecating models(Open-Source)
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_de_xx.md
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_es_xx.md
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_fr_xx.md
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_many_xx.md
Labels: models_hub

#6598 2021-12-10-classifierdl_bert_news_ur
  docs/_posts/murat-gunay/2021-12-10-classifierdl_bert_news_ur.md
Labels: new model

#6582 Feature/graph folder context spell
  python/tensorflow/ner/create_models.py
  python/tensorflow/spellchecker/create_spell_model.ipynb
  scripts/aws_tmp_credentials.sh
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
Labels: enhancement, new-feature, DON'T MERGE

#6575 TensorFlow functions refactor and fix race condition
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDistilBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDistilBertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowElmo.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowGPT2.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowLD.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMultiClassifier.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowRoBerta.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowRoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSentenceDetectorDL.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSentiment.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSpell.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowUSE.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnet.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnetClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ld/dl/LanguageDetectorDL.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2Transformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ElmoEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala
Labels: enhancement, bug-fix, DON'T MERGE

#6604 2021-12-11-sbiobertresolve_clinical_abbreviation_acronym_en
  docs/_posts/muhammetsnts/2021-12-11-sbiobertresolve_clinical_abbreviation_acronym_en.md
Labels: new model

#6605 Fix ignored tokens processing in seq2seq models
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowGPT2.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2Transformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformerTestSpec.scala
Labels: enhancement

#6571 2021-12-06-roberta_token_classifier_icelandic_ner_is
  docs/_posts/murat-gunay/2021-12-06-roberta_token_classifier_icelandic_ner_is.md
Labels: new model

#6609 2021-12-14-distilbert_uncased_te
  docs/_posts/gadde5300/2021-12-14-distilbert_uncased_te.md
Labels: new model

#6607 Feature/sbt 156
  .github/workflows/build_and_test.yml
  build.sbt
  project/build.properties
  project/plugins.sbt
Labels: enhancement

#6602 2021-12-10-bert_hi_en_ner_hi
  docs/_posts/gadde5300/2021-12-10-bert_hi_en_ner_hi.md
Labels: new model

#6611 2021-12-14-text_detection_v1_en
  docs/_posts/kolia1985/2021-12-14-text_detection_v1_en.md
Labels: new model

#6617 2021-12-15-mediacal_bert_token_classifier_ner_bacteria_en
  docs/_posts/xusliebana/2021-12-15-mediacal_bert_token_classifier_ner_bacteria_en.md
Labels: new model

#6618 added release notes for Annotation Lab 2.5.0
  docs/assets/images/annotation_lab/settings/large_taxonomy.png
  docs/en/alab/install.md
  docs/en/alab/release_notes.md
  docs/en/alab/terminology.md
  docs/en/alab/tips.md
Labels: documentation

#6613 Fix filter by checking timestamp on model resolution
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceMetadata.scala
  src/test/resources/resource-downloader/test_bert_v2_newest.json
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceMedataTest.scala
Labels: bug-fix

#6619 2021-12-16-albert_base_sequence_classifier_ag_news_en
  docs/_posts/maziyarpanahi/2021-12-16-albert_base_sequence_classifier_ag_news_en.md
Labels: new model

#6620 2021-12-16-albert_base_sequence_classifier_imdb_en
  docs/_posts/maziyarpanahi/2021-12-16-albert_base_sequence_classifier_imdb_en.md
Labels: new model

#6621 2021-12-16-longformer_base_sequence_classifier_ag_news_en
  docs/_posts/maziyarpanahi/2021-12-16-longformer_base_sequence_classifier_ag_news_en.md
Labels: new model

#6622 2021-12-16-longformer_base_sequence_classifier_imdb_en
  docs/_posts/maziyarpanahi/2021-12-16-longformer_base_sequence_classifier_imdb_en.md
Labels: new model

#6636 2021-12-17-bert_base_finnish_cased_fi
  docs/_posts/Ahmetemintek/2021-12-17-bert_base_finnish_cased_fi.md
Labels: new model

#6638 2021-12-17-bert_base_finnish_uncased_fi
  docs/_posts/Ahmetemintek/2021-12-17-bert_base_finnish_uncased_fi.md
Labels: new model

#6639 2021-12-17-bert_token_classifier_drug_development_trials_en
  docs/_posts/HashamUlHaq/2021-12-17-bert_token_classifier_drug_development_trials_en.md
Labels: new model

#6641 2021-12-20-ner_drugprot_clinical_en
  docs/_posts/luca-martial/2021-12-20-ner_drugprot_clinical_en.md
Labels: new model

#6637 CoNLL Reader: Add Schema to Dataframe
  python/sparknlp/training.py
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
Labels: enhancement

#6627 2021-12-16-roberta_base_sequence_classifier_ag_news_en
  docs/_posts/maziyarpanahi/2021-12-16-roberta_base_sequence_classifier_ag_news_en.md
Labels: new model

#6628 2021-12-16-roberta_base_sequence_classifier_imdb_en
  docs/_posts/maziyarpanahi/2021-12-16-roberta_base_sequence_classifier_imdb_en.md
Labels: new model

#6642 updated description with reasoning for entity labels
  docs/_posts/luca-martial/2021-12-20-ner_drugprot_clinical_en.md
Labels: models_hub

#6645 2021-12-21-text_cleaner_v1_en
  docs/_posts/kolia1985/2021-12-21-text_cleaner_v1_en.md
Labels: new model

#6649 2021-12-21-jsl_sbert_medium_rxnorm_en
  docs/_posts/galiph/2021-12-21-jsl_sbert_medium_rxnorm_en.md
Labels: new model

#6644 2021-12-21-bert_sequence_classifier_sentiment_it
  docs/_posts/murat-gunay/2021-12-21-bert_sequence_classifier_sentiment_it.md
Labels: new model

#6647 2021-12-21-bert_sequence_classifier_finbert_tone_en
  docs/_posts/murat-gunay/2021-12-21-bert_sequence_classifier_finbert_tone_en.md
Labels: new model

#6652 2021-12-22-icd10_icd9_mapping_en
  docs/_posts/muhammetsnts/2021-12-22-icd10_icd9_mapping_en.md
Labels: new model

#6651 2021-12-22-bert_sequence_classifier_toxicity_ru
  docs/_posts/murat-gunay/2021-12-22-bert_sequence_classifier_toxicity_ru.md
Labels: new model

#6655 2021-12-23-xlm_roberta_base_sequence_classifier_ag_news_en
  docs/_posts/maziyarpanahi/2021-12-23-xlm_roberta_base_sequence_classifier_ag_news_en.md
Labels: new model

#6656 2021-12-23-xlm_roberta_base_sequence_classifier_imdb_en
  docs/_posts/maziyarpanahi/2021-12-23-xlm_roberta_base_sequence_classifier_imdb_en.md
Labels: new model

#6657 2021-12-23-xlm_roberta_base_sequence_classifier_allocine_fr
  docs/_posts/maziyarpanahi/2021-12-23-xlm_roberta_base_sequence_classifier_allocine_fr.md
Labels: new model

#6658 2021-12-23-xlnet_base_sequence_classifier_ag_news_en
  docs/_posts/maziyarpanahi/2021-12-23-xlnet_base_sequence_classifier_ag_news_en.md
Labels: new model

#6659 2021-12-23-xlnet_base_sequence_classifier_imdb_en
  docs/_posts/maziyarpanahi/2021-12-23-xlnet_base_sequence_classifier_imdb_en.md
Labels: new model

#6662 2021-12-23-sbiobert_jsl_rxnorm_cased_en
  docs/_posts/galiph/2021-12-23-sbiobert_jsl_rxnorm_cased_en.md
Labels: new model

#6333 Add support for Apache Spark 3.2.0 on Scala 2.12
  .github/workflows/build_and_test.yml
  build.sbt
  project/Dependencies.scala
  python/sparknlp/__init__.py
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
Labels: on-hold, new-feature, DON'T MERGE

#6663 2021-12-24-sblubertresolve_loinc_uncased_en
  docs/_posts/Ahmetemintek/2021-12-24-sblubertresolve_loinc_uncased_en.md
Labels: new model

#6664 2021-12-24-sbiobertresolve_loinc_cased_en
  docs/_posts/Ahmetemintek/2021-12-24-sbiobertresolve_loinc_cased_en.md
Labels: new model

#6667 2021-12-27-roberta_token_classifier_pos_tagger_id
  docs/_posts/murat-gunay/2021-12-27-roberta_token_classifier_pos_tagger_id.md
Labels: new model

#6666 2021-12-26-xlm_roberta_large_token_classifier_hrl_xx
  docs/_posts/murat-gunay/2021-12-26-xlm_roberta_large_token_classifier_hrl_xx.md
Labels: new model

#6669 2021-12-27-bert_token_classifier_hi_en_ner_hi
  docs/_posts/gadde5300/2021-12-27-bert_token_classifier_hi_en_ner_hi.md
Labels: new model

#6661 2021-12-23-sbert_jsl_medium_rxnorm_uncased_en
  docs/_posts/galiph/2021-12-23-sbert_jsl_medium_rxnorm_uncased_en.md
Labels: new model

#6672 2021-12-27-roberta_token_classifier_ticker_en
  docs/_posts/murat-gunay/2021-12-27-roberta_token_classifier_ticker_en.md
Labels: new model

#6665 2021-12-25-xlm_roberta_large_token_classifier_conll03_de
  docs/_posts/murat-gunay/2021-12-25-xlm_roberta_large_token_classifier_conll03_de.md
Labels: new model

#6674 2021-12-28-roberta_token_classifier_timex_semeval_en
  docs/_posts/murat-gunay/2021-12-28-roberta_token_classifier_timex_semeval_en.md
Labels: new model

#6675 2021-12-28-sbertresolve_jsl_rxnorm_augmented_med_en
  docs/_posts/galiph/2021-12-28-sbertresolve_jsl_rxnorm_augmented_med_en.md
Labels: new model

#6678 2021-12-28-sbluebertresolve_rxnorm_augmented_uncased_en
  docs/_posts/galiph/2021-12-28-sbluebertresolve_rxnorm_augmented_uncased_en.md
Labels: new model

#6677 2021-12-28-sbiobertresolve_rxnorm_augmented_cased_en
  docs/_posts/galiph/2021-12-28-sbiobertresolve_rxnorm_augmented_cased_en.md
Labels: new model

#6676 2021-12-27-sbiobertresolve_jsl_rxnorm_augmented_en
  docs/_posts/galiph/2021-12-27-sbiobertresolve_jsl_rxnorm_augmented_en.md
Labels: new model

#6549 Fix configProtoBytes param type in Python
  python/sparknlp/annotator.py
Labels: bug-fix, DON'T MERGE

#6680 2021-12-29-classifierdl_xlm_roberta_sentiment_sw
  docs/_posts/murat-gunay/2021-12-29-classifierdl_xlm_roberta_sentiment_sw.md
Labels: new model

#6682 2021-12-30-layoutlmv2_funsd_en
  docs/_posts/xyutech/2021-12-30-layoutlmv2_funsd_en.md
Labels: new model

#6684 2021-12-30-ner_abbreviation_clinical_en
  docs/_posts/muhammetsnts/2021-12-30-ner_abbreviation_clinical_en.md
Labels: new model

#6686 2021-12-31-sbluebertresolve_loinc_uncased_en
  docs/_posts/iamvarol/2021-12-31-sbluebertresolve_loinc_uncased_en.md
Labels: new model
