Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-06, with the labels that each got.

#2980 2021-05-30-sbiobertresolve_hcc_augmented_en
  docs/_posts/HashamUlHaq/2021-05-30-sbiobertresolve_hcc_augmented_en.md
Labels: new model

#2981 2021-05-30-sbiobertresolve_cpt_procedures_augmented_en
  docs/_posts/HashamUlHaq/2021-05-30-sbiobertresolve_cpt_procedures_augmented_en.md
Labels: new model

#2982 2021-05-30-sbiobertresolve_cpt_augmented_en
  docs/_posts/HashamUlHaq/2021-05-30-sbiobertresolve_cpt_augmented_en.md
Labels: new model

#2989 2021-06-01-ner_deid_generic_augmented_en
  docs/_posts/murat-gunay/2021-06-01-ner_deid_generic_augmented_en.md
Labels: new model

#2990 2021-06-01-ner_deid_subentity_augmented_en
  docs/_posts/murat-gunay/2021-06-01-ner_deid_subentity_augmented_en.md
Labels: new model

#4271 2021-06-01-redl_bodypart_direction_biobert_en
  docs/_posts/muhammetsnts/2021-06-01-redl_bodypart_direction_biobert_en.md
Labels: new model

#4272 2021-06-01-redl_bodypart_problem_biobert_en
  docs/_posts/muhammetsnts/2021-06-01-redl_bodypart_problem_biobert_en.md
Labels: new model

#4273 2021-06-01-redl_bodypart_procedure_test_biobert_en
  docs/_posts/muhammetsnts/2021-06-01-redl_bodypart_procedure_test_biobert_en.md
Labels: new model

#4274 2021-06-01-redl_date_clinical_biobert_en
  docs/_posts/muhammetsnts/2021-06-01-redl_date_clinical_biobert_en.md
Labels: new model

#4325 Remove demo
  docs/demos/recognize_clinical_entities.md
Labels: documentation, models_hub

#5667 Introducing BatchAnnotate in MarianTransformer
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
Labels: new-feature

#5665 2021-06-06-ner_deid_generic_glove_en
  docs/_posts/murat-gunay/2021-06-06-ner_deid_generic_glove_en.md
Labels: new model

#5666 2021-06-06-ner_deid_subentity_glove_en
  docs/_posts/murat-gunay/2021-06-06-ner_deid_subentity_glove_en.md
Labels: new model

#5679 Add new demo
  docs/demos/extract_relationships.md
Labels: documentation, models_hub

#5687 Replace demo icon
  docs/assets/images/ExtractRelationships_2.svg
  docs/assets/images/ExtractRelationships_2_f.svg
  docs/demos/extract_relationships.md
Labels: documentation, models_hub

#5694 2021-06-15-sbiobertresolve_snomed_findings_en
  docs/_posts/muhammetsnts/2021-06-15-sbiobertresolve_snomed_findings_en.md
Labels: new model

#5695 2021-06-15-sbiobertresolve_snomed_bodyStructure_en
  docs/_posts/muhammetsnts/2021-06-15-sbiobertresolve_snomed_bodyStructure_en.md
Labels: new model

#5696 2021-06-15-sbiobertresolve_cpt_procedures_augmented_en
  docs/_posts/muhammetsnts/2021-06-15-sbiobertresolve_cpt_procedures_augmented_en.md
Labels: new model

#5704 2021-06-21-ner_jsl_en
  docs/_posts/muhammetsnts/2021-06-21-ner_jsl_en.md
Labels: new model

#5703 Hide some demos
  docs/_layouts/demopage.html
  docs/_sass/custom.scss
  docs/demos/analyze_non_english_medical_text.md
  docs/demos/recognize_clinical_entities.md
  docs/demos/resolve_entities_codes.md
Labels: documentation, models_hub

#5708 2021-06-21-ner_jsl_greedy_en
  docs/_posts/muhammetsnts/2021-06-21-ner_jsl_greedy_en.md
Labels: new model

#5706 fix datematecher utils for relatives dates
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
Labels: bug-fix

#5711 added explanations on transformers import
  docs/en/transformers.md
Labels: documentation

#5664 Fix typo in `concepts.md`
  docs/en/concepts.md
Labels: documentation

#5677 Feature/allow stdout sterr pipes
  python/setup.py
  python/sparknlp/__init__.py
  python/test/annotators.py
  python/test/util.py
Labels: Feature request, enhancement, on-hold

#5697 Missing getter/setter for random seed
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLTestSpec.scala
Labels: enhancement

#5702 python pubtator fix
  python/sparknlp/training.py
  src/main/scala/com/johnsnowlabs/nlp/training/PubTator.scala
  src/test/resources/corpus_pubtator_not_padding.txt
  src/test/scala/com/johnsnowlabs/nlp/util/PubTatorTestSpec.scala
Labels: bug-fix, enhancement

#5710 2021-06-22-sbiobertresolve_icdo_augmented_en
  docs/_posts/muhammetsnts/2021-06-22-sbiobertresolve_icdo_augmented_en.md
Labels: new model

#5683 Fixing yake bug, was throwing exception on empty token input
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/YakeModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/keyword/yake/YakeTestSpec.scala
Labels: bug-fix, on-hold

#5714 Migrate AlbertEmbeddings to TF v2 and BatchAnnotate
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddingsTestSpec.scala
Labels: enhancement, new-feature

#5715 Fix logger issue in some cluster / add signatures to the sessions
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDistilBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowRoBerta.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
Labels: bug-fix, enhancement

#5716 Use the same batchSize internally in NerDLModel
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
Labels: enhancement

#5719 2021-06-23-albert_xlarge_uncased_en
  docs/_posts/maziyarpanahi/2021-06-23-albert_xlarge_uncased_en.md
Labels: new model

#5718 2021-06-23-albert_large_uncased_en
  docs/_posts/maziyarpanahi/2021-06-23-albert_large_uncased_en.md
Labels: new model

#5717 2021-06-23-albert_base_uncased_en
  docs/_posts/maziyarpanahi/2021-06-23-albert_base_uncased_en.md
Labels: new model

#5720 2021-06-23-albert_xxlarge_uncased_en
  docs/_posts/maziyarpanahi/2021-06-23-albert_xxlarge_uncased_en.md
Labels: new model

#5722 Annotation Lab documentation update to reflect release 1.8.0
  docs/_data/navigation.yml
  docs/assets/images/annotation_lab/1.8.0/5_models.png
  docs/assets/images/annotation_lab/1.8.0/add_license.png
  docs/assets/images/annotation_lab/1.8.0/filters.png
  docs/assets/images/annotation_lab/1.8.0/models_hub.png
  docs/assets/images/annotation_lab/1.8.0/re_download.png
  docs/assets/images/annotation_lab/1.8.0/spark_nlp_pipeline.png
  docs/assets/images/annotation_lab/1.8.0/storage.png
  docs/assets/images/annotation_lab/1.8.0/trainig_models.png
  docs/assets/images/annotation_lab/1.8.0/upload_models.png
  docs/assets/images/annotation_lab/1.8.0/view_as.png
  docs/en/active_learning.md
  docs/en/annotators.md
  docs/en/byol.md
  docs/en/models_hub.md
  docs/en/preannotations.md
  docs/en/tasks.md
  docs/en/transformers.md
Labels: documentation

#5730 2021-06-24-ner_jsl_greedy_en
  docs/_posts/muhammetsnts/2021-06-24-ner_jsl_greedy_en.md
Labels: new model

#5729 2021-06-24-ner_jsl_en
  docs/_posts/muhammetsnts/2021-06-24-ner_jsl_en.md
Labels: new model

#5728 2021-06-24-ner_genetic_variants_en
  docs/_posts/muhammetsnts/2021-06-24-ner_genetic_variants_en.md
Labels: new model

#5732 2021-06-25-ner_genetic_variants_en
  docs/_posts/muhammetsnts/2021-06-25-ner_genetic_variants_en.md
Labels: new model

#5736 updated script for colab
  scripts/colab_setup.sh
Labels: bug-fix

#5743 2021-06-30-sbert_jsl_medium_umls_uncased_en
  docs/_posts/HashamUlHaq/2021-06-30-sbert_jsl_medium_umls_uncased_en.md
Labels: new model

#5744 2021-06-30-sbert_jsl_medium_uncased_en
  docs/_posts/HashamUlHaq/2021-06-30-sbert_jsl_medium_uncased_en.md
Labels: new model

#5745 2021-06-30-sbert_jsl_mini_umls_uncased_en
  docs/_posts/HashamUlHaq/2021-06-30-sbert_jsl_mini_umls_uncased_en.md
Labels: new model

#5752 2021-06-30-ner_deid_subentity_augmented_en
  docs/_posts/HashamUlHaq/2021-06-30-ner_deid_subentity_augmented_en.md
Labels: new model

#5751 2021-06-30-ner_deid_generic_augmented_en
  docs/_posts/HashamUlHaq/2021-06-30-ner_deid_generic_augmented_en.md
Labels: new model

#5750 2021-06-30-sbiobert_jsl_umls_cased_en
  docs/_posts/HashamUlHaq/2021-06-30-sbiobert_jsl_umls_cased_en.md
Labels: new model

#5749 2021-06-30-sbiobert_jsl_cased_en
  docs/_posts/HashamUlHaq/2021-06-30-sbiobert_jsl_cased_en.md
Labels: new model

#5747 2021-06-30-sbert_jsl_tiny_umls_uncased_en
  docs/_posts/HashamUlHaq/2021-06-30-sbert_jsl_tiny_umls_uncased_en.md
Labels: new model

#5748 2021-06-30-sbert_jsl_tiny_uncased_en
  docs/_posts/HashamUlHaq/2021-06-30-sbert_jsl_tiny_uncased_en.md
Labels: new model

#5746 2021-06-30-sbert_jsl_mini_uncased_en
  docs/_posts/HashamUlHaq/2021-06-30-sbert_jsl_mini_uncased_en.md
Labels: new model

#5734 Explore Popular demos page
  docs/_data/navigation.yml
  docs/_layouts/demohomepage.html
  docs/_sass/custom.scss
  docs/assets/images/Classifydocuments_b.svg
  docs/assets/images/Deidentify_DICOM_documents_b.svg
  docs/assets/images/Deidentify_PDF_documents_b.svg
  docs/assets/images/Detect-emotions_b.svg
  docs/assets/images/Detect_signs_and_symptoms_b.svg
  docs/assets/images/Detect_temporal_relations_for_clinical_events_b.svg
  docs/assets/images/Grammar_Analysis_b.svg
  docs/assets/images/Recognize_text_in_natural_scenes_b.svg
  docs/assets/images/Split_Clean_Text_b.svg
  docs/assets/images/epd_banner.png
  docs/assets/images/notebook_1.svg
  docs/assets/images/notebook_2.svg
  docs/assets/images/notebook_3.svg
  docs/assets/images/notebook_4.svg
  docs/assets/images/spelling_b.svg
  docs/demos/demohomepage.md
Labels: documentation, models_hub
