Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-02, with the labels that each got.

#2213 Add anchorDate params to DateMatcher and MultiDateMatcher
  docs/en/annotators.md
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/util/regex/RuleFactory.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
Labels: new-feature

#2220 Mg 01 27 embeddings ner healthcare
  docs/_posts/2020-01-30-ner_bionlp_en.md
  docs/_posts/2020-01-30-ner_clinical_en.md
  docs/_posts/2020-03-25-ner_diseases_en.md
  docs/_posts/2020-03-25-ner_drugs_en.md
  docs/_posts/2020-03-26-ner_healthcare_en.md
  docs/_posts/2020-04-15-ner_posology_en.md
  docs/_posts/2020-04-21-ner_posology_small_en.md
  docs/_posts/2020-04-22-ner_anatomy_en.md
  docs/_posts/2020-04-22-ner_cancer_genetics_en.md
  docs/_posts/2020-04-22-ner_cellular_en.md
  docs/_posts/2020-04-22-ner_jsl_en.md
  docs/_posts/2020-04-22-ner_jsl_enriched_en.md
  docs/_posts/2020-04-22-ner_posology_large_en.md
  docs/_posts/2020-04-22-ner_risk_factors_en.md
  docs/_posts/2020-05-23-ner_clinical_large_en.md
  docs/_posts/2020-07-08-ner_deid_enriched_en.md
  docs/_posts/2020-07-08-ner_diag_proc_es.md
  docs/_posts/2020-07-08-ner_neoplasms_es.md
  docs/_posts/2020-07-22-ner_deid_large_en.md
  docs/_posts/2020-09-21-ner_chemprot_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_gene_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_go_clinical_en.md
  docs/_posts/2020-09-28-ner_healthcare_de.md
  docs/_posts/2020-09-28-ner_legal_de.md
  docs/_posts/2020-09-30-ner_events_clinical_en.md
  docs/_posts/2020-11-04-ner_anatomy_coarse_biobert_en.md
  docs/_posts/2020-11-04-ner_anatomy_coarse_en.md
  docs/_posts/HashamUlHaq/2020-12-01-uner_mk_140M_300d_ur.md
  docs/_posts/HashamUlHaq/2020-12-05-aner_cc_300d_ar.md
  docs/_posts/HashamUlHaq/2020-12-07-personer_cc_300d_fa.md
  docs/_posts/HashamUlHaq/2020-12-08-ner_posology_greedy_en.md
  docs/_posts/HashamUlHaq/2020-12-14-ner_drugs_greedy_en.md
  docs/_posts/HashamUlHaq/2020-12-29-ner_aspect_based_sentiment_en.md
  docs/_posts/HashamUlHaq/2021-01-25-nerdl_atis_840b_300d_en.md
  docs/_posts/dcecchini/2021-01-03-ner_msra_bert_768d_zh.md
  docs/_posts/dcecchini/2021-01-03-ner_ud_gsd_glove_840B_300d_ja.md
  docs/_posts/dcecchini/2021-01-03-ner_ud_kaist_glove_840B_300d_ko.md
  docs/_posts/dcecchini/2021-01-04-ner_weibo_bert_768d_zh.md
  docs/_posts/dcecchini/2021-01-11-ner_lst20_glove_840B_300d_th.md
  docs/_posts/diatrambitas/2020-11-05_ner_clinical_en.md
Labels: documentation, models_hub, updates

#2216 Fixed TF2 graph loading in SentenceDetectorDLApproach
  .gitignore
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
Labels: enhancement

#2232 [skip ci] 2021-02-03-hindi_cc_300d_hi
  docs/_posts/HashamUlHaq/2021-02-03-hindi_cc_300d_hi.md
Labels: new model

#2204 [skip ci] 2021-01-27-ner_jifs_glove_840B_300d_bn
  docs/_posts/dcecchini/2021-01-27-ner_jifs_glove_840B_300d_bn.md
Labels: new model

#2234 Models hub
  docs/_posts/HashamUlHaq/2021-02-03-hindi_cc_300d_hi.md
  docs/_posts/aydinmyilmaz/2021-01-27-ner_clinical_en.md
  docs/_posts/aydinmyilmaz/2021-01-28-deidentify_dl_en.md
  docs/_posts/dcecchini/2021-01-27-ner_jifs_glove_840B_300d_bn.md
  docs/_posts/xusliebana/2021-01-29-deidentify_enriched_clinical_en.md
Labels: models_hub

#2233 Improve T5 performance for multiple sentences in a document
  docs/_includes/scripts/programmingLanguageSwitcherJavaScalaPython.js
  docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
  docs/_posts/2020-01-30-ner_bionlp_en.md
  docs/_posts/2020-01-30-ner_clinical_en.md
  docs/_posts/2020-03-25-ner_diseases_en.md
  docs/_posts/2020-03-25-ner_drugs_en.md
  docs/_posts/2020-03-26-ner_healthcare_en.md
  docs/_posts/2020-04-15-ner_posology_en.md
  docs/_posts/2020-04-21-ner_posology_small_en.md
  docs/_posts/2020-04-22-ner_anatomy_en.md
  docs/_posts/2020-04-22-ner_cancer_genetics_en.md
  docs/_posts/2020-04-22-ner_cellular_en.md
  docs/_posts/2020-04-22-ner_jsl_en.md
  docs/_posts/2020-04-22-ner_jsl_enriched_en.md
  docs/_posts/2020-04-22-ner_posology_large_en.md
  docs/_posts/2020-04-22-ner_risk_factors_en.md
  docs/_posts/2020-05-23-ner_clinical_large_en.md
  docs/_posts/2020-07-08-ner_deid_enriched_en.md
  docs/_posts/2020-07-08-ner_diag_proc_es.md
  docs/_posts/2020-07-08-ner_neoplasms_es.md
  docs/_posts/2020-07-22-ner_deid_large_en.md
  docs/_posts/2020-09-21-ner_chemprot_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_gene_clinical_en.md
  docs/_posts/2020-09-21-ner_human_phenotype_go_clinical_en.md
  docs/_posts/2020-09-28-ner_healthcare_de.md
  docs/_posts/2020-09-28-ner_legal_de.md
  docs/_posts/2020-09-30-ner_events_clinical_en.md
  docs/_posts/2020-11-04-ner_anatomy_coarse_biobert_en.md
  docs/_posts/2020-11-04-ner_anatomy_coarse_en.md
  docs/_posts/HashamUlHaq/2020-12-01-uner_mk_140M_300d_ur.md
  docs/_posts/HashamUlHaq/2020-12-05-aner_cc_300d_ar.md
  docs/_posts/HashamUlHaq/2020-12-07-personer_cc_300d_fa.md
  docs/_posts/HashamUlHaq/2020-12-08-ner_posology_greedy_en.md
  docs/_posts/HashamUlHaq/2020-12-14-ner_drugs_greedy_en.md
  docs/_posts/HashamUlHaq/2020-12-29-ner_aspect_based_sentiment_en.md
  docs/_posts/HashamUlHaq/2021-01-25-nerdl_atis_840b_300d_en.md
  docs/_posts/dcecchini/2021-01-03-ner_msra_bert_768d_zh.md
  docs/_posts/dcecchini/2021-01-03-ner_ud_gsd_glove_840B_300d_ja.md
  docs/_posts/dcecchini/2021-01-03-ner_ud_kaist_glove_840B_300d_ko.md
  docs/_posts/dcecchini/2021-01-04-ner_weibo_bert_768d_zh.md
  docs/_posts/dcecchini/2021-01-11-ner_lst20_glove_840B_300d_th.md
  docs/_posts/dcecchini/2021-01-29-ner_drugs_large_en.md
  docs/_posts/diatrambitas/2020-11-05_ner_clinical_en.md
  docs/assets/images/Flag_of_Bangladesh.png
  docs/demo.md
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5TestSpec.scala
Labels: enhancement

#2238 [skip ci] 2021-02-04-redl_temporal_events_biobert_en
  docs/_posts/HashamUlHaq/2021-02-04-redl_temporal_events_biobert_en.md
Labels: new model

#2239 [skip ci] 2021-02-04-redl_human_phenotype_gene_biobert_en
  docs/_posts/HashamUlHaq/2021-02-04-redl_human_phenotype_gene_biobert_en.md
Labels: new model

#2240 [skip ci] 2021-02-04-redl_drug_drug_interaction_biobert_en
  docs/_posts/HashamUlHaq/2021-02-04-redl_drug_drug_interaction_biobert_en.md
Labels: new model

#2241 [skip ci] 2021-02-04-redl_chemprot_biobert_en
  docs/_posts/HashamUlHaq/2021-02-04-redl_chemprot_biobert_en.md
Labels: new model

#2242 [skip ci] 2021-02-04-redl_clinical_biobert_en
  docs/_posts/HashamUlHaq/2021-02-04-redl_clinical_biobert_en.md
Labels: new model

#2243 [skip ci] 2021-02-04-redl_bodypart_problem_biobert_en
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_problem_biobert_en.md
Labels: new model

#2245 [skip ci] 2021-02-04-redl_bodypart_direction_biobert_en
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_direction_biobert_en.md
Labels: new model

#2246 [skip ci] 2021-02-04-redl_date_clinical_biobert_en
  docs/_posts/HashamUlHaq/2021-02-04-redl_date_clinical_biobert_en.md
Labels: new model

#2244 [skip ci] 2021-02-04-redl_bodypart_procedure_test_biobert_en
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_procedure_test_biobert_en.md
Labels: new model

#2252 [skip ci] 2021-02-06-sbert_biobertresolve_icd10cm_augmented_billable_hcc_en
  docs/_posts/HashamUlHaq/2021-02-06-sbert_biobertresolve_icd10cm_augmented_billable_hcc_en.md
Labels: new model

#2255 Fix typo in /README.md and /python/README.md
  README.md
  python/README.md
Labels: documentation

#2267 Added refactoring for TF2 embeddings classes
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowElmo.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ElmoEmbeddingsTestSpec.scala
Labels: enhancement

#2273 [skip ci] 2021-02-10-bengaliner_cc_300d_bn
  docs/_posts/HashamUlHaq/2021-02-10-bengaliner_cc_300d_bn.md
Labels: new model

#2275 [skip_ci] insertion of new metadata lines
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_direction_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_problem_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_procedure_test_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_chemprot_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_clinical_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_date_clinical_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_drug_drug_interaction_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_human_phenotype_gene_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_temporal_events_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-06-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
Labels: documentation, models_hub, updates

#2279 [skip ci] 2021-02-11-explain_clinical_doc_ade_en
  docs/_posts/HashamUlHaq/2021-02-11-explain_clinical_doc_ade_en.md
Labels: new model

#2272 [skip ci] 2021-02-10-bengali_cc_300d_bn
  docs/_posts/HashamUlHaq/2021-02-10-bengali_cc_300d_bn.md
Labels: new model

#2284 Migrate Loading SentencePiece via TensorFlow Text in TF v2.3.1 #2283
  src/main/resources/sp-process/linux/_sentencepiece_processor_ops.so
  src/main/resources/sp-process/linux/_sentencepiece_tokenizer.so
  src/main/resources/sp-process/mac/_sentencepiece_processor_ops.so
  src/main/resources/sp-process/mac/_sentencepiece_tokenizer.dylib
  src/main/resources/sp-process/win/_sentencepiece_processor_ops.so
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/LoadSentencepiece.scala
Labels: enhancement

#2285 Test TF v2 on GA
  .github/workflows/build_and_test.yml
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
Labels: on-hold

#2291 [skip_ci] Insertion of NLU blocks into stopwords md files and fixing several clinical models
  docs/_posts/2020-07-14-stopwords_af.md
  docs/_posts/2020-07-14-stopwords_ar.md
  docs/_posts/2020-07-14-stopwords_bg.md
  docs/_posts/2020-07-14-stopwords_bn.md
  docs/_posts/2020-07-14-stopwords_br.md
  docs/_posts/2020-07-14-stopwords_ca.md
  docs/_posts/2020-07-14-stopwords_cs.md
  docs/_posts/2020-07-14-stopwords_de.md
  docs/_posts/2020-07-14-stopwords_el.md
  docs/_posts/2020-07-14-stopwords_en.md
  docs/_posts/2020-07-14-stopwords_eo.md
  docs/_posts/2020-07-14-stopwords_es.md
  docs/_posts/2020-07-14-stopwords_eu.md
  docs/_posts/2020-07-14-stopwords_fa.md
  docs/_posts/2020-07-14-stopwords_fi.md
  docs/_posts/2020-07-14-stopwords_fr.md
  docs/_posts/2020-07-14-stopwords_ga.md
  docs/_posts/2020-07-14-stopwords_gl.md
  docs/_posts/2020-07-14-stopwords_ha.md
  docs/_posts/2020-07-14-stopwords_he.md
  docs/_posts/2020-07-14-stopwords_hi.md
  docs/_posts/2020-07-14-stopwords_hu.md
  docs/_posts/2020-07-14-stopwords_hy.md
  docs/_posts/2020-07-14-stopwords_id.md
  docs/_posts/2020-07-14-stopwords_it.md
  docs/_posts/2020-07-14-stopwords_ja.md
  docs/_posts/2020-07-14-stopwords_la.md
  docs/_posts/2020-07-14-stopwords_lv.md
  docs/_posts/2020-07-14-stopwords_mr.md
  docs/_posts/2020-07-14-stopwords_pl.md
  docs/_posts/2020-07-14-stopwords_pt.md
  docs/_posts/2020-07-14-stopwords_ro.md
  docs/_posts/2020-07-14-stopwords_ru.md
  docs/_posts/2020-07-14-stopwords_sk.md
  docs/_posts/2020-07-14-stopwords_sl.md
  docs/_posts/2020-07-14-stopwords_so.md
  docs/_posts/2020-07-14-stopwords_st.md
  docs/_posts/2020-07-14-stopwords_sv.md
  docs/_posts/2020-07-14-stopwords_sw.md
  docs/_posts/2020-07-14-stopwords_th.md
  docs/_posts/2020-07-14-stopwords_tr.md
  docs/_posts/2020-07-14-stopwords_yo.md
  docs/_posts/2020-07-14-stopwords_zu.md
  docs/_posts/HashamUlHaq/2021-01-09-sentimentdl_glove_imdb_en.md
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_ade_biobert_en.md
Labels: documentation, models_hub, updates

#2294 [skip_ci] Insertion of NLU blocks into lemmatizer models
  docs/_posts/2020-02-17-lemma_es.md
  docs/_posts/2020-03-12-lemma_ru.md
  docs/_posts/2020-05-03-lemma_nl.md
  docs/_posts/2020-05-03-lemma_pl.md
  docs/_posts/2020-05-03-lemma_pt.md
  docs/_posts/2020-05-03-lemma_tr.md
  docs/_posts/2020-05-04-lemma_zh.md
  docs/_posts/2020-05-05-lemma_bg.md
  docs/_posts/2020-05-05-lemma_cs.md
  docs/_posts/2020-05-05-lemma_el.md
  docs/_posts/2020-05-05-lemma_fi.md
  docs/_posts/2020-05-05-lemma_hu.md
  docs/_posts/2020-05-05-lemma_nb.md
  docs/_posts/2020-05-05-lemma_ro.md
  docs/_posts/2020-05-05-lemma_sk.md
  docs/_posts/2020-05-05-lemma_sv.md
  docs/_posts/2020-05-05-lemma_uk.md
  docs/_posts/2020-07-29-lemma_br.md
  docs/_posts/2020-07-29-lemma_ca.md
  docs/_posts/2020-07-29-lemma_da.md
  docs/_posts/2020-07-29-lemma_eu.md
  docs/_posts/2020-07-29-lemma_ga.md
  docs/_posts/2020-07-29-lemma_gl.md
  docs/_posts/2020-07-29-lemma_hi.md
  docs/_posts/2020-07-29-lemma_hy.md
  docs/_posts/2020-07-29-lemma_id.md
  docs/_posts/2020-07-29-lemma_la.md
  docs/_posts/2020-07-29-lemma_lv.md
  docs/_posts/2020-07-29-lemma_mr.md
  docs/_posts/2020-07-29-lemma_sl.md
  docs/_posts/2020-07-29-lemma_yo.md
  docs/_posts/HashamUlHaq/2020-11-28-lemma_ar.md
  docs/_posts/HashamUlHaq/2020-11-28-lemma_et.md
  docs/_posts/HashamUlHaq/2020-11-28-lemma_fa.md
  docs/_posts/HashamUlHaq/2020-11-28-lemma_ur.md
  docs/_posts/HashamUlHaq/2020-12-09-lemma_he.md
  docs/_posts/dcecchini/2021-01-15-lemma_ja.md
  docs/_posts/dcecchini/2021-01-15-lemma_ko.md
  docs/_posts/dcecchini/2021-01-18-lemma_bh.md
  docs/_posts/dcecchini/2021-01-20-lemma_am.md
  docs/_posts/dcecchini/2021-01-20-lemma_bn.md
Labels: documentation, models_hub, updates

#2296 [skip_ci] Insertion of NLU blocks into classifier md files
  docs/_posts/2020-05-03-classifierdl_use_trec50_en.md
  docs/_posts/2020-05-03-classifierdl_use_trec6_en.md
  docs/_posts/2020-07-03-classifierdl_use_cyberbullying_en.md
  docs/_posts/2020-07-03-classifierdl_use_emotion_en.md
  docs/_posts/2020-07-03-classifierdl_use_fakenews_en.md
  docs/_posts/2020-07-03-classifierdl_use_sarcasm_en.md
  docs/_posts/2020-07-03-classifierdl_use_spam_en.md
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_cyberbullying_en.md
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_emotion_en.md
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_fakenews_en.md
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_sarcasm_en.md
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_spam_en.md
  docs/_posts/maziyarpanahi/2021-01-08-classifierdl_use_trec50_en.md
  docs/_posts/maziyarpanahi/2021-01-08-classifierdl_use_trec6_en.md
Labels: documentation, models_hub, updates

#2280 [skip_ci] fixing the titles of classifiers that hasham trained
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_cyberbullying_en.md
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_emotion_en.md
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_fakenews_en.md
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_sarcasm_en.md
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_spam_en.md
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_ade_biobert_en.md
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_ade_clinicalbert_en.md
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_ade_conversational_biobert_en.md
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_gender_biobert_en.md
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_gender_sbert_en.md
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_pico_biobert_en.md
Labels: documentation, models_hub, updates

#2278 [skip_ci] NLU Block Insertion to POS md files
  docs/_posts/2020-02-17-pos_ud_gsd_es.md
  docs/_posts/2020-03-12-pos_ud_gsd_ru.md
  docs/_posts/2020-05-03-pos_ud_bosque_pt.md
  docs/_posts/2020-05-03-pos_ud_imst_tr.md
  docs/_posts/2020-05-03-pos_ud_lfg_pl.md
  docs/_posts/2020-05-04-pos_ud_alpino_nl.md
  docs/_posts/2020-05-04-pos_ud_btb_bg.md
  docs/_posts/2020-05-04-pos_ud_gsd_zh.md
  docs/_posts/2020-05-04-pos_ud_pdt_cs.md
  docs/_posts/2020-05-04-pos_ud_rrt_ro.md
  docs/_posts/2020-05-04-pos_ud_snk_sk.md
  docs/_posts/2020-05-04-pos_ud_tal_sv.md
  docs/_posts/2020-05-04-pos_ud_tdt_fi.md
  docs/_posts/2020-05-05-pos_ud_bokmaal_nb.md
  docs/_posts/2020-05-05-pos_ud_gdt_el.md
  docs/_posts/2020-05-05-pos_ud_iu_uk.md
  docs/_posts/2020-05-05-pos_ud_nynorsk_nn.md
  docs/_posts/2020-05-05-pos_ud_szeged_hu.md
  docs/_posts/2020-07-29-pos_ud_ancora_ca.md
  docs/_posts/2020-07-29-pos_ud_armtdp_hy.md
  docs/_posts/2020-07-29-pos_ud_bdt_eu.md
  docs/_posts/2020-07-29-pos_ud_ddt_da.md
  docs/_posts/2020-07-29-pos_ud_gsd_id.md
  docs/_posts/2020-07-29-pos_ud_hdtb_hi.md
  docs/_posts/2020-07-29-pos_ud_idt_ga.md
  docs/_posts/2020-07-29-pos_ud_keb_br.md
  docs/_posts/2020-07-29-pos_ud_llct_la.md
  docs/_posts/2020-07-29-pos_ud_lvtb_lv.md
  docs/_posts/2020-07-29-pos_ud_ssj_sl.md
  docs/_posts/2020-07-29-pos_ud_treegal_gl.md
  docs/_posts/2020-07-29-pos_ud_ufal_mr.md
  docs/_posts/2020-07-29-pos_ud_ytb_yo.md
  docs/_posts/HashamUlHaq/2020-11-30-pos_ud_padt_ar.md
  docs/_posts/HashamUlHaq/2020-11-30-pos_ud_perdt_fa.md
  docs/_posts/HashamUlHaq/2020-11-30-pos_ud_udtb_ur.md
  docs/_posts/HashamUlHaq/2020-12-09-pos_ud_htb_he.md
  docs/_posts/dcecchini/2021-01-03-pos_ctb9_zh.md
  docs/_posts/dcecchini/2021-01-03-pos_ud_gsd_ja.md
  docs/_posts/dcecchini/2021-01-03-pos_ud_gsd_zh.md
  docs/_posts/dcecchini/2021-01-03-pos_ud_kaist_ko.md
  docs/_posts/dcecchini/2021-01-13-pos_lst20_th.md
  docs/_posts/dcecchini/2021-01-18-pos_ud_bhtb_bh.md
  docs/_posts/dcecchini/2021-01-20-pos_msri_bn.md
  docs/_posts/dcecchini/2021-01-20-pos_ud_att_am.md
  docs/_posts/dcecchini/2021-01-25-pos_ud_gsd_trad_zh.md
Labels: documentation, models_hub, updates

#2300 [skip ci] 2021-02-16-spellcheck_clinical_en
  docs/_posts/albertoandreottiATgmail/2021-02-16-spellcheck_clinical_en.md
Labels: new model

#2298 Fixing functions utilities making udf untyped
  src/main/scala/com/johnsnowlabs/nlp/functions.scala
  src/test/scala/com/johnsnowlabs/nlp/FunctionsTestSpec.scala
Labels: bug-fix

#2297 Add catch all to case matchers
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala
Labels: bug-fix

#2290 bug fix for setOutputAsArray(false), add default parameters
  python/sparknlp/base.py
  src/main/scala/com/johnsnowlabs/nlp/Finisher.scala
  src/test/scala/com/johnsnowlabs/nlp/FinisherTestSpec.scala
Labels: bug-fix

#2289 fix for "Check odd behavior in TokenAssembler"
  src/main/scala/com/johnsnowlabs/nlp/TokenAssembler.scala
  src/test/scala/com/johnsnowlabs/nlp/TokenAssemblerTestSpec.scala
Labels: bug-fix, enhancement

#2288 Fix #2287 ClassifierDLModel and SentimentDLModel fails if empty string is passed as input
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLTestSpec.scala
Labels: bug-fix, enhancement

#2292 [skip ci] 2021-02-15-nerdl_snips_100d_en
  docs/_posts/HashamUlHaq/2021-02-15-nerdl_snips_100d_en.md
Labels: new model

#2293 [skip ci] 2021-02-15-classifierdl_use_snips_en
  docs/_posts/HashamUlHaq/2021-02-15-classifierdl_use_snips_en.md
Labels: new model

#2306 Bugfix/clean up warnings
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSpell.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/DistributedPos.scala
Labels: enhancement

#2307 [skip ci] Insertion of NLU blocks into md files of _posts&Hasham's folder
  docs/_posts/2020-01-22-glove_100d.md
  docs/_posts/2020-01-22-glove_6B_300.md
  docs/_posts/2020-01-22-glove_840B_300.md
  docs/_posts/2020-03-19-explain_document_dl.md
  docs/_posts/2020-09-13-sentence_detector_dl_en.md
  docs/_posts/2020-09-14-sentence_detector_dl_xx.md
  docs/_posts/HashamUlHaq/2020-12-01-sentimentdl_urduvec_imdb_ur.md
  docs/_posts/HashamUlHaq/2020-12-01-urduvec_140M_300d_ur.md
  docs/_posts/HashamUlHaq/2020-12-05-arabic_w2v_cc_300d_ar.md
  docs/_posts/HashamUlHaq/2020-12-05-persian_w2v_cc_300d_fa.md
  docs/_posts/HashamUlHaq/2020-12-09-hebrew_cc_300d_he.md
  docs/_posts/HashamUlHaq/2020-12-29-ner_aspect_based_sentiment_en.md
  docs/_posts/HashamUlHaq/2021-01-09-sentimentdl_urduvec_imdb_ur.md
  docs/_posts/HashamUlHaq/2021-01-15-analyze_sentimentdl_use_imdb_en.md
  docs/_posts/HashamUlHaq/2021-01-18-analyze_sentimentdl_use_twitter_en.md
Labels: documentation, models_hub, updates

#2312 shaded httpclient
  build.sbt
Labels: enhancement

#2310 Aws sdk downgrade
  .github/workflows/build_and_test.yml
  build.sbt
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
Labels: bug-fix, enhancement

#2314 [skip ci] 2021-02-19-ner_deid_synthetic_en
  docs/_posts/HashamUlHaq/2021-02-19-ner_deid_synthetic_en.md
Labels: new model

#2219 [skip ci] 2021-02-01-ner_deidentify_dl_en
  docs/_posts/aydinmyilmaz/2021-02-01-ner_deidentify_dl_en.md
Labels: new model

#2316 [skip ci] 2021-02-19-t5_base_mediqa_mnli_en
  docs/_posts/HashamUlHaq/2021-02-19-t5_base_mediqa_mnli_en.md
Labels: new model

#2129 WIP: Start supporting Apache Spark 3.0.1 with Scala 2.12
  .github/workflows/build_and_test.yml
  .gitignore
  build.sbt
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/re/ReadRelationExtractionDLModelTensorflowModel.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/re/ReadablePretrainedRelationExtractionDLModel.html
  docs/licensed/api/index.js
  src/main/resources/sp-process/linux/_sentencepiece_processor_ops.so
  src/main/resources/sp-process/linux/_sentencepiece_tokenizer.so
  src/main/resources/sp-process/mac/_sentencepiece_processor_ops.so
  src/main/resources/sp-process/mac/_sentencepiece_tokenizer.dylib
  src/main/resources/sp-process/win/_sentencepiece_processor_ops.so
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowElmo.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowLD.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSentenceDetectorDL.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSpell.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowUSE.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnet.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/LoadSentencepiece.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproachDistributed.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/functions.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
  src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
  src/test/scala/com/johnsnowlabs/nlp/FunctionsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/DistributedPos.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/SpellCheckerUseCase.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ElmoEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/util/ExportCSVToolBehaviors.scala
Labels: enhancement, new-feature, on-hold

#2330 [skip ci] 2021-02-24-re_test_result_date_en
  docs/_posts/HashamUlHaq/2021-02-24-re_test_result_date_en.md
Labels: new model

#2338 Introducing BatchAnnotation for BertEmbeddings
  src/main/scala/com/johnsnowlabs/nlp/HasBatchedAnnotate.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
Labels: enhancement, new-feature, on-hold
