Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-11, with the labels that each got.

#6323 Comet.ml integration with Spark NLP
  docs/_data/navigation.yml
  docs/en/licensed_install.md
  docs/en/third-party-projects.md
  python/docs/index.rst
  python/docs/reference/index.rst
  python/docs/third_party/Comet.rst
  python/docs/third_party/index.rst
  python/run-tests-thirdparty.py
  python/sparknlp/annotator.py
  python/sparknlp/logging/__init__.py
  python/sparknlp/logging/comet.py
  python/test/thirdparty/__init__.py
  python/test/thirdparty/comet.py
  src/test/resources/logging/comet/spark_nlp_display_viz.html
Labels: documentation, new-feature

#6326 Fix EntityRulerApproach name from import and add the model to ResourceDownloader
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
Labels: enhancement

#6354 Adding instructions for GCP cluster
  README.md
Labels: documentation

#6357 2021-11-01-bert_base_sequence_classifier_imdb_en
  docs/_posts/maziyarpanahi/2021-11-01-bert_base_sequence_classifier_imdb_en.md
Labels: new model

#6358 2021-11-01-bert_large_sequence_classifier_imdb_en
  docs/_posts/maziyarpanahi/2021-11-01-bert_large_sequence_classifier_imdb_en.md
Labels: new model

#6360 Docs: Add BertForSequenceClassification
  docs/en/annotators.md
  docs/en/transformer_entries/BertForSequenceClassification.md
  python/sparknlp/annotator.py
Labels: documentation

#6362 2021-11-01-roberta_base_biomedical_es
  docs/_posts/josejuanmartinez/2021-11-01-roberta_base_biomedical_es.md
Labels: new model

#6363 2021-11-01-sbiobertresolve_icd10cm_augmented_billable_hcc_en
  docs/_posts/muhammetsnts/2021-11-01-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
Labels: new model

#6366 Fix a bug in NerDLModel that degrades GPU performance
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
Labels: bug-fix

#6365 2021-11-02-bert_base_sequence_classifier_ag_news_en
  docs/_posts/maziyarpanahi/2021-11-02-bert_base_sequence_classifier_ag_news_en.md
Labels: new model

#6353 added newline to logs in databricks
  src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
Labels: bug-fix

#6371 2021-11-03-bert_sequence_classifier_japanese_sentiment_ja
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_japanese_sentiment_ja.md
Labels: new model

#6373 2021-11-03-bert_sequence_classifier_multilingual_sentiment_xx
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_multilingual_sentiment_xx.md
Labels: new model

#6374 2021-11-03-bert_sequence_classifier_turkish_sentiment_tr
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_turkish_sentiment_tr.md
Labels: new model

#6375 2021-11-03-bert_sequence_classifier_beto_emotion_analysis_es
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_beto_emotion_analysis_es.md
Labels: new model

#6376 2021-11-03-bert_sequence_classifier_beto_sentiment_analysis_es
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_beto_sentiment_analysis_es.md
Labels: new model

#6377 2021-11-03-bert_sequence_classifier_dehatebert_mono_en
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_dehatebert_mono_en.md
Labels: new model

#6379 2021-11-03-bert_sequence_classifier_finbert_en
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_finbert_en.md
Labels: new model

#6380 2021-11-03-bert_sequence_classifier_sentiment_de
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_sentiment_de.md
Labels: new model

#6381 2021-11-03-bert_sequence_classifier_rubert_sentiment_ru
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_rubert_sentiment_ru.md
Labels: new model

#6382 Models hub
  docs/_posts/HashamUlHaq/2021-10-22-ner_jsl_enriched_en.md
  docs/_posts/galiph/2021-10-29-sbiobertresolve_rxnorm_augmented_en.md
  docs/_posts/josejuanmartinez/2021-11-01-roberta_base_biomedical_es.md
  docs/_posts/maziyarpanahi/2021-11-01-bert_base_sequence_classifier_dbpedia_14_en.md
  docs/_posts/maziyarpanahi/2021-11-01-bert_base_sequence_classifier_imdb_en.md
  docs/_posts/maziyarpanahi/2021-11-01-bert_large_sequence_classifier_imdb_en.md
  docs/_posts/maziyarpanahi/2021-11-01-bert_multilingual_sequence_classifier_allocine_fr.md
  docs/_posts/maziyarpanahi/2021-11-02-bert_base_sequence_classifier_ag_news_en.md
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_beto_emotion_analysis_es.md
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_beto_sentiment_analysis_es.md
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_dehatebert_mono_en.md
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_finbert_en.md
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_japanese_sentiment_ja.md
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_multilingual_sentiment_xx.md
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_rubert_sentiment_ru.md
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_sentiment_de.md
  docs/_posts/maziyarpanahi/2021-11-03-bert_sequence_classifier_turkish_sentiment_tr.md
  docs/_posts/muhammetsnts/2021-10-31-sbiobertresolve_icd10cm_augmented_en.md
  docs/_posts/muhammetsnts/2021-11-01-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
Labels: models_hub, new model

#6372 2021-11-03-robertaresolve_snomed_es
  docs/_posts/josejuanmartinez/2021-11-03-robertaresolve_snomed_es.md
Labels: new model

#6385 2021-11-03-bert_token_classifier_ner_bionlp_en
  docs/_posts/murat-gunay/2021-11-03-bert_token_classifier_ner_bionlp_en.md
Labels: new model

#6391 2021-11-03-ner_profiling_biobert_en
  docs/_posts/muhammetsnts/2021-11-03-ner_profiling_biobert_en.md
Labels: new model

#6389 2021-11-03-ner_profiling_clinical_en
  docs/_posts/muhammetsnts/2021-11-03-ner_profiling_clinical_en.md
Labels: new model

#6398 2021-11-04-sbiobertresolve_rxnorm_augmented_en
  docs/_posts/galiph/2021-11-04-sbiobertresolve_rxnorm_augmented_en.md
Labels: new model

#6397 Docs: Fixed some issues with Comet documentation
  docs/en/third-party-projects.md
  python/docs/third_party/Comet.rst
  python/sparknlp/logging/comet.py
Labels: documentation

#6403 2021-11-05-bert_sequence_classifier_question_statement_clinical_en
  docs/_posts/josejuanmartinez/2021-11-05-bert_sequence_classifier_question_statement_clinical_en.md
Labels: new model

#6402 2021-11-05-ner_covid_trials_en
  docs/_posts/HashamUlHaq/2021-11-05-ner_covid_trials_en.md
Labels: new model

#6400 2021-11-04-ner_chemd_clinical_en
  docs/_posts/murat-gunay/2021-11-04-ner_chemd_clinical_en.md
Labels: new model

#6399 2021-11-04-bert_sequence_classifier_question_statement_en
  docs/_posts/josejuanmartinez/2021-11-04-bert_sequence_classifier_question_statement_en.md
Labels: new model

#6395 2021-11-04-roberta_ner_diag_proc_es
  docs/_posts/josejuanmartinez/2021-11-04-roberta_ner_diag_proc_es.md
Labels: new model

#6420 general updates to alab instructions
  docs/_data/navigation.yml
  docs/en/alab/project_setup.md
  docs/en/alab/start_page.md
  docs/en/alab/user_management.md
Labels: documentation

#6415 2021-11-06-bert_sequence_classifier_antisemitism_en
  docs/_posts/murat-gunay/2021-11-06-bert_sequence_classifier_antisemitism_en.md
Labels: new model

#6419 2021-11-06-bert_sequence_classifier_hatexplain_en
  docs/_posts/murat-gunay/2021-11-06-bert_sequence_classifier_hatexplain_en.md
Labels: new model

#6394 2021-11-04-classifierdl_use_sentiment_pipeline_tr
  docs/_posts/murat-gunay/2021-11-04-classifierdl_use_sentiment_pipeline_tr.md
Labels: new model

#6421 2021-11-06-bert_sequence_classifier_trec_coarse_en
  docs/_posts/murat-gunay/2021-11-06-bert_sequence_classifier_trec_coarse_en.md
Labels: new model

#6422 2021-11-07-bert_sequence_classifier_banking77_en
  docs/_posts/murat-gunay/2021-11-07-bert_sequence_classifier_banking77_en.md
Labels: new model

#6433 Docs/libs install
  docs/en/licensed_install.md
Labels: documentation

#6435 added the NLP libs install script
  docs/en/licensed_install.md
Labels: documentation

#6437 updated installation instructions
  docs/en/licensed_install.md
Labels: documentation

#6423 2021-11-07-bert_sequence_classifier_song_lyrics_en
  docs/_posts/murat-gunay/2021-11-07-bert_sequence_classifier_song_lyrics_en.md
Labels: new model

#6424 2021-11-07-bert_sequence_classifier_age_news_en
  docs/_posts/murat-gunay/2021-11-07-bert_sequence_classifier_age_news_en.md
Labels: new model

#6425 2021-11-07-bert_sequence_classifier_sms_spam_en
  docs/_posts/murat-gunay/2021-11-07-bert_sequence_classifier_sms_spam_en.md
Labels: new model

#6441 2021-11-09-sbiobertresolve_rxnorm_augmented_en
  docs/_posts/galiph/2021-11-09-sbiobertresolve_rxnorm_augmented_en.md
Labels: new model

#6450 2021-11-11-sbiobertresolve_snomed_procedures_measurements_en
  docs/_posts/HashamUlHaq/2021-11-11-sbiobertresolve_snomed_procedures_measurements_en.md
Labels: new model

#6451 2021-11-11-classifierdl_bertwiki_finance_sentiment_pipeline_en
  docs/_posts/murat-gunay/2021-11-11-classifierdl_bertwiki_finance_sentiment_pipeline_en.md
Labels: new model

#6454 installation image is added
  docs/assets/images/installation/amazon-linux.png
Labels: documentation

#6467 Docs/alab2.3.0
  docs/assets/images/annotation_lab/2.3.0/import_pdf.png
  docs/assets/images/annotation_lab/2.3.0/import_pdf_2.png
  docs/assets/images/annotation_lab/2.3.0/multi-page_pdf.png
  docs/assets/images/annotation_lab/2.3.0/multi-page_pdf2.png
  docs/assets/images/annotation_lab/2.3.0/relations.gif
  docs/en/alab/annotation.md
  docs/en/alab/release_notes.md
  docs/en/alab/visual_ner.md
  docs/en/license_getting_started.md
  docs/en/licensed_install.md
Labels: documentation

#6471 Added Docs for Doc2Vec
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecModel.scala
Labels: documentation

#6463 2021-11-14-sbiobertresolve_mesh_en
  docs/_posts/muhammetsnts/2021-11-14-sbiobertresolve_mesh_en.md
Labels: new model

#6439 Adding timestamp in logging file's name
  src/main/scala/com/johnsnowlabs/ml/tensorflow/Logging.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
Labels: on-hold, new-feature, DON'T MERGE

#6449 feature: script for setting up spark and spark nlp on a sagemaker kernel
  scripts/sagemaker_setup.sh
Labels: documentation, DON'T MERGE

#6455 amazon linux 2 installation
  docs/en/install.md
  docs/en/licensed_install.md
Labels: documentation, DON'T MERGE

#6458 Modifies Models Resolution
  src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceMetadata.scala
  src/main/scala/com/johnsnowlabs/util/Version.scala
  src/test/resources/resource-downloader/test_bert_v2_newest.json
  src/test/resources/resource-downloader/test_bert_v3_newest.json
  src/test/resources/resource-downloader/test_example1.json
  src/test/resources/resource-downloader/test_models_same_time.json
  src/test/resources/resource-downloader/test_v2_latest_date.json
  src/test/resources/resource-downloader/test_with_spark_3.2.json
  src/test/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerTest.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/CloudTestResources.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/MockResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceMedataTest.scala
  src/test/scala/com/johnsnowlabs/nlp/util/VersionTest.scala
Labels: enhancement, on-hold, DON'T MERGE

#6460 Add support to labels as LongType in ClassifierDL and SentimentDL
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
Labels: new-feature, DON'T MERGE

#6461 Fix MarianTransformer crashing on both empty sequence or longer than 512
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformerTestSpec.scala
Labels: bug-fix, on-hold, DON'T MERGE

#6462 Optimized batch processing for Bert sentence and word embeddings
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
Labels: enhancement, on-hold, DON'T MERGE

#6474 Introducing Distributed and Trainable Doc2Vec annotators
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecModel.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/resources/aclImdb/test/part-00000-8404c1b6-217a-4219-9729-c805c5f1f685-c000.snappy.parquet
  src/test/resources/aclImdb/test/part-00001-8404c1b6-217a-4219-9729-c805c5f1f685-c000.snappy.parquet
  src/test/resources/aclImdb/test/part-00002-8404c1b6-217a-4219-9729-c805c5f1f685-c000.snappy.parquet
  src/test/resources/aclImdb/test/part-00003-8404c1b6-217a-4219-9729-c805c5f1f685-c000.snappy.parquet
  src/test/resources/aclImdb/test/part-00004-8404c1b6-217a-4219-9729-c805c5f1f685-c000.snappy.parquet
  src/test/resources/aclImdb/test/part-00005-8404c1b6-217a-4219-9729-c805c5f1f685-c000.snappy.parquet
  src/test/resources/aclImdb/test/part-00006-8404c1b6-217a-4219-9729-c805c5f1f685-c000.snappy.parquet
  src/test/resources/aclImdb/test/part-00007-8404c1b6-217a-4219-9729-c805c5f1f685-c000.snappy.parquet
  src/test/resources/aclImdb/test/part-00008-8404c1b6-217a-4219-9729-c805c5f1f685-c000.snappy.parquet
  src/test/resources/aclImdb/train/part-00000-0e52c8df-2da7-403e-b22e-48335b5de23a-c000.snappy.parquet
  src/test/resources/aclImdb/train/part-00001-0e52c8df-2da7-403e-b22e-48335b5de23a-c000.snappy.parquet
  src/test/resources/aclImdb/train/part-00002-0e52c8df-2da7-403e-b22e-48335b5de23a-c000.snappy.parquet
  src/test/resources/aclImdb/train/part-00003-0e52c8df-2da7-403e-b22e-48335b5de23a-c000.snappy.parquet
  src/test/resources/aclImdb/train/part-00004-0e52c8df-2da7-403e-b22e-48335b5de23a-c000.snappy.parquet
  src/test/resources/aclImdb/train/part-00005-0e52c8df-2da7-403e-b22e-48335b5de23a-c000.snappy.parquet
  src/test/resources/aclImdb/train/part-00006-0e52c8df-2da7-403e-b22e-48335b5de23a-c000.snappy.parquet
  src/test/resources/aclImdb/train/part-00007-0e52c8df-2da7-403e-b22e-48335b5de23a-c000.snappy.parquet
  src/test/resources/aclImdb/train/part-00008-0e52c8df-2da7-403e-b22e-48335b5de23a-c000.snappy.parquet
Labels: new-feature, new model, DON'T MERGE

#6475 Introducing a DistilBertForSequenceClassification annotator
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDistilBertClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
Labels: new-feature, new model, DON'T MERGE

#6482 Optimized Conll Reader
  python/sparknlp/training.py
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
Labels: enhancement, new-feature

#6481 Updated docs for release 333
  docs/en/annotator_entries/Doc2Vec.md
  docs/en/annotators.md
  docs/en/training.md
  docs/en/training_entries/Doc2VecApproach.md
  docs/en/transformer_entries/DistilBertForSequenceClassification.md
  python/sparknlp/annotator.py
  python/sparknlp/base.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlnetForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala
Labels: documentation

#6487 Bugfix/date relaxed matcher subword month
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
Labels: bug-fix

#6489 2021-11-21-doc2vec_gigaword_300_en
  docs/_posts/maziyarpanahi/2021-11-21-doc2vec_gigaword_300_en.md
Labels: new model

#6490 2021-11-21-doc2vec_gigaword_wiki_300_en
  docs/_posts/maziyarpanahi/2021-11-21-doc2vec_gigaword_wiki_300_en.md
Labels: new model

#6491 2021-11-21-distilbert_sequence_classifier_policy_en
  docs/_posts/maziyarpanahi/2021-11-21-distilbert_sequence_classifier_policy_en.md
Labels: new model

#6492 2021-11-21-distilbert_sequence_classifier_industry_en
  docs/_posts/maziyarpanahi/2021-11-21-distilbert_sequence_classifier_industry_en.md
Labels: new model

#6493 2021-11-21-distilbert_sequence_classifier_sst2_en
  docs/_posts/maziyarpanahi/2021-11-21-distilbert_sequence_classifier_sst2_en.md
Labels: new model

#6494 2021-11-21-distilbert_sequence_classifier_emotion_en
  docs/_posts/maziyarpanahi/2021-11-21-distilbert_sequence_classifier_emotion_en.md
Labels: new model

#6495 2021-11-21-distilbert_sequence_classifier_banking77_en
  docs/_posts/maziyarpanahi/2021-11-21-distilbert_sequence_classifier_banking77_en.md
Labels: new model

#6496 2021-11-21-distilbert_multilingual_sequence_classifier_allocine_fr
  docs/_posts/maziyarpanahi/2021-11-21-distilbert_multilingual_sequence_classifier_allocine_fr.md
Labels: new model

#6497 2021-11-21-distilbert_base_sequence_classifier_imdb_en
  docs/_posts/maziyarpanahi/2021-11-21-distilbert_base_sequence_classifier_imdb_en.md
Labels: new model

#6498 2021-11-21-distilbert_base_sequence_classifier_ag_news_en
  docs/_posts/maziyarpanahi/2021-11-21-distilbert_base_sequence_classifier_ag_news_en.md
Labels: new model

#6499 2021-11-21-distilbert_base_sequence_classifier_imdb_ur
  docs/_posts/maziyarpanahi/2021-11-21-distilbert_base_sequence_classifier_imdb_ur.md
Labels: new model

#6500 2021-11-21-distilbert_base_sequence_classifier_amazon_polarity_en
  docs/_posts/maziyarpanahi/2021-11-21-distilbert_base_sequence_classifier_amazon_polarity_en.md
Labels: new model

#6504 Added missing pretrained models in models hub
  docs/_posts/maziyarpanahi/2021-11-22-lemma_antbnc_en.md
  docs/_posts/maziyarpanahi/2021-11-22-sentiment_vivekn_en.md
  docs/_posts/maziyarpanahi/2021-11-22-spellcheck_norvig.md
Labels: documentation, models_hub

#6509 2021-11-23-sbiobertresolve_loinc_augmented_en
  docs/_posts/iamvarol/2021-11-23-sbiobertresolve_loinc_augmented_en.md
Labels: new model

#6511 2021-11-24-sbertresolve_ner_model_finder_en
  docs/_posts/muhammetsnts/2021-11-24-sbertresolve_ner_model_finder_en.md
Labels: new model

#6510 2021-11-24-ner_model_finder_en
  docs/_posts/muhammetsnts/2021-11-24-ner_model_finder_en.md
Labels: new model

#6470 2021-11-15-sbiobertresolve_clinical_snomed_procedures_measurements_en
  docs/_posts/HashamUlHaq/2021-11-15-sbiobertresolve_clinical_snomed_procedures_measurements_en.md
Labels: new model

#6477 2021-11-16-redl_nihss_biobert_en
  docs/_posts/HashamUlHaq/2021-11-16-redl_nihss_biobert_en.md
Labels: new model

#6473 2021-11-15-ner_nihss_en
  docs/_posts/HashamUlHaq/2021-11-15-ner_nihss_en.md
Labels: new model

#6513 Fix the wrong name for DistilBertForSequenceClassification in Python
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassification.scala
Labels: bug-fix

#6516 removed broken link from menu
  docs/_includes/demomenu.html
Labels: documentation

#6519 2021-11-26-ner_biomarker_en
  docs/_posts/HashamUlHaq/2021-11-26-ner_biomarker_en.md
Labels: new model

#6521 2021-11-27-sbiobertresolve_ndc_en
  docs/_posts/muhammetsnts/2021-11-27-sbiobertresolve_ndc_en.md
Labels: new model
