Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-07, with the labels that each got.

#5758 2021-07-01-rxnorm_mesh_mapping_en
  docs/_posts/HashamUlHaq/2021-07-01-rxnorm_mesh_mapping_en.md
Labels: new model

#5757 2021-07-01-snomed_umls_mapping_en
  docs/_posts/HashamUlHaq/2021-07-01-snomed_umls_mapping_en.md
Labels: new model

#5756 2021-07-01-rxnorm_umls_mapping_en
  docs/_posts/HashamUlHaq/2021-07-01-rxnorm_umls_mapping_en.md
Labels: new model

#5755 2021-07-01-mesh_umls_mapping_en
  docs/_posts/HashamUlHaq/2021-07-01-mesh_umls_mapping_en.md
Labels: new model

#5754 2021-07-01-icd10cm_umls_mapping_en
  docs/_posts/HashamUlHaq/2021-07-01-icd10cm_umls_mapping_en.md
Labels: new model

#5767 2021-07-02-sbiobertresolve_icdo_base_en
  docs/_posts/HashamUlHaq/2021-07-02-sbiobertresolve_icdo_base_en.md
Labels: new model

#5768 2021-07-02-sbiobertresolve_cpt_procedures_measurements_augmented_en
  docs/_posts/HashamUlHaq/2021-07-02-sbiobertresolve_cpt_procedures_measurements_augmented_en.md
Labels: new model

#5727 Fix XlmRoBertaEmbeddings Scala unit test
  src/test/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddingsTestSpec.scala
Labels: enhancement

#5761 Dynamically extract special tokens ids from SP models in XlmRobertaEmbeddings
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencepieceEncoder.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
Labels: enhancement

#5770 Migrate XlnetEmbeddings to batchAnnotate with TF v2 support
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnet.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddingsTestSpec.scala
Labels: enhancement, new-feature

#5771 Add includeAllConfidenceScores param to NerDLModel and NerDLApproach
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/NerDatasetEncoder.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverterTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
Labels: new-feature

#5773 Synchronize Scala and Python parameters' names
  docs/en/annotator_entries/ContextSpellChecker.md
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcherModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/pos/perceptron/PerceptronApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ws/WordSegmenterApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ws/WordSegmenterModel.scala
  src/test/scala/com/johnsnowlabs/benchmarks/annotators/ws/WordSegmenterBenchmark.scala
  src/test/scala/com/johnsnowlabs/nlp/AnnotatorBuilder.scala
  src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/WordSegmenterTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknSentimentTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/SpellCheckerUseCase.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
Labels: enhancement

#5775 Add missing code block end
  README.md
Labels: documentation

#5765 2021-07-02-nerdl_fewnerd_100d_en
  docs/_posts/murat-gunay/2021-07-02-nerdl_fewnerd_100d_en.md
Labels: new model

#5779 [skip ci] Add NLU video
  docs/learn.md
Labels: documentation, models_hub

#5780 Resolve Issue #5701 With SymmetricDeleteModel
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteModelTestSpec.scala
Labels: bug-fix

#5781 Add new ops for multi-lingual USE models in TensorFlow 2.4.1
  src/main/resources/sp-process/linux/_sentencepiece_tokenizer.so
  src/main/resources/sp-process/mac/_sentencepiece_tokenizer.dylib
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowUSE.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/LoadSentencepiece.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
Labels: bug-fix

#5782 Fixed issue with encoding unknown bytes
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizerTestSpec.scala
Labels: bug-fix

#5783 2021-07-07-xlnet_base_cased_en
  docs/_posts/maziyarpanahi/2021-07-07-xlnet_base_cased_en.md
Labels: new model

#5784 2021-07-07-xlnet_large_cased_en
  docs/_posts/maziyarpanahi/2021-07-07-xlnet_large_cased_en.md
Labels: new model

#5785 2021-07-07-chinese_xlnet_base_zh
  docs/_posts/maziyarpanahi/2021-07-07-chinese_xlnet_base_zh.md
Labels: new model

#5791 Doc: Minor update for python scala API sync
  docs/en/annotator_entries/RegexMatcher.md
  src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
Labels: documentation

#5794 2021-07-08-sbertresolve_snomed_bodyStructure_med_en
  docs/_posts/muhammetsnts/2021-07-08-sbertresolve_snomed_bodyStructure_med_en.md
Labels: new model

#5790 2021-07-08-sbiobertresolve_snomed_bodyStructure_en
  docs/_posts/muhammetsnts/2021-07-08-sbiobertresolve_snomed_bodyStructure_en.md
Labels: new model

#5808 2021-07-12-redl_ade_biobert_en
  docs/_posts/HashamUlHaq/2021-07-12-redl_ade_biobert_en.md
Labels: new model

#5807 2021-07-12-re_ade_clinical_en
  docs/_posts/HashamUlHaq/2021-07-12-re_ade_clinical_en.md
Labels: new model

#5800 2021-07-12-classifierdl_bert_news_de
  docs/_posts/murat-gunay/2021-07-12-classifierdl_bert_news_de.md
Labels: new model

#5812 Add new demos
  docs/assets/images/Classify_visual_documents.svg
  docs/assets/images/Classify_visual_documents_f.svg
  docs/assets/images/Detect_tables_in_documents.svg
  docs/assets/images/Detect_tables_in_documents_f.svg
  docs/assets/images/HPO_coding_Spanish.svg
  docs/assets/images/HPO_coding_Spanish_f.svg
  docs/assets/images/Named_Entity_Recognition_for_Portuguese_Legal_Texts.svg
  docs/assets/images/Named_Entity_Recognition_for_Portuguese_Legal_Texts_f.svg
  docs/assets/images/Translate_text_from_Marathi_to_English.svg
  docs/assets/images/Translate_text_from_Marathi_to_English_f.svg
  docs/assets/images/Translate_text_from_Punjabi_to_English.svg
  docs/assets/images/Translate_text_from_Punjabi_to_English_f.svg
  docs/demos/analyze_non_english_medical_text.md
  docs/demos/extract_tables_structured_data.md
  docs/demos/languages_india.md
Labels: documentation, models_hub

#5815 upgraded licensed release notes
  docs/en/licensed_release_notes.md
Labels: documentation

#5818 2021-07-14-sbiobertresolve_snomed_findings_aux_concepts_en
  docs/_posts/muhammetsnts/2021-07-14-sbiobertresolve_snomed_findings_aux_concepts_en.md
Labels: new model

#5788 Make sure param is not part of the broadcast
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModelPythonReader.scala
  src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
Labels: enhancement, on-hold

#5797 Fix serialization issue in NorvigSweetingModel
  docs/_posts/muhammetsnts/2021-06-15-sbertresolve_snomed_bodyStructure_med_en.md
  docs/en/annotator_entries/RegexMatcher.md
  src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingModel.scala
Labels: bug-fix

#5820 Pydoc Update
  docs/en/annotator_entries/NerOverwriter.md
  docs/en/annotator_entries/WordSegmenter.md
  docs/en/annotators.md
  python/docs/Makefile
  python/docs/README.md
  python/docs/_static/css/custom.css
  python/docs/_static/fav.ico
  python/docs/_static/logo.png
  python/docs/_templates/custom-class-template.rst
  python/docs/_templates/custom-module-template.rst
  python/docs/conf.py
  python/docs/development/index.rst
  python/docs/getting_started/index.rst
  python/docs/index.rst
  python/docs/reference/index.rst
  python/docs/requirements_doc.txt
  python/docs/user_guide/annotation.rst
  python/docs/user_guide/annotators.rst
  python/docs/user_guide/custom_pipelines.rst
  python/docs/user_guide/helpers.rst
  python/docs/user_guide/index.rst
  python/docs/user_guide/light_pipelines.rst
  python/docs/user_guide/pretrained_pipelines.rst
  python/docs/user_guide/training.rst
  python/sparknlp/__init__.py
  python/sparknlp/annotation.py
  python/sparknlp/annotator.py
  python/sparknlp/base.py
  python/sparknlp/common.py
  python/sparknlp/functions.py
  python/sparknlp/internal.py
  python/sparknlp/pretrained.py
  python/sparknlp/training.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerOverwriter.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ws/WordSegmenterApproach.scala
Labels: documentation, new-feature

#5822 PyDoc: adjust requirements.txt
  python/docs/requirements_doc.txt
Labels: documentation, enhancement

#5823 PyDoc: Move generated HTML to api folder
  python/docs/Makefile
  python/docs/README.md
Labels: documentation, enhancement

#5824 2021-07-15-explain_clinical_doc_ade_en
  docs/_posts/HashamUlHaq/2021-07-15-explain_clinical_doc_ade_en.md
Labels: new model

#5830 Update documentation for Spark OCR 3.5.0 release
  docs/assets/images/ocr/display_images_horizontal.png
  docs/assets/images/ocr/display_pdf.png
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
  docs/en/ocr_structures.md
  docs/en/ocr_table_recognition.md
Labels: documentation

#5832 2021-07-19-ner_xtreme_glove_840B_300_xx
  docs/_posts/maziyarpanahi/2021-07-19-ner_xtreme_glove_840B_300_xx.md
Labels: new model

#5833 2021-07-19-ner_xtreme_xlm_roberta_xtreme_base_xx
  docs/_posts/maziyarpanahi/2021-07-19-ner_xtreme_xlm_roberta_xtreme_base_xx.md
Labels: new model

#5834 2021-07-19-xlm_roberta_xtreme_base_xx
  docs/_posts/maziyarpanahi/2021-07-19-xlm_roberta_xtreme_base_xx.md
Labels: new model

#5835 2021-07-19-ner_wikiner_glove_840B_300_xx
  docs/_posts/maziyarpanahi/2021-07-19-ner_wikiner_glove_840B_300_xx.md
Labels: new model

#5836 2021-07-19-ner_wikiner_xlm_roberta_base_xx
  docs/_posts/maziyarpanahi/2021-07-19-ner_wikiner_xlm_roberta_base_xx.md
Labels: new model

#5841 2021-07-20-ner_mit_movie_complex_bert_base_cased_en
  docs/_posts/maziyarpanahi/2021-07-20-ner_mit_movie_complex_bert_base_cased_en.md
Labels: new model

#5842 2021-07-20-ner_mit_movie_complex_distilbert_base_cased_en
  docs/_posts/maziyarpanahi/2021-07-20-ner_mit_movie_complex_distilbert_base_cased_en.md
Labels: new model

#5843 2021-07-20-ner_mit_movie_simple_distilbert_base_cased_en
  docs/_posts/maziyarpanahi/2021-07-20-ner_mit_movie_simple_distilbert_base_cased_en.md
Labels: new model

#5844 2021-07-20-sent_bert_use_cmlm_en_base_en
  docs/_posts/maziyarpanahi/2021-07-20-sent_bert_use_cmlm_en_base_en.md
Labels: new model

#5845 2021-07-20-sent_bert_use_cmlm_en_large_en
  docs/_posts/maziyarpanahi/2021-07-20-sent_bert_use_cmlm_en_large_en.md
Labels: new model

#5846 2021-07-20-sent_bert_use_cmlm_multi_base_br_xx
  docs/_posts/maziyarpanahi/2021-07-20-sent_bert_use_cmlm_multi_base_br_xx.md
Labels: new model

#5847 2021-07-20-sent_bert_use_cmlm_multi_base_xx
  docs/_posts/maziyarpanahi/2021-07-20-sent_bert_use_cmlm_multi_base_xx.md
Labels: new model

#5848 Models hub
  docs/_posts/HashamUlHaq/2021-07-12-re_ade_clinical_en.md
  docs/_posts/HashamUlHaq/2021-07-12-redl_ade_biobert_en.md
  docs/_posts/HashamUlHaq/2021-07-15-explain_clinical_doc_ade_en.md
  docs/_posts/maziyarpanahi/2021-07-19-ner_wikiner_glove_840B_300_xx.md
  docs/_posts/maziyarpanahi/2021-07-19-ner_wikiner_xlm_roberta_base_xx.md
  docs/_posts/maziyarpanahi/2021-07-19-ner_xtreme_glove_840B_300_xx.md
  docs/_posts/maziyarpanahi/2021-07-19-ner_xtreme_xlm_roberta_xtreme_base_xx.md
  docs/_posts/maziyarpanahi/2021-07-19-xlm_roberta_xtreme_base_xx.md
  docs/_posts/maziyarpanahi/2021-07-20-ner_mit_movie_complex_bert_base_cased_en.md
  docs/_posts/maziyarpanahi/2021-07-20-ner_mit_movie_complex_distilbert_base_cased_en.md
  docs/_posts/maziyarpanahi/2021-07-20-ner_mit_movie_simple_distilbert_base_cased_en.md
  docs/_posts/maziyarpanahi/2021-07-20-sent_bert_use_cmlm_en_base_en.md
  docs/_posts/maziyarpanahi/2021-07-20-sent_bert_use_cmlm_en_large_en.md
  docs/_posts/maziyarpanahi/2021-07-20-sent_bert_use_cmlm_multi_base_br_xx.md
  docs/_posts/maziyarpanahi/2021-07-20-sent_bert_use_cmlm_multi_base_xx.md
  docs/_posts/muhammetsnts/2021-07-14-sbiobertresolve_snomed_findings_aux_concepts_en.md
Labels: new model

#5825 2021-07-16-re_ade_biobert_en
  docs/_posts/HashamUlHaq/2021-07-16-re_ade_biobert_en.md
Labels: new model

#5858 3.1.3 licensed release notes
  docs/en/licensed_release_notes.md
Labels: documentation

#5860 Added version compatibility page
  docs/_data/navigation.yml
  docs/en/ocr_install.md
  docs/en/ocr_release_notes.md
  docs/en/version_compatibility.md
Labels: documentation

#5852 2021-07-21-lener_bert_base_pt
  docs/_posts/dcecchini/2021-07-21-lener_bert_base_pt.md
Labels: new model

#5862 2021-07-23-cantemist_scielowiki_es
  docs/_posts/dcecchini/2021-07-23-cantemist_scielowiki_es.md
Labels: new model

#5863 2021-07-24-redl_chemprot_biobert_en
  docs/_posts/muhammetsnts/2021-07-24-redl_chemprot_biobert_en.md
Labels: new model

#5864 2021-07-24-redl_clinical_biobert_en
  docs/_posts/muhammetsnts/2021-07-24-redl_clinical_biobert_en.md
Labels: new model

#5865 2021-07-24-redl_drug_drug_interaction_biobert_en
  docs/_posts/muhammetsnts/2021-07-24-redl_drug_drug_interaction_biobert_en.md
Labels: new model

#5867 2021-07-24-redl_temporal_events_biobert_en
  docs/_posts/muhammetsnts/2021-07-24-redl_temporal_events_biobert_en.md
Labels: new model

#5866 2021-07-24-redl_human_phenotype_gene_biobert_en
  docs/_posts/muhammetsnts/2021-07-24-redl_human_phenotype_gene_biobert_en.md
Labels: new model

#5857 2021-07-22-nerdl_fewnerd_subentity_100d_en
  docs/_posts/murat-gunay/2021-07-22-nerdl_fewnerd_subentity_100d_en.md
Labels: new model

#5851 2021-07-21-classifierdl_berturk_cyberbullying_tr
  docs/_posts/murat-gunay/2021-07-21-classifierdl_berturk_cyberbullying_tr.md
Labels: new model

#5869 2021-07-24-assertion_jsl_large_en
  docs/_posts/muhammetsnts/2021-07-24-assertion_jsl_large_en.md
Labels: new model

#5868 2021-07-24-assertion_jsl_en
  docs/_posts/muhammetsnts/2021-07-24-assertion_jsl_en.md
Labels: new model

#5875 2021-07-26-jsl_ner_wip_greedy_biobert_en
  docs/_posts/HashamUlHaq/2021-07-26-jsl_ner_wip_greedy_biobert_en.md
Labels: new model

#5876 2021-07-26-jsl_rd_ner_wip_greedy_biobert_en
  docs/_posts/HashamUlHaq/2021-07-26-jsl_rd_ner_wip_greedy_biobert_en.md
Labels: new model

#5873 2021-07-25-ms_bluebert_base_uncased_en
  docs/_posts/HashamUlHaq/2021-07-25-ms_bluebert_base_uncased_en.md
Labels: new model

#5883 2021-07-28-lener_bert_large_pt
  docs/_posts/dcecchini/2021-07-28-lener_bert_large_pt.md
Labels: new model

#5882 2021-07-28-lener_bert_base_pt
  docs/_posts/dcecchini/2021-07-28-lener_bert_base_pt.md
Labels: new model

#5877 2021-07-26-meddroprof_scielowiki_es
  docs/_posts/dcecchini/2021-07-26-meddroprof_scielowiki_es.md
Labels: new model

#5887 Introducing BertForTokenClassification annotator
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBertTokenClassification.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sign/ModelSignatureConstants.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassification.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassificationTestSpec.scala
Labels: new model, new-feature

#5890 Introducing LongformerEmbeddings annotator
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowRoBerta.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddingsTestSpec.scala
Labels: new model, new-feature

#5872 Fix wrong version return in sparknlp.version()
  python/sparknlp/__init__.py
Labels: bug-fix, on-hold

#5878 Introducing support for Apache Spark Conf to replace application.conf in Spark NLP
  README.md
  python/run-tests.py
  src/main/resources/application.conf
  src/main/scala/com/johnsnowlabs/nlp/AnnotatorApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/serialization/Feature.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/OutputHelper.scala
  src/main/scala/com/johnsnowlabs/storage/HasStorage.scala
  src/main/scala/com/johnsnowlabs/storage/StorageLocator.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
  src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
  src/test/scala/com/johnsnowlabs/util/ConfigLoaderTest.scala
Labels: new-feature, on-hold

#5879 Introducing a new GraphExtraction annotator
  python/run-tests.py
  python/sparknlp/base.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/AnnotatorType.scala
  src/main/scala/com/johnsnowlabs/nlp/EmbeddingsFinisher.scala
  src/main/scala/com/johnsnowlabs/nlp/Finisher.scala
  src/main/scala/com/johnsnowlabs/nlp/GraphFinisher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/GraphExtraction.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/PretrainedAnnotations.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/DependencyParsed.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/LabeledDependency.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserModel.scala
  src/main/scala/com/johnsnowlabs/nlp/util/FinisherUtil.scala
  src/main/scala/com/johnsnowlabs/nlp/util/GraphBuilder.scala
  src/test/scala/com/johnsnowlabs/nlp/AssertAnnotations.scala
  src/test/scala/com/johnsnowlabs/nlp/EmbeddingsFinisherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/GraphFinisherTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionFixture.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/SparkSessionTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/common/LabeledDependencyTest.scala
  src/test/scala/com/johnsnowlabs/nlp/util/GraphBuilderTest.scala
Labels: new-feature, on-hold
