Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-03, with the labels that each got.

#2342 [skip ci] 2021-03-01-ner_events_admission_clinical_en
  docs/_posts/HashamUlHaq/2021-03-01-ner_events_admission_clinical_en.md
Labels: new model

#2347 [skip ci] 2021-03-02-ner_deid_enriched_en
  docs/_posts/HashamUlHaq/2021-03-02-ner_deid_enriched_en.md
Labels: new model

#2346 [skip ci] Insertion of NLU blocks into onto-ner-models/pipelines and multi lingual use embeddings
  docs/_posts/maziyarpanahi/2020-12-05-onto_bert_base_cased_en.md
  docs/_posts/maziyarpanahi/2020-12-05-onto_bert_large_cased_en.md
  docs/_posts/maziyarpanahi/2020-12-05-onto_electra_base_uncased_en.md
  docs/_posts/maziyarpanahi/2020-12-05-onto_electra_large_uncased_en.md
  docs/_posts/maziyarpanahi/2020-12-05-onto_electra_small_uncased_en.md
  docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L2_128_en.md
  docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L4_256_en.md
  docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L4_512_en.md
  docs/_posts/maziyarpanahi/2020-12-05-onto_small_bert_L8_512_en.md
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_multi_lg_xx.md
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_multi_xx.md
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_de_xx.md
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_es_xx.md
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_en_fr_xx.md
  docs/_posts/maziyarpanahi/2020-12-08-tfhub_use_xling_many_xx.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_base_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_large_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_medium_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_mini_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_small_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_bert_tiny_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_electra_base_en.md
  docs/_posts/maziyarpanahi/2020-12-09-onto_recognize_entities_electra_small_en.md
Labels: documentation, models_hub, updates

#2345 [skip ci] Insertion of NLU blocks into embeddings, lang detector models-pipelines
  docs/_posts/maziyarpanahi/2020-01-02-bert_base_cased.md
  docs/_posts/maziyarpanahi/2020-01-02-bert_base_uncased.md
  docs/_posts/maziyarpanahi/2020-01-02-bert_large_cased.md
  docs/_posts/maziyarpanahi/2020-01-02-bert_large_uncased.md
  docs/_posts/maziyarpanahi/2020-01-31-elmo.md
  docs/_posts/maziyarpanahi/2020-04-17-tfhub_use.md
  docs/_posts/maziyarpanahi/2020-04-17-tfhub_use_lg.md
  docs/_posts/maziyarpanahi/2020-04-28-albert_base_uncased.md
  docs/_posts/maziyarpanahi/2020-04-28-albert_large_uncased.md
  docs/_posts/maziyarpanahi/2020-04-28-albert_xlarge_uncased.md
  docs/_posts/maziyarpanahi/2020-04-28-albert_xxlarge_uncased.md
  docs/_posts/maziyarpanahi/2020-04-28-xlnet_base_cased.md
  docs/_posts/maziyarpanahi/2020-04-28-xlnet_large_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-biobert_clinical_base_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-biobert_discharge_base_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-biobert_pmc_base_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-biobert_pubmed_base_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-biobert_pubmed_large_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-biobert_pubmed_pmc_base_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-sent-biobert_clinical_base_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-sent_biobert_discharge_base_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-sent_biobert_pmc_base_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-sent_biobert_pubmed_base_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-sent_biobert_pubmed_large_cased.md
  docs/_posts/maziyarpanahi/2020-09-19-sent_biobert_pubmed_pmc_base_cased.md
  docs/_posts/maziyarpanahi/2020-09-23-labse.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_21_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_220_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_231_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_375_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_43_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_95_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_99_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-detect_language_bigru_21_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_tatoeba_bigru_21_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_tatoeba_cnn_99_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_cnn_231_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_21_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_220_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_375_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_43_xx.md
  docs/_posts/maziyarpanahi/2020-12-05-ld_wiki_tatoeba_cnn_95_xx.md
Labels: documentation, models_hub, updates

#2323 [skip ci] Insertion of NLU blocks into md files of dchecchini folder
  docs/_posts/dcecchini/2021-01-03-ner_msra_bert_768d_zh.md
  docs/_posts/dcecchini/2021-01-03-ner_ud_kaist_glove_840B_300d_ko.md
  docs/_posts/dcecchini/2021-01-03-wordseg_ctb9_zh.md
  docs/_posts/dcecchini/2021-01-03-wordseg_gsd_ud_ja.md
  docs/_posts/dcecchini/2021-01-03-wordseg_kaist_ud_ko.md
  docs/_posts/dcecchini/2021-01-03-wordseg_large_zh.md
  docs/_posts/dcecchini/2021-01-03-wordseg_msra_zh.md
  docs/_posts/dcecchini/2021-01-03-wordseg_pku_zh.md
  docs/_posts/dcecchini/2021-01-03-wordseg_weibo_zh.md
  docs/_posts/dcecchini/2021-01-04-ner_weibo_bert_768d_zh.md
  docs/_posts/dcecchini/2021-01-11-ner_lst20_glove_840B_300d_th.md
  docs/_posts/dcecchini/2021-01-13-wordseg_best_th.md
  docs/_posts/dcecchini/2021-01-14-sentiment_jager_use_th.md
  docs/_posts/dcecchini/2021-01-25-wordseg_gsd_ud_trad_zh.md
  docs/_posts/dcecchini/2021-01-27-ner_jifs_glove_840B_300d_bn.md
Labels: documentation, models_hub, updates

#2351 added metadata to models.json [skip ci]
  docs/models.json
Labels: documentation

#2354 [skip ci] updates of public annotator pages
  docs/en/annotators.md
Labels: documentation, updates

#2358 Make Spark NLP on Apache Spark 3.0 a default package
  .github/workflows/build_and_test.yml
  .gitignore
  build.sbt
  project/build.properties
  project/plugins.sbt
  python/sparknlp/__init__.py
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserModelTestSpec.scala
Labels: enhancement

#2365 [skip ci] 2021-03-05-pos_anc_spk3_en
  docs/_posts/C-K-Loan/2021-03-05-pos_anc_spk3_en.md
Labels: new model

#2336 fix for BigDecimal bug in NER training
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
Labels: bug-fix

#2337 Shading Hadoop AWS and AWS Java SDK for better EMR intgration
  build.sbt
Labels: enhancement, on-hold

#2368 pos anc docs update
  docs/_posts/C-K-Loan/2021-03-05-pos_anc_spk3_en.md
Labels: documentation, models_hub

#2370 Added error message handler at catalyst level in NorvigSweetingApproach
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala
Labels: enhancement

#2371 Added Spark cross version exception handler in Norvig Approach
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala
Labels: enhancement

#2377 [skip ci] 2021-03-08-pos_ud_isdt_it
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_isdt_it.md
Labels: new model

#2380 [skip ci] 2021-03-08-pos_ud_hdt_de
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_hdt_de.md
Labels: new model

#2381 [skip ci] 2021-03-08-pos_ud_ewt_en
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_ewt_en.md
Labels: new model

#2382 [skip ci] 2021-03-08-pos_ud_gsd_es
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_gsd_es.md
Labels: new model

#2383 [skip ci] 2021-03-08-pos_ud_gsd_ru
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_gsd_ru.md
Labels: new model

#2384 [skip ci] 2021-03-08-pos_ud_imst_tr
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_imst_tr.md
Labels: new model

#2385 [skip ci] 2021-03-08-pos_ud_bosque_pt
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_bosque_pt.md
Labels: new model

#2386 [skip ci] 2021-03-08-pos_ud_lfg_pl
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_lfg_pl.md
Labels: new model

#2387 [skip ci] 2021-03-08-pos_ud_alpino_nl
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_alpino_nl.md
Labels: new model

#2388 [skip ci] 2021-03-08-pos_ud_gsd_zh
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_gsd_zh.md
Labels: new model

#2389 [skip ci] 2021-03-08-pos_ud_btb_bg
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_btb_bg.md
Labels: new model

#2390 [skip ci] 2021-03-08-pos_ud_pdt_cs
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_pdt_cs.md
Labels: new model

#2392 [skip ci] 2021-03-08-pos_ud_rrt_ro
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_rrt_ro.md
Labels: new model

#2393 [skip ci] 2021-03-08-pos_ud_snk_sk
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_snk_sk.md
Labels: new model

#2394 [skip ci] 2021-03-08-pos_ud_tal_sv
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_tal_sv.md
Labels: new model

#2395 [skip ci] 2021-03-08-pos_ud_iu_uk
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_iu_uk.md
Labels: new model

#2396 [skip ci] 2021-03-08-pos_ud_szeged_hu
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_szeged_hu.md
Labels: new model

#2397 [skip ci] 2021-03-08-pos_ud_gdt_el
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_gdt_el.md
Labels: new model

#2408 [skip ci] 2021-03-09-pos_ud_armtdp_hy
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_armtdp_hy.md
Labels: new model

#2409 [skip ci] 2021-03-09-pos_ud_bdt_eu
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_bdt_eu.md
Labels: new model

#2410 [skip ci] 2021-03-09-pos_ud_keb_br
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_keb_br.md
Labels: new model

#2411 [skip ci] 2021-03-09-pos_ud_ancora_ca
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_ancora_ca.md
Labels: new model

#2412 [skip ci] 2021-03-09-pos_ud_ddt_da
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_ddt_da.md
Labels: new model

#2413 [skip ci] 2021-03-09-pos_ud_treegal_gl
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_treegal_gl.md
Labels: new model

#2414 [skip ci] 2021-03-09-pos_ud_hdtb_hi
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_hdtb_hi.md
Labels: new model

#2415 [skip ci] 2021-03-09-pos_ud_gsd_id
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_gsd_id.md
Labels: new model

#2416 [skip ci] 2021-03-09-pos_ud_idt_ga
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_idt_ga.md
Labels: new model

#2417 [skip ci] 2021-03-09-pos_ud_llct_la
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_llct_la.md
Labels: new model

#2418 [skip ci] 2021-03-09-pos_ud_lvtb_lv
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_lvtb_lv.md
Labels: new model

#2419 [skip ci] 2021-03-09-pos_ud_ufal_mr
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_ufal_mr.md
Labels: new model

#2420 [skip ci] 2021-03-09-pos_ud_ssj_sl
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_ssj_sl.md
Labels: new model

#2421 [skip ci] 2021-03-09-pos_ud_ytb_yo
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_ytb_yo.md
Labels: new model

#2422 [skip ci] 2021-03-09-pos_ud_padt_ar
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_padt_ar.md
Labels: new model

#2424 [skip ci] 2021-03-09-pos_ud_udtb_ur
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_udtb_ur.md
Labels: new model

#2425 [skip ci] 2021-03-09-pos_ud_htb_he
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_htb_he.md
Labels: new model

#2426 [skip ci] 2021-03-09-wordseg_ctb9_zh
  docs/_posts/C-K-Loan/2021-03-09-wordseg_ctb9_zh.md
Labels: new model

#2427 [skip ci] 2021-03-09-wordseg_gsd_ud_ja
  docs/_posts/C-K-Loan/2021-03-09-wordseg_gsd_ud_ja.md
Labels: new model

#2428 [skip ci] 2021-03-09-wordseg_kaist_ud_ko
  docs/_posts/C-K-Loan/2021-03-09-wordseg_kaist_ud_ko.md
Labels: new model

#2429 [skip ci] 2021-03-09-wordseg_msra_zh
  docs/_posts/C-K-Loan/2021-03-09-wordseg_msra_zh.md
Labels: new model

#2430 [skip ci] 2021-03-09-wordseg_pku_zh
  docs/_posts/C-K-Loan/2021-03-09-wordseg_pku_zh.md
Labels: new model

#2431 [skip ci] 2021-03-09-wordseg_weibo_zh
  docs/_posts/C-K-Loan/2021-03-09-wordseg_weibo_zh.md
Labels: new model

#2432 [skip ci] 2021-03-09-pos_ud_gsd_zh
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_gsd_zh.md
Labels: new model

#2433 [skip ci] 2021-03-09-pos_ud_gsd_ja
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_gsd_ja.md
Labels: new model

#2436 [skip ci] 2021-03-09-pos_ud_bhtb_bh
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_bhtb_bh.md
Labels: new model

#2437 [skip ci] 2021-03-09-pos_msri_bn
  docs/_posts/C-K-Loan/2021-03-09-pos_msri_bn.md
Labels: new model

#2439 [skip ci] 2021-03-09-pos_ud_gsd_trad_zh
  docs/_posts/C-K-Loan/2021-03-09-pos_ud_gsd_trad_zh.md
Labels: new model

#2401 [skip ci] 2021-03-08-spellcheck_dl_it
  docs/_posts/albertoandreottiATgmail/2021-03-08-spellcheck_dl_it.md
Labels: new model

#2372 Introducing BatchAnnotate in BertSentenceEmbeddings
  python/setup.py
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/HasBatchedAnnotate.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddingsTestSpec.scala
Labels: enhancement, on-hold

#2446 fix shadding package
  build.sbt
Labels: enhancement

#2447 [skip ci] 2021-03-10-pos_ttb_ta
  docs/_posts/dcecchini/2021-03-10-pos_ttb_ta.md
Labels: new model

#2448 [skip ci] 2021-03-10-pos_mtg_te
  docs/_posts/dcecchini/2021-03-10-pos_mtg_te.md
Labels: new model

#2449 [skip ci] 2021-03-10-pos_vtb_vi
  docs/_posts/dcecchini/2021-03-10-pos_vtb_vi.md
Labels: new model

#2451 2021-03-11-tfhub_use_multi_xx
  docs/_posts/maziyarpanahi/2021-03-11-tfhub_use_multi_xx.md
Labels: new model

#2452 2021-03-11-tfhub_use_multi_lg_xx
  docs/_posts/maziyarpanahi/2021-03-11-tfhub_use_multi_lg_xx.md
Labels: new model

#2463 [skip ci] 2021-03-15-ner_deid_large_en
  docs/_posts/HashamUlHaq/2021-03-15-ner_deid_large_en.md
Labels: new model

#2465 [skip ci] 2021-03-16-sentence_detector_dl_healthcare_en
  docs/_posts/HashamUlHaq/2021-03-16-sentence_detector_dl_healthcare_en.md
Labels: new model

#2474 2021-03-18-assertion_dl_radiology_en
  docs/_posts/murat-gunay/2021-03-18-assertion_dl_radiology_en.md
Labels: new model

#2491 2021-03-22-explain_document_sm_es
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_es.md
Labels: new model

#2492 2021-03-22-explain_document_sm_ru
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_ru.md
Labels: new model

#2493 2021-03-22-explain_document_sm_pt
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_pt.md
Labels: new model

#2494 2021-03-22-explain_document_sm_pl
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_pl.md
Labels: new model

#2495 2021-03-22-explain_document_sm_nl
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_nl.md
Labels: new model

#2497 2021-03-22-explain_document_sm_no
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_no.md
Labels: new model

#2498 2021-03-22-explain_document_sm_sv
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_sv.md
Labels: new model

#2499 2021-03-22-explain_document_sm_da
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_da.md
Labels: new model

#2500 2021-03-22-explain_document_sm_fi
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_fi.md
Labels: new model

#2501 2021-03-22-explain_document_md_fr
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_fr.md
Labels: new model

#2502 2021-03-22-explain_document_md_it
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_it.md
Labels: new model

#2503 2021-03-22-explain_document_md_de
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_de.md
Labels: new model

#2504 2021-03-22-explain_document_md_es
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_es.md
Labels: new model

#2505 2021-03-22-explain_document_md_ru
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_ru.md
Labels: new model

#2506 2021-03-22-explain_document_md_pt
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_pt.md
Labels: new model

#2508 2021-03-22-explain_document_md_pl
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_pl.md
Labels: new model

#2509 2021-03-22-explain_document_md_nl
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_nl.md
Labels: new model

#2510 2021-03-22-explain_document_md_no
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_no.md
Labels: new model

#2511 2021-03-22-explain_document_md_sv
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_sv.md
Labels: new model

#2512 2021-03-22-explain_document_md_da
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_da.md
Labels: new model

#2515 2021-03-22-onto_recognize_entities_sm_en
  docs/_posts/C-K-Loan/2021-03-22-onto_recognize_entities_sm_en.md
Labels: new model

#2516 2021-03-22-entity_recognizer_sm_es
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_es.md
Labels: new model

#2517 2021-03-22-entity_recognizer_sm_ru
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_ru.md
Labels: new model

#2518 2021-03-22-entity_recognizer_sm_pt
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_pt.md
Labels: new model

#2519 2021-03-22-entity_recognizer_sm_pl
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_pl.md
Labels: new model

#2514 2021-03-22-explain_document_md_fi
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_fi.md
Labels: new model

#2520 2021-03-22-entity_recognizer_sm_nl
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_nl.md
Labels: new model

#2521 2021-03-22-entity_recognizer_sm_no
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_no.md
Labels: new model

#2522 2021-03-22-entity_recognizer_sm_sv
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_sv.md
Labels: new model

#2523 2021-03-22-entity_recognizer_sm_da
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_da.md
Labels: new model

#2524 2021-03-22-entity_recognizer_sm_fi
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_fi.md
Labels: new model

#2525 2021-03-22-onto_recognize_entities_bert_small_en
  docs/_posts/C-K-Loan/2021-03-22-onto_recognize_entities_bert_small_en.md
Labels: new model

#2526 2021-03-22-onto_recognize_entities_electra_small_en
  docs/_posts/C-K-Loan/2021-03-22-onto_recognize_entities_electra_small_en.md
Labels: new model

#2527 Models hub
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_da.md
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_es.md
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_fi.md
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_nl.md
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_no.md
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_pl.md
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_pt.md
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_ru.md
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_sm_sv.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_da.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_de.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_es.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_fi.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_fr.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_it.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_nl.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_no.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_pl.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_pt.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_ru.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_md_sv.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_da.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_es.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_fi.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_nl.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_no.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_pl.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_pt.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_ru.md
  docs/_posts/C-K-Loan/2021-03-22-explain_document_sm_sv.md
  docs/_posts/C-K-Loan/2021-03-22-onto_recognize_entities_bert_small_en.md
  docs/_posts/C-K-Loan/2021-03-22-onto_recognize_entities_electra_small_en.md
  docs/_posts/C-K-Loan/2021-03-22-onto_recognize_entities_sm_en.md
  docs/_posts/HashamUlHaq/2021-03-15-ner_deid_large_en.md
  docs/_posts/HashamUlHaq/2021-03-16-sentence_detector_dl_healthcare_en.md
  docs/_posts/murat-gunay/2021-03-18-assertion_dl_radiology_en.md
Labels: new model

#2528 2021-03-22-entity_recognizer_md_fr
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_fr.md
Labels: new model

#2529 2021-03-22-entity_recognizer_md_it
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_it.md
Labels: new model

#2530 2021-03-22-entity_recognizer_md_de
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_de.md
Labels: new model

#2531 2021-03-22-entity_recognizer_md_es
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_es.md
Labels: new model

#2532 2021-03-22-entity_recognizer_md_ru
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_ru.md
Labels: new model

#2533 2021-03-22-entity_recognizer_md_pt
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_pt.md
Labels: new model

#2534 2021-03-22-entity_recognizer_md_pl
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_pl.md
Labels: new model

#2535 2021-03-22-entity_recognizer_md_nl
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_nl.md
Labels: new model

#2536 2021-03-22-entity_recognizer_md_no
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_no.md
Labels: new model

#2537 2021-03-22-entity_recognizer_md_sv
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_sv.md
Labels: new model

#2538 2021-03-22-entity_recognizer_md_da
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_da.md
Labels: new model

#2539 2021-03-22-entity_recognizer_md_fi
  docs/_posts/C-K-Loan/2021-03-22-entity_recognizer_md_fi.md
Labels: new model

#2543 2021-03-23-entity_recognizer_lg_fr
  docs/_posts/C-K-Loan/2021-03-23-entity_recognizer_lg_fr.md
Labels: new model

#2544 2021-03-23-entity_recognizer_lg_it
  docs/_posts/C-K-Loan/2021-03-23-entity_recognizer_lg_it.md
Labels: new model

#2545 2021-03-23-explain_document_ml_en
  docs/_posts/C-K-Loan/2021-03-23-explain_document_ml_en.md
Labels: new model

#2546 2021-03-23-explain_document_dl_en
  docs/_posts/C-K-Loan/2021-03-23-explain_document_dl_en.md
Labels: new model

#2547 2021-03-23-recognize_entities_dl_en
  docs/_posts/C-K-Loan/2021-03-23-recognize_entities_dl_en.md
Labels: new model

#2548 2021-03-23-recognize_entities_bert_en
  docs/_posts/C-K-Loan/2021-03-23-recognize_entities_bert_en.md
Labels: new model

#2549 2021-03-23-onto_recognize_entities_bert_base_en
  docs/_posts/C-K-Loan/2021-03-23-onto_recognize_entities_bert_base_en.md
Labels: new model

#2550 2021-03-23-onto_recognize_entities_bert_large_en
  docs/_posts/C-K-Loan/2021-03-23-onto_recognize_entities_bert_large_en.md
Labels: new model

#2551 2021-03-23-onto_recognize_entities_bert_medium_en
  docs/_posts/C-K-Loan/2021-03-23-onto_recognize_entities_bert_medium_en.md
Labels: new model

#2552 2021-03-23-onto_recognize_entities_bert_mini_en
  docs/_posts/C-K-Loan/2021-03-23-onto_recognize_entities_bert_mini_en.md
Labels: new model

#2553 2021-03-23-onto_recognize_entities_bert_tiny_en
  docs/_posts/C-K-Loan/2021-03-23-onto_recognize_entities_bert_tiny_en.md
Labels: new model

#2554 2021-03-23-onto_recognize_entities_electra_base_en
  docs/_posts/C-K-Loan/2021-03-23-onto_recognize_entities_electra_base_en.md
Labels: new model

#2556 2021-03-23-onto_recognize_entities_electra_large_en
  docs/_posts/C-K-Loan/2021-03-23-onto_recognize_entities_electra_large_en.md
Labels: new model

#2564 2021-03-23-check_spelling_dl_en
  docs/_posts/muhammetsnts/2021-03-23-check_spelling_dl_en.md
Labels: new model

#2588 2021-03-24-analyze_sentimentdl_glove_imdb_en
  docs/_posts/C-K-Loan/2021-03-24-analyze_sentimentdl_glove_imdb_en.md
Labels: new model

#2587 2021-03-24-clean_stop_en
  docs/_posts/C-K-Loan/2021-03-24-clean_stop_en.md
Labels: new model

#2586 2021-03-24-analyze_sentiment_en
  docs/_posts/C-K-Loan/2021-03-24-analyze_sentiment_en.md
Labels: new model

#2585 2021-03-24-clean_slang_en
  docs/_posts/C-K-Loan/2021-03-24-clean_slang_en.md
Labels: new model

#2584 2021-03-24-clean_pattern_en
  docs/_posts/C-K-Loan/2021-03-24-clean_pattern_en.md
Labels: new model

#2581 2021-03-23-explain_document_lg_fi
  docs/_posts/C-K-Loan/2021-03-23-explain_document_lg_fi.md
Labels: new model

#2580 2021-03-23-explain_document_lg_da
  docs/_posts/C-K-Loan/2021-03-23-explain_document_lg_da.md
Labels: new model

#2579 2021-03-23-explain_document_lg_sv
  docs/_posts/C-K-Loan/2021-03-23-explain_document_lg_sv.md
Labels: new model

#2578 2021-03-23-explain_document_lg_no
  docs/_posts/C-K-Loan/2021-03-23-explain_document_lg_no.md
Labels: new model

#2577 2021-03-23-explain_document_lg_nl
  docs/_posts/C-K-Loan/2021-03-23-explain_document_lg_nl.md
Labels: new model

#2576 2021-03-23-explain_document_lg_pl
  docs/_posts/C-K-Loan/2021-03-23-explain_document_lg_pl.md
Labels: new model

#2575 2021-03-23-pos_talbanken_sv
  docs/_posts/dcecchini/2021-03-23-pos_talbanken_sv.md
Labels: new model

#2574 2021-03-23-pos_snk_sk
  docs/_posts/dcecchini/2021-03-23-pos_snk_sk.md
Labels: new model

#2573 2021-03-23-pos_lfg_pl
  docs/_posts/dcecchini/2021-03-23-pos_lfg_pl.md
Labels: new model

#2572 2021-03-23-pos_icepahc_is
  docs/_posts/dcecchini/2021-03-23-pos_icepahc_is.md
Labels: new model

#2571 2021-03-23-explain_document_lg_pt
  docs/_posts/C-K-Loan/2021-03-23-explain_document_lg_pt.md
Labels: new model

#2570 2021-03-23-pos_cac_cs
  docs/_posts/dcecchini/2021-03-23-pos_cac_cs.md
Labels: new model

#2569 2021-03-23-pos_btb_bg
  docs/_posts/dcecchini/2021-03-23-pos_btb_bg.md
Labels: new model

#2568 2021-03-23-explain_document_lg_ru
  docs/_posts/C-K-Loan/2021-03-23-explain_document_lg_ru.md
Labels: new model
