Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-04, with the labels that each got.

#2707 2021-04-01-ner_traffic_de
  docs/_posts/HashamUlHaq/2021-04-01-ner_traffic_de.md
Labels: new model

#2706 2021-04-01-ner_bionlp_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_bionlp_biobert_en.md
Labels: new model

#2705 2021-04-01-ner_deid_sd_large_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_deid_sd_large_en.md
Labels: new model

#2704 2021-04-01-ner_healthcare_slim_de
  docs/_posts/HashamUlHaq/2021-04-01-ner_healthcare_slim_de.md
Labels: new model

#2703 2021-04-01-ner_risk_factors_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_risk_factors_biobert_en.md
Labels: new model

#2702 2021-04-01-ner_posology_healthcare_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_posology_healthcare_en.md
Labels: new model

#2701 2021-04-01-ner_diseases_large_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_diseases_large_en.md
Labels: new model

#2700 2021-04-01-ner_ade_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_ade_biobert_en.md
Labels: new model

#2699 2021-04-01-ner_jsl_enriched_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_jsl_enriched_biobert_en.md
Labels: new model

#2698 2021-04-01-ner_ade_healthcare_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_ade_healthcare_en.md
Labels: new model

#2697 2021-04-01-ner_deid_sd_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_deid_sd_en.md
Labels: new model

#2696 2021-04-01-ner_events_healthcare_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_events_healthcare_en.md
Labels: new model

#2695 2021-04-01-ner_financial_contract_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_financial_contract_en.md
Labels: new model

#2694 2021-04-01-ner_chemprot_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_chemprot_biobert_en.md
Labels: new model

#2693 2021-04-01-ner_ade_clinicalbert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_ade_clinicalbert_en.md
Labels: new model

#2692 2021-04-01-ner_posology_large_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_posology_large_biobert_en.md
Labels: new model

#2691 2021-04-01-ner_radiology_wip_clinical_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_radiology_wip_clinical_en.md
Labels: new model

#2690 2021-04-01-ner_jsl_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_jsl_biobert_en.md
Labels: new model

#2689 2021-04-01-ner_clinical_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_clinical_biobert_en.md
Labels: new model

#2687 2021-04-01-ner_posology_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_posology_biobert_en.md
Labels: new model

#2686 2021-04-01-ner_cellular_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_cellular_biobert_en.md
Labels: new model

#2685 2021-04-01-jsl_ner_wip_modifier_clinical_en
  docs/_posts/HashamUlHaq/2021-04-01-jsl_ner_wip_modifier_clinical_en.md
Labels: new model

#2684 2021-04-01-ner_measurements_clinical_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_measurements_clinical_en.md
Labels: new model

#2682 2021-04-01-ner_chemicals_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_chemicals_en.md
Labels: new model

#2679 2021-04-01-ner_bacterial_species_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_bacterial_species_en.md
Labels: new model

#2678 2021-04-01-ner_diseases_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_diseases_biobert_en.md
Labels: new model

#2677 2021-04-01-ner_human_phenotype_gene_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_human_phenotype_gene_biobert_en.md
Labels: new model

#2676 2021-04-01-ner_deid_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_deid_biobert_en.md
Labels: new model

#2675 2021-04-01-nerdl_tumour_demo_en
  docs/_posts/HashamUlHaq/2021-04-01-nerdl_tumour_demo_en.md
Labels: new model

#2674 2021-04-01-ner_human_phenotype_go_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_human_phenotype_go_biobert_en.md
Labels: new model

#2673 2021-04-01-ner_anatomy_biobert_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_anatomy_biobert_en.md
Labels: new model

#2672 2021-04-01-ner_clinical_icdem_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_clinical_icdem_en.md
Labels: new model

#2671 2021-04-01-ner_ade_clinical_en
  docs/_posts/HashamUlHaq/2021-04-01-ner_ade_clinical_en.md
Labels: new model

#2670 2021-04-01-jsl_rd_ner_wip_greedy_clinical_en
  docs/_posts/HashamUlHaq/2021-04-01-jsl_rd_ner_wip_greedy_clinical_en.md
Labels: new model

#2709 2021-04-01-explain_clinical_doc_carp_en
  docs/_posts/HashamUlHaq/2021-04-01-explain_clinical_doc_carp_en.md
Labels: new model

#2712 2021-04-01-recognize_entities_posology_en
  docs/_posts/HashamUlHaq/2021-04-01-recognize_entities_posology_en.md
Labels: new model

#2711 2021-04-01-explain_clinical_doc_ade_en
  docs/_posts/HashamUlHaq/2021-04-01-explain_clinical_doc_ade_en.md
Labels: new model

#2710 2021-04-01-explain_clinical_doc_era_en
  docs/_posts/HashamUlHaq/2021-04-01-explain_clinical_doc_era_en.md
Labels: new model

#2713 2021-04-02-chunkresolve_icdo_clinical_en
  docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_icdo_clinical_en.md
Labels: new model

#2721 2021-04-02-chunkresolve_icd10cm_musculoskeletal_clinical_en
  docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_icd10cm_musculoskeletal_clinical_en.md
Labels: new model

#2720 2021-04-02-chunkresolve_icd10cm_injuries_clinical_en
  docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_icd10cm_injuries_clinical_en.md
Labels: new model

#2719 2021-04-02-chunkresolve_icd10pcs_clinical_en
  docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_icd10pcs_clinical_en.md
Labels: new model

#2718 2021-04-02-chunkresolve_icd10cm_neoplasms_clinical_en
  docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_icd10cm_neoplasms_clinical_en.md
Labels: new model

#2717 2021-04-02-chunkresolve_loinc_clinical_en
  docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_loinc_clinical_en.md
Labels: new model

#2716 2021-04-02-chunkresolve_icd10cm_diseases_clinical_en
  docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_icd10cm_diseases_clinical_en.md
Labels: new model

#2715 2021-04-02-chunkresolve_icd10cm_clinical_en
  docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_icd10cm_clinical_en.md
Labels: new model

#2714 2021-04-02-chunkresolve_cpt_clinical_en
  docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_cpt_clinical_en.md
Labels: new model

#2724 2021-04-02-lemma_af
  docs/_posts/dcecchini/2021-04-02-lemma_af.md
Labels: new model

#2727 2021-04-02-lemma_is
  docs/_posts/dcecchini/2021-04-02-lemma_is.md
Labels: new model

#2728 2021-04-02-lemma_mt
  docs/_posts/dcecchini/2021-04-02-lemma_mt.md
Labels: new model

#2733 2021-04-02-lemma_ta
  docs/_posts/dcecchini/2021-04-02-lemma_ta.md
Labels: new model

#2734 2021-04-02-lemma_vi
  docs/_posts/dcecchini/2021-04-02-lemma_vi.md
Labels: new model

#2735 2021-04-02-lemma_cy
  docs/_posts/dcecchini/2021-04-02-lemma_cy.md
Labels: new model

#2468 2021-03-16-pos_afribooms_af
  docs/_posts/dcecchini/2021-03-16-pos_afribooms_af.md
Labels: new model

#2741 2021-04-06-pos_afribooms_af
  docs/_posts/dcecchini/2021-04-06-pos_afribooms_af.md
Labels: new model

#2759 update in healthcare release notes
  docs/en/licensed_release_notes.md
Labels: documentation

#2761 Documentation update for Spark OCR 3.1.0 release
  docs/assets/images/ocr/showImage1.png
  docs/en/ocr.md
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
  docs/en/ocr_structures.md
Labels: documentation

#2767 2021-04-16-chunkresolve_ICD10GM_2021_de
  docs/_posts/HashamUlHaq/2021-04-16-chunkresolve_ICD10GM_2021_de.md
Labels: new model

#2766 2021-04-16-chunkresolve_rxnorm_cd_clinical_en
  docs/_posts/HashamUlHaq/2021-04-16-chunkresolve_rxnorm_cd_clinical_en.md
Labels: new model

#2765 2021-04-16-chunkresolve_rxnorm_scd_clinical_en
  docs/_posts/HashamUlHaq/2021-04-16-chunkresolve_rxnorm_scd_clinical_en.md
Labels: new model

#2764 2021-04-16-chunkresolve_snomed_findings_clinical_en
  docs/_posts/HashamUlHaq/2021-04-16-chunkresolve_snomed_findings_clinical_en.md
Labels: new model

#2763 2021-04-16-chunkresolve_rxnorm_xsmall_clinical_en
  docs/_posts/HashamUlHaq/2021-04-16-chunkresolve_rxnorm_xsmall_clinical_en.md
Labels: new model

#2762 2021-04-16-chunkresolve_rxnorm_sbd_clinical_en
  docs/_posts/HashamUlHaq/2021-04-16-chunkresolve_rxnorm_sbd_clinical_en.md
Labels: new model

#2768 2021-04-16-chunkresolve_rxnorm_scdc_clinical_en
  docs/_posts/HashamUlHaq/2021-04-16-chunkresolve_rxnorm_scdc_clinical_en.md
Labels: new model

#2770 2021-04-16-chunkresolve_rxnorm_scdc_healthcare_en
  docs/_posts/HashamUlHaq/2021-04-16-chunkresolve_rxnorm_scdc_healthcare_en.md
Labels: new model

#2771 2021-04-16-chunkresolve_rxnorm_in_healthcare_en
  docs/_posts/HashamUlHaq/2021-04-16-chunkresolve_rxnorm_in_healthcare_en.md
Labels: new model

#2772 2021-04-16-chunkresolve_rxnorm_in_clinical_en
  docs/_posts/HashamUlHaq/2021-04-16-chunkresolve_rxnorm_in_clinical_en.md
Labels: new model

#2774 2021-04-19-re_test_problem_finding_en
  docs/_posts/HashamUlHaq/2021-04-19-re_test_problem_finding_en.md
Labels: new model

#2758 added proper conversions for Scala 2.11/2.12
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/parser/SpecialTokensParser.scala
Labels: enhancement

#2760 Provide confidence scores for all available tags in NerDLModel and NerCrfModel
  src/main/scala/com/johnsnowlabs/ml/tensorflow/NerDatasetEncoder.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/TaggedSentence.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/TaggedWord.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
  src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/nlp/SparkAccessor.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfCustomCase.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
Labels: new-feature

#2777 Refactor SentencecPiece encoding in Albert and XLNet
  docs/assets/images/ocr/showImage1.png
  docs/en/annotators.md
  docs/en/licensed_release_notes.md
  docs/en/ocr.md
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
  docs/en/ocr_structures.md
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnet.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencepieceEncoder.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddingsTestSpec.scala
Labels: bug-fix, enhancement

#2743 Adding support for community S3 bucket
  python/sparknlp/pretrained.py
  src/main/resources/application.conf
  src/main/scala/com/johnsnowlabs/nlp/HasPretrained.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceMetadata.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/CloudTestResources.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderSpec.scala
Labels: new-feature

#2784 Add confidence score to NerConverter metadata and fix a bug for dirty documents
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverterTest.scala
Labels: bug-fix, new-feature

#2779 302 release candidate
  .github/workflows/build_and_test.yml
  CHANGELOG
  README.md
  build.sbt
  docs/_layouts/landing.html
  docs/en/concepts.md
  docs/en/examples.md
  docs/en/install.md
  python/README.md
  python/setup.py
  python/sparknlp/__init__.py
  python/sparknlp/pretrained.py
  scripts/colab_setup.sh
  scripts/kaggle_setup.sh
  src/main/resources/application.conf
  src/main/scala/com/johnsnowlabs/ml/tensorflow/NerDatasetEncoder.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnet.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencepieceEncoder.scala
  src/main/scala/com/johnsnowlabs/nlp/HasPretrained.scala
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/Tagged.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/TaggedSentence.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/TaggedWord.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/parser/SpecialTokensParser.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceMetadata.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/util/Build.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
  src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/nlp/SparkAccessor.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverterTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfCustomCase.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/CloudTestResources.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderSpec.scala
Labels: bug-fix, documentation, enhancement, new-feature

#2786 2021-04-21-ner_healthcare_en
  docs/_posts/HashamUlHaq/2021-04-21-ner_healthcare_en.md
Labels: new model

#2722 2021-04-02-chunkresolve_icd10cm_hcc_clinical_en
  docs/_posts/HashamUlHaq/2021-04-02-chunkresolve_icd10cm_hcc_clinical_en.md
Labels: new model

#2806 2021-04-28-ner_jsl_en
  docs/_posts/muhammetsnts/2021-04-28-ner_jsl_en.md
Labels: new model

#2809 2021-04-29-sbluebertresolve_loinc_en
  docs/_posts/HashamUlHaq/2021-04-29-sbluebertresolve_loinc_en.md
Labels: new model

#2808 2021-04-29-sbiobertresolve_loinc_en
  docs/_posts/HashamUlHaq/2021-04-29-sbiobertresolve_loinc_en.md
Labels: new model

#2807 2021-04-29-pos_ud_gsd_fr
  docs/_posts/C-K-Loan/2021-04-29-pos_ud_gsd_fr.md
Labels: new model

#2800 2021-04-26-recognize_entities_dl_fa
  docs/_posts/HashamUlHaq/2021-04-26-recognize_entities_dl_fa.md
Labels: new model

#2819 2021-04-30-ner_jsl_en
  docs/_posts/muhammetsnts/2021-04-30-ner_jsl_en.md
Labels: new model

#2823 2021-04-30-sbiobertresolve_umls_findings_en
  docs/_posts/HashamUlHaq/2021-04-30-sbiobertresolve_umls_findings_en.md
Labels: new model
