Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-05, with the labels that each got.

#2833 2021-05-02-icd10cm_snomed_mapping_en
  docs/_posts/muhammetsnts/2021-05-02-icd10cm_snomed_mapping_en.md
Labels: new model

#2834 2021-05-02-snomed_icd10cm_mapping_en
  docs/_posts/muhammetsnts/2021-05-02-snomed_icd10cm_mapping_en.md
Labels: new model

#2835 2021-05-02-icd10cm_snomed_mapping_en
  docs/_posts/muhammetsnts/2021-05-02-icd10cm_snomed_mapping_en.md
Labels: new model

#2836 2021-05-02-sbiobertresolve_umls_major_concepts_en
  docs/_posts/HashamUlHaq/2021-05-02-sbiobertresolve_umls_major_concepts_en.md
Labels: new model

#2841 2021-05-04-icd10cm_umls_mapping_en
  docs/_posts/muhammetsnts/2021-05-04-icd10cm_umls_mapping_en.md
Labels: new model

#2842 2021-05-04-snomed_umls_mapping_en
  docs/_posts/muhammetsnts/2021-05-04-snomed_umls_mapping_en.md
Labels: new model

#2843 2021-05-04-rxnorm_umls_mapping_en
  docs/_posts/muhammetsnts/2021-05-04-rxnorm_umls_mapping_en.md
Labels: new model

#2844 2021-05-04-mesh_umls_mapping_en
  docs/_posts/muhammetsnts/2021-05-04-mesh_umls_mapping_en.md
Labels: new model

#2845 2021-05-04-rxnorm_mesh_mapping_en
  docs/_posts/muhammetsnts/2021-05-04-rxnorm_mesh_mapping_en.md
Labels: new model

#2824 2021-04-30-explain_document_lg_ko
  docs/_posts/Digaari/2021-04-30-explain_document_lg_ko.md
Labels: new model

#2825 2021-04-30-explain_document_lg_he
  docs/_posts/Digaari/2021-04-30-explain_document_lg_he.md
Labels: new model

#2837 2021-05-03-classifierdl_bert_news_tr
  docs/_posts/murat-gunay/2021-05-03-classifierdl_bert_news_tr.md
Labels: new model

#2850 2021-05-05-sbiobertresolve_HPO_en
  docs/_posts/HashamUlHaq/2021-05-05-sbiobertresolve_HPO_en.md
Labels: new model

#2796 Fix ChunkEmbeddings Array out of bounds exception
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala
Labels: bug-fix

#2799 Added unchecked annotation to suppress type erasure warning
  src/main/scala/com/johnsnowlabs/nlp/HasBatchedAnnotate.scala
Labels: enhancement

#2827 Fix pretrained tfhub_use_multi and tfhub_use_multi_lg models in UniversalSentenceEncoder
  docs/_layouts/landing.html
  docs/_posts/maziyarpanahi/2020-09-23-labse.md
  docs/_posts/muhammetsnts/2021-04-30-ner_jsl_en.md
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoderTestSpec.scala
Labels: bug-fix

#2831 Add new parameters for text generation in T5Transformer
  python/run-tests.py
  python/sparknlp/__init__.py
  python/sparknlp/annotation.py
  python/sparknlp/annotator.py
  python/sparknlp/base.py
  python/sparknlp/common.py
  python/sparknlp/functions.py
  python/sparknlp/internal.py
  python/sparknlp/pretrained.py
  python/sparknlp/training.py
  python/sparknlp/util.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5TestSpec.scala
Labels: new-feature

#2852 2021-05-06-tfhub_use_multi_xx
  docs/_posts/maziyarpanahi/2021-05-06-tfhub_use_multi_xx.md
Labels: new model

#2855 2021-05-06-tfhub_use_multi_lg_xx
  docs/_posts/maziyarpanahi/2021-05-06-tfhub_use_multi_lg_xx.md
Labels: new model

#2867 BPE, input IndexToken, Output Array[TokenPiece]
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizerTestSpec.scala
Labels: new-feature, on-hold

#2872 Bpe based tokenizers
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/XlmTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/moses/MosesTokenizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/moses/MosesTokenizerTest.scala
Labels: Requires changes, new-feature, on-hold

#2876 End Index changed, prepend space for token without one
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizerTestSpec.scala
Labels: enhancement

#2882 2021-05-14-sbert_jsl_tiny_umls_uncased_en
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_tiny_umls_uncased_en.md
Labels: new model

#2884 2021-05-14-sbiobert_jsl_cased_en
  docs/_posts/HashamUlHaq/2021-05-14-sbiobert_jsl_cased_en.md
Labels: new model

#2883 2021-05-14-sbert_jsl_mini_umls_uncased_en
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_mini_umls_uncased_en.md
Labels: new model

#2881 2021-05-14-sbert_jsl_medium_umls_uncased_en
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_medium_umls_uncased_en.md
Labels: new model

#2880 2021-05-14-sbiobert_jsl_umls_cased_en
  docs/_posts/HashamUlHaq/2021-05-14-sbiobert_jsl_umls_cased_en.md
Labels: new model

#2879 2021-05-14-sbert_jsl_mini_uncased_en
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_mini_uncased_en.md
Labels: new model

#2878 2021-05-14-sbert_jsl_tiny_uncased_en
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_tiny_uncased_en.md
Labels: new model

#2877 2021-05-14-sbert_jsl_medium_uncased_en
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_medium_uncased_en.md
Labels: new model

#2901 2021-05-16-sbiobertresolve_icdo_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icdo_en.md
Labels: new model

#2900 2021-05-16-sbiobertresolve_snomed_auxConcepts_int_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_auxConcepts_int_en.md
Labels: new model

#2899 2021-05-16-sbiobertresolve_icd10cm_augmented_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_augmented_en.md
Labels: new model

#2898 2021-05-16-sbiobertresolve_snomed_findings_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_findings_en.md
Labels: new model

#2897 2021-05-16-sbiobertresolve_icd10pcs_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10pcs_en.md
Labels: new model

#2896 2021-05-16-sbiobertresolve_icd10cm_augmented_billable_hcc_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
Labels: new model

#2895 2021-05-16-sbiobertresolve_snomed_findings_int_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_findings_int_en.md
Labels: new model

#2894 2021-05-16-sbiobertresolve_snomed_auxConcepts_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_auxConcepts_en.md
Labels: new model

#2893 2021-05-16-sbiobertresolve_umls_findings_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_umls_findings_en.md
Labels: new model

#2892 2021-05-16-sbiobertresolve_rxnorm_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxnorm_en.md
Labels: new model

#2891 2021-05-16-sbiobertresolve_loinc_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_loinc_en.md
Labels: new model

#2890 2021-05-16-sbiobertresolve_cpt_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_cpt_en.md
Labels: new model

#2889 2021-05-16-sbiobertresolve_rxcui_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxcui_en.md
Labels: new model

#2888 2021-05-16-sbiobertresolve_HPO_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_HPO_en.md
Labels: new model

#2887 2021-05-16-sbiobertresolve_icd10cm_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_en.md
Labels: new model

#2886 2021-05-16-sbiobertresolve_umls_major_concepts_en
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_umls_major_concepts_en.md
Labels: new model

#2904 changed spark version from open source to licensed
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_direction_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_problem_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_procedure_test_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_chemprot_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_clinical_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_date_clinical_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_drug_drug_interaction_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_human_phenotype_gene_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_temporal_events_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-06-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
Labels: documentation

#2905 2021-05-17-sbiobertresolve_icd10cm_slim_normalized_en
  docs/_posts/HashamUlHaq/2021-05-17-sbiobertresolve_icd10cm_slim_normalized_en.md
Labels: new model

#2902 Introducing RoBertaEmbeddings annotator based on RoBERTa models
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala
Labels: new model, new-feature

#2911 2021-05-20-bert_base_dutch_cased_nl
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_medium_umls_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_medium_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_mini_umls_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_mini_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_tiny_umls_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_tiny_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbiobert_jsl_cased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbiobert_jsl_umls_cased_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_HPO_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_cpt_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_augmented_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10pcs_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icdo_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_loinc_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxcui_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxnorm_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_auxConcepts_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_auxConcepts_int_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_findings_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_snomed_findings_int_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_umls_findings_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_umls_major_concepts_en.md
  docs/_posts/HashamUlHaq/2021-05-17-sbiobertresolve_icd10cm_slim_normalized_en.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_dutch_cased_nl.md
Labels: new model

#2913 2021-05-20-bert_base_german_uncased_de
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_german_uncased_de.md
Labels: new model

#2910 2021-05-19-ner_lener_pt
  docs/_posts/dcecchini/2021-05-19-ner_lener_pt.md
Labels: new model

#2917 2021-05-20-bert_base_italian_cased_it
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_italian_cased_it.md
Labels: new model

#2918 2021-05-20-bert_base_italian_uncased_it
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_italian_uncased_it.md
Labels: new model

#2919 2021-05-20-bert_base_turkish_cased_tr
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_turkish_cased_tr.md
Labels: new model

#2920 2021-05-20-bert_base_turkish_uncased_tr
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_turkish_uncased_tr.md
Labels: new model

#2921 2021-05-20-chinese_bert_wwm_zh
  docs/_posts/maziyarpanahi/2021-05-20-chinese_bert_wwm_zh.md
Labels: new model

#2922 2021-05-20-bert_base_cased_en
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_cased_en.md
Labels: new model

#2923 2021-05-20-bert_base_uncased_en
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_uncased_en.md
Labels: new model

#2924 2021-05-20-bert_base_chinese_zh
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_chinese_zh.md
Labels: new model

#2925 2021-05-20-bert_base_multilingual_cased_xx
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_multilingual_cased_xx.md
Labels: new model

#2926 2021-05-20-bert_base_multilingual_uncased_xx
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_multilingual_uncased_xx.md
Labels: new model

#2927 2021-05-20-bert_large_cased_en
  docs/_posts/maziyarpanahi/2021-05-20-bert_large_cased_en.md
Labels: new model

#2928 2021-05-20-bert_large_uncased_en
  docs/_posts/maziyarpanahi/2021-05-20-bert_large_uncased_en.md
Labels: new model

#2929 2021-05-20-distilbert_base_cased_en
  docs/_posts/maziyarpanahi/2021-05-20-distilbert_base_cased_en.md
Labels: new model

#2930 2021-05-20-distilbert_base_uncased_en
  docs/_posts/maziyarpanahi/2021-05-20-distilbert_base_uncased_en.md
Labels: new model

#2932 2021-05-20-distilroberta_base_en
  docs/_posts/maziyarpanahi/2021-05-20-distilroberta_base_en.md
Labels: new model

#2933 2021-05-20-roberta_base_en
  docs/_posts/maziyarpanahi/2021-05-20-roberta_base_en.md
Labels: new model

#2934 2021-05-20-roberta_large_en
  docs/_posts/maziyarpanahi/2021-05-20-roberta_large_en.md
Labels: new model

#2903 XLM Tokenizer
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/XlmTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/moses/MosesTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/normalizer/MosesPunctNormalizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/XlmTokenizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/moses/MosesTokenizerTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/moses/MosesTokenizerTestSpec.scala
Labels: new-feature, on-hold

#2940 2021-05-21-sbiobertresolve_icd10cm_slim_billable_hcc_en
  docs/_posts/HashamUlHaq/2021-05-21-sbiobertresolve_icd10cm_slim_billable_hcc_en.md
Labels: new model

#2941 2021-05-21-sbertresolve_icd10cm_slim_billable_hcc_med_en
  docs/_posts/HashamUlHaq/2021-05-21-sbertresolve_icd10cm_slim_billable_hcc_med_en.md
Labels: new model

#2939 Moses Optimizations
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/moses/MosesTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/normalizer/MosesPunctNormalizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/moses/MosesTokenizerTestSpec.scala
Labels: updates

#2949 Migration to TF 2.4.1 with Java bindings 0.3.1
  project/Dependencies.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
Labels: new-feature

#2947 Introducing new XlmRoBertaEmbeddings annotator
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowRoBerta.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencepieceEncoder.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddingsTestSpec.scala
Labels: new model, new-feature, on-hold

#2952 2021-05-25-sbiobertresolve_icd10cm_slim_billable_hcc_en
  docs/_posts/muhammetsnts/2021-05-25-sbiobertresolve_icd10cm_slim_billable_hcc_en.md
Labels: new model

#2954 2021-05-25-xlm_roberta_base_xx
  docs/_posts/maziyarpanahi/2021-05-25-xlm_roberta_base_xx.md
Labels: new model

#2955 2021-05-25-twitter_xlm_roberta_base_xx
  docs/_posts/maziyarpanahi/2021-05-25-twitter_xlm_roberta_base_xx.md
Labels: new model

#2953 Models hub
  docs/_posts/HashamUlHaq/2021-05-21-sbertresolve_icd10cm_slim_billable_hcc_med_en.md
  docs/_posts/HashamUlHaq/2021-05-21-sbiobertresolve_icd10cm_slim_billable_hcc_en.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_cased_en.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_chinese_zh.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_italian_cased_it.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_italian_uncased_it.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_multilingual_cased_xx.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_multilingual_uncased_xx.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_turkish_cased_tr.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_turkish_uncased_tr.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_base_uncased_en.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_large_cased_en.md
  docs/_posts/maziyarpanahi/2021-05-20-bert_large_uncased_en.md
  docs/_posts/maziyarpanahi/2021-05-20-chinese_bert_wwm_zh.md
  docs/_posts/maziyarpanahi/2021-05-20-distilbert_base_cased_en.md
  docs/_posts/maziyarpanahi/2021-05-20-distilbert_base_multilingual_cased_xx.md
  docs/_posts/maziyarpanahi/2021-05-20-distilbert_base_uncased_en.md
  docs/_posts/maziyarpanahi/2021-05-20-distilroberta_base_en.md
  docs/_posts/maziyarpanahi/2021-05-20-roberta_base_en.md
  docs/_posts/maziyarpanahi/2021-05-20-roberta_large_en.md
  docs/_posts/maziyarpanahi/2021-05-25-twitter_xlm_roberta_base_xx.md
  docs/_posts/maziyarpanahi/2021-05-25-xlm_roberta_base_xx.md
  docs/_posts/muhammetsnts/2021-05-25-sbiobertresolve_icd10cm_slim_billable_hcc_en.md
Labels: new model

#2957 2021-05-25-sbertresolve_icd10cm_slim_billable_hcc_med_en
  docs/_posts/muhammetsnts/2021-05-25-sbertresolve_icd10cm_slim_billable_hcc_med_en.md
Labels: new model

#2951 MosesPunctNormalizer improvements
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/XlmTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/normalizer/MosesPunctNormalizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/normalizer/MosesPunctNormalizerTestSpec.scala
Labels: enhancement

#2961 2021-05-26-demo_sbiobertresolve_icd10cm_augmented_billable_hcc_en
  docs/_posts/muhammetsnts/2021-05-26-demo_sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
Labels: new model

#2962 2021-05-26-demo_sbiobertresolve_cpt_en
  docs/_posts/muhammetsnts/2021-05-26-demo_sbiobertresolve_cpt_en.md
Labels: new model

#2963 2021-05-26-demo_sbiobertresolve_rxnorm_en
  docs/_posts/muhammetsnts/2021-05-26-demo_sbiobertresolve_rxnorm_en.md
Labels: new model

#2960 Migrate MarianTransformer to TensorFlow v2 architecture and improve ModelSignatureConstants
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSerializeModel.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sign/ModelSignatureConstants.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sign/ModelSignatureManager.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddingsTestSpec.scala
Labels: new model, new-feature, on-hold

#2969 2021-05-27-ner_lener_pt
  docs/_posts/dcecchini/2021-05-27-ner_lener_pt.md
Labels: new model

#2970 2021-05-27-clinical_deidentification_en
  docs/_posts/muhammetsnts/2021-05-27-clinical_deidentification_en.md
Labels: new model

#2977 Documentation update for Spark OCR 3.2.0 release
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
Labels: documentation

#2975 Map multiple annotations
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_direction_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_problem_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_bodypart_procedure_test_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_chemprot_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_clinical_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_date_clinical_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_drug_drug_interaction_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_human_phenotype_gene_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-04-redl_temporal_events_biobert_en.md
  docs/_posts/HashamUlHaq/2021-02-06-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
  docs/_posts/HashamUlHaq/2021-03-16-sentence_detector_dl_healthcare_en.md
  docs/en/auxiliary.md
  python/run-tests.py
  python/sparknlp/annotation.py
  python/sparknlp/functions.py
  python/test/functions.py
  src/main/scala/com/johnsnowlabs/nlp/functions.scala
  src/test/scala/com/johnsnowlabs/nlp/FunctionsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
Labels: enhancement, new-feature

#2973 Added slow tests fixes on distilbert and ner crf
  src/test/resources/ner-corpus/ner_fake_connl_cv.txt
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerPerfTest.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddingsTestSpec.scala
Labels: enhancement

#2983 Fix ContextSpellCheckerTestSpec test in scala 11 .
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
Labels: bug-fix

#2986 fix examples for pos_ud_hdt_de
  docs/_posts/C-K-Loan/2021-03-08-pos_ud_hdt_de.md
Labels: documentation, enhancement, models_hub

#2958 2021-05-26-visual_document_NER_SROIE0526_en_3.0.0_3.0.1_1621990933091_en
  docs/_posts/ChicoQ/2021-05-26-visual_document_NER_SROIE0526_en_3.0.0_3.0.1_1621990933091_en.md
Labels: new model
