Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-01, with the labels that each got.

#1706 [skip ci] 2021-01-02-sentence_detector_dl_en
  docs/_posts/vankov/2021-01-02-sentence_detector_dl_en.md
Labels: new model

#1707 [skip ci] 2021-01-02-sentence_detector_dl_en
  docs/_posts/vankov/2021-01-02-sentence_detector_dl_en.md
Labels: new model

#1709 [skip ci] 2021-01-02-sentence_detector_dl_xx
  docs/_posts/vankov/2021-01-02-sentence_detector_dl_xx.md
Labels: new model

#1710 [skip ci] 2021-01-02-sentence_detector_dl_xx
  docs/_posts/vankov/2021-01-02-sentence_detector_dl_xx.md
Labels: new model

#1711 [skip ci] 2021-01-02-sentence_detector_dl_en
  docs/_posts/vankov/2021-01-02-sentence_detector_dl_en.md
Labels: new model

#1730 [skip ci] 2021-01-03-translate_zlw_en_xx
  docs/_posts/maziyarpanahi/2021-01-03-translate_zlw_en_xx.md
Labels: new model

#1968 [skip ci] 2021-01-03-wordseg_large_zh
  docs/_posts/dcecchini/2021-01-03-wordseg_large_zh.md
Labels: new model

#1991 [skip ci] 2021-01-03-wordseg_ctb9_zh
  docs/_posts/dcecchini/2021-01-03-wordseg_ctb9_zh.md
Labels: new model

#1992 [skip ci] 2021-01-03-wordseg_gsd_ud_ja
  docs/_posts/dcecchini/2021-01-03-wordseg_gsd_ud_ja.md
Labels: new model

#1993 [skip ci] 2021-01-03-wordseg_kaist_ud_ko
  docs/_posts/dcecchini/2021-01-03-wordseg_kaist_ud_ko.md
Labels: new model

#1994 [skip ci] 2021-01-03-wordseg_msra_zh
  docs/_posts/dcecchini/2021-01-03-wordseg_msra_zh.md
Labels: new model

#1995 [skip ci] 2021-01-03-wordseg_pku_zh
  docs/_posts/dcecchini/2021-01-03-wordseg_pku_zh.md
Labels: new model

#1996 [skip ci] 2021-01-03-wordseg_weibo_zh
  docs/_posts/dcecchini/2021-01-03-wordseg_weibo_zh.md
Labels: new model

#2030 [skip ci] 2021-01-03-pos_ctb9_zh
  docs/_posts/dcecchini/2021-01-03-pos_ctb9_zh.md
Labels: new model

#2039 [skip ci] 2021-01-03-pos_ud_gsd_zh
  docs/_posts/dcecchini/2021-01-03-pos_ud_gsd_zh.md
Labels: new model

#2051 [skip ci] 2021-01-03-pos_ud_kaist_ko
  docs/_posts/dcecchini/2021-01-03-pos_ud_kaist_ko.md
Labels: new model

#2053 [skip ci] 2021-01-03-ner_msra_bert_768d_zh
  docs/_posts/dcecchini/2021-01-03-ner_msra_bert_768d_zh.md
Labels: new model

#2054 [skip ci] 2021-01-03-ner_weibo_glove_840B_300d_en
  docs/_posts/dcecchini/2021-01-03-ner_weibo_glove_840B_300d_en.md
Labels: new model

#2055 [skip ci] 2021-01-03-ner_ud_gsd_glove_840B_300d_ja
  docs/_posts/dcecchini/2021-01-03-ner_ud_gsd_glove_840B_300d_ja.md
Labels: new model

#2056 [skip ci] 2021-01-03-ner_ud_kaist_glove_840B_300d_ko
  docs/_posts/dcecchini/2021-01-03-ner_ud_kaist_glove_840B_300d_ko.md
Labels: new model

#2057 [skip ci] 2021-01-04-ner_weibo_bert_768d_zh
  docs/_posts/dcecchini/2021-01-04-ner_weibo_bert_768d_zh.md
Labels: new model

#2068 2.7.0 py api bug fixes T5, WordSegmenter
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
Labels: bug-fix, documentation

#2074 changed keys for new optimized model
  docs/_posts/dcecchini/2021-01-03-ner_ud_kaist_glove_840B_300d_ko.md
  docs/demo.md
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
Labels: enhancement

#2077 Feature/alt regex tokenizer algo
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizerTestSpec.scala
Labels: enhancement

#2079 Refactors AssertAnnotations
  src/test/scala/com/johnsnowlabs/nlp/AssertAnnotations.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/LemmatizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/WordSegmenterTest.scala
  src/test/scala/com/johnsnowlabs/nlp/training/CoNLLUTestSpec.scala
Labels: enhancement

#2082 [skip ci] 2021-01-08-classifierdl_use_trec6_en
  docs/_posts/maziyarpanahi/2021-01-08-classifierdl_use_trec6_en.md
Labels: new model

#2083 [skip ci] 2021-01-08-classifierdl_use_trec50_en
  docs/_posts/maziyarpanahi/2021-01-08-classifierdl_use_trec50_en.md
Labels: new model

#2084 [skip ci] 2021-01-08-classifierdl_use_trec6_pipeline_en
  docs/_posts/maziyarpanahi/2021-01-08-classifierdl_use_trec6_pipeline_en.md
Labels: new model

#2085 [skip ci] 2021-01-08-classifierdl_use_trec50_pipeline_en
  docs/_posts/maziyarpanahi/2021-01-08-classifierdl_use_trec50_pipeline_en.md
Labels: new model

#2087 [skip ci] 2021-01-08-t5_small_en
  docs/_posts/maziyarpanahi/2021-01-08-t5_small_en.md
Labels: new model

#2088 [skip ci] 2021-01-08-t5_base_en
  docs/_posts/maziyarpanahi/2021-01-08-t5_base_en.md
Labels: new model

#2089 [skip ci] 2021-01-08-google_t5_small_ssm_nq_en
  docs/_posts/maziyarpanahi/2021-01-08-google_t5_small_ssm_nq_en.md
Labels: new model

#2091 [skip ci] 2021-01-09-sentimentdl_urduvec_imdb_ur
  docs/_posts/HashamUlHaq/2021-01-09-sentimentdl_urduvec_imdb_ur.md
Labels: new model

#2092 [skip ci] 2021-01-09-classifierdl_use_spam_en
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_spam_en.md
Labels: new model

#2093 [skip ci] 2021-01-09-classifierdl_use_fakenews_en
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_fakenews_en.md
Labels: new model

#2094 [skip ci] 2021-01-09-classifierdl_use_cyberbullying_en
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_cyberbullying_en.md
Labels: new model

#2095 [skip ci] 2021-01-09-classifierdl_use_emotion_en
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_emotion_en.md
Labels: new model

#2097 [skip ci] 2021-01-09-sentimentdl_glove_imdb_en
  docs/_posts/HashamUlHaq/2021-01-09-sentimentdl_glove_imdb_en.md
Labels: new model

#2098 [skip ci] 2021-01-09-classifierdl_use_sarcasm_en
  docs/_posts/HashamUlHaq/2021-01-09-classifierdl_use_sarcasm_en.md
Labels: new model

#2106 [skip ci] 2021-01-11-ner_lst20_glove_840B_300d_th
  docs/_posts/dcecchini/2021-01-11-ner_lst20_glove_840B_300d_th.md
Labels: new model

#2117 [skip ci] 2021-01-15-sentimentdl_use_imdb_en
  docs/_posts/HashamUlHaq/2021-01-15-sentimentdl_use_imdb_en.md
Labels: new model

#2112 [skip ci] 2021-01-13-wordseg_best_th
  docs/_posts/dcecchini/2021-01-13-wordseg_best_th.md
Labels: new model

#2113 [skip ci] 2021-01-13-pos_lst20_th
  docs/_posts/dcecchini/2021-01-13-pos_lst20_th.md
Labels: new model

#2115 [skip ci] 2021-01-14-sentiment_jager_use_th
  docs/_posts/dcecchini/2021-01-14-sentiment_jager_use_th.md
Labels: new model

#2119 [skip ci] 2021-01-15-analyze_sentimentdl_glove_imdb_en
  docs/_posts/HashamUlHaq/2021-01-15-analyze_sentimentdl_glove_imdb_en.md
Labels: new model

#2120 [skip ci] 2021-01-15-analyze_sentimentdl_use_imdb_en
  docs/_posts/HashamUlHaq/2021-01-15-analyze_sentimentdl_use_imdb_en.md
Labels: new model

#2126 [skip ci] 2021-01-15-lemma_ja
  docs/_posts/dcecchini/2021-01-15-lemma_ja.md
Labels: new model

#2127 [skip ci] 2021-01-15-lemma_ko
  docs/_posts/dcecchini/2021-01-15-lemma_ko.md
Labels: new model

#2135 [skip ci] 2021-01-18-sentimentdl_use_twitter_en
  docs/_posts/HashamUlHaq/2021-01-18-sentimentdl_use_twitter_en.md
Labels: new model

#2141 [skip ci] 2021-01-18-re_date_en
  docs/_posts/aydinmyilmaz/2021-01-18-re_date_en.md
Labels: new model

#2140 [skip ci] 2021-01-18-re_bodypart_proceduretest_en
  docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_proceduretest_en.md
Labels: new model

#2137 [skip ci] 2021-01-18-re_bodypart_directions_en
  docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_directions_en.md
Labels: new model

#2131 [skip ci] 2021-01-18-re_bodypart_problem_en
  docs/_posts/aydinmyilmaz/2021-01-18-re_bodypart_problem_en.md
Labels: new model

#2143 [skip ci] 2021-01-18-ner_radiology_en
  docs/_posts/aydinmyilmaz/2021-01-18-ner_radiology_en.md
Labels: new model

#2145 [skip ci] 2021-01-18-re_date_clinical_en
  docs/_posts/aydinmyilmaz/2021-01-18-re_date_clinical_en.md
Labels: new model

#2138 [skip ci] 2021-01-18-pos_ud_bhtb_bh
  docs/_posts/dcecchini/2021-01-18-pos_ud_bhtb_bh.md
Labels: new model

#2139 [skip ci] 2021-01-18-lemma_bh
  docs/_posts/dcecchini/2021-01-18-lemma_bh.md
Labels: new model

#2142 [skip ci] 2021-01-18-analyze_sentimentdl_use_twitter_en
  docs/_posts/HashamUlHaq/2021-01-18-analyze_sentimentdl_use_twitter_en.md
Labels: new model

#2152 [skip ci] 2021-01-20-ner_deid_augmented_en
  docs/_posts/aydinmyilmaz/2021-01-20-ner_deid_augmented_en.md
Labels: new model

#2154 [skip ci] 2021-01-20-lemma_bn
  docs/_posts/dcecchini/2021-01-20-lemma_bn.md
Labels: new model

#2157 [skip ci] 2021-01-20-pos_msri_bn
  docs/_posts/dcecchini/2021-01-20-pos_msri_bn.md
Labels: new model

#2158 [skip ci] 2021-01-20-pos_ud_att_am
  docs/_posts/dcecchini/2021-01-20-pos_ud_att_am.md
Labels: new model

#2159 [skip ci] 2021-01-20-lemma_am
  docs/_posts/dcecchini/2021-01-20-lemma_am.md
Labels: new model

#2149 Fix decoder casual mask input
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
Labels: bug-fix, enhancement

#2150 Fix chunks begin and end in RegexMatcher
  src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherBehaviors.scala
Labels: bug-fix, enhancement

#2163 [skip ci] 2021-01-21-multiclassifierdl_use_toxic_sm_en
  docs/_posts/maziyarpanahi/2021-01-21-multiclassifierdl_use_toxic_sm_en.md
Labels: new model

#2164 [skip ci] 2021-01-21-multiclassifierdl_use_toxic_en
  docs/_posts/maziyarpanahi/2021-01-21-multiclassifierdl_use_toxic_en.md
Labels: new model

#2165 [skip ci] 2021-01-21-multiclassifierdl_use_e2e_en
  docs/_posts/maziyarpanahi/2021-01-21-multiclassifierdl_use_e2e_en.md
Labels: new model

#2172 [skip ci] 2021-01-21-classifierdl_ade_conversational_biobert_en
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_ade_conversational_biobert_en.md
Labels: new model

#2171 [skip ci] 2021-01-21-classifierdl_ade_clinicalbert_en
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_ade_clinicalbert_en.md
Labels: new model

#2170 [skip ci] 2021-01-21-classifierdl_biobert_ade_en
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_biobert_ade_en.md
Labels: new model

#2167 Fixed serialization problems + GPU training support
  src/main/resources/spell_nlm/nlm_300_2_1450_43700.pb
  src/main/resources/spell_nlm/nlm_300_2_1500_43700.pb
  src/main/resources/spell_nlm/nlm_300_2_1600_50000.pb
  src/main/resources/spell_nlm/nlm_300_2_1650_56650.pb
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/HasTransducerFeatures.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/parser/SerializableClass.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/parser/SpecialTokensParser.scala
  src/main/scala/com/johnsnowlabs/nlp/serialization/Feature.scala
  src/test/resources/spell/locations.txt
  src/test/resources/spell/meds.txt
  src/test/resources/spell/names.txt
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
Labels: bug-fix

#2186 TF2 support
  build.sbt
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorResources.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowElmo.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowLD.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSentenceDetectorDL.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowUSE.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnet.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddingsTestSpec.scala
Labels: enhancement, new-feature, on-hold

#2194 [skip ci] 2021-01-26-assertion_dl_healthcare_en
  docs/_posts/HashamUlHaq/2021-01-26-assertion_dl_healthcare_en.md
Labels: new model

#2175 [skip ci] 2021-01-21-classifierdl_pico_biobert_en
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_pico_biobert_en.md
Labels: new model

#2174 [skip ci] 2021-01-21-classifierdl_gender_sbert_en
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_gender_sbert_en.md
Labels: new model

#2173 [skip ci] 2021-01-21-classifierdl_gender_biobert_en
  docs/_posts/HashamUlHaq/2021-01-21-classifierdl_gender_biobert_en.md
Labels: new model

#2196 [skip ci] 2021-01-26-assertion_dl_biobert_en
  docs/_posts/HashamUlHaq/2021-01-26-assertion_dl_biobert_en.md
Labels: new model

#2195 [skip ci] 2021-01-26-assertion_dl_en
  docs/_posts/HashamUlHaq/2021-01-26-assertion_dl_en.md
Labels: new model

#2189 [skip ci] 2021-01-25-classifierdl_use_atis_en
  docs/_posts/HashamUlHaq/2021-01-25-classifierdl_use_atis_en.md
Labels: new model

#2190 [skip ci] 2021-01-25-nerdl_atis_840b_300d_en
  docs/_posts/HashamUlHaq/2021-01-25-nerdl_atis_840b_300d_en.md
Labels: new model

#2192 [skip ci] 2021-01-25-pos_ud_gsd_trad_zh
  docs/_posts/dcecchini/2021-01-25-pos_ud_gsd_trad_zh.md
Labels: new model

#2193 [skip ci] 2021-01-25-wordseg_gsd_ud_trad_zh
  docs/_posts/dcecchini/2021-01-25-wordseg_gsd_ud_trad_zh.md
Labels: new model

#2183 [skip_ci] fixing typos and colab links
  docs/_posts/2020-01-30-assertion_dl_en.md
  docs/_posts/2020-05-07-assertion_i2b2_en.md
  docs/_posts/2020-05-16-chunkresolve_loinc_clinical_en.md
  docs/_posts/2020-05-21-assertion_dl_large_en.md
  docs/_posts/2020-06-20-chunkresolve_snomed_findings_clinical_en.md
  docs/_posts/2020-06-24-chunkresolve_rxnorm_xsmall_clinical_en.md
  docs/_posts/2020-07-27-chunkresolve_rxnorm_cd_clinical_en.md
  docs/_posts/2020-07-27-chunkresolve_rxnorm_sbd_clinical_en.md
  docs/_posts/2020-07-27-chunkresolve_rxnorm_scd_clinical_en.md
  docs/_posts/2020-08-19-explain_clinical_doc_carp_en.md
  docs/_posts/2020-09-06-chunkresolve_ICD10GM_de.md
  docs/_posts/2020-09-16-chunkresolve_athena_conditions_healthcare_en.md
  docs/_posts/2020-09-23-assertion_dl_healthcare_en.md
  docs/_posts/2020-09-30-explain_clinical_doc_era_en.md
  docs/_posts/2020-12-16-classifierdl_gender_biobert_en.md
  docs/_posts/2020-12-16-classifierdl_gender_sbert_en.md
Labels: enhancement, updates

#2162 [skip ci] Creating pages on Modelshub for NER models with NLU tab
  docs/_posts/murat-gunay/2020-03-19-ner_dl_en.md
  docs/_posts/murat-gunay/2020-05-06-norne_6B_100_no.md
  docs/_posts/murat-gunay/2020-05-06-norne_6B_300_no.md
  docs/_posts/murat-gunay/2020-05-06-norne_840B_300_no.md
  docs/_posts/murat-gunay/2020-08-30-dane_ner_6B_100_da.md
  docs/_posts/murat-gunay/2020-08-30-dane_ner_6B_300_da.md
  docs/_posts/murat-gunay/2020-08-30-dane_ner_840B_300_da.md
  docs/_posts/murat-gunay/2020-08-30-swedish_ner_6B_100_sv.md
  docs/_posts/murat-gunay/2020-08-30-swedish_ner_6B_300_sv.md
  docs/_posts/murat-gunay/2020-08-30-swedish_ner_840B_300_sv.md
  docs/_posts/murat-gunay/2020-09-01-finnish_ner_6B_100_fi.md
  docs/_posts/murat-gunay/2020-09-01-finnish_ner_6B_300_fi.md
  docs/_posts/murat-gunay/2020-09-01-finnish_ner_840B_300_fi.md
  docs/_posts/murat-gunay/2020-09-08-ner_dl_bert_en.md
Labels: models_hub, new model, updates

#2182 [skip_ci] ner models with nlu tab
  docs/_posts/2020-02-03-onto_100_en.md
  docs/_posts/2020-02-03-onto_300_en.md
  docs/_posts/2020-02-03-wikiner_6B_100_es.md
  docs/_posts/2020-02-03-wikiner_6B_300_de.md
  docs/_posts/2020-02-03-wikiner_6B_300_es.md
  docs/_posts/2020-02-03-wikiner_6B_300_fr.md
  docs/_posts/2020-02-03-wikiner_6B_300_it.md
  docs/_posts/2020-02-03-wikiner_840B_300_de.md
  docs/_posts/2020-02-03-wikiner_840B_300_es.md
  docs/_posts/2020-02-03-wikiner_840B_300_fr.md
  docs/_posts/2020-02-03-wikiner_840B_300_it.md
  docs/_posts/2020-03-16-wikiner_6B_100_ru.md
  docs/_posts/2020-03-16-wikiner_6B_300_ru.md
  docs/_posts/2020-03-16-wikiner_840B_300_ru.md
  docs/_posts/2020-05-10-wikiner_6B_100_nl.md
  docs/_posts/2020-05-10-wikiner_6B_100_pl.md
  docs/_posts/2020-05-10-wikiner_6B_100_pt.md
  docs/_posts/2020-05-10-wikiner_6B_300_nl.md
  docs/_posts/2020-05-10-wikiner_6B_300_pl.md
  docs/_posts/2020-05-10-wikiner_6B_300_pt.md
  docs/_posts/2020-05-10-wikiner_840B_300_nl.md
  docs/_posts/2020-05-10-wikiner_840B_300_pl.md
  docs/_posts/2020-05-10-wikiner_840B_300_pt.md
  docs/_posts/murat-gunay/2020-11-10-turkish_ner_840B_300_tr.md
  docs/_posts/murat-gunay/2020-11-10-turkish_ner_bert_tr.md
Labels: documentation, models_hub, updates

#2181 [skip ci] adding new healthcare models, jsl - assrt-ner-wip
  docs/_posts/2021-01-18-jsl_assertion_wip_en.md
  docs/_posts/2021-01-18-jsl_assertion_wip_large_en.md
  docs/_posts/2021-01-18-jsl_ner_wip_clinical_en.md
  docs/_posts/2021-01-18-jsl_ner_wip_greedy_clinical_en.md
Labels: models_hub, new model

#2202 [skip ci] 2021-01-27-ner_clinical_en
  docs/_posts/aydinmyilmaz/2021-01-27-ner_clinical_en.md
Labels: updates

#2201 [skip_ci] updating colab links of sbiobertreslove models
  docs/_posts/2020-11-27-sbiobertresolve_cpt_en.md
  docs/_posts/2020-11-27-sbiobertresolve_icd10cm_en.md
  docs/_posts/2020-11-27-sbiobertresolve_icd10pcs_en.md
  docs/_posts/2020-11-27-sbiobertresolve_icdo_en.md
  docs/_posts/2020-11-27-sbiobertresolve_rxnorm_en.md
  docs/_posts/2020-11-27-sbiobertresolve_snomed_auxConcepts_en.md
  docs/_posts/2020-11-27-sbiobertresolve_snomed_auxConcepts_int_en.md
  docs/_posts/2020-11-27-sbiobertresolve_snomed_findings_en.md
  docs/_posts/2020-11-27-sbiobertresolve_snomed_findings_int_en.md
  docs/_posts/2020-12-11-sbiobertresolve_rxcui_en.md
  docs/_posts/2020-12-13-sbiobertresolve_icd10cm_augmented_en.md
Labels: Requires changes, models_hub, updates

#2207 [skip ci] 2021-01-28-deidentify_dl_en
  docs/_posts/aydinmyilmaz/2021-01-28-deidentify_dl_en.md
Labels: new model, updates

#2208 [skip_ci] embeddings insertion to public NERs
  docs/_posts/2020-01-30-assertion_dl_en.md
  docs/_posts/2020-01-30-assertion_ml_en.md
  docs/_posts/2020-02-03-onto_100_en.md
  docs/_posts/2020-02-03-onto_300_en.md
  docs/_posts/2020-02-03-wikiner_6B_100_es.md
  docs/_posts/2020-02-03-wikiner_6B_300_de.md
  docs/_posts/2020-02-03-wikiner_6B_300_es.md
  docs/_posts/2020-02-03-wikiner_6B_300_fr.md
  docs/_posts/2020-02-03-wikiner_6B_300_it.md
  docs/_posts/2020-02-03-wikiner_840B_300_de.md
  docs/_posts/2020-02-03-wikiner_840B_300_es.md
  docs/_posts/2020-02-03-wikiner_840B_300_fr.md
  docs/_posts/2020-02-03-wikiner_840B_300_it.md
  docs/_posts/2020-03-16-wikiner_6B_100_ru.md
  docs/_posts/2020-03-16-wikiner_6B_300_ru.md
  docs/_posts/2020-03-16-wikiner_840B_300_ru.md
  docs/_posts/2020-05-10-wikiner_6B_100_nl.md
  docs/_posts/2020-05-10-wikiner_6B_100_pl.md
  docs/_posts/2020-05-10-wikiner_6B_100_pt.md
  docs/_posts/2020-05-10-wikiner_6B_300_nl.md
  docs/_posts/2020-05-10-wikiner_6B_300_pl.md
  docs/_posts/2020-05-10-wikiner_6B_300_pt.md
  docs/_posts/2020-05-10-wikiner_840B_300_nl.md
  docs/_posts/2020-05-10-wikiner_840B_300_pl.md
  docs/_posts/2020-05-10-wikiner_840B_300_pt.md
  docs/_posts/2020-05-21-assertion_dl_large_en.md
  docs/_posts/2020-09-23-assertion_dl_healthcare_en.md
  docs/_posts/2021-01-18-jsl_assertion_wip_en.md
  docs/_posts/2021-01-18-jsl_assertion_wip_large_en.md
Labels: Requires changes, models_hub, updates

#2210 [skip ci] 2021-01-29-deidentify_enriched_clinical_en
  docs/_posts/xusliebana/2021-01-29-deidentify_enriched_clinical_en.md
Labels: new model

#2203 fix typo in getClasses function
  python/sparknlp/annotator.py
Labels: documentation

#2209 Fixing action default value in DocumentNormalizer Python wrapper
  python/sparknlp/annotator.py
Labels: enhancement
