Repository JohnSnowLabs/spark-nlp, pull requests merged in 2021-08, with the labels that each got.

#5891 [skip ci] fix sent_bert code snippets
  docs/_posts/Digaari/2020-08-31-sent_bert_finnish_cased.md
  docs/_posts/Digaari/2020-08-31-sent_bert_finnish_uncased.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_bert_base_cased.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_bert_base_uncased.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_bert_large_cased.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_bert_large_uncased.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_bert_multi_cased.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L10_128.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L10_256.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L10_512.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L10_768.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L12_128.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L12_256.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L12_512.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L12_768.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L2_128.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L2_256.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L2_512.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L2_768.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L4_128.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L4_256.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L4_512.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L4_768.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L6_128.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L6_256.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L6_512.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L6_768.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L8_128.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L8_256.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L8_512.md
  docs/_posts/maziyarpanahi/2020-08-25-sent_small_bert_L8_768.md
  docs/_posts/maziyarpanahi/2020-08-27-sent_covidbert_large_uncased.md
  docs/_posts/maziyarpanahi/2020-08-27-sent_electra_base_uncased.md
  docs/_posts/maziyarpanahi/2020-08-27-sent_electra_large_uncased.md
  docs/_posts/maziyarpanahi/2020-08-27-sent_electra_small_uncased.md
Labels: documentation, models_hub

#5892 Models hub
  docs/_posts/HashamUlHaq/2021-07-16-re_ade_biobert_en.md
  docs/_posts/HashamUlHaq/2021-07-25-ms_bluebert_base_uncased_en.md
  docs/_posts/HashamUlHaq/2021-07-26-jsl_ner_wip_greedy_biobert_en.md
  docs/_posts/HashamUlHaq/2021-07-26-jsl_rd_ner_wip_greedy_biobert_en.md
  docs/_posts/dcecchini/2021-07-21-lener_bert_base_pt.md
  docs/_posts/dcecchini/2021-07-23-cantemist_scielowiki_es.md
  docs/_posts/dcecchini/2021-07-26-meddroprof_scielowiki_es.md
  docs/_posts/dcecchini/2021-07-28-lener_bert_base_pt.md
  docs/_posts/dcecchini/2021-07-28-lener_bert_large_pt.md
  docs/_posts/muhammetsnts/2021-07-24-assertion_jsl_en.md
  docs/_posts/muhammetsnts/2021-07-24-assertion_jsl_large_en.md
  docs/_posts/muhammetsnts/2021-07-24-redl_chemprot_biobert_en.md
  docs/_posts/muhammetsnts/2021-07-24-redl_clinical_biobert_en.md
  docs/_posts/muhammetsnts/2021-07-24-redl_drug_drug_interaction_biobert_en.md
  docs/_posts/muhammetsnts/2021-07-24-redl_human_phenotype_gene_biobert_en.md
  docs/_posts/muhammetsnts/2021-07-24-redl_temporal_events_biobert_en.md
  docs/_posts/murat-gunay/2021-07-21-classifierdl_berturk_cyberbullying_tr.md
  docs/_posts/murat-gunay/2021-07-22-nerdl_fewnerd_subentity_100d_en.md
Labels: models_hub

#5884 Pydoc Update
  python/docs/Makefile
  python/docs/move_folders_for_gh.sh
  python/docs/user_guide/training.rst
  python/sparknlp/annotator.py
  python/sparknlp/base.py
  python/sparknlp/common.py
  python/sparknlp/training.py
  src/main/scala/com/johnsnowlabs/nlp/Chunk2Doc.scala
  src/main/scala/com/johnsnowlabs/nlp/Doc2Chunk.scala
  src/main/scala/com/johnsnowlabs/nlp/DocumentAssembler.scala
  src/main/scala/com/johnsnowlabs/nlp/Finisher.scala
  src/main/scala/com/johnsnowlabs/nlp/TokenAssembler.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/Chunker.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/keyword.yake/YakeModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserModel.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoder.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLLU.scala
  src/main/scala/com/johnsnowlabs/nlp/training/PubTator.scala
Labels: documentation, enhancement, on-hold

#5903 2021-08-04-ner_ontonotes_roberta_base_en
  docs/_posts/maziyarpanahi/2021-08-04-ner_ontonotes_roberta_base_en.md
Labels: new model

#5904 2021-08-04-ner_ontonotes_roberta_large_en
  docs/_posts/maziyarpanahi/2021-08-04-ner_ontonotes_roberta_large_en.md
Labels: new model

#5905 2021-08-04-ner_ontonotes_distilbert_base_cased_en
  docs/_posts/maziyarpanahi/2021-08-04-ner_ontonotes_distilbert_base_cased_en.md
Labels: new model

#5906 2021-08-04-ner_conll_bert_base_cased_en
  docs/_posts/maziyarpanahi/2021-08-04-ner_conll_bert_base_cased_en.md
Labels: new model

#5907 2021-08-04-ner_conll_distilbert_base_cased_en
  docs/_posts/maziyarpanahi/2021-08-04-ner_conll_distilbert_base_cased_en.md
Labels: new model

#5908 2021-08-04-ner_conll_roberta_base_en
  docs/_posts/maziyarpanahi/2021-08-04-ner_conll_roberta_base_en.md
Labels: new model

#5909 2021-08-04-ner_conll_roberta_large_en
  docs/_posts/maziyarpanahi/2021-08-04-ner_conll_roberta_large_en.md
Labels: new model

#5910 2021-08-04-ner_conll_xlm_roberta_base_en
  docs/_posts/maziyarpanahi/2021-08-04-ner_conll_xlm_roberta_base_en.md
Labels: new model

#5911 2021-08-04-ner_conll_longformer_base_4096_en
  docs/_posts/maziyarpanahi/2021-08-04-ner_conll_longformer_base_4096_en.md
Labels: new model

#5912 2021-08-04-ner_conll_longformer_large_4096_en
  docs/_posts/maziyarpanahi/2021-08-04-ner_conll_longformer_large_4096_en.md
Labels: new model

#5913 2021-08-04-longformer_base_4096_en
  docs/_posts/maziyarpanahi/2021-08-04-longformer_base_4096_en.md
Labels: new model

#5914 2021-08-04-longformer_large_4096_en
  docs/_posts/maziyarpanahi/2021-08-04-longformer_large_4096_en.md
Labels: new model

#5916 Add new demos 5
  docs/assets/images/Classify_German_News.svg
  docs/assets/images/Classify_German_News_c.svg
  docs/assets/images/Detect_Genomic_Variant_Information.svg
  docs/assets/images/Detect_Genomic_Variant_Information_c.svg
  docs/assets/images/Detect_tables_and_extract_text.svg
  docs/assets/images/Detect_tables_and_extract_text_c.svg
  docs/assets/images/Extract_entities_from_visual_documents.svg
  docs/assets/images/Extract_entities_from_visual_documents_c.svg
  docs/assets/images/Sentence_Entity_Resolver_for_ICD10-CM_coding.svg
  docs/assets/images/Sentence_Entity_Resolver_for_ICD10-CM_coding_c.svg
  docs/assets/images/Sentence_Entity_Resolver_for_RxNorm.svg
  docs/assets/images/Sentence_Entity_Resolver_for_RxNorm_c.svg
  docs/demos/analyze_non_english_medical_text.md
  docs/demos/european_languages.md
  docs/demos/extract_tables_structured_data.md
  docs/demos/recognize_biomedical_entities.md
  docs/demos/resolve_entities_codes.md
Labels: documentation, models_hub

#5917 Update OCR documentation according to the 3.6.0 release
  docs/en/ocr_object_detection.md
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
  docs/en/ocr_structures.md
  docs/en/version_compatibility.md
Labels: documentation

#5919 2021-08-05-bert_base_token_classifier_conll03_en
  docs/_posts/maziyarpanahi/2021-08-05-bert_base_token_classifier_conll03_en.md
Labels: new model

#5920 2021-08-05-bert_large_token_classifier_conll03_en
  docs/_posts/maziyarpanahi/2021-08-05-bert_large_token_classifier_conll03_en.md
Labels: new model

#5921 2021-08-05-distilbert_base_token_classifier_conll03_en
  docs/_posts/maziyarpanahi/2021-08-05-distilbert_base_token_classifier_conll03_en.md
Labels: new model

#5922 2021-08-05-bert_base_token_classifier_ontonote_en
  docs/_posts/maziyarpanahi/2021-08-05-bert_base_token_classifier_ontonote_en.md
Labels: new model

#5923 2021-08-05-bert_large_token_classifier_ontonote_en
  docs/_posts/maziyarpanahi/2021-08-05-bert_large_token_classifier_ontonote_en.md
Labels: new model

#5924 2021-08-05-distilbert_base_token_classifier_ontonotes_en
  docs/_posts/maziyarpanahi/2021-08-05-distilbert_base_token_classifier_ontonotes_en.md
Labels: new model

#5925 2021-08-05-bert_token_classifier_parsbert_armanner_fa
  docs/_posts/maziyarpanahi/2021-08-05-bert_token_classifier_parsbert_armanner_fa.md
Labels: new model

#5927 2021-08-05-bert_token_classifier_parsbert_ner_fa
  docs/_posts/maziyarpanahi/2021-08-05-bert_token_classifier_parsbert_ner_fa.md
Labels: new model

#5928 2021-08-05-bert_token_classifier_parsbert_peymaner_fa
  docs/_posts/maziyarpanahi/2021-08-05-bert_token_classifier_parsbert_peymaner_fa.md
Labels: new model

#5929 2021-08-05-bert_token_classifier_turkish_ner_tr
  docs/_posts/maziyarpanahi/2021-08-05-bert_token_classifier_turkish_ner_tr.md
Labels: new model

#5930 2021-08-05-bert_token_classifier_spanish_ner_es
  docs/_posts/maziyarpanahi/2021-08-05-bert_token_classifier_spanish_ner_es.md
Labels: new model

#5931 2021-08-05-bert_token_classifier_swedish_ner_sv
  docs/_posts/maziyarpanahi/2021-08-05-bert_token_classifier_swedish_ner_sv.md
Labels: new model

#5932 2021-08-05-distilbert_token_classifier_persian_ner_fa
  docs/_posts/maziyarpanahi/2021-08-05-distilbert_token_classifier_persian_ner_fa.md
Labels: new model

#5934 Add delimiter feature to CoNLL class
  python/sparknlp/training.py
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ElmoEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsTestSpec.scala
Labels: new-feature

#5935 2021-08-08-bert_base_token_classifier_few_nerd_en
  docs/_posts/maziyarpanahi/2021-08-08-bert_base_token_classifier_few_nerd_en.md
Labels: new model

#5936 2021-08-08-distilbert_base_token_classifier_few_nerd_en
  docs/_posts/maziyarpanahi/2021-08-08-distilbert_base_token_classifier_few_nerd_en.md
Labels: new model

#5938 Enable multi language support for en, fr, it, pt, de, es in date matchers
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/resources/date-matcher/supported_languages.txt
  src/main/resources/date-matcher/translation-dictionaries/dynamic/de.json
  src/main/resources/date-matcher/translation-dictionaries/dynamic/en.json
  src/main/resources/date-matcher/translation-dictionaries/dynamic/es.json
  src/main/resources/date-matcher/translation-dictionaries/dynamic/fr.json
  src/main/resources/date-matcher/translation-dictionaries/dynamic/it.json
  src/main/resources/date-matcher/translation-dictionaries/dynamic/pt.json
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTranslator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/DateMatcherUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcher.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherMultiLanguageTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcherMultiLanguageTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcherTestSpec.scala
Labels: new-feature

#5946 2021-08-11-sentence_detector_dl_healthcare_en
  docs/_posts/HashamUlHaq/2021-08-11-sentence_detector_dl_healthcare_en.md
Labels: new model

#5952 2021-08-13-classifierdl_electra_questionpair_en
  docs/_posts/murat-gunay/2021-08-13-classifierdl_electra_questionpair_en.md
Labels: new model

#5953 2021-08-13-classifierdl_berturk_cyberbullying_pipeline_tr
  docs/_posts/murat-gunay/2021-08-13-classifierdl_berturk_cyberbullying_pipeline_tr.md
Labels: new model

#5954 2021-08-13-ner_jsl_greedy_biobert_en
  docs/_posts/muhammetsnts/2021-08-13-ner_jsl_greedy_biobert_en.md
Labels: new model

#5957 2021-08-13-ner_jsl_slim_en
  docs/_posts/HashamUlHaq/2021-08-13-ner_jsl_slim_en.md
Labels: new model

#5955 2021-08-13-classifierdl_bert_news_pipeline_de
  docs/_posts/murat-gunay/2021-08-13-classifierdl_bert_news_pipeline_de.md
Labels: new model

#5956 Add new demos
  docs/_includes/demomenu.html
  docs/assets/images/Detect_Legal_entities_in_Portuguese.svg
  docs/assets/images/Detect_Legal_entities_in_Portuguese_c.svg
  docs/assets/images/Detect_drugs_interactions.svg
  docs/assets/images/Detect_drugs_interactions_c.svg
  docs/assets/images/Detect_relations_between_chemicals_and_proteins.svg
  docs/assets/images/Detect_relations_between_chemicals_and_proteins_c.svg
  docs/assets/images/Detect_wide-ranging_entities_in_the_Market.svg
  docs/assets/images/Detect_wide-ranging_entities_in_the_Market_c.svg
  docs/assets/images/Extract_Signatures.svg
  docs/assets/images/Extract_Signatures_c.svg
  docs/assets/images/Resolve_Clinical_Entities_to_LOINC_Codes.svg
  docs/assets/images/Resolve_Clinical_Entities_to_LOINC_Codes_c.svg
  docs/assets/images/Turkish_Cyberbullying_Detection.svg
  docs/assets/images/Turkish_Cyberbullying_Detection_c.svg
  docs/demos/european_languages.md
  docs/demos/extract_relationships.md
  docs/demos/extract_structured_data.md
  docs/demos/middle_eastern_languages.md
  docs/demos/recognize_entitie.md
  docs/demos/resolve_entities_codes.md
  docs/demos/visual_document_understanding.md
  docs/index.md
Labels: documentation, models_hub

#5959 Avoid exceptions due to corrupt merges in RoBERTa tokenizer
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala
Labels: enhancement

#5964 Remove batchSize from the broadcast
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDistilBertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
Labels: enhancement

#5972 Update locale.yml
  docs/_data/locale.yml
Labels: documentation

#5997 2021-08-28-bert_token_classifier_ner_clinical_en
  docs/_posts/muhammetsnts/2021-08-28-bert_token_classifier_ner_clinical_en.md
Labels: new model

#5998 2021-08-28-bert_token_classifier_ner_jsl_en
  docs/_posts/muhammetsnts/2021-08-28-bert_token_classifier_ner_jsl_en.md
Labels: new model

#5999 2021-08-28-sbertresolve_rxnorm_disposition_en
  docs/_posts/muhammetsnts/2021-08-28-sbertresolve_rxnorm_disposition_en.md
Labels: new model

#6000 2021-08-28-sbertresolve_snomed_conditions_en
  docs/_posts/muhammetsnts/2021-08-28-sbertresolve_snomed_conditions_en.md
Labels: new model

#5994 2021-08-27-classifierdl_bert_news_pipeline_tr
  docs/_posts/murat-gunay/2021-08-27-classifierdl_bert_news_pipeline_tr.md
Labels: new model

#6004 2021-08-30-sentence_detector_dl_bs
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_bs.md
Labels: new model

#6005 2021-08-30-sentence_detector_dl_id
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_id.md
Labels: new model

#6007 2021-08-30-sentence_detector_dl_mr
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_mr.md
Labels: new model

#6008 2021-08-30-sentence_detector_dl_pa
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_pa.md
Labels: new model

#6009 2021-08-30-sentence_detector_dl_ru
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_ru.md
Labels: new model

#6010 2021-08-30-sentence_detector_dl_so
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_so.md
Labels: new model

#6011 2021-08-30-sentence_detector_dl_yi
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_yi.md
Labels: new model

#6012 2021-08-30-sentence_detector_dl_uk
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_uk.md
Labels: new model

#6014 2021-08-30-bert_pubmed_en
  docs/_posts/Digaari/2021-08-30-bert_pubmed_en.md
Labels: new model

#6016 2021-08-30-bert_wiki_books_qqp_en
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_qqp_en.md
Labels: new model

#6017 2021-08-30-bert_wiki_books_qnli_en
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_qnli_en.md
Labels: new model

#6018 2021-08-30-bert_wiki_books_sst2_en
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_sst2_en.md
Labels: new model

#6019 2021-08-30-bert_pubmed_squad2_en
  docs/_posts/Digaari/2021-08-30-bert_pubmed_squad2_en.md
Labels: new model

#6001 2021-08-29-bert_muril_xx
  docs/_posts/Digaari/2021-08-29-bert_muril_xx.md
Labels: new model

#6030 Updated Spark OCR documentation according to 3.7.0 release
  docs/assets/images/ocr/display_pdf_file.png
  docs/assets/images/ocr/display_table.png
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
  docs/en/ocr_structures.md
  docs/en/ocr_table_recognition.md
  docs/en/version_compatibility.md
Labels: documentation

#6029 2021-08-30-sentence_detector_dl_te
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_te.md
Labels: new model

#6028 2021-08-30-sentence_detector_dl_ta
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_ta.md
Labels: new model

#6027 2021-08-30-sentence_detector_dl_sd
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_sd.md
Labels: new model

#6026 2021-08-30-sentence_detector_dl_ml
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_ml.md
Labels: new model

#6025 2021-08-30-sentence_detector_dl_kn
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_kn.md
Labels: new model

#6024 2021-08-30-sentence_detector_dl_gu
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_gu.md
Labels: new model

#6023 2021-08-30-sentence_detector_dl_ne
  docs/_posts/Digaari/2021-08-30-sentence_detector_dl_ne.md
Labels: new model

#6021 2021-08-30-bert_wiki_books_squad2_en
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_squad2_en.md
Labels: new model

#6022 2021-08-30-bert_wiki_books_en
  docs/_posts/Digaari/2021-08-30-bert_wiki_books_en.md
Labels: new model

#6032 2021-08-31-sent_bert_pubmed_squad2_en
  docs/_posts/Digaari/2021-08-31-sent_bert_pubmed_squad2_en.md
Labels: new model

#6033 2021-08-31-sent_bert_wiki_books_en
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_en.md
Labels: new model

#6034 2021-08-31-sent_bert_wiki_books_qqp_en
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_qqp_en.md
Labels: new model

#6035 2021-08-31-sent_bert_wiki_books_mnli_en
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_mnli_en.md
Labels: new model

#6036 2021-08-31-sent_bert_pubmed_en
  docs/_posts/Digaari/2021-08-31-sent_bert_pubmed_en.md
Labels: new model

#6037 2021-08-31-sent_bert_wiki_books_sst2_en
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_sst2_en.md
Labels: new model

#6038 2021-08-31-sent_bert_wiki_books_squad2_en
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_squad2_en.md
Labels: new model

#6039 2021-08-31-sent_bert_wiki_books_qnli_en
  docs/_posts/Digaari/2021-08-31-sent_bert_wiki_books_qnli_en.md
Labels: new model

#6040 2021-08-31-ner_conll_albert_base_uncased_en
  docs/_posts/maziyarpanahi/2021-08-31-ner_conll_albert_base_uncased_en.md
Labels: new model

#6041 2021-08-31-ner_conll_albert_large_uncased_en
  docs/_posts/maziyarpanahi/2021-08-31-ner_conll_albert_large_uncased_en.md
Labels: new model

#6042 2021-08-31-ner_conll_xlnet_base_cased_en
  docs/_posts/maziyarpanahi/2021-08-31-ner_conll_xlnet_base_cased_en.md
Labels: new model

#6043 2021-08-31-ner_conll_elmo_en
  docs/_posts/maziyarpanahi/2021-08-31-ner_conll_elmo_en.md
Labels: new model

#6044 Preserve existing metadata in BertSentenceEmbeddings
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceSplit.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddingsTestSpec.scala
Labels: enhancement, on-hold
