Repository JohnSnowLabs/spark-nlp, pull requests merged in 2022-05, with the labels that each got.

#8227 2022-05-01-lemma_hse_be_3_0
  docs/_posts/maziyarpanahi/2022-05-01-lemma_hse_be_3_0.md
Labels: new model

#8228 2022-05-01-lemma_fictree_cs_3_0
  docs/_posts/maziyarpanahi/2022-05-01-lemma_fictree_cs_3_0.md
Labels: new model

#8229 2022-05-01-lemma_cltt_cs_3_0
  docs/_posts/maziyarpanahi/2022-05-01-lemma_cltt_cs_3_0.md
Labels: new model

#8230 2022-05-01-lemma_ftb_fr_3_0
  docs/_posts/maziyarpanahi/2022-05-01-lemma_ftb_fr_3_0.md
Labels: new model

#8126 Get the download size the same as the model downloaded
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: enhancement, DON'T MERGE

#8102 2022-04-26-bert_pos_bert_base_chinese_pos_zh_3_0
  docs/_posts/gadde5300/2022-04-26-bert_pos_bert_base_chinese_pos_zh_3_0.md
Labels: new model

#8103 2022-04-26-bert_pos_chinese_roberta_large_upos_zh_3_0
  docs/_posts/gadde5300/2022-04-26-bert_pos_chinese_roberta_large_upos_zh_3_0.md
Labels: new model

#8104 2022-04-26-bert_pos_chinese_roberta_base_upos_zh_3_0
  docs/_posts/gadde5300/2022-04-26-bert_pos_chinese_roberta_base_upos_zh_3_0.md
Labels: new model

#8105 2022-04-26-bert_pos_chinese_bert_wwm_ext_upos_zh_3_0
  docs/_posts/gadde5300/2022-04-26-bert_pos_chinese_bert_wwm_ext_upos_zh_3_0.md
Labels: new model

#8277 2022-05-04-camembert_base_fr_3_0
  docs/_posts/maziyarpanahi/2022-05-04-camembert_base_fr_3_0.md
Labels: new model

#8279 2022-05-04-camembert_base_ccnet_4gb_fr_3_0
  docs/_posts/maziyarpanahi/2022-05-04-camembert_base_ccnet_4gb_fr_3_0.md
Labels: new model

#8280 2022-05-04-camembert_base_ccnet_fr_3_0
  docs/_posts/maziyarpanahi/2022-05-04-camembert_base_ccnet_fr_3_0.md
Labels: new model

#8281 2022-05-04-camembert_base_oscar_4gb_fr_3_0
  docs/_posts/maziyarpanahi/2022-05-04-camembert_base_oscar_4gb_fr_3_0.md
Labels: new model

#8236 Removing trove4j dependency
  build.sbt
  project/Dependencies.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/DependencyInstance.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/DependencyPipe.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/PredictionParameters.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/feature/SyntacticFeatureFactory.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/util/Alphabet.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/util/Dictionary.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/util/DictionarySet.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/util/FeatureVector.java
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/PredictionParametersTest.java
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyModelTestSpec.scala
Labels: enhancement, dependencies, DON'T MERGE

#8291 2022-05-06-deberta_v3_xsmall_token_classifier_conll03_en_3_0
  docs/_posts/maziyarpanahi/2022-05-06-deberta_v3_xsmall_token_classifier_conll03_en_3_0.md
Labels: new model

#8292 2022-05-06-deberta_v3_base_token_classifier_conll03_en_3_0
  docs/_posts/maziyarpanahi/2022-05-06-deberta_v3_base_token_classifier_conll03_en_3_0.md
Labels: new model

#8293 2022-05-06-deberta_v3_large_token_classifier_conll03_en_3_0
  docs/_posts/maziyarpanahi/2022-05-06-deberta_v3_large_token_classifier_conll03_en_3_0.md
Labels: new model

#8294 2022-05-06-deberta_v3_small_token_classifier_conll03_en_3_0
  docs/_posts/maziyarpanahi/2022-05-06-deberta_v3_small_token_classifier_conll03_en_3_0.md
Labels: new model

#8299 2022-05-06-deberta_v3_large_token_classifier_ontonotes_en_3_0
  docs/_posts/maziyarpanahi/2022-05-06-deberta_v3_large_token_classifier_ontonotes_en_3_0.md
Labels: new model

#8300 2022-05-06-deberta_v3_small_token_classifier_ontonotes_en_3_0
  docs/_posts/maziyarpanahi/2022-05-06-deberta_v3_small_token_classifier_ontonotes_en_3_0.md
Labels: new model

#8301 2022-05-06-deberta_v3_xsmall_token_classifier_ontonotes_en_3_0
  docs/_posts/maziyarpanahi/2022-05-06-deberta_v3_xsmall_token_classifier_ontonotes_en_3_0.md
Labels: new model

#8302 2022-05-06-deberta_v3_base_token_classifier_ontonotes_en_3_0
  docs/_posts/maziyarpanahi/2022-05-06-deberta_v3_base_token_classifier_ontonotes_en_3_0.md
Labels: new model

#8313 Deprecate support for Spark 2.3 and 2.4 (and Scala 2.11)
  .github/workflows/build_and_test.yml
  .github/workflows/stale.yaml
  build.sbt
  project/Dependencies.scala
  python/sparknlp/__init__.py
  scripts/colab_setup.sh
  scripts/kaggle_setup.sh
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java
  src/test/scala/com/johnsnowlabs/nlp/pretrained/CloudTestResources.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceMedataTest.scala
Labels: dependencies, DON'T MERGE

#8319 Deprecate support for Spark 2.3 and 2.4 (and Scala 2.11)
  .github/workflows/build_and_test.yml
  .github/workflows/stale.yaml
  build.sbt
  project/Dependencies.scala
  python/sparknlp/__init__.py
  scripts/colab_setup.sh
  scripts/kaggle_setup.sh
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java
  src/test/scala/com/johnsnowlabs/nlp/pretrained/CloudTestResources.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceMedataTest.scala
Labels: dependencies

#8305 Release notes content for NLP Server version 0.6.1
  docs/en/nlp_server/release_notes.md
Labels: documentation

#8321 2022-05-08-rxnorm_action_treatment_mapper_en_3_0
  docs/_posts/galiph/2022-05-08-rxnorm_action_treatment_mapper_en_3_0.md
Labels: new model

#8322 2022-05-09-rxnorm_ndc_mapper_en_3_0
  docs/_posts/galiph/2022-05-09-rxnorm_ndc_mapper_en_3_0.md
Labels: new model

#8403 Minor updates to the release notes content.
  docs/en/nlp_server/release_notes.md
Labels: documentation

#8405 2022-05-10-sbiobertresolve_cpt_procedures_measurements_augmented_en_3_0
  docs/_posts/Cabir40/2022-05-10-sbiobertresolve_cpt_procedures_measurements_augmented_en_3_0.md
Labels: new model

#8406 2022-05-10-ner_biomedical_bc2gm_en_3_0
  docs/_posts/murat-gunay/2022-05-10-ner_biomedical_bc2gm_en_3_0.md
Labels: new model

#8410 2022-05-11-drug_brandname_ndc_mapper_en_3_0
  docs/_posts/galiph/2022-05-11-drug_brandname_ndc_mapper_en_3_0.md
Labels: new model

#8411 2022-05-11-ner_biomedical_bc2gm_en_2_4
  docs/_posts/murat-gunay/2022-05-11-ner_biomedical_bc2gm_en_2_4.md
Labels: new model

#6971 Update to TensorFlow 2.7
  build.sbt
  project/Dependencies.scala
  src/main/resources/sp-process/linux/_sentencepiece_tokenizer.so
  src/main/resources/sp-process/mac/_sentencepiece_tokenizer.dylib
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
Labels: new-feature, DON'T MERGE

#8414 2022-05-11-abbreviation_mapper_en_3_0
  docs/_posts/Ahmetemintek/2022-05-11-abbreviation_mapper_en_3_0.md
Labels: new model

#8415 2022-05-12-sbiobertresolve_icd10cm_slim_normalized_en_3_0
  docs/_posts/Cabir40/2022-05-12-sbiobertresolve_icd10cm_slim_normalized_en_3_0.md
Labels: new model

#8413 2022-05-11-sbiobertresolve_icd10cm_slim_billable_hcc_en_3_0
  docs/_posts/Cabir40/2022-05-11-sbiobertresolve_icd10cm_slim_billable_hcc_en_3_0.md
Labels: new model

#8418 Merges models_hub_internal models into master to publish the MD files
  docs/_posts/Ahmetemintek/2022-05-11-abbreviation_mapper_en_3_0.md
  docs/_posts/Cabir40/2022-05-10-sbiobertresolve_cpt_procedures_measurements_augmented_en_3_0.md
  docs/_posts/Cabir40/2022-05-11-sbiobertresolve_icd10cm_slim_billable_hcc_en_3_0.md
  docs/_posts/Cabir40/2022-05-12-sbiobertresolve_icd10cm_slim_normalized_en_3_0.md
  docs/_posts/galiph/2022-05-08-rxnorm_action_treatment_mapper_en_3_0.md
  docs/_posts/galiph/2022-05-09-rxnorm_ndc_mapper_en_3_0.md
  docs/_posts/galiph/2022-05-11-drug_brandname_ndc_mapper_en_3_0.md
  docs/_posts/murat-gunay/2022-05-10-ner_biomedical_bc2gm_en_3_0.md
  docs/_posts/murat-gunay/2022-05-11-ner_biomedical_bc2gm_en_2_4.md
Labels: models_hub, new model

#8438 2022-05-14-xlmroberta_embeddings_xlm_roberta_base_uk_3_0
  docs/_posts/murat-gunay/2022-05-14-xlmroberta_embeddings_xlm_roberta_base_uk_3_0.md
Labels: new model

#8444 2022-05-14-xlmroberta_embeddings_cino_large_xx_3_0
  docs/_posts/murat-gunay/2022-05-14-xlmroberta_embeddings_cino_large_xx_3_0.md
Labels: new model

#8449 Removing json4s-ext dependency
  build.sbt
  project/Dependencies.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceMetadata.scala
  src/main/scala/com/johnsnowlabs/util/TrainingHelper.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherMultiLanguageTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderSpec.scala
Labels: enhancement, new-feature, dependencies, DON'T MERGE

#8451 Feature/unify Spark NLP released packages
  .github/workflows/build_and_test.yml
  build.sbt
  project/Dependencies.scala
Labels: enhancement, dependencies, DON'T MERGE

#8450 2022-05-16-electra_embeddings_kr_electra_generator_ko_3_0
  docs/_posts/murat-gunay/2022-05-16-electra_embeddings_kr_electra_generator_ko_3_0.md
Labels: new model

#8466 2022-05-16-distilbert_ner_ma_ner_v7_distil_en_3_0
  docs/_posts/gadde5300/2022-05-16-distilbert_ner_ma_ner_v7_distil_en_3_0.md
Labels: new model

#8285 2022-05-04-bert_sentence_embeddings_financial_de_3_0
  docs/_posts/gadde5300/2022-05-04-bert_sentence_embeddings_financial_de_3_0.md
Labels: new model

#8286 2022-05-04-roberta_embeddings_financial_en_3_0
  docs/_posts/gadde5300/2022-05-04-roberta_embeddings_financial_en_3_0.md
Labels: new model

#8507 2022-05-17-xlmroberta_ner_xlm_roberta_large_ner_spanish_es_3_0
  docs/_posts/gadde5300/2022-05-17-xlmroberta_ner_xlm_roberta_large_ner_spanish_es_3_0.md
Labels: new model

#8508 2022-05-17-xlmroberta_ner_xlm_roberta_base_turkish_ner_tr_3_0
  docs/_posts/gadde5300/2022-05-17-xlmroberta_ner_xlm_roberta_base_turkish_ner_tr_3_0.md
Labels: new model

#8509 2022-05-17-xlmroberta_ner_xlm_roberta_large_finetuned_conll03_german_de_3_0
  docs/_posts/gadde5300/2022-05-17-xlmroberta_ner_xlm_roberta_large_finetuned_conll03_german_de_3_0.md
Labels: new model

#8510 2022-05-17-xlmroberta_ner_xlm_roberta_base_finetuned_panx_ner_it_3_0
  docs/_posts/gadde5300/2022-05-17-xlmroberta_ner_xlm_roberta_base_finetuned_panx_ner_it_3_0.md
Labels: new model

#8528 2022-05-18-xlmroberta_pos_xlm_roberta_base_english_upos_en_3_0
  docs/_posts/gadde5300/2022-05-18-xlmroberta_pos_xlm_roberta_base_english_upos_en_3_0.md
Labels: new model

#8534 2022-05-20-roberta_ner_jurisbert_finetuning_ner_es_3_0
  docs/_posts/gadde5300/2022-05-20-roberta_ner_jurisbert_finetuning_ner_es_3_0.md
Labels: new model

#8538 2022-05-20-roberta_jurisbert_clas_art_convencion_americana_dh_es_3_0
  docs/_posts/gadde5300/2022-05-20-roberta_jurisbert_clas_art_convencion_americana_dh_es_3_0.md
Labels: new model

#8539 2022-05-20-roberta_jurisbert_class_tratados_internacionales_sistema_universal_es_3_0
  docs/_posts/gadde5300/2022-05-20-roberta_jurisbert_class_tratados_internacionales_sistema_universal_es_3_0.md
Labels: new model

#8540 2022-05-20-roberta_embeddings_financial_roberta_en_3_0
  docs/_posts/gadde5300/2022-05-20-roberta_embeddings_financial_roberta_en_3_0.md
Labels: new model

#8541 2022-05-20-rxnorm_ndc_mapper_en_3_0
  docs/_posts/galiph/2022-05-20-rxnorm_ndc_mapper_en_3_0.md
Labels: new model

#8533 M1 support, upgrade to newer RocksDB and AWS Java SDK
  project/Dependencies.scala
  src/main/resources/sentencepiece/libsentencepiece_jni.dylib
  src/main/resources/sentencepiece/libsentencepiece_jni.so
  src/main/resources/sentencepiece/libsentencepiece_jni_m1.dylib
  src/main/resources/sentencepiece/sentencepiece_jni.dll
  src/main/resources/sp-process/mac/_sentencepiece_tokenizer_m1.dylib
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/LoadSentencepiece.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/SentencePieceJNI.java
Labels: enhancement, new-feature, dependencies, DON'T MERGE

#8555 Bugfix/8546 docnorm
  src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentNormalizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentNormalizerBehaviors.scala
Labels: enhancement, bug-fix

#8544 Migrate to Scala 2.12.15
  .github/workflows/build_and_test.yml
  project/Dependencies.scala
  project/plugins.sbt
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerUtil.scala
  src/test/scala/com/johnsnowlabs/nlp/AssertAnnotations.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerUtilTest.scala
Labels: enhancement, dependencies, DON'T MERGE

#8558 Migrate T5Transformer to TensorFlow v2
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sign/ModelSignatureConstants.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
Labels: enhancement

#8561 2022-05-27-rct_binary_classifier_use_en_3_0
  docs/_posts/Ahmetemintek/2022-05-27-rct_binary_classifier_use_en_3_0.md
Labels: new model

#8560 2022-05-27-rct_binary_classifier_biobert_en_3_0
  docs/_posts/Ahmetemintek/2022-05-27-rct_binary_classifier_biobert_en_3_0.md
Labels: new model

#8637 2022-05-31-t5_small_en_3_0
  docs/_posts/maziyarpanahi/2022-05-31-t5_small_en_3_0.md
Labels: new model

#8630 2022-05-31-t5_formal_to_informal_styletransfer_en_3_0
  docs/_posts/maziyarpanahi/2022-05-31-t5_formal_to_informal_styletransfer_en_3_0.md
Labels: new model

#8632 2022-05-31-t5_active_to_passive_styletransfer_en_3_0
  docs/_posts/maziyarpanahi/2022-05-31-t5_active_to_passive_styletransfer_en_3_0.md
Labels: new model

#8634 2022-05-31-t5_passive_to_active_styletransfer_en_3_0
  docs/_posts/maziyarpanahi/2022-05-31-t5_passive_to_active_styletransfer_en_3_0.md
Labels: new model

#8635 2022-05-31-google_t5_small_ssm_nq_en_3_0
  docs/_posts/maziyarpanahi/2022-05-31-google_t5_small_ssm_nq_en_3_0.md
Labels: new model

#8636 2022-05-31-t5_base_en_3_0
  docs/_posts/maziyarpanahi/2022-05-31-t5_base_en_3_0.md
Labels: new model
