Repository JohnSnowLabs/spark-nlp, pull requests merged in 2022-10, with the labels that each got.

#12870 2022-09-30-ner_oncology_wip_en
  docs/_posts/mauro-nievoff/2022-09-30-ner_oncology_anatomy_general_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-30-ner_oncology_demographics_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-30-ner_oncology_diagnosis_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-30-ner_oncology_test_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-30-ner_oncology_therapy_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-30-ner_oncology_tnm_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-30-ner_oncology_unspecific_posology_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-30-ner_oncology_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-ner_oncology_anatomy_granular_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-ner_oncology_biomarker_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-ner_oncology_posology_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-ner_oncology_response_to_treatment_wip_en.md
Labels: new model

#12876 2022-10-02-legner_arabert_arabic_ar
  docs/_posts/josejuanmartinez/2022-10-02-legner_arabert_arabic_ar.md
  docs/_posts/josejuanmartinez/2022-10-02-legner_bert_base_courts_de.md
  docs/_posts/josejuanmartinez/2022-10-02-legner_bert_large_courts_de.md
  docs/_posts/josejuanmartinez/2022-10-02-legner_courts_de.md
Labels: new model

#12878 2022-10-02-legner_bert_base_courts_de
  docs/_posts/josejuanmartinez/2022-10-02-legner_bert_base_courts_de.md
Labels: new model

#12873 2022-10-01-assertion_oncology_wip_en
  docs/_posts/mauro-nievoff/2022-10-01-assertion_oncology_demographic_binary_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-assertion_oncology_family_history_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-assertion_oncology_problem_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-assertion_oncology_response_to_treatment_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-assertion_oncology_smoking_status_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-assertion_oncology_test_binary_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-assertion_oncology_treatment_binary_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-01-assertion_oncology_wip_en.md
Labels: new model

#12893 Docs/visual nlp
  docs/_layouts/nlp_products.html
  docs/en/ocr.md
Labels: documentation

#12894 Add new demos, fixing tabs in posts
  docs/_data/navigation.yml
  docs/_includes/demomenu.html
  docs/_includes/programmingLanguageSelectScalaPythonMFL.html
  docs/_includes/programmingLanguageSelectScalaPythonNLU.html
  docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
  docs/_posts/josejuanmartinez/2022-09-06-finclf_augmented_esg_en.md
  docs/_sass/custom.scss
  docs/assets/images/Classify_Public_Health_Mentions.svg
  docs/assets/images/Detect_Law_and_Money_entities_in_Spanish.svg
  docs/assets/images/Extract_Entities_in_Indemnification_Clauses.svg
  docs/assets/images/Long_Text_Splitting.svg
  docs/demos/financial_document_splitting.md
  docs/demos/legal_entity_recognition.md
  docs/demos/legal_relation_extraction.md
  docs/demos/long_document_splitting.md
  docs/demos/public_health.md
  docs/en/alab/tutorials.md
Labels: enhancement, documentation

#12896 added details on relation constraints
  docs/en/alab/project_setup.md
Labels: documentation

#12868 Improve Error Handling to fullAnnotateImage in LightPipeline
  python/sparknlp/annotation.py
  python/sparknlp/base/light_pipeline.py
  python/test/annotator/cv/vit_for_image_classification_test.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowViTClassifier.scala
  src/main/scala/com/johnsnowlabs/nlp/ImageAssembler.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/util/io/ImageIOUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/ViTImageClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/feature_extractor/ImageUtilsTestSpec.scala
Labels: bug-fix, DON'T MERGE

#12889 Added Docs for SpanBertCoref
  docs/en/annotators.md
  docs/en/transformer_entries/SpanBertCoref.md
  python/sparknlp/annotator/coref/spanbert_coref.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/coref/SpanBertCorefModel.scala
Labels: enhancement, documentation, DON'T MERGE

#12901 Silently skip to construct bad Chunks
  docs/_data/navigation.yml
  docs/_includes/demomenu.html
  docs/_includes/programmingLanguageSelectScalaPythonMFL.html
  docs/_includes/programmingLanguageSelectScalaPythonNLU.html
  docs/_includes/scripts/programmingLanguageSwitcherScalaPython.js
  docs/_includes/templates/anno_template.md
  docs/_includes/templates/approach_model_template.md
  docs/_includes/templates/licensed_anno_template.md
  docs/_includes/templates/licensed_approach_model_template.md
  docs/_includes/templates/licensed_training_anno_template.md
  docs/_includes/templates/licensed_training_dataset_entry.md
  docs/_includes/templates/training_anno_template.md
  docs/_includes/templates/training_dataset_entry.md
  docs/_includes/templates/transformer_usecases_template.md
  docs/_layouts/nlp_products.html
  docs/_posts/Meryem1425/2022-07-28-bert_sequence_classifier_treatement_changes_sentiment_tweet_en_3_0.md
  docs/_posts/josejuanmartinez/2022-09-06-finclf_augmented_esg_en.md
  docs/_posts/kolia1985/2021-12-09-text_detection_v1_en.md
  docs/_posts/kolia1985/2021-12-21-text_cleaner_v1_en.md
  docs/_posts/kolia1985/2022-02-16-ocr_base_handwritten_en.md
  docs/_posts/kolia1985/2022-02-16-ocr_small_printed_en.md
  docs/_posts/kolia1985/2022-02-17-ocr_small_handwritten_en.md
  docs/_posts/luca-martial/2022-07-07-clinical_deidentification_wip_en_3_2.md
  docs/_posts/xyutech/2021-09-04-ocr_table_detection_general_model_en.md
  docs/_posts/xyutech/2022-01-05-layoutlmv2_funsd_en.md
  docs/_sass/custom.scss
  docs/assets/images/Classify_Public_Health_Mentions.svg
  docs/assets/images/Detect_Law_and_Money_entities_in_Spanish.svg
  docs/assets/images/Extract_Entities_in_Indemnification_Clauses.svg
  docs/assets/images/Long_Text_Splitting.svg
  docs/demos/financial_document_splitting.md
  docs/demos/legal_entity_recognition.md
  docs/demos/legal_relation_extraction.md
  docs/demos/long_document_splitting.md
  docs/demos/public_health.md
  docs/en/alab/project_setup.md
  docs/en/alab/tutorials.md
  docs/en/annotator_entries/SentenceEmbeddings.md
  docs/en/annotator_entries/StopWordsCleaner.md
  docs/en/auxiliary.md
  docs/en/concepts.md
  docs/en/evaluation.md
  docs/en/ocr.md
  docs/en/ocr_object_detection.md
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_table_recognition.md
  docs/en/ocr_visual_document_understanding.md
  docs/en/third-party-projects.md
  docs/en/training.md
  src/main/scala/com/johnsnowlabs/nlp/annotators/Chunker.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ChunkerTestSpec.scala
Labels: bug-fix, DON'T MERGE

#12904 Add support for Double in AudioAssembler
  docs/_frontend/src/models/FilterForm/FilterForm.js
  docs/_frontend/src/models/ModelItem/ModelItem.js
  docs/_frontend/src/models/ModelItem/utils.js
  python/sparknlp/base/audio_assembler.py
  python/test/annotator/audio/wav2vec2_for_ctc_test.py
  src/main/scala/com/johnsnowlabs/nlp/AudioAssembler.scala
  src/test/scala/com/johnsnowlabs/nlp/AudioAssemblerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/audio/Wav2Vec2ForCTCTestSpec.scala
Labels: new-feature

#12895 Adding audio input support in LightPipeline
  python/sparknlp/base/light_pipeline.py
  python/sparknlp/internal/__init__.py
  python/sparknlp/training/_tf_graph_builders/graph_builders.py
  python/sparknlp/training/_tf_graph_builders_1x/graph_builders.py
  python/test/annotator/audio/wav2vec2_for_ctc_test.py
  python/test/base/light_pipeline_test.py
  src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
  src/test/resources/audio/csv/audio_floats.csv
  src/test/scala/com/johnsnowlabs/nlp/AudioAssemblerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/audio/Wav2Vec2ForCTCTestSpec.scala
Labels: bug-fix, new-feature, DON'T MERGE

#12910 2022-10-11-beto_sentiment_es
  docs/_posts/gokhanturer/2022-10-11-beto_sentiment_es.md
Labels: new model

#12875 FIX: ContextSpellCheckerModel updateVocabClass Nullpointer
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
Labels: bug-fix, DON'T MERGE

#12917 2022-10-12-cvx_code_mapper_en
  docs/_posts/Ahmetemintek/2022-10-12-cvx_code_mapper_en.md
  docs/_posts/Ahmetemintek/2022-10-12-cvx_name_mapper_en.md
Labels: new model

#12916 2022-10-12-pipeline_image_classifier_vit_rock_challenge_DeiT_solo_2_en
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_SDO_VT1_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_Teeth_B_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit__spectrogram_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_amgerindaf_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_anomaly_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_autotrain_dog_vs_food_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_base_avengers_v1_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_base_movie_scenes_v1_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_base_patch16_224_in21k_classify_4scence_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_base_patch16_224_in21k_ucSat_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_croupier_creature_classifier_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_digital_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_dog_food__base_patch16_224_in21k_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_dwarf_goats_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_electric_pole_type_classification_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_exper5_mesum5_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_exper_batch_16_e4_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_exper_batch_8_e4_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_exper_batch_8_e8_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_finetuned_cats_dogs_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_generation_xyz_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_grain_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_gtsrb_model_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_hot_dog_or_sandwich_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_hugging_geese_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_huggingpics_package_demo_2_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_ice_cream_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_koala_panda_wombat_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_llama_alpaca_snake_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_llama_or_what_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_lung_cancer_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_mit_indoor_scenes_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_modeversion1_m7_e4_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_modeversion2_m7_e8_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_new_exper3_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_pasta_shapes_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_planes_trains_automobiles_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_pneumonia_bielefeld_dl_course_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_pond_image_classification_12_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_pond_image_classification_3_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_pond_image_classification_5_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_rare_bottle_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_rare_puppers3_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_rare_puppers_09_04_2021_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_resnet_50_euroSat_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_resnet_50_ucSat_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_rock_challenge_DeiT_solo_2_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_rust_image_classification_10_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_rust_image_classification_11_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_rust_image_classification_12_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_rust_image_classification_5_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_snacks_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_string_instrument_detector_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_taco_or_what_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_teeth_test_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_trainer_rare_puppers_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_vc_bantai__withoutAMBI_adunest_v1_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_vc_bantai__withoutAMBI_adunest_v2_en.md
  docs/_posts/ahmedlone127/2022-10-12-pipeline_image_classifier_vit_where_am_I_hospital_balcony_hallway_airport_coffee_house_apartment_office_en.md
Labels: new model, DON'T MERGE

#12892 2022-10-05-sbiobertresolve_cvx_en
  docs/_posts/galiph/2022-10-05-sbiobertresolve_cvx_en.md
Labels: new model

#12924 2022-10-12-sbiobertresolve_cvx_en
  docs/_posts/Ahmetemintek/2022-10-12-cvx_code_mapper_en.md
  docs/_posts/Ahmetemintek/2022-10-12-cvx_name_mapper_en.md
  docs/_posts/Ahmetemintek/2022-10-12-sbiobertresolve_cvx_en.md
Labels: new model

#12911 2022-10-11-assertion_oncology_wip_en
  docs/_posts/mauro-nievoff/2022-10-11-assertion_oncology_demographic_binary_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-11-assertion_oncology_family_history_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-11-assertion_oncology_problem_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-11-assertion_oncology_response_to_treatment_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-11-assertion_oncology_smoking_status_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-11-assertion_oncology_treatment_binary_wip_en.md
  docs/_posts/mauro-nievoff/2022-10-11-assertion_oncology_wip_en.md
Labels: new model

#12926 2022-10-12-cvx_resolver_pipeline_en
  docs/_posts/Ahmetemintek/2022-10-12-cvx_resolver_pipeline_en.md
Labels: new model

#12921 Changes to the installation page
  docs/en/alab/install.md
Labels: documentation

#12935 Added/updated content and images for Administration section.
  docs/_data/navigation.yml
  docs/_includes/sidebar/toc.html
  docs/_sass/custom.scss
  docs/assets/images/annotation_lab/4.1.0/add_license.png
  docs/assets/images/annotation_lab/4.1.0/analytics_requests.png
  docs/assets/images/annotation_lab/4.1.0/ar_granted.png
  docs/assets/images/annotation_lab/4.1.0/ar_revoked.png
  docs/assets/images/annotation_lab/4.1.0/backupRestoreUI.png
  docs/assets/images/annotation_lab/4.1.0/infrastructure.png
  docs/assets/images/annotation_lab/4.1.0/list_of_projects.png
  docs/assets/images/annotation_lab/4.1.0/server_management.gif
  docs/assets/images/annotation_lab/4.1.0/server_status.png
  docs/assets/images/annotation_lab/4.1.0/swagger.png
  docs/assets/images/annotation_lab/4.1.0/user_credentials.png
  docs/assets/images/annotation_lab/4.1.0/user_details.png
  docs/assets/images/annotation_lab/4.1.0/user_group.png
  docs/assets/images/annotation_lab/4.1.0/user_management.png
  docs/assets/images/annotation_lab/4.1.0/users.png
  docs/en/alab/analytics_permission.md
  docs/en/alab/api.md
  docs/en/alab/backup_restore.md
  docs/en/alab/byol.md
  docs/en/alab/cluster_management.md
  docs/en/alab/infrastructure.md
  docs/en/alab/user_management.md
Labels: documentation

#12939 2022-10-15-finre_has_ticker_en
  docs/_posts/gokhanturer/2022-10-15-finre_has_ticker_en.md
Labels: new model

#12942 2022-10-17-legner_confidentiality_en
  docs/_posts/gadde5300/2022-10-17-legner_confidentiality_en.md
  docs/_posts/gadde5300/2022-10-17-legner_warranty_en.md
Labels: new model

#12932 Docs/databricks install update 20221013
  docs/assets/images/install_form.png
  docs/assets/images/myJSLdeployment.png
  docs/en/licensed_install.md
Labels: documentation

#12947 2022-10-18-legclf_cuad_warranty_clause_en
  docs/_posts/josejuanmartinez/2022-10-18-legclf_cuad_warranty_clause_en.md
Labels: new model

#12948 2022-10-18-legre_confidentiality_en
  docs/_posts/gadde5300/2022-10-18-legre_confidentiality_en.md
Labels: new model

#12956 2022-10-19-finner_financial_small_en
  docs/_posts/josejuanmartinez/2022-10-19-finner_financial_medium_en.md
  docs/_posts/josejuanmartinez/2022-10-19-finner_financial_small_en.md
Labels: new model

#12953 2022-10-19-ner_covid_trials_en
  docs/_posts/Ahmetemintek/2022-10-19-ner_covid_trials_en.md
  docs/_posts/Ahmetemintek/2022-10-19-ner_jsl_en.md
Labels: new model

#12961 2022-10-20-finner_financial_large_en
  docs/_posts/josejuanmartinez/2022-10-20-finner_financial_large_en.md
Labels: new model

#12928 Added Details for Project page
  docs/_data/navigation.yml
  docs/assets/images/annotation_lab/4.1.0/NER_template.png
  docs/assets/images/annotation_lab/4.1.0/dashboardCloneImportExport.png
  docs/assets/images/annotation_lab/4.1.0/dashboardGroup.png
  docs/assets/images/annotation_lab/4.1.0/dashboardShared.png
  docs/assets/images/annotation_lab/4.1.0/dashboardSort.png
  docs/assets/images/annotation_lab/4.1.0/loginScreenALAB.png
  docs/assets/images/annotation_lab/4.1.0/reserved.gif
  docs/assets/images/annotation_lab/4.1.0/template.jpg
  docs/en/alab/install.md
  docs/en/alab/project_configuration.md
  docs/en/alab/project_creation.md
  docs/en/alab/project_dashboard.md
  docs/en/alab/project_setup.md
  docs/en/alab/start_page.md
Labels: documentation

#12968 2022-10-21-legclf_consulting_agreement_en
  docs/_posts/josejuanmartinez/2022-10-21-legclf_consulting_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-21-legclf_credit_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-21-legclf_employment_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-21-legclf_lease_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-21-legclf_loan_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-21-legclf_management_contract_en.md
  docs/_posts/josejuanmartinez/2022-10-21-legclf_purchase_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-21-legclf_service_agreement_en.md
Labels: new model

#12972 2022-10-22-finel_nasdaq_data_company_name_en
  docs/_posts/josejuanmartinez/2022-10-22-finel_nasdaq_data_company_name_en.md
  docs/_posts/josejuanmartinez/2022-10-22-finel_nasdaq_data_ticker_en.md
  docs/_posts/josejuanmartinez/2022-10-22-finmapper_nasdaq_data_company_name_en.md
  docs/_posts/josejuanmartinez/2022-10-22-finmapper_nasdaq_data_ticker_en.md
Labels: new model

#12975 2022-10-22-finclf_bert_sentiment_analysis_lt
  docs/_posts/josejuanmartinez/2022-10-22-finclf_bert_sentiment_analysis_lt.md
Labels: new model

#12979 2022-10-24-legclf_consulting_agreement_en
  docs/_posts/josejuanmartinez/2022-10-24-legclf_consulting_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-24-legclf_credit_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-24-legclf_employment_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-24-legclf_lease_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-24-legclf_loan_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-24-legclf_management_contract_en.md
  docs/_posts/josejuanmartinez/2022-10-24-legclf_purchase_agreement_en.md
  docs/_posts/josejuanmartinez/2022-10-24-legclf_service_agreement_en.md
Labels: new model

#12986 2022-10-25-legner_indian_court_judgement_en
  docs/_posts/bunyamin-polat/2022-10-25-legner_indian_court_judgement_en.md
Labels: new model

#12987 2022-10-25-legner_indian_court_preamble_en
  docs/_posts/bunyamin-polat/2022-10-25-legner_indian_court_preamble_en.md
Labels: new model

#12990 2022-10-25-legclf_bert_swiss_judgements_it
  docs/_posts/bunyamin-polat/2022-10-25-legclf_bert_swiss_judgements_de.md
  docs/_posts/bunyamin-polat/2022-10-25-legclf_bert_swiss_judgements_en.md
  docs/_posts/bunyamin-polat/2022-10-25-legclf_bert_swiss_judgements_fr.md
  docs/_posts/bunyamin-polat/2022-10-25-legclf_bert_swiss_judgements_it.md
Labels: new model

#12984 2022-10-25-t5_base_pubmedqa_en
  docs/_posts/HashamUlHaq/2022-10-25-t5_base_pubmedqa_en.md
Labels: new model

#12989 2022-10-25-ner_oncology_en
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_anatomy_general_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_anatomy_granular_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_biomarker_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_demographics_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_diagnosis_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_posology_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_response_to_treatment_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_test_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_therapy_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_tnm_en.md
  docs/_posts/mauro-nievoff/2022-10-25-ner_oncology_unspecific_posology_en.md
Labels: new model

#12950 Unify fullAnnotate between LightPipeline and PretrainedPipeline
  python/sparknlp/base/light_pipeline.py
  python/sparknlp/pretrained/pretrained_pipeline.py
  python/test/pretrained/pretrained_pipeline_test.py
  python/test/pretrained/resource_downloader_test.py
  src/main/scala/com/johnsnowlabs/nlp/Annotation.scala
  src/main/scala/com/johnsnowlabs/nlp/AnnotationAudio.scala
  src/main/scala/com/johnsnowlabs/nlp/AnnotationImage.scala
  src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/PretrainedPipeline.scala
  src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/MultiDocumentAssemblerTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/audio/Wav2Vec2ForCTCTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/ViTImageClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/PretrainedPipelineTest.scala
Labels: enhancement, DON'T MERGE

#12959 Fix Inconsistent Names Annotator Schema
  python/sparknlp/annotation.py
  python/sparknlp/annotation_audio.py
  python/sparknlp/annotation_image.py
Labels: enhancement, DON'T MERGE

#12965 Adding token indexes in RecursiveTokenizer output
  src/main/scala/com/johnsnowlabs/nlp/annotators/RecursiveTokenizerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RecursiveTokenizerFixture.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RecursiveTokenizerTest.scala
Labels: bug-fix, DON'T MERGE

#12995 SPARKNLP-561: Adjust return format of copyToLocal
  src/main/scala/com/johnsnowlabs/ml/util/LoadExternalModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
  src/test/scala/com/johnsnowlabs/util/ResourceHelperTestSpec.scala
Labels: enhancement, bug-fix

#12994 2022-10-27-legclf_bert_swiss_judgements_de
  docs/_posts/bunyamin-polat/2022-10-27-legclf_bert_swiss_judgements_de.md
  docs/_posts/bunyamin-polat/2022-10-27-legclf_bert_swiss_judgements_en.md
  docs/_posts/bunyamin-polat/2022-10-27-legclf_bert_swiss_judgements_fr.md
  docs/_posts/bunyamin-polat/2022-10-27-legclf_bert_swiss_judgements_it.md
Labels: new model

#13003 2022-10-28-sbiobertresolve_icd10pcs_augmented_en
  docs/_posts/Ahmetemintek/2022-10-28-sbiobertresolve_icd10pcs_augmented_en.md
Labels: new model

#12985 Changes for model training docs
  docs/_data/navigation.yml
  docs/assets/images/annotation_lab/4.1.0/activeLearning.png
  docs/assets/images/annotation_lab/4.1.0/classification_pipeline.png
  docs/assets/images/annotation_lab/4.1.0/config_update.png
  docs/assets/images/annotation_lab/4.1.0/customScript.png
  docs/assets/images/annotation_lab/4.1.0/modelinPredefined.png
  docs/assets/images/annotation_lab/4.1.0/train_setup_label.png
  docs/assets/images/annotation_lab/4.1.0/train_setup_model.png
  docs/assets/images/annotation_lab/4.1.0/train_setup_pipeline.png
  docs/assets/images/annotation_lab/4.1.0/trainingparameters.png
  docs/assets/images/annotation_lab/4.1.0/transferLearning.gif
  docs/en/alab/active_learning.md
  docs/en/alab/training_configurations.md
  docs/en/alab/transfer_learning.md
Labels: documentation

#13004 2022-10-29-icd10cm_mapper_en
  docs/_posts/Ahmetemintek/2022-10-29-icd10cm_mapper_en.md
Labels: new model
