Repository JohnSnowLabs/spark-nlp, pull requests merged in 2022-04, with the labels that each got.

#7651 2022-04-01-re_zeroshot_biobert_en_3_0
  docs/_posts/josejuanmartinez/2022-04-01-re_zeroshot_biobert_en_3_0.md
Labels: new model

#7653 2022-04-01-explain_clinical_doc_medication_en_3_0
  docs/_posts/Cabir40/2022-04-01-explain_clinical_doc_medication_en_3_0.md
Labels: new model

#7655 2022-04-01-spellcheck_dl_en_2_4
  docs/_posts/murat-gunay/2022-04-01-spellcheck_dl_en_2_4.md
Labels: new model

#7657 2022-04-01-normalized_section_header_mapper_en_3_0
  docs/_posts/Ahmetemintek/2022-04-01-normalized_section_header_mapper_en_3_0.md
Labels: new model

#7575 2022-03-31-drug_action_treatment_mapper_en_3_0
  docs/_posts/Ahmetemintek/2022-03-31-drug_action_treatment_mapper_en_3_0.md
Labels: new model

#7660 2022-04-02-zero_shot_re_en_3_0
  docs/_posts/josejuanmartinez/2022-04-02-zero_shot_re_en_3_0.md
Labels: new model

#7486 Docs: Update SentenceDetector
  docs/en/annotator_entries/SentenceDetector.md
  docs/en/annotators.md
  docs/en/training_entries/conll.md
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.scala
Labels: enhancement, documentation

#7662 2022-04-02-spellcheck_dl_en_2_4
  docs/_posts/murat-gunay/2022-04-02-spellcheck_dl_en_2_4.md
Labels: new model

#7664 2022-04-03-roberta_token_classifier_ticker_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-03-roberta_token_classifier_ticker_pipeline_en_3_0.md
Labels: new model

#7667 2022-04-04-re_zeroshot_biobert_en_3_0
  docs/_posts/josejuanmartinez/2022-04-04-re_zeroshot_biobert_en_3_0.md
Labels: new model

#7670 2022-04-04-normalized_section_header_mapper_en_3_0
  docs/_posts/Ahmetemintek/2022-04-04-normalized_section_header_mapper_en_3_0.md
Labels: new model

#7669 2022-04-04-drug_action_treatment_mapper_en_3_0
  docs/_posts/Ahmetemintek/2022-04-04-drug_action_treatment_mapper_en_3_0.md
Labels: new model

#7674 2022-04-05-zero_shot_re_en_3_0
  docs/_posts/josejuanmartinez/2022-04-05-zero_shot_re_en_3_0.md
Labels: new model

#7671 Added first draft of release notes for NLP Server v060
  docs/en/nlp_server/release_notes.md
Labels: documentation

#7676 2022-04-05-re_zeroshot_biobert_en_3_0
  docs/_posts/josejuanmartinez/2022-04-05-re_zeroshot_biobert_en_3_0.md
Labels: new model

#7679 Annotation Lab 3.0.0 release notes
  docs/en/alab/active_learning.md
  docs/en/alab/byol.md
  docs/en/alab/infrastructure.md
  docs/en/alab/preannotations.md
  docs/en/alab/release_notes.md
  docs/en/alab/visual_ner.md
Labels: documentation

#7683 minor updates to the release note for v060
  docs/en/nlp_server/release_notes.md
Labels: documentation

#7682 Add a new functionality to download and extract models from S3 via direct link
  python/sparknlp/internal.py
  python/sparknlp/pretrained.py
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/MockResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala
Labels: new-feature

#7689 2022-04-08-bert_biolink_large_en_3_0
  docs/_posts/murat-gunay/2022-04-08-bert_biolink_large_en_3_0.md
Labels: new model

#7700 2022-04-09-deberta_v3_small_sequence_classifier_imdb_en_3_0
  docs/_posts/maziyarpanahi/2022-04-09-deberta_v3_small_sequence_classifier_imdb_en_3_0.md
Labels: new model

#7704 2022-04-09-deberta_v3_small_sequence_classifier_imdb_en_3_0
  docs/_posts/maziyarpanahi/2022-04-09-deberta_v3_small_sequence_classifier_imdb_en_3_0.md
Labels: new model

#7705 2022-04-09-deberta_v3_xsmall_sequence_classifier_imdb_en_3_0
  docs/_posts/maziyarpanahi/2022-04-09-deberta_v3_xsmall_sequence_classifier_imdb_en_3_0.md
Labels: new model

#7706 2022-04-09-deberta_v3_base_sequence_classifier_imdb_en_3_0
  docs/_posts/maziyarpanahi/2022-04-09-deberta_v3_base_sequence_classifier_imdb_en_3_0.md
Labels: new model

#7707 2022-04-09-deberta_v3_large_sequence_classifier_imdb_en_3_0
  docs/_posts/maziyarpanahi/2022-04-09-deberta_v3_large_sequence_classifier_imdb_en_3_0.md
Labels: new model

#7708 2022-04-09-deberta_v3_small_sequence_classifier_ag_news_en_3_0
  docs/_posts/maziyarpanahi/2022-04-09-deberta_v3_small_sequence_classifier_ag_news_en_3_0.md
Labels: new model

#7709 2022-04-09-deberta_v3_xsmall_sequence_classifier_ag_news_en_3_0
  docs/_posts/maziyarpanahi/2022-04-09-deberta_v3_xsmall_sequence_classifier_ag_news_en_3_0.md
Labels: new model

#7710 2022-04-09-mdeberta_v3_base_sequence_classifier_imdb_ur_3_0
  docs/_posts/maziyarpanahi/2022-04-09-mdeberta_v3_base_sequence_classifier_imdb_ur_3_0.md
Labels: new model

#7711 2022-04-09-mdeberta_v3_base_sequence_classifier_allocine_fr_3_0
  docs/_posts/maziyarpanahi/2022-04-09-mdeberta_v3_base_sequence_classifier_allocine_fr_3_0.md
Labels: new model

#7712 2022-04-09-deberta_v3_small_sequence_classifier_dbpedia_14_en_3_0
  docs/_posts/maziyarpanahi/2022-04-09-deberta_v3_small_sequence_classifier_dbpedia_14_en_3_0.md
Labels: new model

#7693 2022-04-08-bert_embeddings_mengzi_bert_base_zh_3_0
  docs/_posts/luca-martial/2022-04-08-bert_embeddings_mengzi_bert_base_zh_3_0.md
Labels: new model

#7714 2022-04-08-bert_biolink_base_en_3_0
  docs/_posts/murat-gunay/2022-04-08-bert_biolink_base_en_3_0.md
Labels: new model

#7828 2022-04-11-bert_embeddings_legal_bert_base_uncased_en_3_0
  docs/_posts/luca-martial/2022-04-11-bert_embeddings_legal_bert_base_uncased_en_3_0.md
Labels: new model

#7837 2022-04-11-bert_embeddings_legal_bert_small_uncased_en_3_0
  docs/_posts/luca-martial/2022-04-11-bert_embeddings_legal_bert_small_uncased_en_3_0.md
Labels: new model

#7882 2022-04-11-biobert_embeddings_all_pt_3_0
  docs/_posts/luca-martial/2022-04-11-biobert_embeddings_all_pt_3_0.md
Labels: new model

#7883 2022-04-11-biobert_embeddings_clinical_pt_3_0
  docs/_posts/luca-martial/2022-04-11-biobert_embeddings_clinical_pt_3_0.md
Labels: new model

#7884 2022-04-11-biobert_embeddings_biomedical_pt_3_0
  docs/_posts/luca-martial/2022-04-11-biobert_embeddings_biomedical_pt_3_0.md
Labels: new model

#7889 2022-04-12-bert_embeddings_sec_bert_base_en_3_0
  docs/_posts/luca-martial/2022-04-12-bert_embeddings_sec_bert_base_en_3_0.md
Labels: new model

#7887 2022-04-12-bert_embeddings_sec_bert_sh_en_3_0
  docs/_posts/luca-martial/2022-04-12-bert_embeddings_sec_bert_sh_en_3_0.md
Labels: new model

#7888 2022-04-12-bert_embeddings_sec_bert_num_en_3_0
  docs/_posts/luca-martial/2022-04-12-bert_embeddings_sec_bert_num_en_3_0.md
Labels: new model

#7926 2022-04-13-ner_deid_subentity_pt_3_0
  docs/_posts/josejuanmartinez/2022-04-13-ner_deid_subentity_pt_3_0.md
Labels: new model

#7831 2022-04-11-spellcheck_clinical_en_3_0
  docs/_posts/murat-gunay/2022-04-11-spellcheck_clinical_en_3_0.md
Labels: new model

#7927 2022-04-13-ner_deid_generic_pt_3_0
  docs/_posts/josejuanmartinez/2022-04-13-ner_deid_generic_pt_3_0.md
Labels: new model

#7931 2022-04-13-spellcheck_clinical_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-13-spellcheck_clinical_pipeline_en_3_0.md
Labels: new model

#7932 2022-04-14-spellcheck_clinical_en_2_4
  docs/_posts/murat-gunay/2022-04-14-spellcheck_clinical_en_2_4.md
Labels: new model

#7934 2022-04-14-spellcheck_clinical_pipeline_en_2_4
  docs/_posts/murat-gunay/2022-04-14-spellcheck_clinical_pipeline_en_2_4.md
Labels: new model

#7936 2022-04-14-spellcheck_dl_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-14-spellcheck_dl_pipeline_en_3_0.md
Labels: new model

#8025 2022-04-14-clinical_deidentification_pt_3_0
  docs/_posts/josejuanmartinez/2022-04-14-clinical_deidentification_pt_3_0.md
Labels: new model

#8026 updated backup configuration
  docs/assets/images/annotation_lab/3.1.0/backupRestoreUI.png
  docs/en/alab/install.md
Labels: documentation

#8045 2022-04-18-spellcheck_dl_pipeline_en_2_4
  docs/_posts/murat-gunay/2022-04-18-spellcheck_dl_pipeline_en_2_4.md
Labels: new model

#8046 2022-04-18-spellcheck_clinical_en_2_4
  docs/_posts/murat-gunay/2022-04-18-spellcheck_clinical_en_2_4.md
Labels: new model

#7939 2022-04-14-roberta_embeddings_roberta_base_wechsel_chinese_zh_3_0
  docs/_posts/luca-martial/2022-04-14-roberta_embeddings_roberta_base_wechsel_chinese_zh_3_0.md
Labels: new model

#7977 2022-04-14-roberta_embeddings_roberta_base_russian_v0_ru_3_0
  docs/_posts/luca-martial/2022-04-14-roberta_embeddings_roberta_base_russian_v0_ru_3_0.md
Labels: new model

#8050 2022-04-19-spellcheck_clinical_pipeline_en_2_4
  docs/_posts/murat-gunay/2022-04-19-spellcheck_clinical_pipeline_en_2_4.md
Labels: new model

#8054 2022-04-19-bert_token_classifier_dutch_udlassy_ner_pipeline_nl_3_0
  docs/_posts/murat-gunay/2022-04-19-bert_token_classifier_dutch_udlassy_ner_pipeline_nl_3_0.md
Labels: new model

#8055 2022-04-19-xlm_roberta_large_token_classifier_conll03_pipeline_de_3_0
  docs/_posts/murat-gunay/2022-04-19-xlm_roberta_large_token_classifier_conll03_pipeline_de_3_0.md
Labels: new model

#8048 2022-04-18-sbiobertresolve_ndc_en_2_4
  docs/_posts/galiph/2022-04-18-sbiobertresolve_ndc_en_2_4.md
Labels: new model

#8056 2022-04-20-roberta_token_classifier_bne_capitel_ner_pipeline_es_3_0
  docs/_posts/murat-gunay/2022-04-20-roberta_token_classifier_bne_capitel_ner_pipeline_es_3_0.md
Labels: new model

#8057 2022-04-20-roberta_token_classifier_icelandic_ner_pipeline_is_3_0
  docs/_posts/murat-gunay/2022-04-20-roberta_token_classifier_icelandic_ner_pipeline_is_3_0.md
Labels: new model

#8058 2022-04-20-longformer_base_token_classifier_conll03_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-20-longformer_base_token_classifier_conll03_pipeline_en_3_0.md
Labels: new model

#8059 2022-04-20-longformer_large_token_classifier_conll03_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-20-longformer_large_token_classifier_conll03_pipeline_en_3_0.md
Labels: new model

#8062 2022-04-21-xlm_roberta_base_token_classifier_ontonotes_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-21-xlm_roberta_base_token_classifier_ontonotes_pipeline_en_3_0.md
Labels: new model

#8063 2022-04-21-xlm_roberta_base_token_classifier_conll03_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-21-xlm_roberta_base_token_classifier_conll03_pipeline_en_3_0.md
Labels: new model

#8064 2022-04-21-xlnet_large_token_classifier_conll03_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-21-xlnet_large_token_classifier_conll03_pipeline_en_3_0.md
Labels: new model

#8070 2022-04-22-albert_base_token_classifier_conll03_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-22-albert_base_token_classifier_conll03_pipeline_en_3_0.md
Labels: new model

#8078 2022-04-23-sbiobertresolve_rxnorm_action_treatment_en_2_4
  docs/_posts/galiph/2022-04-23-sbiobertresolve_rxnorm_action_treatment_en_2_4.md
Labels: new model

#7881 Tokenizer: Optimized tokenization with exceptions
  src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: enhancement, DON'T MERGE

#7930 Update XlmRoBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassification.scala
Labels: enhancement, DON'T MERGE

#8028 Support more PySpark in Colab and Kaggle scripts
  docs/en/ocr.md
  docs/en/ocr_install.md
  docs/en/ocr_object_detection.md
  docs/en/ocr_pipeline_components.md
  docs/en/ocr_release_notes.md
  docs/en/ocr_structures.md
  docs/en/ocr_table_recognition.md
  docs/en/ocr_visual_document_understanding.md
  scripts/colab_setup.sh
  scripts/kaggle_setup.sh
  scripts/sagemaker_setup.sh
Labels: enhancement, DON'T MERGE

#8041 Feature/upgrade dependencies
  .github/workflows/build_and_test.yml
  build.sbt
  project/Dependencies.scala
  project/build.properties
Labels: enhancement, DON'T MERGE

#8086 2022-04-25-bert_sequence_classifier_binary_rct_biobert_en_3_0
  docs/_posts/gadde5300/2022-04-25-bert_sequence_classifier_binary_rct_biobert_en_3_0.md
Labels: new model

#8085 2022-04-25-rct_binary_classifier_biobert_en_3_0
  docs/_posts/gadde5300/2022-04-25-rct_binary_classifier_biobert_en_3_0.md
Labels: new model

#8084 2022-04-24-rct_binary_classifier_use_en_3_0
  docs/_posts/gadde5300/2022-04-24-rct_binary_classifier_use_en_3_0.md
Labels: new model

#8073 2022-04-23-albert_large_token_classifier_conll03_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-23-albert_large_token_classifier_conll03_pipeline_en_3_0.md
Labels: new model

#8074 2022-04-23-albert_xlarge_token_classifier_conll03_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-23-albert_xlarge_token_classifier_conll03_pipeline_en_3_0.md
Labels: new model

#8076 2022-04-23-roberta_base_token_classifier_ontonotes_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-23-roberta_base_token_classifier_ontonotes_pipeline_en_3_0.md
Labels: new model

#8077 2022-04-23-roberta_large_token_classifier_conll03_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-04-23-roberta_large_token_classifier_conll03_pipeline_en_3_0.md
Labels: new model

#8089 2022-04-25-rct_binary_classifier_biobert_pipeline_en_3_0
  docs/_posts/gadde5300/2022-04-25-rct_binary_classifier_biobert_pipeline_en_3_0.md
Labels: new model

#8088 2022-04-25-rct_binary_classifier_use_pipeline_en_3_0
  docs/_posts/gadde5300/2022-04-25-rct_binary_classifier_use_pipeline_en_3_0.md
Labels: new model

#8087 2022-04-25-bert_sequence_classifier_binary_rct_biobert_pipeline_en_3_0
  docs/_posts/gadde5300/2022-04-25-bert_sequence_classifier_binary_rct_biobert_pipeline_en_3_0.md
Labels: new model

#8082 Introducing DeBertaForTokenClassification annotator
  python/run-tests.py
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForTokenClassificationTestSpec.scala
Labels: new-feature, DON'T MERGE

#8093 2022-04-25-sbiobertresolve_rxnorm_action_treatment_en_2_4
  docs/_posts/Cabir40/2022-04-25-sbiobertresolve_rxnorm_action_treatment_en_2_4.md
Labels: new model
