Repository JohnSnowLabs/spark-nlp, pull requests merged in 2022-02, with the labels that each got.

#6838 2022-02-01-ner_supplement_clinical_en
  docs/_posts/HashamUlHaq/2022-02-01-ner_supplement_clinical_en.md
Labels: new model

#6839 2022-02-01-sbiobertresolve_clinical_abbreviation_acronym_en
  docs/_posts/HashamUlHaq/2022-02-01-sbiobertresolve_clinical_abbreviation_acronym_en.md
Labels: new model

#6822 Feature/init spark32 realtime output
  .lift/ignoreFiles
  python/sparknlp/__init__.py
Labels: enhancement

#6841 Adding sentence match parameter to EntityRuler
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerModel.scala
  src/main/scala/com/johnsnowlabs/util/spark/SparkUtil.scala
  src/test/resources/entity-ruler/patterns.csv
  src/test/resources/entity-ruler/patterns.json
  src/test/resources/entity-ruler/patterns.jsonl
  src/test/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerTest.scala
  src/test/scala/com/johnsnowlabs/util/JsonParserTest.scala
  src/test/scala/com/johnsnowlabs/util/ResourceHelperTestSpec.scala
Labels: new-feature

#6843 2022-02-01-word2vec_wac_200_fr
  docs/_posts/luca-martial/2022-02-01-word2vec_wac_200_fr.md
Labels: new model

#6825 2022-01-26-word2vec_wiki_1000_fr
  docs/_posts/luca-martial/2022-01-26-word2vec_wiki_1000_fr.md
Labels: new model

#6845 Fix GraphExtraction crashing when fullAnnotate and document are used at the same time
  src/main/scala/com/johnsnowlabs/nlp/annotators/GraphExtraction.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionTest.scala
Labels: bug-fix

#6848 2022-02-03-w2v_cc_300d_fr
  docs/_posts/luca-martial/2022-02-03-w2v_cc_300d_fr.md
Labels: new model

#6849 Fix Word2VecModel being cast to Doc2VecModel by mistake
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
Labels: bug-fix

#6826 2022-01-26-albert_indic_xx
  docs/_posts/DevinTDHa/2022-01-26-albert_indic_xx.md
Labels: new model

#6867 Fix broken BertEmbeddings wrong sentence indexing
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala
Labels: bug-fix

#6868 Fix broken setExceptionsPath in Tokenizer in Python
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/test/resources/token_exception_list.txt
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: bug-fix

#6874 2022-02-07-bert_sequence_classifier_pico_biobert_en
  docs/_posts/luca-martial/2022-02-07-bert_sequence_classifier_pico_biobert_en.md
Labels: new model

#6875 2022-02-08-clinical_longformer_en
  docs/_posts/murat-gunay/2022-02-08-clinical_longformer_en.md
Labels: new model

#6876 2022-02-08-bert_sequence_classifier_gender_biobert_en
  docs/_posts/luca-martial/2022-02-08-bert_sequence_classifier_gender_biobert_en.md
Labels: new model

#6879 2022-02-08-bert_sequence_classifier_ade_en
  docs/_posts/luca-martial/2022-02-08-bert_sequence_classifier_ade_en.md
Labels: new model

#6883 2022-02-08-distilbert_sequence_classifier_ade_en
  docs/_posts/luca-martial/2022-02-08-distilbert_sequence_classifier_ade_en.md
Labels: new model

#6885 2022-02-09-bert_token_classifier_ner_supplement_en
  docs/_posts/gadde5300/2022-02-09-bert_token_classifier_ner_supplement_en.md
Labels: new model

#6884 2022-02-08-ner_nature_nero_clinical_en
  docs/_posts/HashamUlHaq/2022-02-08-ner_nature_nero_clinical_en.md
Labels: new model

#6888 2022-02-09-classifierdl_bert_news_pipeline_ur
  docs/_posts/murat-gunay/2022-02-09-classifierdl_bert_news_pipeline_ur.md
Labels: new model

#6890 2022-02-09-classifierdl_distilbert_sentiment_vi
  docs/_posts/murat-gunay/2022-02-09-classifierdl_distilbert_sentiment_vi.md
Labels: new model

#6889 2022-02-09-sbiobertresolve_rxnorm_augmented_re_en
  docs/_posts/galiph/2022-02-09-sbiobertresolve_rxnorm_augmented_re_en.md
Labels: new model

#6901 2022-02-10-xlm_roberta_large_token_classifier_masakhaner_pipeline_xx
  docs/_posts/murat-gunay/2022-02-10-xlm_roberta_large_token_classifier_masakhaner_pipeline_xx.md
Labels: new model

#6905 2022-02-11-clinical_deidentification_es
  docs/_posts/josejuanmartinez/2022-02-11-clinical_deidentification_es.md
Labels: new model

#6907 2022-02-11-ner_deid_generic_fr
  docs/_posts/luca-martial/2022-02-11-ner_deid_generic_fr.md
Labels: new model

#6909 2022-02-11-ner_deid_generic_fr
  docs/_posts/luca-martial/2022-02-11-ner_deid_generic_fr.md
Labels: new model

#6908 2022-02-11-ner_deid_subentity_fr
  docs/_posts/luca-martial/2022-02-11-ner_deid_subentity_fr.md
Labels: new model

#6915 2022-02-12-distilbert_base_sequence_classifier_qqp_en
  docs/_posts/murat-gunay/2022-02-12-distilbert_base_sequence_classifier_qqp_en.md
Labels: new model

#6919 2022-02-14-clinical_deidentification_es
  docs/_posts/josejuanmartinez/2022-02-14-clinical_deidentification_es.md
Labels: new model

#6921 2022-02-14-ner_deid_subentity_fr
  docs/_posts/luca-martial/2022-02-14-ner_deid_subentity_fr.md
Labels: new model

#6923 2022-02-14-distilbert_base_sequence_classifier_food_en
  docs/_posts/murat-gunay/2022-02-14-distilbert_base_sequence_classifier_food_en.md
Labels: new model

#6926 2022-02-15-ner_deid_generic_augmented_es
  docs/_posts/josejuanmartinez/2022-02-15-ner_deid_generic_augmented_es.md
Labels: new model

#6925 2022-02-15-clinical_deidentification_augmented_es
  docs/_posts/josejuanmartinez/2022-02-15-clinical_deidentification_augmented_es.md
Labels: new model

#6928 2022-02-15-ner_deid_subentity_augmented_es
  docs/_posts/josejuanmartinez/2022-02-15-ner_deid_subentity_augmented_es.md
Labels: new model

#6930 2022-02-15-ner_deid_subentity_roberta_augmented_es
  docs/_posts/josejuanmartinez/2022-02-15-ner_deid_subentity_roberta_augmented_es.md
Labels: new model

#6933 2022-02-15-bert_token_classifier_scandi_ner_pipeline_xx
  docs/_posts/murat-gunay/2022-02-15-bert_token_classifier_scandi_ner_pipeline_xx.md
Labels: new model

#6939 2022-02-16-ocr_small_printed_en
  docs/_posts/kolia1985/2022-02-16-ocr_small_printed_en.md
Labels: new model

#6940 2022-02-16-ocr_base_handwritten_en
  docs/_posts/kolia1985/2022-02-16-ocr_base_handwritten_en.md
Labels: new model

#6942 2022-02-17-ocr_small_handwritten_en
  docs/_posts/kolia1985/2022-02-17-ocr_small_handwritten_en.md
Labels: new model

#6938 2022-02-16-ner_deid_subentity_roberta_augmented_es
  docs/_posts/josejuanmartinez/2022-02-16-ner_deid_subentity_roberta_augmented_es.md
Labels: new model

#6937 2022-02-16-ner_deid_subentity_augmented_es
  docs/_posts/josejuanmartinez/2022-02-16-ner_deid_subentity_augmented_es.md
Labels: new model

#6936 2022-02-16-ner_deid_generic_roberta_augmented_es
  docs/_posts/josejuanmartinez/2022-02-16-ner_deid_generic_roberta_augmented_es.md
Labels: new model

#6935 2022-02-16-ner_deid_generic_augmented_es
  docs/_posts/josejuanmartinez/2022-02-16-ner_deid_generic_augmented_es.md
Labels: new model

#6934 2022-02-16-clinical_deidentification_augmented_es
  docs/_posts/josejuanmartinez/2022-02-16-clinical_deidentification_augmented_es.md
Labels: new model

#6945 2022-02-16-distilbert_base_sequence_classifier_toxicity_de
  docs/_posts/murat-gunay/2022-02-16-distilbert_base_sequence_classifier_toxicity_de.md
Labels: new model

#6948 2022-02-17-clinical_deidentification_es
  docs/_posts/josejuanmartinez/2022-02-17-clinical_deidentification_es.md
Labels: new model

#6878 2022-02-08-Ner_conll2003_100d_en
  docs/_posts/gokhanturer/2022-02-08-Ner_conll2003_100d_en.md
Labels: new model

#6954 2022-02-20-Ner_glove_100d_en
  docs/_posts/gokhanturer/2022-02-20-Ner_glove_100d_en.md
Labels: new model

#6950 2022-02-18-distilbert_base_sequence_classifier_airlines_en
  docs/_posts/murat-gunay/2022-02-18-distilbert_base_sequence_classifier_airlines_en.md
Labels: new model

#6955 2022-02-21-bert_biomed_pubmed_uncased_en
  docs/_posts/murat-gunay/2022-02-21-bert_biomed_pubmed_uncased_en.md
Labels: new model

#6958 2022-02-22-bert_sequence_classifier_hatexplain_pipeline_en
  docs/_posts/murat-gunay/2022-02-22-bert_sequence_classifier_hatexplain_pipeline_en.md
Labels: new model

#6957 2022-02-22-bert_sequence_classifier_antisemitism_pipeline_en
  docs/_posts/murat-gunay/2022-02-22-bert_sequence_classifier_antisemitism_pipeline_en.md
Labels: new model

#6960 2022-02-23-bert_sequence_classifier_trec_coarse_pipeline_en
  docs/_posts/murat-gunay/2022-02-23-bert_sequence_classifier_trec_coarse_pipeline_en.md
Labels: new model

#6961 2022-02-23-bert_sequence_classifier_age_news_pipeline_en
  docs/_posts/murat-gunay/2022-02-23-bert_sequence_classifier_age_news_pipeline_en.md
Labels: new model

#6963 2022-02-23-clinical_deidentification_fr
  docs/_posts/luca-martial/2022-02-23-clinical_deidentification_fr.md
Labels: new model

#6975 2022-02-26-sbiobertresolve_snomed_findings_aux_concepts_en_3_0
  docs/_posts/Ahmetemintek/2022-02-26-sbiobertresolve_snomed_findings_aux_concepts_en_3_0.md
Labels: new model

#6984 2022-02-28-clinical_deidentification_fr_2_4
  docs/_posts/luca-martial/2022-02-28-clinical_deidentification_fr_2_4.md
Labels: new model

#6983 2022-02-28-sbiobertresolve_hcpcs_en_2_4
  docs/_posts/egenc/2022-02-28-sbiobertresolve_hcpcs_en_2_4.md
Labels: new model

#6982 2022-02-28-sbiobertresolve_hcpcs_en_3_0
  docs/_posts/egenc/2022-02-28-sbiobertresolve_hcpcs_en_3_0.md
Labels: new model
