Repository JohnSnowLabs/spark-nlp, pull requests merged in 2022-03, with the labels that each got.

#6991 2022-03-01-bert_sequence_classifier_rct_biobert_en_3_0
  docs/_posts/gadde5300/2022-03-01-bert_sequence_classifier_rct_biobert_en_3_0.md
Labels: new model

#6992 2022-03-01-bert_sequence_classifier_rct_biobert_en_2_4
  docs/_posts/gadde5300/2022-03-01-bert_sequence_classifier_rct_biobert_en_2_4.md
Labels: new model

#6990 2022-03-01-sbiobertresolve_atc_en_2_4
  docs/_posts/Cabir40/2022-03-01-sbiobertresolve_atc_en_2_4.md
Labels: new model

#6978 Make sure bestModelMetric is being used
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
Labels: bug-fix, DON'T MERGE

#6988 Introducing enableCaching param in Doc2Vec and Word2Vec trainable annotators
  python/sparknlp/annotator.py
  python/sparknlp/common.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/HasEnableCachingProperties.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/Word2VecApproach.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/Word2VecTestSpec.scala
Labels: new-feature

#7034 2022-03-03-clinical_deidentification_en_3_0
  docs/_posts/Cabir40/2022-03-03-clinical_deidentification_en_3_0.md
Labels: new model

#7035 2022-03-03-clinical_deidentification_en_2_4
  docs/_posts/Cabir40/2022-03-03-clinical_deidentification_en_2_4.md
Labels: new model

#7033 2022-03-03-german_deid_pipeline_spark24_de_2_4
  docs/_posts/galiph/2022-03-03-german_deid_pipeline_spark24_de_2_4.md
Labels: new model

#7032 2022-03-03-clinical_deidentification_augmented_es_2_4
  docs/_posts/josejuanmartinez/2022-03-03-clinical_deidentification_augmented_es_2_4.md
Labels: new model

#7031 2022-03-03-clinical_deidentification_de_3_0
  docs/_posts/galiph/2022-03-03-clinical_deidentification_de_3_0.md
Labels: new model

#7010 2022-03-03-lemma_spacylookup_sr_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_sr_3_0.md
Labels: new model

#7011 2022-03-03-lemma_spacylookup_da_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_da_3_0.md
Labels: new model

#7012 2022-03-03-lemma_spacylookup_hu_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_hu_3_0.md
Labels: new model

#7013 2022-03-03-lemma_spacylookup_id_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_id_3_0.md
Labels: new model

#7014 2022-03-03-lemma_spacylookup_it_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_it_3_0.md
Labels: new model

#7015 2022-03-03-lemma_spacylookup_sv_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_sv_3_0.md
Labels: new model

#7016 2022-03-03-lemma_spacylookup_de_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_de_3_0.md
Labels: new model

#7017 2022-03-03-lemma_spacylookup_ro_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_ro_3_0.md
Labels: new model

#7018 2022-03-03-lemma_spacylookup_ur_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_ur_3_0.md
Labels: new model

#7019 2022-03-03-lemma_spacylookup_ru_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_ru_3_0.md
Labels: new model

#7020 2022-03-03-lemma_spacylookup_tr_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_tr_3_0.md
Labels: new model

#7021 2022-03-03-lemma_spacylookup_cs_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_cs_3_0.md
Labels: new model

#7022 2022-03-03-lemma_spacylookup_lb_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_lb_3_0.md
Labels: new model

#7023 2022-03-03-lemma_spacylookup_hr_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_hr_3_0.md
Labels: new model

#7024 2022-03-03-lemma_spacylookup_nl_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_nl_3_0.md
Labels: new model

#7025 2022-03-03-lemma_spacylookup_fr_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_fr_3_0.md
Labels: new model

#7026 2022-03-03-lemma_spacylookup_es_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_es_3_0.md
Labels: new model

#7027 2022-03-03-lemma_spacylookup_mk_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_mk_3_0.md
Labels: new model

#7028 2022-03-03-lemma_spacylookup_tl_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_tl_3_0.md
Labels: new model

#7029 2022-03-03-lemma_spacylookup_lt_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_lt_3_0.md
Labels: new model

#7030 2022-03-03-lemma_spacylookup_ca_3_0
  docs/_posts/gadde5300/2022-03-03-lemma_spacylookup_ca_3_0.md
Labels: new model

#7042 Introducing DeBERTa annotator
  python/sparknlp/annotator.py
  python/sparknlp/internal.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDeBerta.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DeBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/DeBertaEmbeddingsTestSpec.scala
Labels: new-feature

#7046 2022-03-07-stopwords_iso_lij_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_lij_3_0.md
Labels: new model

#7047 2022-03-07-w2v_cc_300d_it_3_0
  docs/_posts/luca-martial/2022-03-07-w2v_cc_300d_it_3_0.md
Labels: new model

#7133 2022-03-07-stopwords_iso_am_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_am_3_0.md
Labels: new model

#7132 2022-03-07-stopwords_iso_lb_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_lb_3_0.md
Labels: new model

#7131 2022-03-07-stopwords_iso_sk_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_sk_3_0.md
Labels: new model

#7130 2022-03-07-stopwords_iso_cs_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_cs_3_0.md
Labels: new model

#7129 2022-03-07-stopwords_iso_tr_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_tr_3_0.md
Labels: new model

#7128 2022-03-07-stopwords_iso_hr_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_hr_3_0.md
Labels: new model

#7127 2022-03-07-stopwords_iso_nl_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_nl_3_0.md
Labels: new model

#7126 2022-03-07-stopwords_iso_ko_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ko_3_0.md
Labels: new model

#7124 2022-03-07-stopwords_iso_zh_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_zh_3_0.md
Labels: new model

#7123 2022-03-07-stopwords_iso_lv_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_lv_3_0.md
Labels: new model

#7122 2022-03-07-stopwords_iso_tn_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_tn_3_0.md
Labels: new model

#7121 2022-03-07-stopwords_iso_pl_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_pl_3_0.md
Labels: new model

#7120 2022-03-07-stopwords_iso_th_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_th_3_0.md
Labels: new model

#7119 2022-03-07-stopwords_iso_gu_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_gu_3_0.md
Labels: new model

#7118 2022-03-07-stopwords_iso_grc_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_grc_3_0.md
Labels: new model

#7117 2022-03-07-stopwords_iso_si_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_si_3_0.md
Labels: new model

#7116 2022-03-07-stopwords_iso_is_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_is_3_0.md
Labels: new model

#7115 2022-03-07-stopwords_iso_ky_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ky_3_0.md
Labels: new model

#7114 2022-03-07-stopwords_iso_sq_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_sq_3_0.md
Labels: new model

#7113 2022-03-07-stopwords_iso_ca_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ca_3_0.md
Labels: new model

#7112 2022-03-07-stopwords_iso_sa_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_sa_3_0.md
Labels: new model

#7111 2022-03-07-stopwords_iso_pt_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_pt_3_0.md
Labels: new model

#7110 2022-03-07-stopwords_iso_ga_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ga_3_0.md
Labels: new model

#7109 2022-03-07-stopwords_iso_fr_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_fr_3_0.md
Labels: new model

#7108 2022-03-07-stopwords_iso_mk_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_mk_3_0.md
Labels: new model

#7107 2022-03-07-stopwords_iso_es_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_es_3_0.md
Labels: new model

#7106 2022-03-07-stopwords_iso_tt_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_tt_3_0.md
Labels: new model

#7105 2022-03-07-stopwords_iso_nb_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_nb_3_0.md
Labels: new model

#7104 2022-03-07-stopwords_iso_uk_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_uk_3_0.md
Labels: new model

#7103 2022-03-07-stopwords_iso_bn_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_bn_3_0.md
Labels: new model

#7101 2022-03-07-stopwords_iso_tl_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_tl_3_0.md
Labels: new model

#7100 2022-03-07-stopwords_iso_id_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_id_3_0.md
Labels: new model

#7099 2022-03-07-stopwords_iso_hu_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_hu_3_0.md
Labels: new model

#7098 2022-03-07-stopwords_iso_ti_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ti_3_0.md
Labels: new model

#7097 2022-03-07-stopwords_iso_he_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_he_3_0.md
Labels: new model

#7095 2022-03-07-stopwords_iso_ta_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ta_3_0.md
Labels: new model

#7094 2022-03-07-stopwords_iso_sr_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_sr_3_0.md
Labels: new model

#7093 2022-03-07-stopwords_iso_da_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_da_3_0.md
Labels: new model

#7092 2022-03-07-stopwords_iso_te_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_te_3_0.md
Labels: new model

#7091 2022-03-07-stopwords_iso_sv_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_sv_3_0.md
Labels: new model

#7090 2022-03-07-stopwords_iso_kn_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_kn_3_0.md
Labels: new model

#7089 2022-03-07-stopwords_iso_de_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_de_3_0.md
Labels: new model

#7088 2022-03-07-stopwords_iso_ml_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ml_3_0.md
Labels: new model

#7087 2022-03-07-stopwords_iso_et_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_et_3_0.md
Labels: new model

#7086 2022-03-07-stopwords_iso_bg_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_bg_3_0.md
Labels: new model

#7085 2022-03-07-stopwords_iso_hi_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_hi_3_0.md
Labels: new model

#7084 2022-03-07-stopwords_iso_ro_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ro_3_0.md
Labels: new model

#7083 2022-03-07-stopwords_iso_el_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_el_3_0.md
Labels: new model

#7082 2022-03-07-stopwords_iso_hy_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_hy_3_0.md
Labels: new model

#7081 2022-03-07-stopwords_iso_ja_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ja_3_0.md
Labels: new model

#7080 2022-03-07-stopwords_iso_az_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_az_3_0.md
Labels: new model

#7079 2022-03-07-stopwords_iso_ne_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ne_3_0.md
Labels: new model

#7077 2022-03-07-stopwords_iso_ar_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ar_3_0.md
Labels: new model

#7078 2022-03-07-stopwords_iso_en_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_en_3_0.md
Labels: new model

#7076 2022-03-07-stopwords_iso_af_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_af_3_0.md
Labels: new model

#7075 2022-03-07-stopwords_iso_ur_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_ur_3_0.md
Labels: new model

#7073 2022-03-07-stopwords_iso_fa_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_fa_3_0.md
Labels: new model

#7071 2022-03-07-stopwords_iso_mr_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_mr_3_0.md
Labels: new model

#7069 2022-03-07-stopwords_iso_vi_3_0
  docs/_posts/gadde5300/2022-03-07-stopwords_iso_vi_3_0.md
Labels: new model

#7134 2022-03-08-distilbert_token_classifier_typo_detector_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-08-distilbert_token_classifier_typo_detector_pipeline_en_3_0.md
Labels: new model

#7136 2022-03-08-distilbert_token_classifier_typo_detector_pipeline_is_3_0
  docs/_posts/murat-gunay/2022-03-08-distilbert_token_classifier_typo_detector_pipeline_is_3_0.md
Labels: new model

#7043 Fix path to S3 for some models which were renamed
  docs/_posts/HashamUlHaq/2021-03-31-ner_posology_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_medium_umls_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_medium_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_mini_umls_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_mini_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_tiny_umls_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbert_jsl_tiny_uncased_en.md
  docs/_posts/HashamUlHaq/2021-05-14-sbiobert_jsl_cased_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md
  docs/_posts/HashamUlHaq/2021-05-16-sbiobertresolve_rxnorm_en.md
  docs/_posts/HashamUlHaq/2021-05-21-sbiobertresolve_icd10cm_slim_billable_hcc_en.md
  docs/_posts/HashamUlHaq/2021-06-30-ner_deid_subentity_augmented_en.md
  docs/_posts/muhammetsnts/2021-05-04-rxnorm_mesh_mapping_en.md
  docs/_posts/muhammetsnts/2021-05-04-rxnorm_umls_mapping_en.md
  docs/_posts/muhammetsnts/2021-05-04-snomed_umls_mapping_en.md
  docs/_posts/muhammetsnts/2021-05-25-sbertresolve_icd10cm_slim_billable_hcc_med_en.md
  docs/_posts/muhammetsnts/2021-05-25-sbiobertresolve_icd10cm_slim_billable_hcc_en.md
  docs/_posts/murat-gunay/2021-06-01-ner_deid_generic_augmented_en.md
  docs/_posts/murat-gunay/2021-09-03-ner_deid_subentity_augmented_en.md
Labels: documentation

#7139 2022-03-08-lemma_spacylookup_nb_3_0
  docs/_posts/gadde5300/2022-03-08-lemma_spacylookup_nb_3_0.md
Labels: new model

#7140 2022-03-08-lemma_spacylookup_grc_3_0
  docs/_posts/gadde5300/2022-03-08-lemma_spacylookup_grc_3_0.md
Labels: new model

#7141 2022-03-08-lemma_spacylookup_en_3_0
  docs/_posts/gadde5300/2022-03-08-lemma_spacylookup_en_3_0.md
Labels: new model

#7142 2022-03-08-lemma_spacylookup_pt_3_0
  docs/_posts/gadde5300/2022-03-08-lemma_spacylookup_pt_3_0.md
Labels: new model

#7039 2022-03-04-clinical_deidentification_glove_en_3_0
  docs/_posts/Meryem1425/2022-03-04-clinical_deidentification_glove_en_3_0.md
Labels: new model

#7038 2022-03-04-clinical_deidentification_fr_2_4
  docs/_posts/luca-martial/2022-03-04-clinical_deidentification_fr_2_4.md
Labels: new model

#7001 2022-03-02-clinical_deidentification_es_2_4
  docs/_posts/josejuanmartinez/2022-03-02-clinical_deidentification_es_2_4.md
Labels: new model

#7146 2022-03-09-bert_token_classifier_ner_cellular_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-09-bert_token_classifier_ner_cellular_pipeline_en_3_0.md
Labels: new model

#7150 2022-03-10-deberta_v3_base_en_3_0
  docs/_posts/maziyarpanahi/2022-03-10-deberta_v3_base_en_3_0.md
Labels: new model

#7152 2022-03-10-deberta_v3_large_en_3_0
  docs/_posts/maziyarpanahi/2022-03-10-deberta_v3_large_en_3_0.md
Labels: new model

#7153 2022-03-10-deberta_v3_small_en_3_0
  docs/_posts/maziyarpanahi/2022-03-10-deberta_v3_small_en_3_0.md
Labels: new model

#7154 2022-03-10-deberta_v3_xsmall_en_3_0
  docs/_posts/maziyarpanahi/2022-03-10-deberta_v3_xsmall_en_3_0.md
Labels: new model

#7155 2022-03-10-mdeberta_v3_base_xx_3_0
  docs/_posts/maziyarpanahi/2022-03-10-mdeberta_v3_base_xx_3_0.md
Labels: new model

#7160 Docs/nlp server
  docs/assets/images/nlp_server/license/authorize.png
  docs/assets/images/nlp_server/license/choose_license.png
  docs/assets/images/nlp_server/license/login.png
  docs/assets/images/nlp_server/license/select.png
  docs/assets/images/nlp_server/license/success.png
  docs/en/alab/quickstart.md
  docs/en/nlp_server/nlp_server.md
  docs/en/nlp_server/release_notes.md
Labels: documentation

#7161 DebertaEmbedding documentation update
  docs/en/annotators.md
  docs/en/transformer_entries/DeBertaEmbeddings.md
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DeBertaEmbeddings.scala
Labels: enhancement, documentation

#7157 2022-03-10-bert_token_classifier_ner_cellular_pipeline_en_2_4
  docs/_posts/murat-gunay/2022-03-10-bert_token_classifier_ner_cellular_pipeline_en_2_4.md
Labels: new model

#7158 2022-03-10-w2v_cc_300d_th_3_0
  docs/_posts/luca-martial/2022-03-10-w2v_cc_300d_th_3_0.md
Labels: new model

#7211 2022-03-15-bert_token_classifier_ner_chemprot_pipeline_en_2_4
  docs/_posts/murat-gunay/2022-03-15-bert_token_classifier_ner_chemprot_pipeline_en_2_4.md
Labels: new model

#7214 Added some of parameters of SentenceDetector to SentenceDetectorDL
  python/run-tests.py
  python/sparknlp/annotator.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLSpec.scala
Labels: new-feature, DON'T MERGE

#7217 2022-03-15-w2v_cc_300d_myv_3_0
  docs/_posts/luca-martial/2022-03-15-w2v_cc_300d_myv_3_0.md
Labels: new model

#7218 2022-03-15-w2v_cc_300d_eo_3_0
  docs/_posts/luca-martial/2022-03-15-w2v_cc_300d_eo_3_0.md
Labels: new model

#7219 2022-03-15-w2v_cc_300d_et_3_0
  docs/_posts/luca-martial/2022-03-15-w2v_cc_300d_et_3_0.md
Labels: new model

#7220 2022-03-15-w2v_cc_300d_hif_3_0
  docs/_posts/luca-martial/2022-03-15-w2v_cc_300d_hif_3_0.md
Labels: new model

#7223 2022-03-15-w2v_cc_300d_gl_3_0
  docs/_posts/luca-martial/2022-03-15-w2v_cc_300d_gl_3_0.md
Labels: new model

#7224 2022-03-15-w2v_cc_300d_ka_3_0
  docs/_posts/luca-martial/2022-03-15-w2v_cc_300d_ka_3_0.md
Labels: new model

#7225 2022-03-15-w2v_cc_300d_gom_3_0
  docs/_posts/luca-martial/2022-03-15-w2v_cc_300d_gom_3_0.md
Labels: new model

#7222 2022-03-15-w2v_cc_300d_fi_3_0
  docs/_posts/luca-martial/2022-03-15-w2v_cc_300d_fi_3_0.md
Labels: new model

#7339 2022-03-17-assertion_dl_scope_L10R10_en_3_0
  docs/_posts/gadde5300/2022-03-17-assertion_dl_scope_L10R10_en_3_0.md
Labels: new model

#7209 2022-03-15-bert_token_classifier_ner_chemprot_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-15-bert_token_classifier_ner_chemprot_pipeline_en_3_0.md
Labels: new model

#7212 2022-03-15-bert_token_classifier_ner_clinical_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-15-bert_token_classifier_ner_clinical_pipeline_en_3_0.md
Labels: new model

#7345 2022-03-17-assertion_dl_scope_L10R10_en_2_4
  docs/_posts/gadde5300/2022-03-17-assertion_dl_scope_L10R10_en_2_4.md
Labels: new model

#7244 2022-03-15-bert_token_classifier_ner_clinical_pipeline_en_2_4
  docs/_posts/murat-gunay/2022-03-15-bert_token_classifier_ner_clinical_pipeline_en_2_4.md
Labels: new model

#7169 2022-03-14-bert_token_classifier_ner_chemicals_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-14-bert_token_classifier_ner_chemicals_pipeline_en_3_0.md
Labels: new model

#7170 2022-03-14-bert_token_classifier_ner_chemicals_pipeline_en_2_4
  docs/_posts/murat-gunay/2022-03-14-bert_token_classifier_ner_chemicals_pipeline_en_2_4.md
Labels: new model

#7348 2022-03-18-distilbert_base_token_classifier_masakhaner_pipeline_xx_3_0
  docs/_posts/murat-gunay/2022-03-18-distilbert_base_token_classifier_masakhaner_pipeline_xx_3_0.md
Labels: new model

#7351 2022-03-18-nerdl_restaurant_100d_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-18-nerdl_restaurant_100d_pipeline_en_3_0.md
Labels: new model

#7352 2022-03-19-roberta_token_classifier_timex_semeval_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-19-roberta_token_classifier_timex_semeval_pipeline_en_3_0.md
Labels: new model

#7358 2022-03-21-bert_token_classifier_ner_anatomy_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-21-bert_token_classifier_ner_anatomy_pipeline_en_3_0.md
Labels: new model

#7359 2022-03-21-bert_token_classifier_ner_ade_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-21-bert_token_classifier_ner_ade_pipeline_en_3_0.md
Labels: new model

#7344 Enabling CoNLLU() and Lemmatizer to set names for columns
  python/sparknlp/annotator.py
  python/sparknlp/training.py
  python/test/annotators.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/Lemmatizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticSymbols.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/RuleSymbols.scala
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLLU.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/LemmatizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/training/CoNLLUTestSpec.scala
Labels: new-feature, DON'T MERGE

#7454 2022-03-21-w2v_cc_300d_de_2_4
  docs/_posts/Ahmetemintek/2022-03-21-w2v_cc_300d_de_2_4.md
Labels: new model

#7455 2022-03-21-bert_token_classifier_ner_jsl_en_2_4
  docs/_posts/Meryem1425/2022-03-21-bert_token_classifier_ner_jsl_en_2_4.md
Labels: new model

#7463 2022-03-22-clinical_deidentification_glove_augmented_en_3_0
  docs/_posts/josejuanmartinez/2022-03-22-clinical_deidentification_glove_augmented_en_3_0.md
Labels: new model

#7461 2022-03-22-bert_token_classifier_drug_development_trials_en_2_4
  docs/_posts/bunyamin-polat/2022-03-22-bert_token_classifier_drug_development_trials_en_2_4.md
Labels: new model

#7460 2022-03-22-bert_token_classifier_drug_development_trials_en_3_0
  docs/_posts/Damla-Gurbaz/2022-03-22-bert_token_classifier_drug_development_trials_en_3_0.md
Labels: new model

#7465 2022-03-22-ner_deid_subentity_it_3_0
  docs/_posts/luca-martial/2022-03-22-ner_deid_subentity_it_3_0.md
Labels: new model

#7468 2022-03-23-assertion_dl_biobert_scope_L10R10_en_3_0
  docs/_posts/Cabir40/2022-03-23-assertion_dl_biobert_scope_L10R10_en_3_0.md
Labels: new model

#7473 2022-03-24-assertion_dl_biobert_scope_L10R10_en_2_4
  docs/_posts/Cabir40/2022-03-24-assertion_dl_biobert_scope_L10R10_en_2_4.md
Labels: new model

#7475 2022-03-25-ner_deid_subentity_it_2_4
  docs/_posts/luca-martial/2022-03-25-ner_deid_subentity_it_2_4.md
Labels: new model

#7476 2022-03-25-ner_deid_generic_it_3_0
  docs/_posts/luca-martial/2022-03-25-ner_deid_generic_it_3_0.md
Labels: new model

#7477 2022-03-25-ner_deid_generic_it_2_4
  docs/_posts/luca-martial/2022-03-25-ner_deid_generic_it_2_4.md
Labels: new model

#7416 2022-03-21-ner_bacterial_species_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-21-ner_bacterial_species_pipeline_en_3_0.md
Labels: new model

#7397 2022-03-21-ner_measurements_clinical_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-21-ner_measurements_clinical_pipeline_en_3_0.md
Labels: new model

#7399 2022-03-21-ner_medmentions_coarse_pipeline_en_3_0
  docs/_posts/murat-gunay/2022-03-21-ner_medmentions_coarse_pipeline_en_3_0.md
Labels: new model
