Repository JohnSnowLabs/spark-nlp, pull requests merged in 2022-09, with the labels that each got.

#12666 2022-09-01-medication_resolver_pipeline_en
  docs/_posts/Damla-Gurbaz/2022-09-01-medication_resolver_pipeline_en.md
Labels: new model

#12667 2022-09-01-medication_resolver_transform_pipeline_en
  docs/_posts/Damla-Gurbaz/2022-09-01-medication_resolver_transform_pipeline_en.md
Labels: new model

#12671 2022-09-02-finner_roberta_zeroshot_en
  docs/_posts/josejuanmartinez/2022-09-02-finner_roberta_zeroshot_en.md
Labels: new model

#12672 2022-09-02-legner_roberta_zeroshot_en
  docs/_posts/josejuanmartinez/2022-09-02-legner_roberta_zeroshot_en.md
Labels: new model

#12678 2022-09-05-sbertresolve_ner_model_finder_en
  docs/_posts/muhammetsnts/2022-09-05-ner_model_finder_en.md
  docs/_posts/muhammetsnts/2022-09-05-sbertresolve_ner_model_finder_en.md
Labels: new model

#12682 2022-09-06-finner_financial_small_en
  docs/_posts/josejuanmartinez/2022-09-06-finner_financial_small_en.md
Labels: new model

#12683 2022-09-06-finclf_bert_fls_en
  docs/_posts/josejuanmartinez/2022-09-06-finclf_bert_fls_en.md
Labels: new model

#12684 2022-09-06-finclf_bert_sentiment_en
  docs/_posts/josejuanmartinez/2022-09-06-finclf_bert_sentiment_en.md
Labels: new model

#12685 2022-09-06-finclf_esg_en
  docs/_posts/josejuanmartinez/2022-09-06-finclf_esg_en.md
Labels: new model

#12686 2022-09-06-finclf_augmented_esg_en
  docs/_posts/josejuanmartinez/2022-09-06-finclf_augmented_esg_en.md
  docs/_posts/josejuanmartinez/2022-09-06-finclf_bert_sentiment_phrasebank_en.md
Labels: new model

#12693 2022-09-07-finclf_bert_sentiment_phrasebank_en
  docs/_posts/josejuanmartinez/2022-09-07-finclf_bert_sentiment_phrasebank_en.md
Labels: new model

#12694 2022-09-07-finclf_bert_banking77_en
  docs/_posts/josejuanmartinez/2022-09-07-finclf_bert_banking77_en.md
Labels: new model

#12698 2022-09-07-finvisualclf_vit_tickets_en
  docs/_posts/josejuanmartinez/2022-09-07-finvisualclf_vit_tickets_en.md
Labels: new model

#12700 2022-09-07-legclf_bert_judgements_agent_en
  docs/_posts/josejuanmartinez/2022-09-07-legclf_bert_judgements_agent_en.md
  docs/_posts/josejuanmartinez/2022-09-07-legclf_bert_judgements_argtype_en.md
Labels: new model

#12704 2022-09-08-finel_names2tickers_en
  docs/_posts/josejuanmartinez/2022-09-08-finel_names2tickers_en.md
Labels: new model

#12706 2022-09-08-finre_acquisitions_subsidiaries_en
  docs/_posts/josejuanmartinez/2022-09-08-finre_acquisitions_subsidiaries_en.md
Labels: new model

#12709 2022-09-09-finpipe_org_per_role_date_en
  docs/_posts/josejuanmartinez/2022-09-09-finpipe_org_per_role_date_en.md
Labels: new model

#12712 2022-09-09-finel_tickers2names_en
  docs/_posts/josejuanmartinez/2022-09-09-finel_tickers2names_en.md
Labels: new model

#12692 2022-09-07-bert_classifier_analytical_da
  docs/_posts/murat-gunay/2022-09-07-bert_classifier_analytical_da.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_detect_acoso_twitter_es.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_emoroberta_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_fs_distil_fine_tuned_en.md
Labels: new model

#12714 2022-09-09-roberta_classifier_policyberta_7d_en
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_bert_covid_407910467_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_cml_412010597_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_doctor_de_24595548_de.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_fa_473312409_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_formality_scoring_2_32597818_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_fred2_2682064_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_group_classification_441411446_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_imdb_demo_hf_16622775_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_imdb_reviews_sentiment_329982_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_imdb_sentiment_classification_31154_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_imdb_test_21134453_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_my_own_imdb_sentiment_analysis_2131817_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_reading_prediction_172506_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autonlp_traffic_nlp_binary_537215209_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autotrain_article_pred_1142742075_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autotrain_car_review_project_966432120_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autotrain_car_review_project_966432121_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autotrain_news_916530070_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_banking77_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_multiclass_textclassification_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_policyberta_7d_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_ruperta_base_sentiment_analysis_es.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_soongsilbert_base_beep_ko.md
Labels: new model

#12715 2022-09-09-roberta_classifier_autotrain_commonsense_1_696121179_en
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autotrain_atc2_en.md
  docs/_posts/murat-gunay/2022-09-09-roberta_classifier_autotrain_commonsense_1_696121179_en.md
Labels: new model

#12716 2022-09-09-finassertiondl_past_roles_en
  docs/_posts/josejuanmartinez/2022-09-09-finassertiondl_past_roles_en.md
Labels: new model

#12719 2022-09-10-bert_embeddings_jobbert_base_cased_en
  docs/_posts/gadde5300/2022-09-10-bert_embeddings_jobbert_base_cased_en.md
Labels: new model

#12720 2022-09-10-bert_sequence_classifier_electricidad_base_finetuned_sst2_en
  docs/_posts/gadde5300/2022-09-10-bert_sequence_classifier_electricidad_base_finetuned_sst2_en.md
Labels: new model

#12723 2022-09-12-finre_work_experience_en
  docs/_posts/josejuanmartinez/2022-09-12-finre_work_experience_en.md
Labels: new model

#12731 2022-09-13-xlmroberta_classifier_autonlp_fake_news_detection_system_29906863_hi
  docs/_posts/murat-gunay/2022-09-13-xlmroberta_classifier_autonlp_fake_news_detection_system_29906863_hi.md
  docs/_posts/murat-gunay/2022-09-13-xlmroberta_classifier_base_mrpc_en.md
  docs/_posts/murat-gunay/2022-09-13-xlmroberta_classifier_base_snli_mnli_anli_xnli_xx.md
  docs/_posts/murat-gunay/2022-09-13-xlmroberta_classifier_da_xlmr_ned_da.md
  docs/_posts/murat-gunay/2022-09-13-xlmroberta_classifier_deoffxlmr_mono_kannada_kn.md
  docs/_posts/murat-gunay/2022-09-13-xlmroberta_classifier_deoffxlmr_mono_malyalam_ml.md
  docs/_posts/murat-gunay/2022-09-13-xlmroberta_classifier_deoffxlmr_mono_tamil_ta.md
  docs/_posts/murat-gunay/2022-09-13-xlmroberta_classifier_large_en_ru_mnli_xx.md
  docs/_posts/murat-gunay/2022-09-13-xlmroberta_classifier_twitter_emotion_es.md
  docs/_posts/murat-gunay/2022-09-13-xlmroberta_classifier_verdict_xx.md
Labels: new model

#12736 2022-09-14-finassertion_time_en
  docs/_posts/josejuanmartinez/2022-09-14-finassertion_time_en.md
Labels: new model

#12737 2022-09-14-legassertion_time_en
  docs/_posts/josejuanmartinez/2022-09-14-legassertion_time_en.md
Labels: new model

#12741 2022-09-14-electra_classifier_beep_kc_base_bias_ko
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_base_discriminator_offenseval2019_downsample_en.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_beep_kc_base_bias_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_beep_kc_base_hate_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_beep_ko_base_v3_discriminator_bias_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_beep_ko_base_v3_discriminator_hate_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_bertic_tweetsentiment_xx.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_dv_small_news_classification_dv.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_electricidad_base_finetuned_go_emotions_es.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_kc_base_bad_sentence_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_base_bad_sentence_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_base_bias_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_base_finetuned_nsmc_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_base_finetuned_sentiment_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_small_finetuned_intent_cls_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_small_finetuned_nsmc_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_small_finetuned_sentiment_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_large_discriminator_nli_efl_hateval_en.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_large_discriminator_nli_efl_tweeteval_en.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_large_discriminator_snli_mnli_fever_anli_r1_r2_r3_nli_en.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_mrm8488_electricidad_small_finetuned_amazon_review_classification_es.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_small_finetuned_imdb_en.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_turkish_sentiment_analysis_tr.md
Labels: new model

#12742 2022-09-14-electra_classifier_ko_base_v3_hate_speech_ko
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_base_gender_bias_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_base_v3_bias_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_base_v3_gender_bias_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_base_v3_hate_speech_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_senti_1_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_korean_hatespeech_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_korean_hatespeech_multilabel_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_mfma_en.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_nsmc_ko_test_model_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_qd_dialog_base_turkish_tr.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_qd_quora_base_turkish_tr.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_qd_tweet_base_turkish_tr.md
Labels: new model

#12744 2022-09-14-clinical_deidentification_en
  docs/_posts/Cabir40/2022-09-14-clinical_deidentification_en.md
Labels: new model

#12743 2022-09-14-electra_classifier_kote_for_easygoing_people_ko
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_ko_base_v3_generalized_sentiment_analysis_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_kote_for_easygoing_people_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_mindlogic_ko_ai_citizen_base_ko.md
  docs/_posts/murat-gunay/2022-09-14-electra_classifier_tunib_base_bad_sentence_ko.md
Labels: new model

#12747 2022-09-15-assertion_jsl_augmented_en
  docs/_posts/Ahmetemintek/2022-09-15-assertion_jsl_augmented_en.md
Labels: new model

#12748 2022-09-15-clinical_deidentification_glove_augmented_en
  docs/_posts/Cabir40/2022-09-15-clinical_deidentification_glove_augmented_en.md
Labels: new model

#12750 2022-09-16-clinical_deidentification_glove_augmented_en
  docs/_posts/Cabir40/2022-09-16-clinical_deidentification_glove_augmented_en.md
Labels: new model

#12758 2022-09-19-legre_indemnifications_en
  docs/_posts/josejuanmartinez/2022-09-19-legner_bert_indemnifications_en.md
  docs/_posts/josejuanmartinez/2022-09-19-legre_indemnifications_en.md
Labels: new model

#12760 2022-09-19-bert_classifier_evidence_types_en
  docs/_posts/gadde5300/2022-09-19-bert_classifier_autotrain_base_tweeteval_1281248997_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_autotrain_base_tweeteval_1281248998_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_autotrain_base_tweeteval_1281248999_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_autotrain_wikipedia_sst_2_1034235509_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_base_cased_tamil_mix_sentiment_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_base_gpt2detector_topp92_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_base_uncased_english_multilable_classification_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_base_uncased_offenseval2019_unbalanced_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_base_uncased_qnli_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_base_uncased_toxicity_a_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_based_uncased_sst2_e1_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_beep_kc_base_bias_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_bio_pubmed200krct_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_bioformer_cased_v1.0_mnli_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_bioformer_cased_v1.0_qnli_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_covid_misinfo_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_dehate_mono_indonesian_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_distil_base_uncased_finetuned_emotion_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_drug_sentiment_analysis_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_emojify_mvp_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_english_tweetsentiment_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_evidence_types_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_extra_bio_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_fine_tuned_cola1_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_fine_tuned_cola2_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_hinglish_class_xx.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_italian_news_classification_headlines_xx.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_kor_3i4k_base_cased_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_krm_sa3_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_minilm_finetuned_emotion_nm_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_mnli_large_cased_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_model1_test_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_multilabel_inpatient_comments_14labels_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_nb_base_target_group_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_platzi_base_mrpc_glue_omar_espejel_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_pubmed_pubmed200krct_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_sa_sub5_ar.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_sentence_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_sentiment_tweets_tr.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_spanish_news_classification_headlines_es.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_text_cls_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_tiny_aug_sst2_distilled_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_tiny_best_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_tiny_sst2_1_mobile_2_distillation_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_tiny_sst2_1_mobile_and_multi_teacher_distillation_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_topic_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_trash_mail_cls_2022_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_turkish_product_comment_sentiment_classification_tr.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_vaccinchatsentenceclassifierdutch_frombertje2_dadialog02_nl.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_vaccinchatsentenceclassifierdutch_frombertje2_dadialogqonly_nl.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_vaccinchatsentenceclassifierdutch_frombertjedial_nl.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_vijaygoriya_test_trainer_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_wiselinjayajos_finetuned_mrpc_en.md
Labels: new model

#12762 2022-09-19-bert_classifier_joniponi_finetuned_sem_eval_english_en
  docs/_posts/gadde5300/2022-09-19-bert_classifier_amitkayal_finetuned_sem_eval_english_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_autotrain_base_tweeteval_1281248996_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_autotrain_base_tweeteval_1281249000_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_autotrain_gluefinetunedmodel_1013533786_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_base_arabic_camel_mix_poetry_finetuned_qawaf_ar.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_base_uncased_finetuned_glue_cola_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_binary_classification_arabic_ar.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_claim_hugging_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_clog_assessment_model_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_contextualized_hate_speech_es.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_dutch_news_clf_finetuned_nl.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_english_news_classification_headlines_xx.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_extreme_go_emotion_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_fine_tuned_cola_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_finetuned_semantic_chinese_zh.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_guns_relevant_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_hashtag_to_hashtag_20_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_ibrahim2030_tiny_sst2_distilled_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_ilana_tiny_sst2_distilled_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_joniponi_finetuned_sem_eval_english_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_large_cased_whole_word_masking_sst2_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_large_gpt2detector_topk40_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_manglish_offensive_language_identification_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_mini_sst2_distilled_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_minilm_finetuned_emotion_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_minilm_l12_h384_uncased_sst2_all_train_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_minlm_finetuned_emotionnew1_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_minlm_finetuned_emotionnew2_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_mnli_base_cased_3_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_non_cl_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_non_contextualized_hate_speech_es.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_obgv_gder_xx.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_pro_cell_expert_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_reddit_tc_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_rotten_tomatoes_finetuned_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_small_finetuned_glue_rte_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_sponsorblock_v2_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_taipeiqa_v1_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_test_model_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_testing3_multilavel_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_testing4_multilabel_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_tiny_russian_toxic_ru.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_tiny_sst2_1_mobile_2_3_gold_labels_distillation_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_tiny_sst2_1_mobile_2_only_distillation_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_tiny_sst2_1_mobile_only_distillation_en.md
  docs/_posts/gadde5300/2022-09-19-bert_classifier_tiny_sst2_mobile_distillation_en.md
Labels: new model

#12634 EntityRuler Latency Improvement
  python/sparknlp/annotator/er/entity_ruler.py
  python/test/annotator/er/entity_ruler_test.py
  src/main/scala/com/johnsnowlabs/nlp/HasInputAnnotationCols.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/AhoCorasickAutomaton.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityPattern.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerUtil.scala
  src/main/scala/com/johnsnowlabs/storage/Database.scala
  src/test/resources/entity-ruler/keywords_only.json
  src/test/resources/entity-ruler/keywords_regex.json
  src/test/resources/entity-ruler/keywords_regex_with_id.json
  src/test/resources/entity-ruler/keywords_regex_with_regex_field.csv
  src/test/resources/entity-ruler/keywords_regex_without_id.jsonl
  src/test/resources/entity-ruler/keywords_with_id.jsonl
  src/test/resources/entity-ruler/keywords_with_regex_field.csv
  src/test/resources/entity-ruler/keywords_without_regex_field.csv
  src/test/resources/entity-ruler/patterns.csv
  src/test/resources/entity-ruler/regex_only.json
  src/test/resources/entity-ruler/regex_patterns.csv
  src/test/resources/entity-ruler/regex_patterns.jsonl
  src/test/resources/entity-ruler/sample_japanese_alphabet.txt
  src/test/resources/entity-ruler/single_keyword.json
  src/test/scala/com/johnsnowlabs/nlp/annotators/SparkSessionTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/er/AhoCorasickAutomatonTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerFixture.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerUtilTest.scala
  src/test/scala/com/johnsnowlabs/util/JsonParserTest.scala
  src/test/scala/com/johnsnowlabs/util/ResourceHelperTestSpec.scala
Labels: enhancement, DON'T MERGE

#12636 Fix bug in generating NER TF2 graphs when sequence length is 1
  python/sparknlp/training/_tf_graph_builders/ner_dl/create_graph.py
  python/sparknlp/training/_tf_graph_builders/ner_dl/ner_model.py
Labels: enhancement, DON'T MERGE

#12641 Fix a bug introduced in 4.0.0 release between Transformer-based Word Embeddings and SentenceEmbeddings
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowAlbert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowCamemBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDeBerta.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowDistilBert.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowElmo.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowRoBerta.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlnet.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/CamemBertEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/DeBertaEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala
Labels: bug-fix, DON'T MERGE

#12653 LightPipeline support for 2 Array Targets
  python/sparknlp/annotation.py
  python/sparknlp/base/light_pipeline.py
  python/test/base/multi_document_assembler_test.py
  src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
  src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/MultiDocumentAssemblerTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/multipleannotations/MultiAnnotationsSpec.scala
Labels: new-feature, DON'T MERGE

#12661 Fix/gpt2 edge case exceptions
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowGPT2.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2TestSpec.scala
Labels: bug-fix, DON'T MERGE

#12707 Adding support for S3 in cache folder config
  src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
  src/test/scala/com/johnsnowlabs/util/ResourceHelperTestSpec.scala
Labels: new-feature, DON'T MERGE

#12725 fixed docs
  docs/_posts/dcecchini/2021-01-03-ner_msra_bert_768d_zh.md
  docs/_posts/dcecchini/2021-01-03-ner_ud_gsd_glove_840B_300d_ja.md
  docs/_posts/dcecchini/2021-01-03-ner_ud_kaist_glove_840B_300d_ko.md
  docs/_posts/dcecchini/2021-01-03-wordseg_ctb9_zh.md
  docs/_posts/dcecchini/2021-01-03-wordseg_gsd_ud_ja.md
  docs/_posts/dcecchini/2021-01-03-wordseg_kaist_ud_ko.md
  docs/_posts/dcecchini/2021-01-03-wordseg_large_zh.md
  docs/_posts/dcecchini/2021-01-03-wordseg_msra_zh.md
  docs/_posts/dcecchini/2021-01-03-wordseg_pku_zh.md
  docs/_posts/dcecchini/2021-01-03-wordseg_weibo_zh.md
  docs/_posts/dcecchini/2021-01-04-ner_weibo_bert_768d_zh.md
  docs/_posts/dcecchini/2021-01-11-ner_lst20_glove_840B_300d_th.md
  docs/_posts/dcecchini/2021-01-13-wordseg_best_th.md
  docs/_posts/dcecchini/2021-01-14-sentiment_jager_use_th.md
  docs/_posts/dcecchini/2021-01-20-pos_msri_bn.md
  docs/_posts/dcecchini/2021-01-25-wordseg_gsd_ud_trad_zh.md
  docs/_posts/dcecchini/2021-01-27-ner_jifs_glove_840B_300d_bn.md
  docs/_posts/dcecchini/2021-01-29-ner_drugs_large_en.md
  docs/_posts/dcecchini/2021-03-10-pos_mtg_te.md
  docs/_posts/dcecchini/2021-03-10-pos_ttb_ta.md
  docs/_posts/dcecchini/2021-03-10-pos_vtb_vi.md
  docs/_posts/dcecchini/2021-03-16-pos_afribooms_af.md
  docs/_posts/dcecchini/2021-03-23-pos_btb_bg.md
  docs/_posts/dcecchini/2021-03-23-pos_cac_cs.md
  docs/_posts/dcecchini/2021-03-23-pos_icepahc_is.md
  docs/_posts/dcecchini/2021-03-23-pos_lfg_pl.md
  docs/_posts/dcecchini/2021-03-23-pos_snk_sk.md
  docs/_posts/dcecchini/2021-03-23-pos_talbanken_sv.md
  docs/_posts/dcecchini/2021-04-06-pos_afribooms_af.md
  docs/_posts/dcecchini/2021-09-20-wordseg_large_zh.md
  docs/_posts/dcecchini/2021-09-22-wordseg_best_th.md
Labels: documentation

#12735 Feat lookaround in doc norm
  src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentNormalizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentNormalizerBehaviors.scala
Labels: new-feature, DON'T MERGE

#12752 Introducing CamemBERT for Token Classification
  python/sparknlp/annotator/classifier_dl/__init__.py
  python/sparknlp/annotator/classifier_dl/camembert_for_token_classification.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/classifier_dl/camembert_for_token_classification_test.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowCamemBertClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForTokenClassificationTestSpec.scala
Labels: new-feature, DON'T MERGE

#12769 2022-09-20-bert_embeddings_InCaseLawBERT_en
  docs/_posts/gadde5300/2022-09-20-bert_embeddings_InCaseLawBERT_en.md
  docs/_posts/gadde5300/2022-09-20-bert_embeddings_InLegalBERT_en.md
Labels: new model

#12770 2022-09-20-legclf_cuad_confidentiality_clause_en
  docs/_posts/josejuanmartinez/2022-09-20-legclf_cuad_confidentiality_clause_en.md
  docs/_posts/josejuanmartinez/2022-09-20-legclf_cuad_indemnifications_clause_en.md
  docs/_posts/josejuanmartinez/2022-09-20-legclf_cuad_licenses_clause_en.md
  docs/_posts/josejuanmartinez/2022-09-20-legclf_cuad_obligations_clause_en.md
  docs/_posts/josejuanmartinez/2022-09-20-legclf_cuad_whereas_clause_en.md
Labels: new model

#12773 2022-09-21-visualner_receipts_xx
  docs/_posts/josejuanmartinez/2022-09-21-visualner_receipts_xx.md
Labels: new model

#12774 2022-09-21-visualner_10kfilings_en
  docs/_posts/josejuanmartinez/2022-09-21-visualner_10kfilings_en.md
Labels: new model

#12776 2022-09-21-visualner_keyvalue_10kfilings_en
  docs/_posts/josejuanmartinez/2022-09-21-visualner_keyvalue_10kfilings_en.md
Labels: new model

#12745 Implement setReplaceEntities feature in NerOverwriter annotator
  python/sparknlp/annotator/ner/ner_overwriter.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerOverwriter.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerOverwriterTest.scala
Labels: Requires more input, Requires changes, on-hold, new-feature, DON'T MERGE

#12783 2022-09-23-table_qa_tapas_small_finetuned_sqa_en
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_base_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_small_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_small_finetuned_wikisql_supervised_en.md
Labels: new model

#12786 2022-09-23-table_qa_tapas_mini_finetuned_wtq_en
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_table_question_answering_tapas_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_base_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_base_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_base_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_large_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_large_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_large_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_medium_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_medium_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_medium_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_mini_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_mini_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_small_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_small_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_small_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_temporary_repo_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_tiny_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-23-table_qa_tapas_tiny_finetuned_wtq_en.md
Labels: new model

#12787 2022-09-23-camembert_large_token_classifier_wikiner_en
  docs/_posts/maziyarpanahi/2022-09-23-camembert_base_token_classifier_wikiner_en.md
  docs/_posts/maziyarpanahi/2022-09-23-camembert_large_token_classifier_wikiner_en.md
Labels: new model

#12791 2022-09-23-asr_wav2vec2_base_960h_en
  docs/_posts/ahmedlone127/2022-09-23-asr_wav2vec2_base_960h_en.md
  docs/_posts/ahmedlone127/2022-09-23-pipeline_asr_wav2vec2_base_960h_en.md
Labels: new model

#12779 Azure Marketplace deployment guide
  docs/en/nlp_server/installation.md
Labels: documentation

#12780 Video tutorial section for NLP Server
  docs/_data/navigation.yml
  docs/en/nlp_server/video_tutorials.md
Labels: documentation

#12804 2022-09-25-camembert_classifier_berties_en
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_base_wikipedia_4gb_finetuned_job_ner_en.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_berties_en.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_das22_41_pretrained_finetuned_ref_en.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_das22_42_finetuned_ref_en.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_das22_43_pretrained_finetuned_pero_en.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_das22_44_finetuned_pero_en.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_est_roberta_hist_ner_et.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_magbert_ner_fr.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_ner_fr.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_ner_with_dates_fr.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_poet_fr.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_pos_french_fr.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_squadfr_fquad_piaf_answer_extraction_fr.md
  docs/_posts/gadde5300/2022-09-25-camembert_classifier_test_tcp_ca_cassandra_themis_en.md
Labels: new model, DON'T MERGE

#12806 2022-09-25-pipeline_asr_exp_w2v2t_vp_s878_gpu_it
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2r_xls_r_gender_male_8_female_2_s755_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s222_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s27_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s335_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_xls_r_s226_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_xls_r_s250_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_xls_r_s417_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_xlsr_53_s800_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_sanskrit_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_base_vietnamese_160h_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_base_vietnamese_250h_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_base_vietnamese_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xls_r_300m_cantonese_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_53_demo_colab_by_project2you_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_53_vietnamese_by_not_tanh_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_french_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_vietnamese_by_CuongLD_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_vietnamese_by_Nhut_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_murad_with_some_data_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_xlsr_53_phon_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2r_xls_r_gender_male_8_female_2_s755_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s222_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s27_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s335_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s878_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_xls_r_s226_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_xls_r_s250_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_xls_r_s417_gpu_it.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_xlsr_53_s800_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_sanskrit_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_base_vietnamese_160h_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_base_vietnamese_250h_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_base_vietnamese_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xls_r_300m_cantonese_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_demo_colab_by_project2you_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_vietnamese_by_not_tanh_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_french_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_vietnamese_by_CuongLD_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_vietnamese_by_Nhut_gpu_vi.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_murad_with_some_data_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_xlsr_53_phon_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_xls_r_test_gpu_hi.md
Labels: new model, DON'T MERGE

#12807 2022-09-25-asr_exp_w2v2r_xls_r_gender_male_10_female_0_s287_en
  docs/_posts/ahmedlone127/2022-09-25-asr_exp_w2v2r_xls_r_gender_male_10_female_0_s287_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_iloko_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_model_2_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_model_4_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_romanian_wav2vec2_ro.md
  docs/_posts/ahmedlone127/2022-09-25-asr_vakyansh_wav2vec2_indian_english_enm_700_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_100h_test_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_100h_with_lm_by_patrickvonplaten_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_german_de.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_timit_demo_google_colab_by_adelgalu_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_japanese_hiragana_vtuber_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_tedlium_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xls_r_300m_turkish_colab_by_lilitket_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xls_r_300m_turkish_colab_by_masapasa_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_53_arabic_by_logicbloke_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_53_arabic_egyptian_by_arbml_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_53_german_by_jonatasgrosman_de.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_53_german_cv9_de.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_53_german_with_lm_de.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_53_gpt_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_53_romanian_by_anton_l_ro.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_53_romanian_by_gmihaila_ro.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_ksponspeech_1_20_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_moroccan_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_xls_r_300m_english_by_aware_ai_de.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_xlsr_1b_finnish_lm_v2_by_aapot_fi.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_xlsr_train_aug_bigLM_1B_fi.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec_large_xlsr_korean_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wynehills_mimi_ASR_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_exp_w2v2r_xls_r_gender_male_10_female_0_s287_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_iloko_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_model_2_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_model_4_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_romanian_wav2vec2_ro.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_100h_test_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_timit_demo_google_colab_by_adelgalu_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_japanese_hiragana_vtuber_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_tedlium_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xls_r_300m_CN_colab_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xls_r_300m_turkish_colab_by_lilitket_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xls_r_300m_turkish_colab_by_masapasa_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_arabic_by_logicbloke_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_german_by_jonatasgrosman_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_german_cv9_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_german_with_lm_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_gpt_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_romanian_by_anton_l_ro.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_romanian_by_gmihaila_ro.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_german_by_maxidl_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_ksponspeech_1_20_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_moroccan_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_xls_r_300m_english_by_aware_ai_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_xlsr_1b_finnish_lm_v2_by_aapot_fi.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec_large_xlsr_korean_en.md
Labels: new model, DON'T MERGE

#12810 2022-09-25-pipeline_asr_models_6_en
  docs/_posts/ahmedlone127/2022-09-25-asr_ai_light_dance_singing2_wav2vec2_large_xlsr_53_5gram_v4_2_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_exp_w2v2r_xls_r_accent_germany_0_austria_10_s350_de.md
  docs/_posts/ahmedlone127/2022-09-25-asr_models_6_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_100h_13K_steps_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_german_cv9_de.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_nst_da.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_rj_try_5_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_swbd_turn_eos_long_short_utt_removed_3percent_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_timit_demo_colab_by_radhakri119_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_base_timit_demo_colab_by_samantharhay_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_in_lm_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xls_r_300m_CN_colab_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_53_german_by_marcel_de.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_53_greek_by_vasilis_el.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_large_xlsr_hindi_demo_colab_by_rafiulrumy_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_tcrs_runtest_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_vee_demo_colab_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_wav2vec2_xls_r_300m_mixed_by_malay_huggingface_en.md
  docs/_posts/ahmedlone127/2022-09-25-asr_xls_r_300m_danish_nst_cv9_da.md
  docs/_posts/ahmedlone127/2022-09-25-asr_xlsr_wav2vec2_base_commonvoice_demo_colab_4_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_alvenir_wav2vec2_base_nst_cv9_da.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_exp_w2v2r_xls_r_accent_germany_0_austria_10_s350_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_exp_w2v2t_vp_100k_s627_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_models_6_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_vakyansh_wav2vec2_indian_english_enm_700_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_100h_13K_steps_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_german_cv9_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_german_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_rj_try_5_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_swbd_turn_eos_long_short_utt_removed_3percent_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_timit_demo_colab_by_radhakri119_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_timit_demo_colab_by_samantharhay_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_timit_demo_colab_by_terri1102_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_base_timit_demo_test_jong_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_ksponspeech_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xls_r_300m_urdu_proj_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_arabic_egyptian_by_arbml_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_german_by_marcel_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_german_by_oliverguhr_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_german_demo_de.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_hindi_demo_colab_by_rafiulrumy_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_vee_demo_colab_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_xls_r_300m_ftspeech_da.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_xls_r_300m_hindi_lm_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_xls_r_300m_mixed_by_malay_huggingface_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_xls_r_300m_danish_nst_cv9_da.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_xlsr_wav2vec2_base_commonvoice_demo_colab_4_en.md
Labels: new model, DON'T MERGE

#12813 Fix AttributeError for ImageAssembler in PretrainedPipeline
  README.md
  docs/_layouts/landing.html
  python/README.md
  python/sparknlp/__init__.py
  src/test/scala/com/johnsnowlabs/nlp/annotators/audio/Wav2Vec2ForCTCTestSpec.scala
Labels: bug-fix

#12812 2022-09-25-pipeline_asr_xlsr_lm_gpu_fa
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2r_xls_r_gender_male_10_female_0_s559_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_100k_s973_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s738_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s749_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_wav2vec2_s168_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_xlsr_53_s286_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_xlsr_53_s356_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_w2v2_ami_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_base_finetuned_spgi_speech_dev_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_burak_v2.1_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_cgn_3hrs_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xls_r_300m_guarani_colab_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_53_Dutch_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_53_dutch_by_jonatasgrosman_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_53_dutch_by_nithinholla_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_dutch_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec_asr_swbd_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec_lite_gpu_lt.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2r_vp_100k_gender_male_10_female_0_s714_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2r_vp_100k_gender_male_2_female_8_s255_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2r_vp_100k_gender_male_2_female_8_s3_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2r_vp_100k_gender_male_8_female_2_s428_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_100k_s509_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_100k_s88_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_100k_s973_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s738_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_wav2vec2_s321_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_wav2vec2_s809_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_wav2vec2_s870_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_xlsr_53_s116_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_xlsr_53_s356_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_vakyansh_wav2vec2_sanskrit_sam_60_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_base_10k_voxpopuli_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_bilal_2022_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_common_voice_demo_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_ctc_earnings22_baseline_5_gram_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xls_r_300m_hausa_v1.2_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_Dutch_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_dutch_by_wietsedv_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_53_polish_by_facebook_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_dutch_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xlsr_latvian_gpu_lv.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec_demo_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec_lite_gpu_lt.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_xlsr300m_8.0_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_xlsr_lm_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_xlsr_training_gpu_en.md
Labels: new model, DON'T MERGE

#12815 2022-09-25-asr_wav2vec2_common_voice_demo_gpu_nl
  docs/_posts/maziyarpanahi/2022-09-25-asr_Quran_speech_recognizer_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_XLS_R_53_english_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2r_vp_100k_gender_male_8_female_2_s428_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_pretraining_s461_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_100k_s408_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_100k_s899_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s165_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s198_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s224_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s281_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s339_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s438_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s533_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s875_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_vp_s877_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_wav2vec2_s227_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_wav2vec2_s379_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_xlsr_53_s116_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_xlsr_53_s204_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_exp_w2v2t_xlsr_53_s948_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_common_voice_demo_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xls_r_300m_hausa_v1.2_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xls_r_300m_spanish_small_by_tomascufaro_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_53_French_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_large_xlsr_egyptian_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_russian_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_test_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_wav2vec2_xlsr_53_phon_babel_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_XLS_R_53_english_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2r_vp_100k_gender_male_8_female_2_s911_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2r_xls_r_gender_male_2_female_8_s295_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_pretraining_s461_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_pretraining_s650_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_pretraining_s929_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_100k_s407_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s198_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s339_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s419_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s596_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s689_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_vp_s877_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_wav2vec2_s379_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_wav2vec2_s754_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_xlsr_53_s204_gpu_fa.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_xlsr_53_s539_gpu_fr.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_exp_w2v2t_xlsr_53_s799_gpu_nl.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_indicwav2vec_v1_bengali_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_large_xls_r_300m_guarani_colab_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_test_gpu_en.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_wav2vec2_xlsr_multilingual_53_gpu_en.md
Labels: new model

#12816 2022-09-25-pipeline_asr_wav2vec2_large_xls_r_300m_hyAM_batch4_en
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_english_filipino_wav2vec2_l_xls_r_test_07_en.md
  docs/_posts/ahmedlone127/2022-09-25-pipeline_asr_wav2vec2_large_xls_r_300m_hyAM_batch4_en.md
Labels: new model

#12827 2022-09-27-legclf_cuad_licenses_clause_en
  docs/_posts/josejuanmartinez/2022-09-27-legclf_cuad_licenses_clause_en.md
Labels: new model

#12828 2022-09-27-legclf_cuad_indemnifications_clause_en
  docs/_posts/josejuanmartinez/2022-09-27-legclf_cuad_indemnifications_clause_en.md
Labels: new model

#12833 2022-09-27-finassertion_time_en
  docs/_posts/josejuanmartinez/2022-09-27-finassertion_time_en.md
Labels: new model

#12838 2022-09-27-finner_bert_rufacts_ru
  docs/_posts/josejuanmartinez/2022-09-27-finner_bert_rufacts_ru.md
Labels: new model

#12837 2022-09-27-legner_br_base_pt
  docs/_posts/josejuanmartinez/2022-09-27-legner_br_base_pt.md
Labels: new model

#12839 2022-09-27-legner_br_large_pt
  docs/_posts/josejuanmartinez/2022-09-27-legner_br_large_pt.md
Labels: new model

#12844 2022-09-28-finre_work_experience_en
  docs/_posts/josejuanmartinez/2022-09-28-finre_work_experience_en.md
Labels: new model

#12845 2022-09-28-finclf_bert_banking77_en
  docs/_posts/josejuanmartinez/2022-09-28-finclf_bert_banking77_en.md
Labels: new model

#12849 2022-09-28-legre_indemnifications_en
  docs/_posts/josejuanmartinez/2022-09-28-legre_indemnifications_en.md
Labels: new model

#12850 2022-09-28-legner_br_bert_large_pt
  docs/_posts/josejuanmartinez/2022-09-28-legner_br_bert_large_pt.md
Labels: new model

#12852 2022-09-28-legner_br_bert_base_pt
  docs/_posts/josejuanmartinez/2022-09-28-legclf_enforceability_clause_en.md
  docs/_posts/josejuanmartinez/2022-09-28-legclf_enforcement_clause_en.md
  docs/_posts/josejuanmartinez/2022-09-28-legclf_environmental_matters_clause_en.md
  docs/_posts/josejuanmartinez/2022-09-28-legner_br_bert_base_pt.md
  docs/_posts/josejuanmartinez/2022-09-28-legner_law_money_es.md
  docs/_posts/josejuanmartinez/2022-09-28-legner_laws_treaties_es.md
Labels: new model

#12856 2022-09-29-rxnorm_normalized_mapper_en
  docs/_posts/Ahmetemintek/2022-09-29-rxnorm_normalized_mapper_en.md
Labels: new model

#12825 2022-09-26-re_oncology_size_wip_en
  docs/_posts/mauro-nievoff/2022-09-26-re_oncology_size_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-27-re_oncology_biomarker_result_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-27-re_oncology_granular_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-27-re_oncology_location_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-27-re_oncology_temporal_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-27-re_oncology_test_result_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-27-re_oncology_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-28-redl_oncology_size_biobert_wip_en.md
Labels: new model

#12858 2022-09-29-redl_oncology_location_biobert_wip_en
  docs/_posts/mauro-nievoff/2022-09-29-redl_oncology_biobert_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-29-redl_oncology_biomarker_result_biobert_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-29-redl_oncology_granular_biobert_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-29-redl_oncology_location_biobert_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-29-redl_oncology_temporal_biobert_wip_en.md
  docs/_posts/mauro-nievoff/2022-09-29-redl_oncology_test_result_biobert_wip_en.md
Labels: new model

#12862 2022-09-30-table_qa_tapas_tiny_finetuned_sqa_en
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_table_question_answering_tapas_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_base_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_base_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_base_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_large_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_large_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_large_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_medium_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_medium_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_medium_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_mini_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_mini_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_small_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_small_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_small_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_temporary_repo_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_tiny_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_tiny_finetuned_wtq_en.md
Labels: new model

#12863 Models hub
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_table_question_answering_tapas_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_base_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_base_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_base_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_large_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_large_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_large_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_medium_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_medium_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_medium_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_mini_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_mini_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_small_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_small_finetuned_wikisql_supervised_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_small_finetuned_wtq_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_temporary_repo_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_tiny_finetuned_sqa_en.md
  docs/_posts/josejuanmartinez/2022-09-30-table_qa_tapas_tiny_finetuned_wtq_en.md
  docs/_posts/maziyarpanahi/2022-09-25-asr_Wav2Vec2_large_xlsr_hindi_gpu_hi.md
  docs/_posts/maziyarpanahi/2022-09-25-pipeline_asr_Wav2Vec2_large_xlsr_hindi_gpu_hi.md
Labels: DON'T MERGE

#12865 2022-09-30-icd10_icd9_mapper_en
  docs/_posts/Ahmetemintek/2022-09-30-icd10_icd9_mapper_en.md
  docs/_posts/Ahmetemintek/2022-09-30-icd9_mapper_en.md
  docs/_posts/Ahmetemintek/2022-09-30-sbiobertresolve_icd9_en.md
Labels: new model

#12867 2022-09-30-icd9_icd10_mapper_en
  docs/_posts/Ahmetemintek/2022-09-30-icd10_icd9_mapping_en.md
  docs/_posts/Ahmetemintek/2022-09-30-icd9_icd10_mapper_en.md
  docs/_posts/Ahmetemintek/2022-09-30-icd9_resolver_pipeline_en.md
Labels: new model
