Repository JohnSnowLabs/spark-nlp, pull requests merged in 2022-06, with the labels that each got.

#8640 Enabling in-memory Param for WordEmeddings
  docs/api/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcher.html
  docs/api/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcherModel.html
  docs/api/com/johnsnowlabs/nlp/annotators/er/EntityRulerApproach.html
  docs/api/com/johnsnowlabs/nlp/annotators/er/EntityRulerModel.html
  docs/api/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.html
  docs/api/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.html
  docs/api/com/johnsnowlabs/storage/HasExcludableStorage.html
  docs/api/com/johnsnowlabs/storage/HasStorage.html
  docs/api/com/johnsnowlabs/storage/HasStorageModel.html
  docs/api/com/johnsnowlabs/storage/index.html
  docs/licensed/api/com/johnsnowlabs/nlp/annotators/resolution/SentenceEntityResolverModel.html
  python/sparknlp/common/storage.py
  python/test/annotator/embeddings/word_embeddings_test.py
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
  src/main/scala/com/johnsnowlabs/storage/BytesKey.java
  src/main/scala/com/johnsnowlabs/storage/HasStorage.scala
  src/main/scala/com/johnsnowlabs/storage/HasStorageModel.scala
  src/main/scala/com/johnsnowlabs/storage/HasStorageOptions.scala
  src/main/scala/com/johnsnowlabs/storage/StorageReader.scala
  src/test/java/com/johnsnowlabs/storage/BytesKeyJavaTest.java
  src/test/scala/com/johnsnowlabs/nlp/AssertAnnotations.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/SparkSessionTest.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/Word2VecTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/storage/BytesKeyTest.scala
Labels: new-feature, DON'T MERGE

#8547 2022-05-23-camembert_embeddings_bertweetfr_base_fr_3_0
  docs/_posts/murat-gunay/2022-05-23-camembert_embeddings_bertweetfr_base_fr_3_0.md
Labels: new model

#8548 2022-05-23-camembert_embeddings_DataikuNLP_camembert_base_fr_3_0
  docs/_posts/murat-gunay/2022-05-23-camembert_embeddings_DataikuNLP_camembert_base_fr_3_0.md
Labels: new model

#8549 2022-05-23-camembert_embeddings_distilcamembert_base_fr_3_0
  docs/_posts/murat-gunay/2022-05-23-camembert_embeddings_distilcamembert_base_fr_3_0.md
Labels: new model

#8550 2022-05-23-camembert_embeddings_dummy_fr_3_0
  docs/_posts/murat-gunay/2022-05-23-camembert_embeddings_dummy_fr_3_0.md
Labels: new model

#8551 2022-05-23-camembert_embeddings_umberto_commoncrawl_cased_v1_it_3_0
  docs/_posts/murat-gunay/2022-05-23-camembert_embeddings_umberto_commoncrawl_cased_v1_it_3_0.md
Labels: new model

#8552 2022-05-23-camembert_embeddings_umberto_wikipedia_uncased_v1_it_3_0
  docs/_posts/murat-gunay/2022-05-23-camembert_embeddings_umberto_wikipedia_uncased_v1_it_3_0.md
Labels: new model

#8661 2022-06-01-nerdl_conll_elmo_en_3_0
  docs/_posts/maziyarpanahi/2022-06-01-nerdl_conll_elmo_en_3_0.md
Labels: new model

#8659 2022-06-01-nerdl_conll_deberta_base_en_3_0
  docs/_posts/maziyarpanahi/2022-06-01-nerdl_conll_deberta_base_en_3_0.md
Labels: new model

#8662 2022-06-02-bert_qa_bert_small_2_finetuned_squadv2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_bert_small_2_finetuned_squadv2_en_3_0.md
Labels: new model

#8995 2022-06-02-bert_qa_xtremedistil_l6_h256_uncased_finetuned_lr_2e_05_epochs_3_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_xtremedistil_l6_h256_uncased_finetuned_lr_2e_05_epochs_3_en_3_0.md
Labels: new model

#8997 2022-06-02-bert_qa_zero_shot_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_zero_shot_en_3_0.md
Labels: new model

#8991 2022-06-02-bert_qa_unqover_bert_base_uncased_squad_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_unqover_bert_base_uncased_squad_en_3_0.md
Labels: new model

#8902 2022-06-02-bert_qa_linkbert_large_finetuned_squad_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_linkbert_large_finetuned_squad_en_3_0.md
Labels: new model

#8906 2022-06-02-bert_qa_mbert_bengali_tydiqa_qa_bn_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_mbert_bengali_tydiqa_qa_bn_3_0.md
Labels: new model

#8907 2022-06-02-bert_qa_minilm_uncased_squad2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_minilm_uncased_squad2_en_3_0.md
Labels: new model

#8913 2022-06-02-bert_qa_multilingual_bert_base_cased_arabic_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_multilingual_bert_base_cased_arabic_en_3_0.md
Labels: new model

#8914 2022-06-02-bert_qa_multilingual_bert_base_cased_english_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_multilingual_bert_base_cased_english_en_3_0.md
Labels: new model

#8915 2022-06-02-bert_qa_multilingual_bert_base_cased_german_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_multilingual_bert_base_cased_german_en_3_0.md
Labels: new model

#8916 2022-06-02-bert_qa_multilingual_bert_base_cased_hindi_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_multilingual_bert_base_cased_hindi_en_3_0.md
Labels: new model

#8917 2022-06-02-bert_qa_multilingual_bert_base_cased_spanish_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_multilingual_bert_base_cased_spanish_en_3_0.md
Labels: new model

#8979 2022-06-02-bert_qa_squad1.1_1_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_squad1.1_1_en_3_0.md
Labels: new model

#8971 2022-06-02-bert_qa_squad_baseline_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_squad_baseline_en_3_0.md
Labels: new model

#8978 2022-06-02-bert_qa_squad1.1_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_squad1.1_en_3_0.md
Labels: new model

#8980 2022-06-02-bert_qa_squad2.0_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_squad2.0_en_3_0.md
Labels: new model

#8950 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_128_finetuned_squad_seed_6_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_128_finetuned_squad_seed_6_en_3_0.md
Labels: new model

#8779 2022-06-02-bert_qa_csarron_bert_base_uncased_squad_v1_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_csarron_bert_base_uncased_squad_v1_en_3_0.md
Labels: new model

#8873 2022-06-02-bert_qa_chinese_pretrain_mrc_roberta_wwm_ext_large_zh_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_chinese_pretrain_mrc_roberta_wwm_ext_large_zh_3_0.md
Labels: new model

#8874 2022-06-02-bert_qa_covid_squad_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_covid_squad_en_3_0.md
Labels: new model

#8875 2022-06-02-bert_qa_covidbert_squad_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_covidbert_squad_en_3_0.md
Labels: new model

#8878 2022-06-02-bert_qa_demo_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_demo_en_3_0.md
Labels: new model

#8879 2022-06-02-bert_qa_distilbert_base_uncased_finetuned_custom_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_distilbert_base_uncased_finetuned_custom_en_3_0.md
Labels: new model

#8882 2022-06-02-bert_qa_distilbert_tr_q_a_tr_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_distilbert_tr_q_a_tr_3_0.md
Labels: new model

#8883 2022-06-02-bert_qa_eauction_section_parsing_from_pretrained_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_eauction_section_parsing_from_pretrained_en_3_0.md
Labels: new model

#8884 2022-06-02-bert_qa_fewrel_zero_shot_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_fewrel_zero_shot_en_3_0.md
Labels: new model

#8887 2022-06-02-bert_qa_finetune_bert_base_v1_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_finetune_bert_base_v1_en_3_0.md
Labels: new model

#8880 2022-06-02-bert_qa_juliusco_distilbert_base_uncased_finetuned_squad_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_juliusco_distilbert_base_uncased_finetuned_squad_en_3_0.md
Labels: new model

#8881 2022-06-02-bert_qa_kamilali_distilbert_base_uncased_finetuned_squad_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_kamilali_distilbert_base_uncased_finetuned_squad_en_3_0.md
Labels: new model

#8892 2022-06-02-bert_qa_fpdm_hier_bert_FT_new_newsqa_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_fpdm_hier_bert_FT_new_newsqa_en_3_0.md
Labels: new model

#8894 2022-06-02-bert_qa_fpdm_triplet_bert_FT_new_newsqa_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_fpdm_triplet_bert_FT_new_newsqa_en_3_0.md
Labels: new model

#8897 2022-06-02-bert_qa_huBert_fine_tuned_hungarian_squadv1_hu_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_huBert_fine_tuned_hungarian_squadv1_hu_3_0.md
Labels: new model

#8899 2022-06-02-bert_qa_klue_bert_base_aihub_mrc_ko_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_klue_bert_base_aihub_mrc_ko_3_0.md
Labels: new model

#8775 2022-06-02-bert_qa_jimypbr_bert_base_uncased_squad_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_jimypbr_bert_base_uncased_squad_en_3_0.md
Labels: new model

#8988 2022-06-02-bert_qa_tinybert_6l_768d_squad2_large_teacher_finetuned_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_tinybert_6l_768d_squad2_large_teacher_finetuned_en_3_0.md
Labels: new model

#8992 2022-06-02-bert_qa_xdistil_l12_h384_squad2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_xdistil_l12_h384_squad2_en_3_0.md
Labels: new model

#8716 2022-06-02-bert_qa_ydshieh_bert_base_cased_squad2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_ydshieh_bert_base_cased_squad2_en_3_0.md
Labels: new model

#8787 2022-06-02-bert_qa_twmkn9_bert_base_uncased_squad2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_twmkn9_bert_base_uncased_squad2_en_3_0.md
Labels: new model

#8984 2022-06-02-bert_qa_tf_bert_base_cased_squad2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_tf_bert_base_cased_squad2_en_3_0.md
Labels: new model

#8969 2022-06-02-bert_qa_spanbert_large_recruit_qa_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_large_recruit_qa_en_3_0.md
Labels: new model

#8970 2022-06-02-bert_qa_spanbert_recruit_qa_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_recruit_qa_en_3_0.md
Labels: new model

#8962 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_64_finetuned_squad_seed_0_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_64_finetuned_squad_seed_0_en_3_0.md
Labels: new model

#8963 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_64_finetuned_squad_seed_10_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_64_finetuned_squad_seed_10_en_3_0.md
Labels: new model

#8952 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_16_finetuned_squad_seed_42_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_16_finetuned_squad_seed_42_en_3_0.md
Labels: new model

#8895 2022-06-02-bert_qa_fpdm_triplet_bert_FT_newsqa_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_fpdm_triplet_bert_FT_newsqa_en_3_0.md
Labels: new model

#8766 2022-06-02-bert_qa_kaporter_bert_base_uncased_finetuned_squad_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_kaporter_bert_base_uncased_finetuned_squad_en_3_0.md
Labels: new model

#8767 2022-06-02-bert_qa_srmukundb_bert_base_uncased_finetuned_squad_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_srmukundb_bert_base_uncased_finetuned_squad_en_3_0.md
Labels: new model

#8786 2022-06-02-bert_qa_deepset_bert_base_uncased_squad2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_deepset_bert_base_uncased_squad2_en_3_0.md
Labels: new model

#9020 2022-06-03-bert_qa_multilingual_bert_base_cased_chinese_zh_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_multilingual_bert_base_cased_chinese_zh_3_0.md
Labels: new model

#9019 2022-06-03-bert_qa_bert_multi_cased_finedtuned_xquad_tydiqa_goldp_xx_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_bert_multi_cased_finedtuned_xquad_tydiqa_goldp_xx_3_0.md
Labels: new model

#9018 2022-06-03-bert_qa_triviaqa_bert_el_Danastos_en_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_triviaqa_bert_el_Danastos_en_3_0.md
Labels: new model

#9017 2022-06-03-bert_qa_squad_bert_el_Danastos_en_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_squad_bert_el_Danastos_en_3_0.md
Labels: new model

#8964 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_64_finetuned_squad_seed_2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_64_finetuned_squad_seed_2_en_3_0.md
Labels: new model

#8966 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_64_finetuned_squad_seed_6_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_64_finetuned_squad_seed_6_en_3_0.md
Labels: new model

#8967 2022-06-02-bert_qa_spanbert_finetuned_squadv1_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_finetuned_squadv1_en_3_0.md
Labels: new model

#8968 2022-06-02-bert_qa_spanbert_finetuned_squadv2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_finetuned_squadv2_en_3_0.md
Labels: new model

#8973 2022-06-02-bert_qa_squad_mbert_en_de_es_model_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_squad_mbert_en_de_es_model_en_3_0.md
Labels: new model

#8953 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_256_finetuned_squad_seed_10_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_256_finetuned_squad_seed_10_en_3_0.md
Labels: new model

#8954 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_32_finetuned_squad_seed_0_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_32_finetuned_squad_seed_0_en_3_0.md
Labels: new model

#8956 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_32_finetuned_squad_seed_2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_32_finetuned_squad_seed_2_en_3_0.md
Labels: new model

#8957 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_32_finetuned_squad_seed_6_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_32_finetuned_squad_seed_6_en_3_0.md
Labels: new model

#8958 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_512_finetuned_squad_seed_0_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_512_finetuned_squad_seed_0_en_3_0.md
Labels: new model

#8959 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_512_finetuned_squad_seed_10_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_512_finetuned_squad_seed_10_en_3_0.md
Labels: new model

#8960 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_512_finetuned_squad_seed_6_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_512_finetuned_squad_seed_6_en_3_0.md
Labels: new model

#8961 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_512_finetuned_squad_seed_8_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_512_finetuned_squad_seed_8_en_3_0.md
Labels: new model

#8893 2022-06-02-bert_qa_fpdm_hier_bert_FT_newsqa_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_fpdm_hier_bert_FT_newsqa_en_3_0.md
Labels: new model

#8870 2022-06-02-bert_qa_bioformer_cased_v1.0_squad1_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_bioformer_cased_v1.0_squad1_en_3_0.md
Labels: new model

#8885 2022-06-02-bert_qa_fine_tuned_squad_aip_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_fine_tuned_squad_aip_en_3_0.md
Labels: new model

#8888 2022-06-02-bert_qa_finetune_bert_base_v2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_finetune_bert_base_v2_en_3_0.md
Labels: new model

#8889 2022-06-02-bert_qa_finetune_bert_base_v3_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_finetune_bert_base_v3_en_3_0.md
Labels: new model

#8890 2022-06-02-bert_qa_fpdm_bert_FT_new_newsqa_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_fpdm_bert_FT_new_newsqa_en_3_0.md
Labels: new model

#8891 2022-06-02-bert_qa_fpdm_bert_FT_newsqa_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_fpdm_bert_FT_newsqa_en_3_0.md
Labels: new model

#8949 2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_128_finetuned_squad_seed_4_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_spanbert_base_cased_few_shot_k_128_finetuned_squad_seed_4_en_3_0.md
Labels: new model

#8876 2022-06-02-bert_qa_danish_bert_botxo_qa_squad_da_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_danish_bert_botxo_qa_squad_da_3_0.md
Labels: new model

#8974 2022-06-02-bert_qa_squad_mbert_en_de_es_vi_zh_model_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_squad_mbert_en_de_es_vi_zh_model_en_3_0.md
Labels: new model

#8976 2022-06-02-bert_qa_squad_mbert_model_2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_squad_mbert_model_2_en_3_0.md
Labels: new model

#8977 2022-06-02-bert_qa_squad_ms_bert_base_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_squad_ms_bert_base_en_3_0.md
Labels: new model

#8981 2022-06-02-bert_qa_telugu_bertu_tydiqa_xx_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_telugu_bertu_tydiqa_xx_3_0.md
Labels: new model

#8983 2022-06-02-bert_qa_tests_finetuned_squad_test_bert_2_en_3_0
  docs/_posts/gadde5300/2022-06-02-bert_qa_tests_finetuned_squad_test_bert_2_en_3_0.md
Labels: new model

#9003 2022-06-03-bert_qa_bert_base_italian_uncased_squad_it_antoniocappiello_it_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_bert_base_italian_uncased_squad_it_antoniocappiello_it_3_0.md
Labels: new model

#9004 2022-06-03-bert_qa_bert_base_portuguese_cased_finetuned_squad_v1_pt_mrm8488_pt_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_bert_base_portuguese_cased_finetuned_squad_v1_pt_mrm8488_pt_3_0.md
Labels: new model

#9005 2022-06-03-bert_qa_bert_base_spanish_wwm_cased_finetuned_spa_squad2_es_mrm8488_es_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_bert_base_spanish_wwm_cased_finetuned_spa_squad2_es_mrm8488_es_3_0.md
Labels: new model

#9006 2022-06-03-bert_qa_bert_base_spanish_wwm_cased_finetuned_sqac_finetuned_squad2_es_MMG_es_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_bert_base_spanish_wwm_cased_finetuned_sqac_finetuned_squad2_es_MMG_es_3_0.md
Labels: new model

#9007 2022-06-03-bert_qa_bert_base_spanish_wwm_cased_finetuned_squad2_es_MMG_es_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_bert_base_spanish_wwm_cased_finetuned_squad2_es_MMG_es_3_0.md
Labels: new model

#9008 2022-06-03-bert_qa_bert_multi_cased_squad_sv_marbogusz_en_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_bert_multi_cased_squad_sv_marbogusz_en_3_0.md
Labels: new model

#9009 2022-06-03-bert_qa_bert_qa_vi_nvkha_en_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_bert_qa_vi_nvkha_en_3_0.md
Labels: new model

#9010 2022-06-03-bert_qa_distill_bert_base_spanish_wwm_cased_finetuned_spa_squad2_es_mrm8488_es_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_distill_bert_base_spanish_wwm_cased_finetuned_spa_squad2_es_mrm8488_es_3_0.md
Labels: new model

#9011 2022-06-03-bert_qa_ixambert_finetuned_squad_eu_MarcBrun_en_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_ixambert_finetuned_squad_eu_MarcBrun_en_3_0.md
Labels: new model

#9012 2022-06-03-bert_qa_ixambert_finetuned_squad_eu_en_MarcBrun_en_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_ixambert_finetuned_squad_eu_en_MarcBrun_en_3_0.md
Labels: new model

#9013 2022-06-03-bert_qa_newsqa_bert_el_Danastos_en_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_newsqa_bert_el_Danastos_en_3_0.md
Labels: new model

#9014 2022-06-03-bert_qa_nq_bert_el_Danastos_en_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_nq_bert_el_Danastos_en_3_0.md
Labels: new model

#9015 2022-06-03-bert_qa_qacombination_bert_el_Danastos_el_3_0
  docs/_posts/gadde5300/2022-06-03-bert_qa_qacombination_bert_el_Danastos_el_3_0.md
Labels: new model

#9024 2022-06-06-bert_sequence_classifier_binary_rct_biobert_pipeline_en_3_0
  docs/_posts/Damla-Gurbaz/2022-06-06-bert_sequence_classifier_binary_rct_biobert_pipeline_en_3_0.md
Labels: new model

#9026 2022-06-06-rct_binary_classifier_use_pipeline_en_3_0
  docs/_posts/Damla-Gurbaz/2022-06-06-rct_binary_classifier_use_pipeline_en_3_0.md
Labels: new model

#9091 2022-06-06-sbiobertresolve_icdo_augmented_en_3_0
  docs/_posts/Meryem1425/2022-06-06-sbiobertresolve_icdo_augmented_en_3_0.md
Labels: new model

#9094 Release notes content for v0.7.0
  docs/en/nlp_server/release_notes.md
Labels: documentation

#9097 2022-06-07-rxnorm_mapper_en_3_0
  docs/_posts/Ahmetemintek/2022-06-07-rxnorm_mapper_en_3_0.md
Labels: new model

#9250 Make sure classifiers have accuracies between 0.0 and 1.0
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowClassifier.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowSentiment.scala
Labels: enhancement

#9258 2022-06-09-layoutlmv2_rvl_cdip_1500_en_3_0
  docs/_posts/xyutech/2022-06-09-layoutlmv2_rvl_cdip_1500_en_3_0.md
Labels: new model

#9253 2022-06-09-distilbert_qa_multi_finedtuned_squad_pt_3_0
  docs/_posts/murat-gunay/2022-06-09-distilbert_qa_multi_finedtuned_squad_pt_3_0.md
Labels: new model

#9267 Optimizing batch processing for transformer-based Word Embeddings on GPU
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowXlmRoberta.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DeBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlnetEmbeddings.scala
Labels: enhancement, DON'T MERGE

#9264 2022-06-12-layoutlmv2_rvl_cdip_1500_en_2_4
  docs/_posts/xyutech/2022-06-12-layoutlmv2_rvl_cdip_1500_en_2_4.md
Labels: new model

#9299 2022-06-14-distilroberta_base_token_classifier_ontonotes_pipeline_en_3_0
  docs/_posts/ahmedlone127/2022-06-14-distilroberta_base_token_classifier_ontonotes_pipeline_en_3_0.md
Labels: new model

#9297 2022-06-14-albert_base_token_classifier_conll03_pipeline_en_3_0
  docs/_posts/ahmedlone127/2022-06-14-albert_base_token_classifier_conll03_pipeline_en_3_0.md
Labels: new model

#9271 2022-06-13-roberta_large_token_classifier_conll03_pipeline_en_3_0
  docs/_posts/ahmedlone127/2022-06-13-roberta_large_token_classifier_conll03_pipeline_en_3_0.md
Labels: new model

#9305 2022-06-15-deberta_v3_xsmall_qa_squad2_en_3_0
  docs/_posts/murat-gunay/2022-06-15-deberta_v3_xsmall_qa_squad2_en_3_0.md
Labels: new model

#9306 2022-06-15-distilbert_base_cased_qa_squad2_en_3_0
  docs/_posts/murat-gunay/2022-06-15-distilbert_base_cased_qa_squad2_en_3_0.md
Labels: new model

#9307 2022-06-15-longformer_base_base_qa_squad2_en_3_0
  docs/_posts/murat-gunay/2022-06-15-longformer_base_base_qa_squad2_en_3_0.md
Labels: new model

#9308 2022-06-15-roberta_base_qa_squad2_en_3_0
  docs/_posts/murat-gunay/2022-06-15-roberta_base_qa_squad2_en_3_0.md
Labels: new model

#9309 2022-06-15-xlm_roberta_base_qa_squad2_en_3_0
  docs/_posts/murat-gunay/2022-06-15-xlm_roberta_base_qa_squad2_en_3_0.md
Labels: new model

#9310 2022-06-15-albert_base_qa_squad2_en_3_0
  docs/_posts/murat-gunay/2022-06-15-albert_base_qa_squad2_en_3_0.md
Labels: new model

#9313 2022-06-15-ocr_base_handwritten_v2_en_3_0
  docs/_posts/kolia1985/2022-06-15-ocr_base_handwritten_v2_en_3_0.md
Labels: new model

#9323 2022-06-15-clean_slang_en_3_0
  docs/_posts/ahmedlone127/2022-06-15-clean_slang_en_3_0.md
Labels: new model

#9320 2022-06-15-match_chunks_en_3_0
  docs/_posts/ahmedlone127/2022-06-15-match_chunks_en_3_0.md
Labels: new model

#9327 2022-06-18-bert_token_classifier_drug_development_trials_en_3_0
  docs/_posts/HashamUlHaq/2022-06-18-bert_token_classifier_drug_development_trials_en_3_0.md
Labels: new model

#9340 2022-06-19-xlm_roberta_base_token_classifier_ontonotes_pipeline_en_3_0
  docs/_posts/ahmedlone127/2022-06-19-xlm_roberta_base_token_classifier_ontonotes_pipeline_en_3_0.md
Labels: new model

#9345 2022-06-19-distilroberta_base_token_classifier_ontonotes_pipeline_en_3_0
  docs/_posts/ahmedlone127/2022-06-19-distilroberta_base_token_classifier_ontonotes_pipeline_en_3_0.md
Labels: new model

#9346 2022-06-19-distilroberta_base_token_classifier_ontonotes_pipeline_en_3_0
  docs/_posts/ahmedlone127/2022-06-19-distilroberta_base_token_classifier_ontonotes_pipeline_en_3_0.md
Labels: new model

#9325 Release notes content for v07.1
  docs/en/nlp_server/release_notes.md
Labels: documentation

#9576 2022-06-21-clinical_deidentification_pt_3_0
  docs/_posts/josejuanmartinez/2022-06-21-clinical_deidentification_pt_3_0.md
Labels: new model

#9584 2022-06-22-ner_living_species_en_3_0
  docs/_posts/bunyamin-polat/2022-06-22-ner_living_species_en_3_0.md
Labels: new model

#9585 2022-06-22-ner_biomedical_bc2gm_pipeline_en_3_0
  docs/_posts/Cabir40/2022-06-22-ner_biomedical_bc2gm_pipeline_en_3_0.md
Labels: new model

#9589 2022-06-22-ner_living_species_300_es_3_0
  docs/_posts/bunyamin-polat/2022-06-22-ner_living_species_300_es_3_0.md
Labels: new model

#9651 2022-06-22-ner_living_species_roberta_pt_3_0
  docs/_posts/bunyamin-polat/2022-06-22-ner_living_species_roberta_pt_3_0.md
Labels: new model

#9652 2022-06-22-ner_living_species_bert_pt_3_0
  docs/_posts/bunyamin-polat/2022-06-22-ner_living_species_bert_pt_3_0.md
Labels: new model

#9649 2022-06-22-bert_token_classifier_ner_living_species_pt_3_0
  docs/_posts/bunyamin-polat/2022-06-22-bert_token_classifier_ner_living_species_pt_3_0.md
Labels: new model

#9650 2022-06-22-ner_living_species_pt_3_0
  docs/_posts/bunyamin-polat/2022-06-22-ner_living_species_pt_3_0.md
Labels: new model

#9660 2022-06-23-ner_living_species_gl_3_0
  docs/_posts/bunyamin-polat/2022-06-23-ner_living_species_gl_3_0.md
Labels: new model

#9659 2022-06-23-ner_living_species_ca_3_0
  docs/_posts/bunyamin-polat/2022-06-23-ner_living_species_ca_3_0.md
Labels: new model

#9658 2022-06-23-ner_living_species_bert_ro_3_0
  docs/_posts/bunyamin-polat/2022-06-23-ner_living_species_bert_ro_3_0.md
Labels: new model

#9657 2022-06-23-ner_living_species_fr_3_0
  docs/_posts/bunyamin-polat/2022-06-23-ner_living_species_fr_3_0.md
Labels: new model

#9656 2022-06-23-ner_living_species_bert_fr_3_0
  docs/_posts/bunyamin-polat/2022-06-23-ner_living_species_bert_fr_3_0.md
Labels: new model

#9655 2022-06-23-ner_living_species_it_3_0
  docs/_posts/bunyamin-polat/2022-06-23-ner_living_species_it_3_0.md
Labels: new model

#9654 2022-06-23-ner_living_species_bert_it_3_0
  docs/_posts/bunyamin-polat/2022-06-23-ner_living_species_bert_it_3_0.md
Labels: new model

#9653 2022-06-23-bert_token_classifier_ner_living_species_it_3_0
  docs/_posts/bunyamin-polat/2022-06-23-bert_token_classifier_ner_living_species_it_3_0.md
Labels: new model

#9590 2022-06-22-ner_living_species_es_3_0
  docs/_posts/bunyamin-polat/2022-06-22-ner_living_species_es_3_0.md
Labels: new model

#9588 2022-06-22-ner_living_species_roberta_es_3_0
  docs/_posts/bunyamin-polat/2022-06-22-ner_living_species_roberta_es_3_0.md
Labels: new model

#9587 2022-06-22-ner_living_species_bert_es_3_0
  docs/_posts/bunyamin-polat/2022-06-22-ner_living_species_bert_es_3_0.md
Labels: new model

#9586 2022-06-22-bert_token_classifier_ner_living_species_es_3_0
  docs/_posts/bunyamin-polat/2022-06-22-bert_token_classifier_ner_living_species_es_3_0.md
Labels: new model

#9591 2022-06-22-ner_clinical_trials_abstracts_en_3_0
  docs/_posts/luca-martial/2022-06-22-ner_clinical_trials_abstracts_en_3_0.md
Labels: new model

#9505 2022-06-20-roberta_qa_avioo1_roberta_base_squad2_finetuned_squad_en_3_0
  docs/_posts/gadde5300/2022-06-20-roberta_qa_avioo1_roberta_base_squad2_finetuned_squad_en_3_0.md
Labels: new model
