Repository JohnSnowLabs/spark-nlp, pull requests merged in 2022-01, with the labels that each got.

#6687 2022-01-01-sbiobertresolve_snomed_drug_en
  docs/_posts/muhammetsnts/2022-01-01-sbiobertresolve_snomed_drug_en.md
Labels: new model

#6683 2021-12-29-classifierdl_urduvec_fakenews_ur
  docs/_posts/murat-gunay/2021-12-29-classifierdl_urduvec_fakenews_ur.md
Labels: new model

#6691 2021-12-31-nerdl_restaurant_100d_en
  docs/_posts/murat-gunay/2021-12-31-nerdl_restaurant_100d_en.md
Labels: new model

#6695 2022-01-03-bert_token_classifier_ner_bionlp_en
  docs/_posts/egenc/2022-01-03-bert_token_classifier_ner_bionlp_en.md
Labels: new model

#6694 2022-01-03-clean_slang_en
  docs/_posts/egenc/2022-01-03-clean_slang_en.md
Labels: new model

#6696 2022-01-03-word2vec_gigaword_300_en
  docs/_posts/maziyarpanahi/2022-01-03-word2vec_gigaword_300_en.md
Labels: new model

#6697 2022-01-03-word2vec_gigaword_wiki_300_en
  docs/_posts/maziyarpanahi/2022-01-03-word2vec_gigaword_wiki_300_en.md
Labels: new model

#6698 Models hub
  docs/_posts/egenc/2022-01-03-clean_slang_en.md
  docs/_posts/gadde5300/2021-12-27-bert_token_classifier_hi_en_ner_hi.md
  docs/_posts/galiph/2021-12-23-sbert_jsl_medium_rxnorm_uncased_en.md
  docs/_posts/maziyarpanahi/2021-12-23-xlm_roberta_base_sequence_classifier_ag_news_en.md
  docs/_posts/maziyarpanahi/2021-12-23-xlm_roberta_base_sequence_classifier_allocine_fr.md
  docs/_posts/maziyarpanahi/2021-12-23-xlm_roberta_base_sequence_classifier_imdb_en.md
  docs/_posts/maziyarpanahi/2021-12-23-xlnet_base_sequence_classifier_ag_news_en.md
  docs/_posts/maziyarpanahi/2021-12-23-xlnet_base_sequence_classifier_imdb_en.md
  docs/_posts/maziyarpanahi/2022-01-03-word2vec_gigaword_300_en.md
  docs/_posts/maziyarpanahi/2022-01-03-word2vec_gigaword_wiki_300_en.md
  docs/_posts/murat-gunay/2021-12-21-bert_sequence_classifier_finbert_tone_en.md
  docs/_posts/murat-gunay/2021-12-21-bert_sequence_classifier_sentiment_it.md
  docs/_posts/murat-gunay/2021-12-22-bert_sequence_classifier_toxicity_ru.md
  docs/_posts/murat-gunay/2021-12-25-xlm_roberta_large_token_classifier_conll03_de.md
  docs/_posts/murat-gunay/2021-12-26-xlm_roberta_large_token_classifier_hrl_xx.md
  docs/_posts/murat-gunay/2021-12-27-roberta_token_classifier_pos_tagger_id.md
  docs/_posts/murat-gunay/2021-12-27-roberta_token_classifier_ticker_en.md
  docs/_posts/murat-gunay/2021-12-28-roberta_token_classifier_timex_semeval_en.md
  docs/_posts/murat-gunay/2021-12-29-classifierdl_urduvec_fakenews_ur.md
  docs/_posts/murat-gunay/2021-12-29-classifierdl_xlm_roberta_sentiment_sw.md
  docs/_posts/murat-gunay/2021-12-31-nerdl_restaurant_100d_en.md
Labels: models_hub, new model

#6702 2022-01-03-sbiobertresolve_rxnorm_augmented_en
  docs/_posts/galiph/2022-01-03-sbiobertresolve_rxnorm_augmented_en.md
Labels: new model

#6701 2022-01-03-sbiobertresolve_clinical_abbreviation_acronym_en
  docs/_posts/muhammetsnts/2022-01-03-sbiobertresolve_clinical_abbreviation_acronym_en.md
Labels: new model

#6700 2022-01-03-sbert_jsl_medium_rxnorm_uncased_en
  docs/_posts/galiph/2022-01-03-sbert_jsl_medium_rxnorm_uncased_en.md
Labels: new model

#6699 Preserve the actual trained weights from NerDLApproach
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLSpec.scala
Labels: enhancement

#6703 2022-01-03-bert_base_finnish_cased_fi
  docs/_posts/gadde5300/2022-01-03-bert_base_finnish_cased_fi.md
Labels: new model

#6704 2022-01-03-bert_base_finnish_uncased_fi
  docs/_posts/gadde5300/2022-01-03-bert_base_finnish_uncased_fi.md
Labels: new model

#6712 2022-01-04-electra_medal_acronym_en
  docs/_posts/josejuanmartinez/2022-01-04-electra_medal_acronym_en.md
Labels: new model

#6715 2022-01-05-layoutlmv2_funsd_en
  docs/_posts/xyutech/2022-01-05-layoutlmv2_funsd_en.md
Labels: new model

#6711 2022-01-04-match_datetime_en
  docs/_posts/egenc/2022-01-04-match_datetime_en.md
Labels: new model

#6710 2022-01-04-match_chunks_en
  docs/_posts/egenc/2022-01-04-match_chunks_en.md
Labels: new model

#6709 2022-01-04-check_spelling_dl_en
  docs/_posts/egenc/2022-01-04-check_spelling_dl_en.md
Labels: new model

#6716 Models hub
  docs/_posts/egenc/2022-01-04-check_spelling_dl_en.md
  docs/_posts/egenc/2022-01-04-match_chunks_en.md
  docs/_posts/egenc/2022-01-04-match_datetime_en.md
Labels: models_hub, new model

#6720 2022-01-05-redl_drugprot_biobert_en
  docs/_posts/luca-martial/2022-01-05-redl_drugprot_biobert_en.md
Labels: new model

#6723 2022-01-05-re_drugprot_clinical_en
  docs/_posts/luca-martial/2022-01-05-re_drugprot_clinical_en.md
Labels: new model

#6705 2022-01-04-bert_token_classifier_ner_ade_en
  docs/_posts/egenc/2022-01-04-bert_token_classifier_ner_ade_en.md
Labels: new model

#6731 2022-01-06-bert_token_classifier_ner_chemicals_en
  docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_chemicals_en.md
Labels: new model

#6727 2022-01-06-bert_token_classifier_ner_anatomy_en
  docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_anatomy_en.md
Labels: new model

#6728 2022-01-06-bert_token_classifier_ner_cellular_en
  docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_cellular_en.md
Labels: new model

#6730 2022-01-06-ner_deid_generic_de
  docs/_posts/galiph/2022-01-06-ner_deid_generic_de.md
Labels: new model

#6729 2022-01-06-ner_deid_subentity_de
  docs/_posts/galiph/2022-01-06-ner_deid_subentity_de.md
Labels: new model

#6738 2022-01-06-bert_token_classifier_ner_jsl_en
  docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_jsl_en.md
Labels: new model

#6737 2022-01-06-bert_token_classifier_ner_jsl_slim_en
  docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_jsl_slim_en.md
Labels: new model

#6736 2022-01-06-bert_token_classifier_ner_clinical_en
  docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_clinical_en.md
Labels: new model

#6735 2022-01-06-bert_token_classifier_ner_drugs_en
  docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_drugs_en.md
Labels: new model

#6734 2022-01-06-bert_token_classifier_ner_deid_en
  docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_deid_en.md
Labels: new model

#6732 2022-01-06-bert_token_classifier_ner_chemprot_en
  docs/_posts/egenc/2022-01-06-bert_token_classifier_ner_chemprot_en.md
Labels: new model

#6739 2022-01-06-clinical_deidentification_de
  docs/_posts/galiph/2022-01-06-clinical_deidentification_de.md
Labels: new model

#6740 2022-01-07-bert_token_classifier_ner_bacteria_en
  docs/_posts/egenc/2022-01-07-bert_token_classifier_ner_bacteria_en.md
Labels: new model

#6744 2022-01-08-clinical_deidentification_de
  docs/_posts/galiph/2022-01-08-clinical_deidentification_de.md
Labels: new model

#6751 2022-01-11-sbiobertresolve_snomed_findings_aux_concepts_en
  docs/_posts/muhammetsnts/2022-01-11-sbiobertresolve_snomed_findings_aux_concepts_en.md
Labels: new model

#6757 Docs/alab2.6.0
  docs/en/alab/install.md
  docs/en/alab/models_hub.md
  docs/en/alab/quickstart.md
  docs/en/alab/release_notes.md
Labels: documentation

#6752 2022-01-11-pos_ud_bokmaal_nb
  docs/_posts/egenc/2022-01-11-pos_ud_bokmaal_nb.md
Labels: new model

#6758 2022-01-12-t5_small_wikiSQL_en
  docs/_posts/DevinTDHa/2022-01-12-t5_small_wikiSQL_en.md
Labels: new model

#6759 2022-01-12-t5_grammar_error_corrector_en
  docs/_posts/DevinTDHa/2022-01-12-t5_grammar_error_corrector_en.md
Labels: new model

#6762 2022-01-12-t5_informal_to_formal_styletransfer_en
  docs/_posts/DevinTDHa/2022-01-12-t5_informal_to_formal_styletransfer_en.md
Labels: new model

#6763 2022-01-12-t5_active_to_passive_styletransfer_en
  docs/_posts/DevinTDHa/2022-01-12-t5_active_to_passive_styletransfer_en.md
Labels: new model

#6766 2022-01-13-distilbert_base_cased_vi
  docs/_posts/murat-gunay/2022-01-13-distilbert_base_cased_vi.md
Labels: new model

#6771 2022-01-14-bert_sequence_classifier_emotion_en
  docs/_posts/murat-gunay/2022-01-14-bert_sequence_classifier_emotion_en.md
Labels: new model

#6776 2022-01-17-sbertresolve_ner_model_finder_en
  docs/_posts/egenc/2022-01-17-sbertresolve_ner_model_finder_en.md
Labels: new model

#6777 2022-01-17-sbiobertresolve_clinical_abbreviation_acronym_en
  docs/_posts/egenc/2022-01-17-sbiobertresolve_clinical_abbreviation_acronym_en.md
Labels: new model

#6779 2022-01-17-ner_deid_generic_roberta_es
  docs/_posts/josejuanmartinez/2022-01-17-ner_deid_generic_roberta_es.md
Labels: new model

#6780 2022-01-18-ner_profiling_clinical_en
  docs/_posts/egenc/2022-01-18-ner_profiling_clinical_en.md
Labels: new model

#6782 2022-01-18-bert_sequence_classifier_sentiment_da
  docs/_posts/murat-gunay/2022-01-18-bert_sequence_classifier_sentiment_da.md
Labels: new model

#6783 2022-01-18-bert_sequence_classifier_news_sentiment_de
  docs/_posts/murat-gunay/2022-01-18-bert_sequence_classifier_news_sentiment_de.md
Labels: new model

#6787 2022-01-18-sbiobertresolve_icd10cm_augmented_en
  docs/_posts/egenc/2022-01-18-sbiobertresolve_icd10cm_augmented_en.md
Labels: new model

#6786 2022-01-18-ner_deid_generic_es
  docs/_posts/josejuanmartinez/2022-01-18-ner_deid_generic_es.md
Labels: new model

#6785 2022-01-18-ner_deid_subentity_es
  docs/_posts/josejuanmartinez/2022-01-18-ner_deid_subentity_es.md
Labels: new model

#6788 2022-01-18-sbiobertresolve_loinc_augmented_en
  docs/_posts/egenc/2022-01-18-sbiobertresolve_loinc_augmented_en.md
Labels: new model

#6791 2022-01-18-sbluebertresolve_loinc_uncased_en
  docs/_posts/egenc/2022-01-18-sbluebertresolve_loinc_uncased_en.md
Labels: new model

#6790 2022-01-18-sbiobertresolve_snomed_drug_en
  docs/_posts/egenc/2022-01-18-sbiobertresolve_snomed_drug_en.md
Labels: new model

#6789 2022-01-18-sbiobertresolve_mesh_en
  docs/_posts/egenc/2022-01-18-sbiobertresolve_mesh_en.md
Labels: new model

#6792 2022-01-18-ner_profiling_biobert_en
  docs/_posts/egenc/2022-01-18-ner_profiling_biobert_en.md
Labels: new model

#6798 2022-01-20-trocr_base_printed_en
  docs/_posts/kolia1985/2022-01-20-trocr_base_printed_en.md
Labels: new model

#6781 Allow T5 models to change task
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5TestSpec.scala
Labels: enhancement, DON'T MERGE

#6802 2022-01-21-ner_profiling_biobert_en
  docs/_posts/egenc/2022-01-21-ner_profiling_biobert_en.md
Labels: new model

#6803 2022-01-21-sbiobertresolve_icd10cm_augmented_en
  docs/_posts/egenc/2022-01-21-sbiobertresolve_icd10cm_augmented_en.md
Labels: new model

#6808 2022-01-24-craft_text_detector_en
  docs/_posts/kolia1985/2022-01-24-craft_text_detector_en.md
Labels: new model

#6810 2022-01-24-deid_pipeline_es
  docs/_posts/josejuanmartinez/2022-01-24-deid_pipeline_es.md
Labels: new model

#6812 2022-01-25-craft_en
  docs/_posts/kolia1985/2022-01-25-craft_en.md
Labels: new model

#6807 2022-01-23-ner_ncbi_glove_100d_en
  docs/_posts/bunyamin-polat/2022-01-23-ner_ncbi_glove_100d_en.md
Labels: new model

#6741 Revert back to none optional session for more reliable serializations
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowWrapper.scala
Labels: enhancement, DON'T MERGE

#6748 Fix RecursiveTokenizerModel not being readable in a saved Pipeline
  src/main/scala/com/johnsnowlabs/nlp/annotators/RecursiveTokenizerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: bug-fix, DON'T MERGE

#6749 Add bestModelMetric param to choose between Micro-average or Macro-average for best model
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/test/scala/com/johnsnowlabs/benchmarks/jvm/NerDLCoNLL2003.scala
Labels: enhancement, DON'T MERGE

#6750 Serialization context spell
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/parser/SerializableClass.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/parser/SpecialTokensParser.scala
Labels: bug-fix, DON'T MERGE

#6767 Update slow unit tests
  src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala
  src/test/scala/com/johnsnowlabs/nlp/EmbeddingsFinisherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/TokenAssemblerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/LemmatizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TextMatcherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcherTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverterTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/NerPerfTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticDetectionPerfTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/sda/vivekn/ViveknPerformanceTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/SpellCheckersPerfTest.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/ChunkEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/UniversalSentenceEncoderTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsTestSpec.scala
Labels: enhancement, DON'T MERGE

#6773 Implement TF Session warmup for some TF-based annotators
  python/sparknlp/annotator.py
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowGPT2.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMarian.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowT5.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2TestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5TestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddingsTestSpec.scala
Labels: enhancement, DON'T MERGE

#6799 fix tokens order based in ContextSpellCheckerModel when there are sentences
  src/main/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/context/ContextSpellCheckerTestSpec.scala
Labels: bug-fix

#6796 2022-01-19-distilbert_token_classifier_typo_detector_en
  docs/_posts/murat-gunay/2022-01-19-distilbert_token_classifier_typo_detector_en.md
Labels: new model

#6793 2022-01-18-distilbert_base_token_classifier_masakhaner_xx
  docs/_posts/murat-gunay/2022-01-18-distilbert_base_token_classifier_masakhaner_xx.md
Labels: new model

#6824 2022-01-19-distilbert_token_classifier_typo_detector_is
  docs/_posts/murat-gunay/2022-01-19-distilbert_token_classifier_typo_detector_is.md
Labels: new model

#6829 2022-01-28-layoutlmv2_key_value_pairs_en
  docs/_posts/xyutech/2022-01-28-layoutlmv2_key_value_pairs_en.md
Labels: new model

#6834 2022-01-31-image_text_detector_v2_en
  docs/_posts/kolia1985/2022-01-31-image_text_detector_v2_en.md
Labels: new model
