Repository JohnSnowLabs/spark-nlp, pull requests merged in 2022-12, with the labels that each got.

#13176 2022-12-01-legner_whereas_md_en
  docs/_posts/josejuanmartinez/2022-12-01-legner_contract_doc_parties_md_en.md
  docs/_posts/josejuanmartinez/2022-12-01-legner_grants_md_en.md
  docs/_posts/josejuanmartinez/2022-12-01-legner_indemnifications_md_en.md
  docs/_posts/josejuanmartinez/2022-12-01-legner_termination_md_en.md
  docs/_posts/josejuanmartinez/2022-12-01-legner_warranty_md_en.md
  docs/_posts/josejuanmartinez/2022-12-01-legner_whereas_md_en.md
Labels: new model

#13177 Added content for ALAB 430 features and enhancements
  docs/assets/images/annotation_lab/4.3.0/infrastructure.png
  docs/en/alab/annotation.md
  docs/en/alab/byol.md
  docs/en/alab/import.md
  docs/en/alab/infrastructure.md
  docs/en/alab/models_hub.md
  docs/en/alab/preannotation.md
  docs/en/alab/project_configuration.md
  docs/en/alab/rules.md
  docs/en/alab/security.md
  docs/en/alab/tasks.md
  docs/en/alab/training_configurations.md
  docs/en/alab/user_management.md
Labels: documentation

#13180 2022-12-01-finclf_sec_filings_en
  docs/_posts/bunyamin-polat/2022-12-01-finclf_sec_filings_en.md
Labels: new model

#13183 2022-12-02-finner_10q_xlbr_en
  docs/_posts/josejuanmartinez/2022-12-02-finner_10q_xlbr_en.md
Labels: new model

#13191 2022-12-05-legclf_principal_underwriter_clause_en
  docs/_posts/gadde5300/2022-12-05-legclf_eminent_domain_clause_en.md
  docs/_posts/gadde5300/2022-12-05-legclf_erisa_reports_clause_en.md
  docs/_posts/gadde5300/2022-12-05-legclf_injury_pay_clause_en.md
  docs/_posts/gadde5300/2022-12-05-legclf_no_appraisal_rights_clause_en.md
  docs/_posts/gadde5300/2022-12-05-legclf_payment_of_interest_defaulted_interest_clause_en.md
  docs/_posts/gadde5300/2022-12-05-legclf_principal_underwriter_clause_en.md
  docs/_posts/gadde5300/2022-12-05-legclf_retention_of_sub_adviser_clause_en.md
  docs/_posts/gadde5300/2022-12-05-legclf_right_to_cure_clause_en.md
  docs/_posts/gadde5300/2022-12-05-legclf_sick_days_clause_en.md
  docs/_posts/gadde5300/2022-12-05-legclf_successor_to_the_bank_clause_en.md
Labels: new model

#13166 2022-11-29-bert_token_classifier_swedish_ner_sv
  docs/_posts/gokhanturer/2022-11-29-bert_token_classifier_swedish_ner_sv.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_aleph_finetuned_metaphor_detection_he.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_ara_ner_ar.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_autonlp_ingredient_pseudo_label_training_ner_29576765_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_autonlp_ingredient_sentiment_analysis_19126711_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_autotrain_final_784824206_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_autotrain_final_784824213_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_autotrain_gro_ner_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_autotrain_lucy_alicorp_1356152290_es.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_autotrain_medicaltokenclassification_1279048948_unk.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_autotrain_ner_favsbot_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_autotrain_tk_1181244086_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_base_chinese_ws_zh.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_base_german_finetuned_ler_de.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_base_han_chinese_ws_zh.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_base_multilingual_cased_finetuned_albanian_ner_sq.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_base_multilingual_cased_finetuned_norsk_ner_no.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_base_swedish_lowermix_reallysimple_ner_sv.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_base_uncased_city_country_ner_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_berturk_cased_keyword_discriminator_tr.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_berturk_cased_ner_tr.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_berturk_sunlp_ner_turkish_tr.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_biobertpt_clin_tempclinbr_pt.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_cased_keyword_discriminator_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_clinicalnerpt_chemical_pt.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_clinicalnerpt_diagnostic_pt.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_clinicalnerpt_disease_pt.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_clinicalnerpt_disorder_pt.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_clinicalnerpt_finding_pt.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_fernet_cc_sk_ner_sk.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_german_ler_de.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_large_ner_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_lewip_informal_tagger_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_loodos_sunlp_ner_turkish_tr.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_ncbi_bc5cdr_disease_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_ner4designtutor_en.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_ner_fine_tuned_beto_es.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_ner_japanese_ja.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_ner_legal_de.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_restore_punctuation_ptbr_pt.md
  docs/_posts/gokhanturer/2022-11-30-bert_token_classifier_tiny_chinese_ws_zh.md
Labels: new model

#13182 2022-12-02-roberta_qa_icebert_is
  docs/_posts/Damla-Gurbaz/2022-12-02-bert_embeddings_arbert_ar.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_akdeniz27_base_cuad_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_autoevaluate_base_squad2_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_1b_1_finetuned_squadv1_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_1b_1_finetuned_squadv2_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_bne_squad2_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_bne_squad_2.0_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_ca_cased_ca.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_ca_v2_cased_ca.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_cuad_finetuned_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_mitmovie_squad_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_on_cuad_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_spanish_s_c_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_spanish_squades_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_squad2_distilled_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_squad_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_squad_v1_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_base_squad_v2_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_bertin_large_finetuned_s_c_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_bsc_temu_base_bne_s_c_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_bsc_temu_large_bne_s_c_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_carbonblog_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_cart_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_deepset_base_squad2_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_deepset_large_squad2_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_icebert_is.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_large_bne_squad_2.0_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_large_cuad_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_large_finetuned_squad2_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_large_syn_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_large_syn_ext_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_longformer_base_4096_spanish_finetuned_squad_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_marshmellow77_base_cuad_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_movie_mitmovie_squad_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_movie_squad_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_mrm8488_base_bne_finetuned_s_c_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_navteca_base_squad2_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_navteca_large_squad2_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_nlp_en_es_base_bne_finetuned_s_c_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_nlu_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_plantl_gob_es_base_bne_s_c_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_plantl_gob_es_large_bne_s_c_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_plm_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_ruperta_base_finetuned_squadv1_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_ruperta_base_finetuned_squadv2_es.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_sper_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_tiny_6l_768d_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_tiny_squad2_en.md
  docs/_posts/Damla-Gurbaz/2022-12-02-roberta_qa_ydshieh_base_squad2_en.md
Labels: new model

#13195 2022-12-06-bert_embeddings_chinese_roberta_l_10_h_256_zh
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_10_h_256_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_10_h_512_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_10_h_768_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_12_h_128_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_12_h_256_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_12_h_512_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_12_h_768_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_2_h_128_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_2_h_256_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_2_h_512_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_2_h_768_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_4_h_128_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_4_h_256_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_4_h_512_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_4_h_768_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_6_h_128_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_6_h_256_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_6_h_512_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_6_h_768_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_8_h_128_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_8_h_256_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_8_h_512_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_l_8_h_768_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_chinese_roberta_wwm_large_ext_fix_mlm_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_cicero_similis_la.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_deberta_base_uncased_en.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_false_positives_scancode_base_uncased_l8_1_en.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_fin_pretrain_yiyanghkust_en.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_g_base_de.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_g_large_de.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_greeksocial_base_greek_uncased_v1_el.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_indic_transformers_bn.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_indic_transformers_hi.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_indic_transformers_te.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_javanese_small_imdb_jv.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_javanese_small_jv.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_kb_distilled_cased_sv.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_lic_class_scancode_base_cased_l32_1_en.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_minirbt_h256_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_minirbt_h288_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_netbert_en.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_norbert2_no.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_norbert_no.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_rbt3_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_rbt4_h312_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_rbt4_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_rbt6_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_rbtl3_zh.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_v_2021_base_en.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_v_2021_large_en.md
  docs/_posts/Mary-Sci/2022-12-06-bert_embeddings_wo_chinese_plus_zh.md
Labels: new model

#13178 2022-12-01-oncology_general_pipeline_en
  docs/_posts/mauro-nievoff/2022-12-01-oncology_biomarker_pipeline_en.md
  docs/_posts/mauro-nievoff/2022-12-01-oncology_diagnosis_pipeline_en.md
  docs/_posts/mauro-nievoff/2022-12-01-oncology_general_pipeline_en.md
  docs/_posts/mauro-nievoff/2022-12-01-oncology_therapy_pipeline_en.md
Labels: new model

#13197 2022-12-06-legclf_agreement_and_plan_of_reorganization_en
  docs/_posts/bunyamin-polat/2022-12-06-legclf_agreement_and_plan_of_reorganization_en.md
  docs/_posts/bunyamin-polat/2022-12-06-legclf_deposit_agreement_en.md
  docs/_posts/bunyamin-polat/2022-12-06-legclf_indemnity_agreement_en.md
  docs/_posts/bunyamin-polat/2022-12-06-legclf_investment_advisory_agreement_en.md
  docs/_posts/bunyamin-polat/2022-12-06-legclf_option_agreement_en.md
  docs/_posts/bunyamin-polat/2022-12-06-legclf_pledge_agreement_en.md
  docs/_posts/bunyamin-polat/2022-12-06-legclf_restricted_stock_unit_agreement_en.md
  docs/_posts/bunyamin-polat/2022-12-06-legclf_revolving_credit_agreement_en.md
  docs/_posts/bunyamin-polat/2022-12-06-legclf_severance_agreement_en.md
  docs/_posts/bunyamin-polat/2022-12-06-legclf_underwriting_agreement_en.md
Labels: new model

#13203 2022-12-07-legclf_governing_law_clause_en
  docs/_posts/bunyamin-polat/2022-12-07-legclf_business_day_clause_en.md
  docs/_posts/bunyamin-polat/2022-12-07-legclf_demand_registration_clause_en.md
  docs/_posts/bunyamin-polat/2022-12-07-legclf_electronic_communications_clause_en.md
  docs/_posts/bunyamin-polat/2022-12-07-legclf_entire_agreement_clause_en.md
  docs/_posts/bunyamin-polat/2022-12-07-legclf_governing_law_clause_en.md
  docs/_posts/bunyamin-polat/2022-12-07-legclf_health_and_safety_clause_en.md
  docs/_posts/bunyamin-polat/2022-12-07-legclf_language_clause_en.md
  docs/_posts/bunyamin-polat/2022-12-07-legclf_replacement_of_lenders_clause_en.md
  docs/_posts/bunyamin-polat/2022-12-07-legclf_rules_and_regulations_clause_en.md
  docs/_posts/bunyamin-polat/2022-12-07-legclf_ti_allowance_clause_en.md
Labels: new model

#13208 2022-12-09-legclf_administrative_services_agreement_en
  docs/_posts/gadde5300/2022-12-09-legclf_administrative_services_agreement_bert_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_administrative_services_agreement_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_aircraft_lease_agreement_bert_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_aircraft_lease_agreement_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_custody_agreement_bert_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_custody_agreement_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_expense_limitation_agreement_bert_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_expense_limitation_agreement_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_joinder_agreement_bert_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_joinder_agreement_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_plan_and_agreement_of_merger_bert_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_plan_and_agreement_of_merger_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_reference_trust_agreement_bert_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_reference_trust_agreement_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_restricted_stock_agreement_bert_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_restricted_stock_agreement_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_share_purchase_agreement_bert_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_share_purchase_agreement_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_subadvisory_agreement_bert_en.md
  docs/_posts/gadde5300/2022-12-09-legclf_subadvisory_agreement_en.md
Labels: new model

#13200 2022-12-07-sbert_chinese_qmc_finance_v1_distill_zh
  docs/_posts/gadde5300/2022-12-07-sbert_chinese_qmc_finance_v1_distill_zh.md
  docs/_posts/gadde5300/2022-12-07-sbert_setfit_finetuned_financial_text_classification_en.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_base_TSDAE_sts_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_large_GPL_sts_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_large_TSDAE_sts_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_large_TSDAE_sts_v2_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_large_TSDAE_sts_v4_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_large_TSDAE_v4_GPL_sts_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_large_v2_sts_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_sts_base_ma_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_sts_base_ma_v2_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_sts_base_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_sts_large_ma_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_sts_large_ma_v3_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_sts_large_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_Legal_BERTimbau_sts_large_v2_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_sts_v0.10_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_sts_v0.1_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_sts_v0.2_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_sts_v0.3_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_sts_v0.4_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_sts_v0.5_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_sts_v0.7_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_sts_v0.8_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_sts_v0.9_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_sts_v1.0_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_v0.11_gpl_nli_sts_v0_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_v0.11_gpl_nli_sts_v1_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_v0.11_nli_sts_v0_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_v0.11_nli_sts_v1_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_v0.11_sts_v0_pt.md
  docs/_posts/gadde5300/2022-12-10-sbert_bert_large_portuguese_cased_legal_mlm_v0.11_sts_v1_pt.md
Labels: new model

#13211 2022-12-09-roberta_classifier_detect_acoso_twitter_es
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_autonlp_imdb_rating_625417974_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_autonlp_predict_roi_1_29797730_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_autonlp_sst1_529214890_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_autonlp_trec_classification_522314623_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_autonlp_txc_17923124_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_autotrain_amazon_shoe_reviews_classification_1104340243_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_autotrain_citizen_nlu_bn_1370652766_bn.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_autotrain_citizen_nlu_hindi_1370952776_hi.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_autotrain_neurips_chanllenge_1287149282_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_autotrain_pan_976832386_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_ctrl44_clf_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_cuenb_mnli_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_detect_acoso_twitter_es.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_sentence_classification4designtutor_en.md
  docs/_posts/Meryem1425/2022-12-09-roberta_classifier_sentiment_analysis_en.md
Labels: new model

#13214 Added content for 440 and 441
  docs/en/alab/annotation.md
  docs/en/alab/annotation_configurations.md
  docs/en/alab/annotation_labs_releases/release_notes_4_4_0.md
  docs/en/alab/productivity.md
  docs/en/alab/rules.md
  docs/en/alab/tasks.md
  docs/en/alab/training_configurations.md
Labels: documentation

#13222 FEATURE NMH-142: Add annotator to models.json [skip-test]
  docs/_plugins/search_index.rb
Labels: enhancement, models_hub

#13225 2022-12-14-finner_10q_xlbr_md_subset1_en
  docs/_posts/gadde5300/2022-12-14-finner_10q_xlbr_md_subset1_en.md
  docs/_posts/gadde5300/2022-12-14-finner_10q_xlbr_md_subset2_en.md
  docs/_posts/gadde5300/2022-12-14-finner_10q_xlbr_md_subset3_en.md
  docs/_posts/gadde5300/2022-12-15-finner_10q_xlbr_md_subset10_en.md
  docs/_posts/gadde5300/2022-12-15-finner_10q_xlbr_md_subset11_en.md
  docs/_posts/gadde5300/2022-12-15-finner_10q_xlbr_md_subset12_en.md
  docs/_posts/gadde5300/2022-12-15-finner_10q_xlbr_md_subset4_en.md
  docs/_posts/gadde5300/2022-12-15-finner_10q_xlbr_md_subset5_en.md
  docs/_posts/gadde5300/2022-12-15-finner_10q_xlbr_md_subset6_en.md
  docs/_posts/gadde5300/2022-12-15-finner_10q_xlbr_md_subset7_en.md
  docs/_posts/gadde5300/2022-12-15-finner_10q_xlbr_md_subset8_en.md
  docs/_posts/gadde5300/2022-12-15-finner_10q_xlbr_md_subset9_en.md
Labels: new model

#13228 2022-12-15-camembert_large_sequence_classifier_allocine_fr
  docs/_posts/maziyarpanahi/2022-12-15-camembert_base_sequence_classifier_allocine_fr.md
  docs/_posts/maziyarpanahi/2022-12-15-camembert_large_sequence_classifier_allocine_fr.md
Labels: new model

#13169 SPARKNLP-664 Adding inputColsValidation to TFNerDLGraphBuilder
  python/sparknlp/annotator/tf_ner_dl_graph_builder.py
Labels: enhancement, DON'T MERGE

#13194 SPARKNLP 680 Update sbt, sbt-assembly, and GA for Scala unit tests
  .github/workflows/build_and_test.yml
  build.sbt
  project/Dependencies.scala
  project/M2Resolvers.scala
  project/Resolvers.scala
  project/assembly.sbt
  project/build.properties
Labels: dependencies, DON'T MERGE

#13202 SPARKNLP-676 Elaborating Alphabet Error Message in EntityRuler
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/AhoCorasickAutomaton.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/er/AhoCorasickAutomatonTest.scala
Labels: enhancement, DON'T MERGE

#13218 2022-12-12-roberta_embeddings_codeberta_small_v1_co
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_base_uncased_en.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_base_uncased_sparse_85_unstructured_pruneofa_en.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_base_uncased_sparse_90_unstructured_pruneofa_en.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_bertino_it.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_indic_transformers_bn.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_indic_transformers_hi.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_indic_transformers_te.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_javanese_small_imdb_jv.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_javanese_small_jv.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_malaysian_small_ms.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_marathi_mr.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_test_text_en.md
  docs/_posts/Mary-Sci/2022-12-12-distilbert_embeddings_zwnj_base_fa.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_base_bulgarian_bg.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_base_en.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_base_indonesian_522m_id.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_codeberta_small_v1_co.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_cord19_1m7k_en.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_distil_base_en.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_fernet_news_cs.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_fernet_news_sk.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_hotelbert_de.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_hotelbert_small_de.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_indic_transformers_bn.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_indic_transformers_hi.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_indic_transformers_te.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_indo_small_id.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_javanese_small_imdb_jv.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_javanese_small_jv.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_large_en.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_legal_base_en.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_model_attribution_challenge_base_en.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_palobert_base_greek_uncased_v1_el.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_pdelobelle_robbert_v2_dutch_base_nl.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_sinhalaberto_si.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_slovakbert_sk.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_small_bulgarian_bg.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_tagalog_base_tl.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_tagalog_large_tl.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_tswanabert_tn.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_zuberta_zu.md
  docs/_posts/Mary-Sci/2022-12-12-roberta_embeddings_zwnj_base_fa.md
Labels: new model

#13219 SPARKNLP-657, SPARKNLP-673: Update install.md
  docs/en/install.md
Labels: documentation

#13224 SPARKNLP-682 Refactoring Error Handling Resource Downloader
  src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala
Labels: enhancement, DON'T MERGE

#13207 SPARKNLP-675: BigTextMatcher matches entities with overlapping definitions
  src/main/scala/com/johnsnowlabs/nlp/annotators/btm/TMEdgesReadWriter.scala
  src/test/resources/entity-extractor/test-overlapping.txt
  src/test/scala/com/johnsnowlabs/nlp/annotators/btm/BigTextMatcherTestSpec.scala
Labels: bug-fix, DON'T MERGE

#13205 SPARKNLP-678: Fix indexing issue for RegexTokenizer
  src/main/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizerTestSpec.scala
Labels: bug-fix, DON'T MERGE

#13230 2022-12-15-drug_category_mapper_en
  docs/_posts/Ahmetemintek/2022-12-15-drug_category_mapper_en.md
Labels: new model

#13226 Added content for AKS deployment
  docs/assets/images/annotation_lab/AKS-cluster-validation.png
  docs/assets/images/annotation_lab/AKS-create-k8-cluster.png
  docs/assets/images/annotation_lab/AKS-deployment.png
  docs/en/alab/install.md
Labels: documentation

#13233 2022-12-15-finner_earning_calls_specific_md_en
  docs/_posts/dcecchini/2022-12-15-finner_contraliability_en.md
  docs/_posts/dcecchini/2022-12-15-finner_earning_calls_generic_md_en.md
  docs/_posts/dcecchini/2022-12-15-finner_earning_calls_specific_md_en.md
Labels: new model

#13236 added one missing step in EKS install
  docs/en/alab/install.md
Labels: documentation

#13237 2022-12-16-legner_sigma_absa_people_en
  docs/_posts/josejuanmartinez/2022-12-16-legner_sigma_absa_people_en.md
Labels: new model

#13238 2022-12-16-legassertion_sigma_absa_sentiment_en
  docs/_posts/josejuanmartinez/2022-12-16-legassertion_sigma_absa_sentiment_en.md
Labels: new model

#13239 2022-12-16-legclf_notice_clause_en
  docs/_posts/bunyamin-polat/2022-12-16-legclf_notice_clause_en.md
Labels: new model

#13241 2022-12-16-legner_notice_clause_en
  docs/_posts/bunyamin-polat/2022-12-16-legner_notice_clause_en.md
Labels: new model

#13243 2022-12-16-legclf_survival_bert_en
  docs/_posts/dcecchini/2022-12-16-legclf_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_agreement_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_applicable_law_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_confidential_information_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_defined_terms_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_events_of_default_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_general_provisions_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_indenture_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_indenture_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_license_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_license_agreement_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_limitation_of_liability_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_limited_liability_company_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_limited_liability_company_agreement_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_management_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_management_agreement_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_registration_rights_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_registration_rights_agreement_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_representations_and_warranties_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_representations_and_warranties_of_the_company_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_stock_option_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_stock_option_agreement_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_sub_advisory_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_sub_advisory_agreement_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_successors_and_assigns_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_supplemental_indenture_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_supplemental_indenture_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_survival_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_warrant_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_warrant_agreement_en.md
Labels: new model

#13245 2022-12-17-ner_sdoh_mentions_en
  docs/_posts/Damla-Gurbaz/2022-12-17-ner_sdoh_mentions_en.md
Labels: new model

#13247 2022-12-17-legre_notice_clause_xs_en
  docs/_posts/bunyamin-polat/2022-12-17-legre_notice_clause_xs_en.md
Labels: new model

#13252 2022-12-18-meddroprof_scielowiki_es
  docs/_posts/Damla-Gurbaz/2022-12-18-bert_sequence_classifier_sdoh_community_absent_status_en.md
  docs/_posts/Damla-Gurbaz/2022-12-18-bert_sequence_classifier_sdoh_community_present_status_en.md
  docs/_posts/Damla-Gurbaz/2022-12-18-bert_sequence_classifier_sdoh_environment_status_en.md
  docs/_posts/Damla-Gurbaz/2022-12-18-drug_category_mapper_en.md
  docs/_posts/Damla-Gurbaz/2022-12-18-meddroprof_scielowiki_es.md
  docs/_posts/Damla-Gurbaz/2022-12-18-ner_sdoh_mentions_en.md
Labels: new model

#13254 2022-12-18-legclf_survival_clause_en
  docs/_posts/dcecchini/2022-12-16-legclf_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_confidential_information_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_events_of_default_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_general_provisions_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_indenture_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_representations_and_warranties_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_representations_and_warranties_of_the_company_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_stock_option_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_supplemental_indenture_bert_en.md
  docs/_posts/dcecchini/2022-12-16-legclf_warrant_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_agreement_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_applicable_law_clause_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_confidential_information_clause_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_defined_terms_clause_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_events_of_default_clause_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_general_provisions_clause_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_indenture_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_indenture_agreement_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_license_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_license_agreement_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_limitation_of_liability_clause_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_limited_liability_company_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_limited_liability_company_agreement_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_management_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_management_agreement_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_registration_rights_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_registration_rights_agreement_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_representations_and_warranties_clause_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_representations_and_warranties_of_the_company_clause_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_stock_option_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_stock_option_agreement_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_sub_advisory_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_sub_advisory_agreement_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_successors_and_assigns_clause_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_supplemental_indenture_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_supplemental_indenture_agreement_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_survival_clause_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_warrant_agreement_bert_en.md
  docs/_posts/dcecchini/2022-12-18-legclf_warrant_agreement_en.md
Labels: new model

#13259 2022-12-18-ner_sdoh_mentions_test_en
  docs/_posts/Cabir40/2022-12-18-ner_sdoh_mentions_test_en.md
Labels: new model

#13244 SPARKNLP-689 Fix inputAnnotatorTypes in TypedDependencyParser
  python/sparknlp/annotator/dependency/typed_dependency_parser.py
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
Labels: bug-fix, DON'T MERGE

#13260 SPARKNLP-693: Fix doc generation issue
  python/__init__.py
Labels: documentation, bug-fix

#13264 2022-12-20-word2vec_osf_replaced_lemmatized_legal_en
  docs/_posts/gadde5300/2022-12-20-word2vec_osf_lemmatized_legal_en.md
  docs/_posts/gadde5300/2022-12-20-word2vec_osf_raw_legal_en.md
  docs/_posts/gadde5300/2022-12-20-word2vec_osf_replaced_lemmatized_legal_en.md
  docs/_posts/gadde5300/2022-12-20-word2vec_osf_replaced_raw_legal_en.md
Labels: new model, DON'T MERGE

#13268 SPARKNLP 698 update spark/pyspark from 3.2.1 to 3.2.3
  .github/workflows/build_and_test.yml
  README.md
  docs/_includes/scripts/custom.js
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_anatomy_general_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_anatomy_granular_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_demographics_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_diagnosis_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_test_en.md
  docs/_posts/Cabir40/2022-12-18-ner_sdoh_mentions_test_en.md
  docs/_posts/Damla-Gurbaz/2022-12-18-bert_sequence_classifier_sdoh_community_absent_status_en.md
  docs/_posts/Damla-Gurbaz/2022-12-18-bert_sequence_classifier_sdoh_community_present_status_en.md
  docs/_posts/Damla-Gurbaz/2022-12-18-bert_sequence_classifier_sdoh_environment_status_en.md
  docs/_posts/Damla-Gurbaz/2022-12-18-drug_category_mapper_en.md
  docs/_posts/Damla-Gurbaz/2022-12-18-meddroprof_scielowiki_es.md
  docs/_posts/Damla-Gurbaz/2022-12-18-ner_sdoh_mentions_en.md
  docs/_posts/bunyamin-polat/2022-12-01-finclf_sec_filings_en.md
  docs/_posts/mauro-nievoff/2022-12-01-oncology_biomarker_pipeline_en.md
  docs/_posts/mauro-nievoff/2022-12-01-oncology_diagnosis_pipeline_en.md
  docs/_sass/custom.scss
  docs/en/alab/install.md
  docs/en/concepts.md
  docs/en/developers.md
  docs/en/examples.md
  docs/en/install.md
  project/Dependencies.scala
  python/README.md
  python/docs/conf.py
  scripts/colab_setup.sh
  scripts/kaggle_setup.sh
  scripts/sagemaker_setup.sh
Labels: dependencies, DON'T MERGE

#13223 Added links to Python API for licensed annotators
  docs/en/licensed_annotator_entries/AssertionDL.md
  docs/en/licensed_annotator_entries/AssertionFilterer.md
  docs/en/licensed_annotator_entries/AssertionLogReg.md
  docs/en/licensed_annotator_entries/ChunkFilterer.md
  docs/en/licensed_annotator_entries/ChunkKeyPhraseExtraction.md
  docs/en/licensed_annotator_entries/ChunkMerge.md
  docs/en/licensed_annotator_entries/ContextualParser.md
  docs/en/licensed_annotator_entries/DeIdentification.md
  docs/en/licensed_annotator_entries/DocumentLogRegClassifier.md
  docs/en/licensed_annotator_entries/DrugNormalizer.md
  docs/en/licensed_annotator_entries/FeaturesAssembler.md
  docs/en/licensed_annotator_entries/GenericClassifier.md
  docs/en/licensed_annotator_entries/IOBTagger.md
  docs/en/licensed_annotator_entries/NerChunker.md
  docs/en/licensed_annotator_entries/NerConverterInternal.md
  docs/en/licensed_annotator_entries/NerDisambiguator.md
  docs/en/licensed_annotator_entries/NerModel.md
  docs/en/licensed_annotator_entries/RENerChunksFilter.md
  docs/en/licensed_annotator_entries/ReIdentification.md
  docs/en/licensed_annotator_entries/RelationExtraction.md
  docs/en/licensed_annotator_entries/RelationExtractionDL.md
  docs/en/licensed_annotator_entries/SentenceEntityResolver.md
Labels: documentation

#13280 Removed duplicated method definition (ContextSpellCheckerApproach)
  python/sparknlp/annotator/spell_check/context_spell_checker.py
Labels: enhancement, bug-fix

#13282 SPARKNLP-703 Fix Finisher outputAnnotatorType Issue
  python/sparknlp/base/light_pipeline.py
  python/sparknlp/internal/annotator_transformer.py
  python/test/pretrained/pretrained_pipeline_test.py
Labels: bug-fix, DON'T MERGE

#13283 SPARKNLP-667: Fix indexing issue for custom pattern
  src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: bug-fix, DON'T MERGE

#13284 SPARKNLP-708 Enabling Embeddings output in LightPipeline.fullAnnotate
  python/sparknlp/annotation.py
  python/sparknlp/base/light_pipeline.py
  python/test/base/light_pipeline_test.py
  src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
  src/test/scala/com/johnsnowlabs/nlp/LightPipelineTestSpec.scala
Labels: bug-fix, DON'T MERGE

#13291 SPARKNLP-667: Added try-catch block for custom pattern/char
  src/main/scala/com/johnsnowlabs/nlp/annotators/TokenizerModel.scala
Labels: enhancement
