Repository JohnSnowLabs/spark-nlp, pull requests merged in 2022-11, with the labels that each got.

#13013 2022-11-01-finner_sec_dates_en
  docs/_posts/josejuanmartinez/2022-11-01-finner_sec_dates_en.md
Labels: new model

#13014 2022-11-01-finre_acquisitions_subsidiaries_md_en
  docs/_posts/josejuanmartinez/2022-11-01-finre_acquisitions_subsidiaries_md_en.md
Labels: new model

#13005 2022-10-30-abbreviation_mapper_augmented_en
  docs/_posts/Ahmetemintek/2022-10-30-abbreviation_mapper_augmented_en.md
Labels: new model

#13017 2022-11-02-icd10cm_resolver_pipeline_en
  docs/_posts/Ahmetemintek/2022-11-02-icd10cm_resolver_pipeline_en.md
Labels: new model

#13016 Updating s3 link for dependency_conllu model
  docs/_posts/danilojsl/2022-06-29-dependency_conllu_en_3_0.md
Labels: documentation, models_hub

#13018 2022-11-02-finclf_acquisitions_item_en
  docs/_posts/josejuanmartinez/2022-11-02-finclf_acquisitions_item_en.md
  docs/_posts/josejuanmartinez/2022-11-02-finclf_work_experience_item_en.md
Labels: new model

#13019 2022-11-02-finre_work_experience_md_en
  docs/_posts/bunyamin-polat/2022-11-02-finre_work_experience_md_en.md
Labels: new model

#13021 2022-11-02-legre_contract_doc_parties_md_en
  docs/_posts/bunyamin-polat/2022-11-02-legre_contract_doc_parties_md_en.md
Labels: new model

#13028 2022-11-03-legre_obligations_md_en
  docs/_posts/bunyamin-polat/2022-11-03-legre_obligations_md_en.md
Labels: new model

#13029 2022-11-03-finclf_acquisitions_item_en
  docs/_posts/josejuanmartinez/2022-11-03-finclf_acquisitions_item_en.md
  docs/_posts/josejuanmartinez/2022-11-03-finclf_work_experience_item_en.md
Labels: new model

#13031 2022-11-03-oncology_general_pipeline_en
  docs/_posts/mauro-nievoff/2022-11-03-oncology_general_pipeline_en.md
Labels: new model

#13034 Docs/alab update documentation 410
  docs/_data/navigation.yml
  docs/assets/images/annotation_lab/4.2.0/before_after.png
  docs/assets/images/annotation_lab/4.2.0/benchmarking.png
  docs/assets/images/annotation_lab/4.2.0/clusters.png
  docs/assets/images/annotation_lab/4.2.0/search.png
  docs/assets/images/annotation_lab/4.2.0/training_logs.png
  docs/en/alab/models.md
  docs/en/alab/models_hub.md
  docs/en/alab/project_creation.md
  docs/en/alab/rules.md
  docs/en/alab/training_configurations.md
Labels: documentation

#13035 SPARKNLP 643 detecting spark version in a safer way
  python/sparknlp/internal/extended_java_wrapper.py
Labels: bug-fix

#13037 2022-11-04-finre_acquisitions_subsidiary_md_en
  docs/_posts/josejuanmartinez/2022-11-04-finre_acquisitions_subsidiary_md_en.md
Labels: new model

#13040 2022-11-04-finclf_auditor_sentiment_analysis_en
  docs/_posts/josejuanmartinez/2022-11-04-finclf_auditor_sentiment_analysis_en.md
Labels: new model

#13043 2022-11-07-finre_financial_small_en
  docs/_posts/josejuanmartinez/2022-11-07-finre_financial_small_en.md
Labels: new model

#13027 Bump model card Spark NLP HC version to 4.2.1
  docs/_posts/Ahmetemintek/2022-10-12-cvx_code_mapper_en.md
  docs/_posts/Ahmetemintek/2022-10-12-cvx_name_mapper_en.md
  docs/_posts/Ahmetemintek/2022-10-12-cvx_resolver_pipeline_en.md
  docs/_posts/Ahmetemintek/2022-10-12-sbiobertresolve_cvx_en.md
  docs/_posts/mauro-nievoff/2022-10-01-ner_oncology_biomarker_wip_en.md
Labels: documentation, models_hub

#13032 SPARKNLP-642: Fix indexing issue for regex splits without space
  src/main/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizerTestSpec.scala
Labels: bug-fix, DON'T MERGE

#13001 Serializable Issue K8s Word Embeddings
  src/main/scala/com/johnsnowlabs/storage/BytesKey.java
Labels: bug-fix, DON'T MERGE

#13047 2022-11-08-finre_work_experience_md_en
  docs/_posts/josejuanmartinez/2022-11-08-finre_work_experience_md_en.md
Labels: new model

#13050 2022-11-08-finre_acquisitions_subsidiaries_md_en
  docs/_posts/josejuanmartinez/2022-11-08-finre_acquisitions_subsidiaries_md_en.md
Labels: new model

#13052 2022-11-08-finre_work_experience_md_en
  docs/_posts/josejuanmartinez/2022-11-08-finre_work_experience_md_en.md
Labels: new model

#13054 2022-11-09-legner_termination_en
  docs/_posts/josejuanmartinez/2022-11-09-legner_termination_en.md
Labels: new model

#13055 2022-11-09-legclf_cuad_termination_clause_en
  docs/_posts/josejuanmartinez/2022-11-09-legclf_cuad_termination_clause_en.md
Labels: new model

#13063 2022-11-10-finclf_indian_news_sentiment_medium_en
  docs/_posts/gadde5300/2022-11-10-finclf_indian_news_sentiment_en.md
  docs/_posts/gadde5300/2022-11-10-finclf_indian_news_sentiment_medium_en.md
Labels: new model

#13057 2022-11-09-legre_confidentiality_md_en
  docs/_posts/gadde5300/2022-11-09-legre_confidentiality_md_en.md
  docs/_posts/gadde5300/2022-11-09-legre_grants_md_en.md
  docs/_posts/gadde5300/2022-11-09-legre_indemnifications_md_en.md
  docs/_posts/gadde5300/2022-11-09-legre_whereas_md_en.md
  docs/_posts/gadde5300/2022-11-10-legclf_judgement_de.md
  docs/_posts/gadde5300/2022-11-10-legclf_judgement_medium_de.md
Labels: new model

#13048 Fix a bug in Vision Transformer annotator that results in NaNs for some models
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowViTClassifier.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/ViTForImageClassification.scala
Labels: bug-fix

#13053 Bug fix and enhancements for CoNLLGenerator annotator
  python/sparknlp/internal/__init__.py
  python/sparknlp/util.py
  python/test/annotator/conll_generator_test.py
  src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala
  src/test/resources/conllgenerator/conllgenerator_nonint_token_metadata.parquet/part-00000-dcc1011a-9618-40ca-884c-f8456a8c9351-c000.snappy.parquet
  src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorBatchNERDLTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala
Labels: enhancement, bug-fix, DON'T MERGE

#13060 SPARKNLP-621: Add string support to RegexMatcher in addition to a file
  docs/en/annotator_entries/RegexMatcher.md
  docs/en/annotators.md
  python/sparknlp/annotator/matcher/regex_matcher.py
  python/test/annotator/matcher/regex_matcher_test.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/RegexMatcher.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RegexMatcherBehaviors.scala
Labels: enhancement, new-feature

#13061 Add ScalaDoc for IAnnotation
  src/main/scala/com/johnsnowlabs/nlp/IAnnotation.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/ViTImageClassificationTestSpec.scala
Labels: documentation

#13066 2022-11-10-legclf_contribution_agreement_en
  docs/_posts/gadde5300/2022-11-10-legclf_contribution_agreement_en.md
  docs/_posts/gadde5300/2022-11-10-legclf_custodian_agreement_en.md
  docs/_posts/gadde5300/2022-11-10-legclf_exchange_agreement_en.md
  docs/_posts/gadde5300/2022-11-10-legclf_general_distribution_agreement_en.md
  docs/_posts/gadde5300/2022-11-10-legclf_guarantee_agreement_en.md
  docs/_posts/gadde5300/2022-11-10-legclf_intercreditor_agreement_en.md
  docs/_posts/gadde5300/2022-11-10-legclf_master_repurchase_agreement_en.md
  docs/_posts/gadde5300/2022-11-10-legclf_pledge_and_security_agreement_en.md
  docs/_posts/gadde5300/2022-11-10-legclf_share_exchange_agreement_en.md
  docs/_posts/gadde5300/2022-11-10-legclf_terms_agreement_en.md
Labels: new model

#13068 2022-11-10-legner_romanian_official_lg_ro
  docs/_posts/bunyamin-polat/2022-11-10-legner_romanian_official_lg_ro.md
Labels: new model

#13071 2022-11-10-legclf_asset_purchase_agreement_en
  docs/_posts/bunyamin-polat/2022-11-10-legclf_asset_purchase_agreement_en.md
Labels: new model

#13072 2022-11-10-legclf_distribution_agreement_en
  docs/_posts/bunyamin-polat/2022-11-10-legclf_distribution_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-10-legclf_executive_employment_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-10-legclf_indemnification_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-10-legclf_loan_and_security_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-10-legclf_participation_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-10-legclf_securities_purchase_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-10-legclf_security_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-10-legclf_stock_purchase_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-10-legclf_subscription_agreement_en.md
Labels: new model

#13073 2022-11-10-legclf_agreement_and_declaration_en
  docs/_posts/gokhanturer/2022-11-10-legclf_agreement_and_declaration_en.md
  docs/_posts/gokhanturer/2022-11-10-legclf_control_agreement_en.md
  docs/_posts/gokhanturer/2022-11-10-legclf_equity_distribution_agreement_en.md
  docs/_posts/gokhanturer/2022-11-10-legclf_exclusive_license_agreement_en.md
  docs/_posts/gokhanturer/2022-11-10-legclf_investment_subadvisory_agreement_en.md
  docs/_posts/gokhanturer/2022-11-10-legclf_limited_partnership_agreement_en.md
  docs/_posts/gokhanturer/2022-11-10-legclf_master_lease_agreement_en.md
  docs/_posts/gokhanturer/2022-11-10-legclf_stockholder_agreement_en.md
  docs/_posts/gokhanturer/2022-11-10-legclf_sublease_agreement_en.md
  docs/_posts/gokhanturer/2022-11-10-legclf_transition_services_agreement_en.md
Labels: new model

#13076 2022-11-11-legclf_sbert_cuad_termination_clause_en
  docs/_posts/josejuanmartinez/2022-11-11-legclf_sbert_cuad_termination_clause_en.md
Labels: new model

#13085 2022-11-15-longformer_legal_embeddings_es
  docs/_posts/gadde5300/2022-11-15-longformer_legal_embeddings_es.md
Labels: new model

#13088 2022-11-15-ner_sdoh_slim_wip_en
  docs/_posts/gokhanturer/2022-11-15-ner_sdoh_slim_wip_en.md
Labels: new model

#13090 2022-11-15-word2vec_cbow_legal_d100_cased_es
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d100_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d100_uncased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d300_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d300_uncased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d50_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d50_uncased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d100_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d100_uncased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d300_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d300_uncased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d50_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d50_uncased_es.md
Labels: new model

#13093 2022-11-16-legclf_administration_agreement_en
  docs/_posts/bunyamin-polat/2022-11-16-legclf_administration_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-16-legclf_joint_filing_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-16-legclf_letter_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-16-legclf_note_purchase_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-16-legclf_operating_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-16-legclf_rights_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-16-legclf_separation_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-16-legclf_settlement_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-16-legclf_trust_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-16-legclf_voting_agreement_en.md
Labels: new model

#13095 2022-11-16-abbreviation_category_mapper_en
  docs/_posts/Ahmetemintek/2022-11-16-abbreviation_category_mapper_en.md
Labels: new model

#13097 added languages
  docs/_posts/2020-09-14-sentence_detector_dl_xx.md
Labels: documentation, models_hub

#13098 2022-11-16-legclf_employee_benefit_plans_md_en
  docs/_posts/josejuanmartinez/2022-11-16-legclf_employee_benefit_plans_md_en.md
  docs/_posts/josejuanmartinez/2022-11-16-legclf_grievance_procedure_md_en.md
  docs/_posts/josejuanmartinez/2022-11-16-legclf_indemnification_and_contribution_md_en.md
  docs/_posts/josejuanmartinez/2022-11-16-legclf_indemnification_md_en.md
  docs/_posts/josejuanmartinez/2022-11-16-legclf_method_of_payment_md_en.md
  docs/_posts/josejuanmartinez/2022-11-16-legclf_power_of_attorney_md_en.md
  docs/_posts/josejuanmartinez/2022-11-16-legclf_termination_md_en.md
  docs/_posts/josejuanmartinez/2022-11-16-legclf_whereas_md_en.md
Labels: new model

#13101 2022-11-17-legclf_introduction_clause_en
  docs/_posts/josejuanmartinez/2022-11-17-legclf_introduction_clause_en.md
Labels: new model

#13103 2022-11-17-legclf_cuad_signers_clause_en
  docs/_posts/josejuanmartinez/2022-11-17-legclf_cuad_signers_clause_en.md
Labels: new model

#13104 Docs/alab 4.3.0
  docs/en/alab/export.md
  docs/en/alab/install.md
  docs/en/alab/project_configuration.md
  docs/en/alab/user_management.md
Labels: documentation

#13105 Added content for installation in OpenShift
  docs/assets/images/annotation_lab/Create-Instance.png
  docs/assets/images/annotation_lab/Define-Hostname.png
  docs/assets/images/annotation_lab/Define-StorageClass.png
  docs/assets/images/annotation_lab/Install-Operator.png
  docs/assets/images/annotation_lab/Select-Operator.png
  docs/assets/images/annotation_lab/View-Resources.png
  docs/en/alab/install.md
Labels: documentation

#13118 2022-11-21-legner_dates_sm_en
  docs/_posts/josejuanmartinez/2022-11-21-legner_dates_sm_en.md
Labels: new model

#13117 2022-11-21-roberta_base_bne_conll_ner_spark_nlp_es
  docs/_posts/cayorodriguez/2022-11-21-roberta_base_bne_conll_ner_spark_nlp_es.md
Labels: new model

#13119 Models hub
  docs/_posts/cayorodriguez/2022-11-21-roberta_base_bne_conll_ner_spark_nlp_es.md
  docs/_posts/gadde5300/2022-11-15-longformer_legal_embeddings_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d100_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d100_uncased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d300_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d300_uncased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d50_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_cbow_legal_d50_uncased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d100_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d100_uncased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d300_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d300_uncased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d50_cased_es.md
  docs/_posts/gadde5300/2022-11-15-word2vec_skipgram_legal_d50_uncased_es.md
  docs/_posts/josejuanmartinez/2022-10-20-legal_longformer_base_en.md
Labels: models_hub, new model

#13120 2022-11-21-legclf_dates_sm_en
  docs/_posts/josejuanmartinez/2022-11-21-legclf_dates_sm_en.md
Labels: new model

#13113 2022-11-18-kegg_disease_mapper_en
  docs/_posts/Ahmetemintek/2022-11-18-kegg_disease_mapper_en.md
  docs/_posts/Ahmetemintek/2022-11-21-kegg_drug_mapper_en.md
Labels: new model

#13122 2022-11-22-pipeline_bsc_roberta_base_bne_es
  docs/_posts/cayorodriguez/2022-11-22-pipeline_bsc_roberta_base_bne_es.md
Labels: new model

#13115 Added content for healthcare nlp integration
  docs/_data/navigation.yml
  docs/en/alab/healthcare.md
Labels: documentation

#13116 Added some content for troubleshooting section
  docs/_data/navigation.yml
  docs/en/alab/troubleshooting.md
Labels: documentation

#13128 2022-11-23-finsum_news_lg_spark_nlp_eo
  docs/_posts/josejuanmartinez/2022-11-23-finsum_news_lg_spark_nlp_eo.md
Labels: new model

#13130 2022-11-23-finsum_news_lg_spark_nlp_en
  docs/_posts/josejuanmartinez/2022-11-23-finsum_news_lg_spark_nlp_en.md
Labels: new model

#13132 2022-11-23-finsum_news_xs_en
  docs/_posts/josejuanmartinez/2022-11-23-finsum_news_xs_en.md
Labels: new model

#13134 2022-11-23-finsum_news_headers_md_en
  docs/_posts/josejuanmartinez/2022-11-23-finsum_news_headers_md_en.md
Labels: new model

#13136 2022-11-24-finsum_news_headers_lg_en
  docs/_posts/josejuanmartinez/2022-11-24-finsum_news_headers_lg_en.md
Labels: new model

#13137 2022-11-24-legclf_administration_agreement_en
  docs/_posts/bunyamin-polat/2022-11-24-legclf_administration_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-24-legclf_joint_filing_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-24-legclf_letter_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-24-legclf_note_purchase_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-24-legclf_operating_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-24-legclf_rights_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-24-legclf_separation_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-24-legclf_settlement_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-24-legclf_trust_agreement_en.md
  docs/_posts/bunyamin-polat/2022-11-24-legclf_voting_agreement_en.md
Labels: new model

#13138 2022-11-24-finclf_earning_broker_10k_en
  docs/_posts/josejuanmartinez/2022-11-24-finclf_earning_broker_10k_en.md
Labels: new model

#13145 2022-11-24-finsum_news_md_en
  docs/_posts/josejuanmartinez/2022-11-24-finsum_news_md_en.md
Labels: new model

#13139 2022-11-24-ner_oncology_anatomy_general_en
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_anatomy_general_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_anatomy_granular_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_biomarker_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_demographics_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_diagnosis_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_posology_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_response_to_treatment_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_test_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_therapy_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_tnm_en.md
  docs/_posts/Ahmetemintek/2022-11-24-ner_oncology_unspecific_posology_en.md
Labels: new model

#13148 2022-11-25-legclf_introduction_clause_cuad_en
  docs/_posts/josejuanmartinez/2022-11-25-legclf_introduction_clause_cuad_en.md
Labels: new model

#13149 2022-11-25-legclf_employee_benefit_plans_md_en
  docs/_posts/josejuanmartinez/2022-11-25-legclf_employee_benefit_plans_md_en.md
  docs/_posts/josejuanmartinez/2022-11-25-legclf_grievance_procedure_md_en.md
  docs/_posts/josejuanmartinez/2022-11-25-legclf_indemnification_and_contribution_md_en.md
  docs/_posts/josejuanmartinez/2022-11-25-legclf_indemnification_md_en.md
  docs/_posts/josejuanmartinez/2022-11-25-legclf_method_of_payment_md_en.md
  docs/_posts/josejuanmartinez/2022-11-25-legclf_power_of_attorney_md_en.md
  docs/_posts/josejuanmartinez/2022-11-25-legclf_termination_md_en.md
  docs/_posts/josejuanmartinez/2022-11-25-legclf_whereas_md_en.md
Labels: new model

#13147 2022-11-25-legclf_vacancies_clause_en
  docs/_posts/gadde5300/2022-11-25-legclf_additional_covenants_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_bulletin_boards_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_conversion_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_delays_or_omissions_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_escrow_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_exclusive_remedy_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_expenses_indemnity_damage_waiver_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_expiration_date_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_formation_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_hazardous_materials_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_indemnification_and_insurance_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_leave_of_absence_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_limitation_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_non_contravention_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_ofac_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_opinions_of_counsel_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_other_definitions_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_paid_holidays_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_prepayment_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_register_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_risk_of_loss_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_subcontracting_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_third_party_rights_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_vacancies_clause_en.md
  docs/_posts/gadde5300/2022-11-25-legclf_w_i_t_n_e_s_s_e_t_h_clause_en.md
Labels: new model

#13150 2022-11-25-legclf_cuad_whereas_clause_en
  docs/_posts/josejuanmartinez/2022-11-25-legclf_cuad_whereas_clause_en.md
Labels: new model

#13151 2022-11-26-longformer_legal_base_8192_es
  docs/_posts/gadde5300/2022-11-26-longformer_legal_base_8192_es.md
Labels: new model

#13108 SPARKNLP-656 & SPARKNLP-657: Updated Documentation
  docs/en/annotator_entries/ClassifierDL.md
  docs/en/annotator_entries/MultiClassifierDL.md
  docs/en/annotator_entries/NerDL.md
  docs/en/annotator_entries/SentimentDL.md
  docs/en/install.md
  python/sparknlp/annotator/classifier_dl/classifier_dl.py
  python/sparknlp/annotator/classifier_dl/multi_classifier_dl.py
  python/sparknlp/annotator/classifier_dl/sentiment_dl.py
  python/sparknlp/annotator/ner/ner_dl.py
  python/sparknlp/annotator/param/evaluation_dl_params.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MultiClassifierDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/param/EvaluationDLParams.scala
Labels: enhancement, documentation, DON'T MERGE

#13112 SPARKNLP-661: Add missing setPreservePosition in NerConverter
  python/sparknlp/annotator/ner/ner_converter.py
  python/sparknlp/common/annotator_properties.py
  python/test/annotator/ner/ner_converter_test.py
Labels: bug-fix, DON'T MERGE

#13141 SPARKNLP-620 Provide GCP Support for Cache Folder
  build.sbt
  project/Dependencies.scala
  project/plugins.sbt
  src/main/scala/com/johnsnowlabs/client/gcp/GCPGateway.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
  src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
Labels: new-feature, DON'T MERGE

#13152 SPARKNLP-665 Updating to TensorFlow 2.7.4
  project/Dependencies.scala
Labels: enhancement, DON'T MERGE

#13153 SPARKNLP-671 incorporate the exception into the error message
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
Labels: enhancement, DON'T MERGE

#13157 2022-11-28-legclf_cuad_obligations_clause_en
  docs/_posts/josejuanmartinez/2022-11-28-legclf_cuad_obligations_clause_en.md
Labels: new model

#13158 2022-11-28-legclf_cuad_confidentiality_clause_en
  docs/_posts/josejuanmartinez/2022-11-28-legclf_cuad_confidentiality_clause_en.md
Labels: new model

#13159 2022-11-28-t5_grammar_error_corrector_en
  docs/_posts/maziyarpanahi/2022-11-28-t5_grammar_error_corrector_en.md
Labels: new model

#13160 Models hub
  docs/_posts/gadde5300/2022-11-26-longformer_legal_base_8192_es.md
  docs/_posts/maziyarpanahi/2022-11-28-t5_grammar_error_corrector_en.md
Labels: new model

#13161 2022-11-28-finre_earning_calls_sm_en
  docs/_posts/josejuanmartinez/2022-11-28-finre_earning_calls_sm_en.md
Labels: new model

#13170 2022-11-30-legner_force_majeure_en
  docs/_posts/josejuanmartinez/2022-11-30-legner_force_majeure_en.md
Labels: new model

#13172 2022-11-30-finner_german_financial_entities_de
  docs/_posts/gadde5300/2022-11-30-finner_german_financial_entities_de.md
Labels: new model

#13174 2022-11-30-finner_earning_calls_specific_sm_en
  docs/_posts/dcecchini/2022-11-30-finner_earning_calls_generic_sm_en.md
  docs/_posts/dcecchini/2022-11-30-finner_earning_calls_specific_sm_en.md
  docs/_posts/dcecchini/2022-11-30-finner_financial_xlarge_en.md
Labels: new model
