Repository JohnSnowLabs/spark-nlp, pull requests merged in 2023-02, with the labels that each got.

#13450 2023-02-01-finner_capital_calls_en
  docs/_posts/josejuanmartinez/2023-02-01-finner_capital_calls_en.md
Labels: new model

#13447 Sparknlp 736 Implement Date2Chunk annotator
  python/sparknlp/annotator/token/__init__.py
  python/sparknlp/base/__init__.py
  python/sparknlp/base/date2_chunk.py
  python/sparknlp/base/token2_chunk.py
  python/test/annotator/date2_chunk_test.py
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/Date2Chunk.scala
  src/test/scala/com/johnsnowlabs/nlp/Date2ChunkTestSpec.scala
Labels: new-feature, DON'T MERGE

#13432 SPARKNLP-733: Fix loadSavedModel for private buckets
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
  src/test/scala/com/johnsnowlabs/util/ResourceHelperTestSpec.scala
Labels: bug-fix

#13460 2023-02-02-legclf_sales_agreement_bert_en
  docs/_posts/Mary-Sci/2023-02-02-legclf_acquisition_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-02-02-legclf_forbearance_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-02-02-legclf_limited_liability_company_operating_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-02-02-legclf_nonstatutory_stock_option_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-02-02-legclf_private_placement_warrants_purchase_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-02-02-legclf_sales_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-02-02-legclf_second_supplemental_indenture_bert_en.md
  docs/_posts/Mary-Sci/2023-02-02-legclf_stock_pledge_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-02-02-legclf_subordination_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-02-02-legclf_third_supplemental_indenture_bert_en.md
Labels: new model

#13462 2023-02-02-legmulticlf_mnda_sections_en
  docs/_posts/josejuanmartinez/2023-02-02-legmulticlf_mnda_sections_en.md
Labels: new model

#13461 2023-02-02-legpipe_ner_contract_doc_parties_alias_former_en
  docs/_posts/gadde5300/2023-02-02-legpipe_ner_contract_doc_parties_alias_former_en.md
Labels: new model

#13463 2023-02-03-finclf_customer_service_category_en
  docs/_posts/bunyamin-polat/2023-02-03-finclf_customer_service_category_en.md
Labels: new model

#13465 2023-02-03-finclf_customer_service_intent_type_en
  docs/_posts/bunyamin-polat/2023-02-03-finclf_customer_service_intent_type_en.md
Labels: new model

#13466 2023-02-03-finmulticlf_customer_service_lin_features_en
  docs/_posts/bunyamin-polat/2023-02-03-finmulticlf_customer_service_lin_features_en.md
Labels: new model

#13471 2023-02-04-finner_finance_chinese_sm_zh
  docs/_posts/dcecchini/2023-02-04-finner_finance_chinese_sm_zh.md
Labels: new model

#13410 Doc id conll reader
  python/sparknlp/training/conll.py
  python/test/training/__init__.py
  python/test/training/conll_test.py
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
  src/test/resources/conll/test_conll_docid.txt
  src/test/scala/com/johnsnowlabs/nlp/training/CoNLLTestSpec.scala
Labels: new-feature, DON'T MERGE

#13474 SPARKNLP-737: ZeroShotNer Notebook
  docs/en/transformer_entries/ZeroShotNer.md
  examples/bak2.Text_Preprocessing_with_SparkNLP_Annotators_Transformers.ipynb
  examples/bak3.SparkNLP_Pretrained_Models.ipynb
  examples/bakSentenceDetectorDL.ipynb
  examples/python/annotation/text/english/named-entity-recognition/ZeroShot_NER.ipynb
  python/sparknlp/annotator/ner/zero_shot_ner_model.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/ZeroShotNerModel.scala
Labels: documentation

#13476 Sparknlp 740 rename refactor m 1 to silicon
  README.md
  build.sbt
  project/Dependencies.scala
  python/README.md
  python/sparknlp/__init__.py
  src/main/scala/com/johnsnowlabs/nlp/MultiDocumentAssembler.scala
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/audio/HubertForCTC.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/audio/Wav2Vec2ForCTC.scala
  src/main/scala/com/johnsnowlabs/nlp/training/CoNLL.scala
  src/test/scala/com/johnsnowlabs/nlp/training/CoNLLTestSpec.scala
Labels: documentation, new-feature, DON'T MERGE

#13481 2023-02-07-asr_hubert_large_ls960_en
  docs/_posts/maziyarpanahi/2023-02-07-asr_hubert_large_ls960_en.md
  docs/_posts/maziyarpanahi/2023-02-07-image_classifier_swin_base_patch4_window12_384_in22k_en.md
  docs/_posts/maziyarpanahi/2023-02-07-image_classifier_swin_base_patch4_window7_224_en.md
  docs/_posts/maziyarpanahi/2023-02-07-image_classifier_swin_base_patch4_window7_224_in22k_en.md
  docs/_posts/maziyarpanahi/2023-02-07-image_classifier_swin_tiny_patch4_window7_224_en.md
Labels: new model

#13454 2023-02-01-ner_eu_clinical_case_es
  docs/_posts/gpirge/2023-02-01-ner_eu_clinical_case_es.md
  docs/_posts/gpirge/2023-02-01-ner_eu_clinical_case_fr.md
  docs/_posts/gpirge/2023-02-02-ner_eu_clinical_case_eu.md
  docs/_posts/gpirge/2023-02-06-ner_eu_clinical_condition_en.md
  docs/_posts/gpirge/2023-02-06-ner_eu_clinical_condition_es.md
  docs/_posts/gpirge/2023-02-06-ner_eu_clinical_condition_eu.md
  docs/_posts/gpirge/2023-02-06-ner_eu_clinical_condition_fr.md
  docs/_posts/gpirge/2023-02-06-ner_eu_clinical_condition_it.md
Labels: new model

#13483 2023-02-08-camembert_base_qa_fquad_fr
  docs/_posts/maziyarpanahi/2023-02-08-camembert_base_qa_fquad_fr.md
Labels: new model

#13485 2023-02-08-legclf_nda_agreements_en
  docs/_posts/josejuanmartinez/2023-02-08-legclf_nda_agreements_en.md
Labels: new model

#13486 2023-02-08-zero_shot_ner_roberta_en
  docs/_posts/maziyarpanahi/2023-02-08-zero_shot_ner_roberta_en.md
Labels: new model

#13488 2023-02-09-legmulticlf_mnda_sections_other_en
  docs/_posts/josejuanmartinez/2023-02-09-legmulticlf_mnda_sections_other_en.md
Labels: new model

#13493 2023-02-09-rxnorm_drug_brandname_mapper_en
  docs/_posts/Ahmetemintek/2023-02-09-rxnorm_drug_brandname_mapper_en.md
Labels: new model

#13496 2023-02-10-ner_sdoh_social_environment_wip_en
  docs/_posts/Meryem1425/2023-02-10-ner_sdoh_demographics_wip_en.md
  docs/_posts/Meryem1425/2023-02-10-ner_sdoh_income_social_status_wip_en.md
  docs/_posts/Meryem1425/2023-02-10-ner_sdoh_social_environment_wip_en.md
Labels: new model

#13498 Docs/playground prompts
  docs/_data/navigation.yml
  docs/en/alab/playground.md
  docs/en/alab/prompts.md
  docs/en/alab/rules.md
Labels: documentation

#13507 2023-02-11-ner_sdoh_wip_en
  docs/_posts/Meryem1425/2023-02-11-ner_sdoh_wip_en.md
Labels: new model

#13514 2023-02-13-legclf_names_of_parties_clause_en
  docs/_posts/Mary-Sci/2023-02-13-legclf_applic_law_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_assignment_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_def_of_conf_info_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_dispute_resol_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_exceptions_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_names_of_parties_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_non_comp_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_non_solic_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_permitted_use_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_preamble_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_remedies_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_req_discl_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_restricted_use_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_return_of_conf_info_clause_en.md
  docs/_posts/Mary-Sci/2023-02-13-legclf_termination_clause_en.md
Labels: new model

#13405 Update licensed docs
  .gitignore
  docs/en/licensed_annotator_entries/AssertionChunkConverter.md
  docs/en/licensed_annotator_entries/EntityChunkEmbeddings.md
  docs/en/licensed_annotator_entries/NerConverterInternal.md
  docs/en/licensed_annotator_entries/RENerChunksFilter.md
  docs/en/licensed_annotator_entries/RelationExtraction.md
  python/sparknlp/annotator/spell_check/context_spell_checker.py
Labels: documentation

#13518 2023-02-16-tabform_v1_en
  docs/_posts/kolia1985/2023-02-16-tabform_v1_en.md
Labels: new model

#13520 2023-02-16-roberta_base_irish_legal_gle
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_bulgarian_legal_bul.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_czech_legal_cs.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_dutch_legal_nl.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_finnish_legal_fi.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_greek_legal_el.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_hungarian_legal_hu.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_irish_legal_gle.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_latvian_legal_lv.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_lithuanian_legal_lt.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_maltese_legal_mt.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_polish_legal_pl.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_portuguese_legal_pt.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_romanian_legal_ro.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_large_french_legal_fr.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_large_italian_legal_it.md
Labels: new model

#13525 2023-02-16-legsum_proposal_en
  docs/_posts/bunyamin-polat/2023-02-16-legsum_proposal_en.md
  docs/_posts/bunyamin-polat/2023-02-17-legclf_proposal_topic_en.md
Labels: new model

#13524 2023-02-16-finclf_capital_call_notices_en
  docs/_posts/bunyamin-polat/2023-02-16-finclf_capital_call_notices_en.md
Labels: new model

#13523 2023-02-16-roberta_base_croatian_legal_hr
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_croatian_legal_hr.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_danish_legal_da.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_estonian_legal_et.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_french_legal_fr.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_italian_legal_it.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_spanish_legal_es.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_base_swiss_legal_gsw.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_large_german_legal_de.md
  docs/_posts/Mary-Sci/2023-02-16-roberta_large_swiss_legal_gsw.md
Labels: new model

#13526 2023-02-17-legclf_bert_support_proposal_en
  docs/_posts/bunyamin-polat/2023-02-17-legclf_bert_support_proposal_en.md
Labels: new model

#13528 2023-02-17-legre_contract_doc_parties_lg_en
  docs/_posts/gadde5300/2023-02-17-legre_contract_doc_parties_lg_en.md
Labels: new model

#13529 2023-02-17-roberta_base_english_legal_en
  docs/_posts/Mary-Sci/2023-02-17-roberta_base_english_legal_en.md
  docs/_posts/Mary-Sci/2023-02-17-roberta_base_slovak_legal_sk.md
  docs/_posts/Mary-Sci/2023-02-17-roberta_base_swedish_legal_se.md
Labels: new model

#13530 2023-02-17-roberta_large_english_legal_en
  docs/_posts/Mary-Sci/2023-02-17-roberta_large_english_legal_en.md
Labels: new model

#13532 2023-02-17-legpipe_re_contract_doc_parties_alias_en
  docs/_posts/gadde5300/2023-02-17-legpipe_re_contract_doc_parties_alias_en.md
Labels: new model

#13522 2023-02-16-finclf_bert_broker_reports_suggested_actions_en
  docs/_posts/gadde5300/2023-02-16-finclf_bert_broker_reports_suggested_actions_en.md
Labels: new model

#13545 Docs/prepaid lib product
  docs/en/license_getting_started.md
  docs/en/licensed_install.md
Labels: documentation

#13550 2023-02-21-bert_embeddings_legalbert_adept_en
  docs/_posts/gadde5300/2023-02-21-bert_embeddings_legalbert_adept_en.md
  docs/_posts/gadde5300/2023-02-21-bert_embeddings_lsg16k_Italian_Legal_it.md
Labels: new model

#13552 2023-02-22-legpipe_deid_en
  docs/_posts/josejuanmartinez/2023-02-22-legpipe_deid_en.md
Labels: new model

#13554 2023-02-22-ndc_drug_brandname_mapper_en
  docs/_posts/Ahmetemintek/2023-02-22-ndc_drug_brandname_mapper_en.md
  docs/_posts/Ahmetemintek/2023-02-22-sbiobertresolve_rxnorm_nih_en.md
  docs/_posts/Ahmetemintek/2023-02-23-rxnorm_nih_mapper_en.md
Labels: new model

#13510 SPARKNLP-743: Add parameter to SparkNLP.start
  python/sparknlp/__init__.py
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/test/java/com/johnsnowlabs/nlp/GeneralAnnotationsTest.java
  src/test/scala/com/johnsnowlabs/nlp/SparkNLPTestSpec.scala
Labels: new-feature, DON'T MERGE

#13515 SPARKNLP-735 Adding SpacyToAnnotation component
  python/sparknlp/training/__init__.py
  python/sparknlp/training/spacy_to_annotation.py
  python/test/training/spacy_to_annotation_test.py
  src/main/scala/com/johnsnowlabs/nlp/training/SpacyToAnnotation.scala
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
  src/test/resources/spacy-to-annotation/multi_doc_tokens.json
  src/test/resources/spacy-to-annotation/without_sentence_ends.json
  src/test/scala/com/johnsnowlabs/nlp/training/SpacyToAnnotationFixture.scala
  src/test/scala/com/johnsnowlabs/nlp/training/SpacyToAnnotationTest.scala
Labels: Feature request, new-feature, DON'T MERGE

#13551 2023-02-21-ieeeBERT_en
  docs/_posts/Zhengyi-Xiao/2023-02-21-ieeeBERT_en.md
Labels: new model

#13548 2023-02-20-bert_embeddings_pretrain_ko
  docs/_posts/Mary-Sci/2023-02-20-bert_embeddings_base_uncased_issues_128_en.md
  docs/_posts/Mary-Sci/2023-02-20-bert_embeddings_pretrain_ko.md
  docs/_posts/Mary-Sci/2023-02-21-bert_embeddings_chemical_uncased_finetuned_cust_c1_cust_en.md
  docs/_posts/Mary-Sci/2023-02-21-bert_embeddings_chemical_uncased_finetuned_cust_c2_en.md
  docs/_posts/Mary-Sci/2023-02-21-bert_embeddings_olm_base_uncased_oct_2022_en.md
  docs/_posts/Mary-Sci/2023-02-22-bert_embeddings_carlbert_webex_mlm_spatial_en.md
  docs/_posts/Mary-Sci/2023-02-22-bert_embeddings_distil_clinical_en.md
  docs/_posts/Mary-Sci/2023-02-23-deberta_embeddings_erlangshen_v2_chinese_sentencepiece_zh.md
  docs/_posts/Mary-Sci/2023-02-23-distilbert_embeddings_base_multilingual_cased_xx.md
Labels: new model

#13560 SPARKNLP 735 adding notebook examples
  examples/python/annotation/text/english/SpacyToAnnotation_Tutorial.ipynb
  examples/python/annotation/text/english/graph-extraction/graph_extraction.ipynb
  examples/python/annotation/text/english/graph-extraction/graph_extraction_explode_entities.ipynb
  examples/python/annotation/text/english/graph-extraction/graph_extraction_helper_display.ipynb
  examples/python/annotation/text/english/graph-extraction/graph_extraction_intro.ipynb
  examples/python/annotation/text/english/graph-extraction/graph_extraction_roots_paths.ipynb
Labels: documentation

#13561 2023-02-24-finner_signers_en
  docs/_posts/josejuanmartinez/2023-02-24-finner_signers_en.md
Labels: new model

#13557 2023-02-23-ner_sdoh_substance_usage_wip_en
  docs/_posts/Meryem1425/2023-02-23-ner_sdoh_substance_usage_wip_en.md
  docs/_posts/Meryem1425/2023-02-24-ner_sdoh_access_to_healthcare_wip_en.md
  docs/_posts/Meryem1425/2023-02-24-ner_sdoh_community_condition_wip_en.md
  docs/_posts/Meryem1425/2023-02-24-ner_sdoh_health_behaviours_problems_wip_en.md
Labels: new model

#13564 2023-02-24-finner_deid_sec_en
  docs/_posts/josejuanmartinez/2023-02-24-finner_deid_sec_en.md
Labels: new model

#13566 2023-02-25-ner_vop_slim_wip_en
  docs/_posts/Meryem1425/2023-02-25-ner_vop_slim_wip_en.md
Labels: new model

#13568 2023-02-26-biogpt_pubmed_qa_en
  docs/_posts/Cabir40/2023-02-26-biogpt_pubmed_qa_en.md
Labels: new model

#13570 2023-02-27-tabform_v1_en
  docs/_posts/kolia1985/2023-02-27-tabform_v1_en.md
Labels: new model

#13574 2023-02-27-finpipe_deid_en
  docs/_posts/josejuanmartinez/2023-02-27-finpipe_deid_en.md
Labels: new model
