Repository JohnSnowLabs/spark-nlp, pull requests merged in 2023-12, with the labels that each got.

#14029 ONNX support for T5 and Marian
  docs/api/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.html
  python/sparknlp/annotator/seq2seq/marian_transformer.py
  python/sparknlp/annotator/seq2seq/t5_transformer.py
  src/main/scala/com/johnsnowlabs/ml/ai/Marian.scala
  src/main/scala/com/johnsnowlabs/ml/ai/T5.scala
  src/main/scala/com/johnsnowlabs/ml/ai/seq2seq/DecoderProcessor.scala
  src/main/scala/com/johnsnowlabs/ml/ai/seq2seq/MarianEncoderDecoder.scala
  src/main/scala/com/johnsnowlabs/ml/ai/seq2seq/OnnxMarianEncoderDecoder.scala
  src/main/scala/com/johnsnowlabs/ml/ai/seq2seq/OnnxT5EncoderDecoder.scala
  src/main/scala/com/johnsnowlabs/ml/ai/seq2seq/T5EncoderDecoder.scala
  src/main/scala/com/johnsnowlabs/ml/ai/seq2seq/TensorflowMarianEncoderDecoder.scala
  src/main/scala/com/johnsnowlabs/ml/ai/seq2seq/TensorflowT5EncoderDecoder.scala
  src/main/scala/com/johnsnowlabs/ml/ai/t5/OnnxT5EncoderDecoder.scala
  src/main/scala/com/johnsnowlabs/ml/ai/t5/T5EncoderDecoder.scala
  src/main/scala/com/johnsnowlabs/ml/ai/t5/TensorflowT5EncoderDecoder.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sign/ModelSignatureConstants.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5TestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#14051 SPARKNLP-938 E5 and MPNet embeddings crash on a sentence basis - missing pool average
  src/main/scala/com/johnsnowlabs/ml/ai/E5.scala
  src/main/scala/com/johnsnowlabs/ml/ai/MPNet.scala
  src/main/scala/com/johnsnowlabs/ml/util/LinAlg.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/E5EmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/MPNetEmbeddingsTestSpec.scala
Labels: bug-fix, DON'T MERGE

#14052 [SPARKNLP-939] Adding ONNX support for CamemBert transformers
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_CamemBertForQuestionAnswering.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_CamemBertForSequenceClassification.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_CamemBertForTokenClassification.ipynb
  src/main/scala/com/johnsnowlabs/ml/ai/CamemBertClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForTokenClassification.scala
Labels: new-feature, DON'T MERGE

#14053 SPARKNLP-925 DocumentTokenSplitter
  docs/en/annotator_entries/DocumentCharacterTextSplitter.md
  docs/en/annotator_entries/DocumentTokenSplitter.md
  docs/en/annotators.md
  python/sparknlp/annotator/__init__.py
  python/sparknlp/annotator/document_character_text_splitter.py
  python/sparknlp/annotator/document_token_splitter.py
  python/sparknlp/annotator/document_token_splitter_test.py
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitter.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentTokenSplitter.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/TextSplitter.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitterTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentTokenSplitterTest.scala
Labels: new-feature

#14078 [SPARKNLP-941] Adding OnnxSession to broadcast onnx options
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_AlbertForQuestionAnswering.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_BERT.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_BertForQuestionAnswering.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DistilBERT.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_E5.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_MPNet.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_Whisper.ipynb
  src/main/scala/com/johnsnowlabs/ml/ai/Albert.scala
  src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/Bert.scala
  src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/CamemBert.scala
  src/main/scala/com/johnsnowlabs/ml/ai/DeBerta.scala
  src/main/scala/com/johnsnowlabs/ml/ai/DistilBert.scala
  src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/E5.scala
  src/main/scala/com/johnsnowlabs/ml/ai/MPNet.scala
  src/main/scala/com/johnsnowlabs/ml/ai/RoBerta.scala
  src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/Whisper.scala
  src/main/scala/com/johnsnowlabs/ml/ai/XlmRoberta.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSession.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddingsTestSpec.scala
Labels: bug-fix, DON'T MERGE

#14082 2023-12-02-zero_shot_classifier_clip_vit_base_patch32_en
  docs/_posts/DevinTDHa/2023-12-02-zero_shot_classifier_clip_vit_base_patch32_en.md
Labels: new model

#14088 SPARKNLP-955: DocumentCharacterTextSplitter Bug Fix
  src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitter.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitterTest.scala
Labels: bug-fix

#14089 SPARKNLP-951 & SPARKNLP-952: Added example notebooks for Marian and T5
  docs/en/transformers.md
  examples/python/transformers/HuggingFace in Spark NLP - T5.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_Marian.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_T5.ipynb
Labels: documentation

#14104 [SPARKNLP-957] Solves average pooling computation
  src/main/scala/com/johnsnowlabs/ml/ai/E5.scala
  src/main/scala/com/johnsnowlabs/ml/ai/MPNet.scala
  src/main/scala/com/johnsnowlabs/ml/util/LinAlg.scala
  src/test/scala/com/johnsnowlabs/ml/util/LinAlgTest.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/E5EmbeddingsTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/MPNetEmbeddingsTestSpec.scala
Labels: bug-fix, DON'T MERGE

#14106 2023-12-22-Affiliation_Classifier_Roberta_en
  docs/_posts/alex2awesome/2023-12-22-Affiliation_Classifier_Roberta_en.md
Labels: new model
