Repository JohnSnowLabs/spark-nlp, pull requests merged in 2023-07, with the labels that each got.

#13850 2023-06-08-instructor_base_en
  docs/_posts/prabod/2023-06-08-instructor_base_en.md
  docs/_posts/prabod/2023-06-21-e5_base_en.md
  docs/_posts/prabod/2023-06-21-e5_base_v2_en.md
  docs/_posts/prabod/2023-06-21-e5_large_en.md
  docs/_posts/prabod/2023-06-21-e5_large_v2_en.md
  docs/_posts/prabod/2023-06-21-e5_small_en.md
  docs/_posts/prabod/2023-06-21-e5_small_v2_en.md
  docs/_posts/prabod/2023-06-21-instructor_large_en.md
Labels: new model

#13871 2023-06-28-roberta_base_en
  docs/_posts/ahmedlone127/2023-06-28-deberta_v3_base_en.md
  docs/_posts/ahmedlone127/2023-06-28-deberta_v3_base_opt_en.md
  docs/_posts/ahmedlone127/2023-06-28-deberta_v3_base_quantized_en.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_base_cased_en.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_base_cased_opt_en.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_base_cased_quantized_en.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_base_multilingual_cased_opt_xx.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_base_multilingual_cased_quantized_xx.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_base_multilingual_cased_xx.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_base_uncased_en.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_base_uncased_opt_en.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_base_uncased_quantized_en.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_embeddings_distilbert_base_german_cased_de.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_embeddings_distilbert_base_german_cased_opt_de.md
  docs/_posts/ahmedlone127/2023-06-28-distilbert_embeddings_distilbert_base_german_cased_quantized_de.md
  docs/_posts/ahmedlone127/2023-06-28-roberta_base_en.md
  docs/_posts/ahmedlone127/2023-06-28-roberta_base_opt_en.md
  docs/_posts/ahmedlone127/2023-06-28-roberta_base_quantized_en.md
  docs/_posts/ahmedlone127/2023-06-28-small_bert_L2_768_en.md
  docs/_posts/ahmedlone127/2023-06-28-small_bert_L2_768_opt_en.md
  docs/_posts/ahmedlone127/2023-06-28-small_bert_L2_768_quantized_en.md
  docs/_posts/ahmedlone127/2023-06-29-bert_base_cased_en.md
  docs/_posts/ahmedlone127/2023-06-29-bert_base_cased_opt_en.md
  docs/_posts/ahmedlone127/2023-06-29-bert_base_cased_quantized_en.md
Labels: new model

#13849 SPARKNLP 836 - Introducing "Instructor Embeddings" for sentence embeddings like Instructor-XL model
  python/sparknlp/annotator/embeddings/__init__.py
  python/sparknlp/annotator/embeddings/instructor_embeddings.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/embeddings/instructor_embeddings_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/Instructor.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sign/ModelSignatureConstants.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/InstructorEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/InstructorEmbeddingsTestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#13859 SPARKNLP 852 - Introducing "E5 Embeddings" for sentence embeddings like e5-large-v2 model
  python/sparknlp/annotator/embeddings/__init__.py
  python/sparknlp/annotator/embeddings/e5_embeddings.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/embeddings/e5_embeddings_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/E5.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/E5Embeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/E5EmbeddingsTestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#13863 SPARKNLP-846: BART: Added maxInputLength.
  python/test/annotator/seq2seq/bart_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTransformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTestSpec.scala
Labels: bug-fix

#13858 Feature/doc similarity ranker
  .gitignore
  examples/python/annotation/text/english/text-similarity/doc-sim-ranker/test_doc_sim_ranker.ipynb
  python/sparknlp/annotator/similarity/__init__.py
  python/sparknlp/annotator/similarity/document_similarity_ranker.py
  python/sparknlp/common/annotator_type.py
  python/test/annotator/similarity/__init__.py
  python/test/annotator/similarity/doc_similarity_ranker_test.py
  src/main/scala/com/johnsnowlabs/nlp/AnnotatorType.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/similarity/DocumentSimilarityRankerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/similarity/DocumentSimilarityRankerModel.scala
  src/main/scala/com/johnsnowlabs/nlp/finisher/DocumentSimilarityRankerFinisher.scala
  src/test/scala/com/johnsnowlabs/nlp/similarity/DocumentSimilarityRankerTestSpec.scala
Labels: new-feature

#13882 2023-07-06-quora_distilbert_multilingual_en
  docs/_posts/purulalwani/2023-07-06-quora_distilbert_multilingual_en.md
Labels: new model

#13888 SPARKNLP-867 Solves multiLabel param issue in ZeroShot annotators
  python/sparknlp/annotator/classifier_dl/bert_for_zero_shot_classification.py
  src/main/scala/com/johnsnowlabs/nlp/HasClassifierActivationProperties.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForZeroShotClassification.scala
Labels: bug-fix, DON'T MERGE

#13894 Sparknlp 868 make spark driver cores override local in start functions
  python/sparknlp/__init__.py
  src/main/scala/com/johnsnowlabs/nlp/SparkNLP.scala
  src/test/scala/com/johnsnowlabs/nlp/SparkNLPTestSpec.scala
Labels: enhancement, bug-fix

#13889 [SPARKNLP-863 SPARKNLP-864 SPARKNLP-865 SPARKNLP-866] ONNX Export Notebooks
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_BERT.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DeBERTa.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DistilBERT.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_RoBERTa.ipynb
Labels: DON'T MERGE

#13890 SPARKNLP-869 Adding threshold to properties for python module
  python/sparknlp/common/properties.py
Labels: bug-fix, DON'T MERGE

#13900 2023-07-20-xlm_roberta_large_zero_shot_classifier_xnli_anli_xx
  docs/_posts/ahmedlone127/2023-07-20-xlm_roberta_large_zero_shot_classifier_xnli_anli_xx.md
Labels: new model

#13905 2023-07-28-twitter_xlm_roberta_base_sentiment_en
  docs/_posts/veerdhwaj/2023-07-28-twitter_xlm_roberta_base_sentiment_en.md
Labels: new model
