Repository JohnSnowLabs/spark-nlp, pull requests merged in 2023-04, with the labels that each got.

#13740 2023-04-05-bert_base_cased_zero_shot_classifier_xnli_en
  docs/_posts/maziyarpanahi/2023-04-05-bert_base_cased_zero_shot_classifier_xnli_en.md
Labels: new model

#13664 SPARKNLP-782 Removes deprecated parameter enablePatternRegex
  python/sparknlp/annotator/er/entity_ruler.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/er/EntityRulerModel.scala
  src/main/scala/com/johnsnowlabs/storage/Database.scala
Labels: DON'T MERGE

#13680 SPARKNLP-748: Custom Entity Name for Date2Chunk
  python/sparknlp/annotator/date2_chunk.py
  python/test/annotator/date2_chunk_test.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/Date2Chunk.scala
  src/test/scala/com/johnsnowlabs/nlp/Date2ChunkTestSpec.scala
Labels: new-feature, DON'T MERGE

#13707 SPARKNLP-784 Fix loading WordEmbeddingsModel Bug
  src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/storage/StorageHelper.scala
  src/main/scala/com/johnsnowlabs/storage/StorageLocator.scala
Labels: bug-fix, DON'T MERGE

#13715 SPARKNLP-785 Fix WordEmbeddingsModel Bug with LightPipeline
  src/main/scala/com/johnsnowlabs/nlp/embeddings/WordEmbeddingsModel.scala
Labels: bug-fix, DON'T MERGE

#13724 SPARKNLP-783: Python 3.6 deprecated in Spark 3.2
  docs/en/install.md
  python/docs/getting_started/index.rst
  python/sparknlp/__init__.py
Labels: documentation, DON'T MERGE

#13731 Sparknlp 534 Introducing BART Transformer for text-to-text generation tasks like translation and summarization
  python/sparknlp/annotator/seq2seq/__init__.py
  python/sparknlp/annotator/seq2seq/bart_transformer.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/seq2seq/bart_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/Logit.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/LogitProcessor.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/MinLengthLogitProcessor.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/NoRepeatNgramsLogitProcessor.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/RepetitionPenaltyLogitProcessor.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcessorList.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/LogitWarper.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/TemperatureLogitWarper.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/TopKLogitWarper.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/TopPLogitWarper.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Search/BeamHypotheses.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Search/BeamScorer.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Search/BeamSearchScorer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BartTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BartTokenizerTestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#13745 SPARKNLP-796 Creating a new `nerHasNoSchema` param
  docs/en/CPUvsGPUbenchmark.md
  python/sparknlp/annotator/ner/ner_converter.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerTagsEncoding.scala
Labels: enhancement

#13746 2023-04-07-distilbart_xsum_12_6_en
  docs/_posts/maziyarpanahi/2023-04-07-distilbart_xsum_12_6_en.md
Labels: new model

#13743 SPARKNLP-805: Documentation for release/440
  docs/en/annotators.md
  docs/en/transformer_entries/BartTransformer.md
  docs/en/transformer_entries/BertForZeroShotClassification.md
  python/sparknlp/annotator/classifier_dl/bert_for_zero_shot_classification.py
  python/sparknlp/annotator/seq2seq/bart_transformer.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTransformer.scala
Labels: enhancement, documentation

#13749 2023-04-09-distilbart_xsum_12_6_en
  docs/_posts/maziyarpanahi/2023-04-09-distilbart_xsum_12_6_en.md
Labels: new model

#13750 2023-04-09-distilbart_cnn_6_6_en
  docs/_posts/maziyarpanahi/2023-04-09-distilbart_cnn_6_6_en.md
Labels: new model

#13751 2023-04-09-bart_large_cnn_en
  docs/_posts/maziyarpanahi/2023-04-09-bart_large_cnn_en.md
Labels: new model

#13757 2023-04-13-CyberbullyingDetection_ClassifierDL_tfhub_en
  docs/_posts/Naveen-004/2023-04-13-CyberbullyingDetection_ClassifierDL_tfhub_en.md
Labels: new model

#13761 2023-04-20-distilbert_base_uncased_mnli_en
  docs/_posts/ahmedlone127/2023-04-20-distilbert_base_zero_shot_classifier_turkish_cased_allnli_tr.md
  docs/_posts/ahmedlone127/2023-04-20-distilbert_base_zero_shot_classifier_turkish_cased_multinli_tr.md
  docs/_posts/ahmedlone127/2023-04-20-distilbert_base_zero_shot_classifier_turkish_cased_snli_tr.md
  docs/_posts/ahmedlone127/distilbert_base_zero_shot_classifier_turkish_cased_snli_en.md
Labels: new model

#13760 SPARKNLP-800 Adding threshold parameter to all ForSequenceClassification
  src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/CamemBertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/DeBertaClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/XXXForClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/XlmRoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/XlnetClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/HasClassifierActivationProperties.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlnetForSequenceClassification.scala
Labels: enhancement, DON'T MERGE
