Repository JohnSnowLabs/spark-nlp, pull requests merged in 2023-09, with the labels that each got.

#13944 2023-08-28-asr_whisper_tiny_opt_xx
  docs/_posts/DevinTDHa/2023-08-28-asr_whisper_tiny_opt_xx.md
Labels: new model

#13945 [SPARKNLP-906] Fix reading suffix
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/audio/WhisperForCTCTest.scala
Labels: bug-fix, DON'T MERGE

#13955 Sparknlp 888 Add ONNX support to MPNet embeddings
  src/main/scala/com/johnsnowlabs/ml/ai/MPNet.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/MPNetEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/MPNetEmbeddingsTestSpec.scala
Labels: new-feature, new model

#13956 Adding ONNX Support to ALBERT Token and Sequence Classification and Question Answering annotators
  src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/XXXForClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/ZeroShotNerClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForTokenClassification.scala
Labels: new-feature, DON'T MERGE

#13957 SPARKNLP-884 Enabling getVectors method
  python/sparknlp/annotator/embeddings/doc2vec.py
  python/sparknlp/annotator/embeddings/word2vec.py
  src/main/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecModel.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/Word2VecModel.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/Doc2VecTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/Word2VecTestSpec.scala
Labels: new-feature, DON'T MERGE

#13958 [SPARKNLP-890] ONNX E5 MPnet example
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_E5.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_MPNet.ipynb
Labels: documentation

#13988 2023-09-18-AtgxRobertaBaseSquad2_en
  docs/_posts/LIN-Yu-Ting/2023-09-18-AtgxRobertaBaseSquad2_en.md
Labels: new model

#13996 SPARKNLP-915, SPARKNLP-918:MPNet ONNX Example and missing Documentation
  docs/en/annotator_entries/Date2Chunk.md
  docs/en/annotator_entries/DocumentSimilarityRanker.md
  docs/en/annotators.md
  docs/en/transformer_entries/BartForZeroShotClassification.md
  docs/en/transformer_entries/CamemBertForQuestionAnswering.md
  docs/en/transformer_entries/DeBertaForSequenceClassification.md
  docs/en/transformer_entries/DeBertaForTokenClassification.md
  docs/en/transformer_entries/E5Embeddings.md
  docs/en/transformer_entries/InstructorEmbeddings.md
  docs/en/transformer_entries/MPNetEmbeddings.md
  docs/en/transformer_entries/OpenAICompletion.md
  docs/en/transformer_entries/VisionEncoderDecoderForImageCaptioning.md
  docs/en/transformer_entries/XlmRoBertaForZeroShotClassification.md
  docs/en/transformers.md
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_MPNet.ipynb
  python/sparknlp/annotator/classifier_dl/deberta_for_token_classification.py
  python/sparknlp/annotator/openai/openai_completion.py
  python/sparknlp/annotator/similarity/document_similarity_ranker.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/similarity/DocumentSimilarityRankerApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/similarity/DocumentSimilarityRankerModel.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/MPNetEmbeddings.scala
Labels: documentation, bug-fix

#13999 2023-09-20-image_captioning_vit_gpt2_en
  docs/_posts/DevinTDHa/2023-09-20-image_captioning_vit_gpt2_en.md
Labels: new model

#14002 2023-09-21-multilingual_e5_base_xx
  docs/_posts/ahmedlone127/2023-09-21-multilingual_e5_base_xx.md
  docs/_posts/ahmedlone127/2023-09-21-multilingual_e5_large_xx.md
  docs/_posts/ahmedlone127/2023-09-21-multilingual_e5_small_xx.md
Labels: new model

#14003 2023-09-22-bert_embeddings_frpile_gpl_en
  docs/_posts/SKocer/2023-09-22-bert_embeddings_allnli_gronlp_base_dutch_cased_nl.md
  docs/_posts/SKocer/2023-09-22-bert_embeddings_bge_base_en.md
  docs/_posts/SKocer/2023-09-22-bert_embeddings_bge_large_en.md
  docs/_posts/SKocer/2023-09-22-bert_embeddings_bge_small_en.md
  docs/_posts/SKocer/2023-09-22-bert_embeddings_bi_encoder_msmarco_base_german_de.md
  docs/_posts/SKocer/2023-09-22-bert_embeddings_claif_base_en.md
  docs/_posts/SKocer/2023-09-22-bert_embeddings_claif_scaled_base_en.md
  docs/_posts/SKocer/2023-09-22-bert_embeddings_frpile_gpl_en.md
  docs/_posts/SKocer/2023-09-22-bert_embeddings_retromae_beir_en.md
  docs/_posts/SKocer/2023-09-22-bert_embeddings_retromae_msmarco_finetune_en.md
Labels: new model
