Repository JohnSnowLabs/spark-nlp, pull requests merged in 2023-01, with the labels that each got.

#13294 2023-01-01-legassertion_negation_en
  docs/_posts/josejuanmartinez/2023-01-01-legassertion_negation_en.md
Labels: new model

#13293 2023-01-01-finassertion_negation_en
  docs/_posts/josejuanmartinez/2023-01-01-finassertion_negation_en.md
Labels: new model

#13296 2023-01-01-legner_org_per_role_date_en
  docs/_posts/josejuanmartinez/2023-01-01-legner_org_per_role_date_en.md
Labels: new model

#13295 2023-01-01-visualner_receipts_xx
  docs/_posts/gadde5300/2023-01-01-visualner_10kfilings_en.md
  docs/_posts/gadde5300/2023-01-01-visualner_keyvalue_10kfilings_en.md
  docs/_posts/gadde5300/2023-01-01-visualner_receipts_xx.md
Labels: new model

#13297 2023-01-02-visualner_10kfilings_en
  docs/_posts/gadde5300/2023-01-02-visualner_10kfilings_en.md
Labels: new model

#13261 Databricks installation instructions update.
  docs/en/licensed_install.md
Labels: documentation

#13304 2023-01-02-legassertion_time_md_en
  docs/_posts/josejuanmartinez/2023-01-02-legassertion_time_md_en.md
Labels: new model

#13307 2023-01-03-finqa_bert_en
  docs/_posts/josejuanmartinez/2023-01-03-finqa_bert_en.md
Labels: new model

#13308 2023-01-03-finqa_bert_large_en
  docs/_posts/josejuanmartinez/2023-01-03-finqa_bert_large_en.md
Labels: new model

#13299 2023-01-02-finner_10q_xlbr_lg_asset_en
  docs/_posts/gadde5300/2023-01-02-finner_10q_xlbr_lg_asset_en.md
  docs/_posts/gadde5300/2023-01-02-finner_10q_xlbr_lg_contra_liability_en.md
  docs/_posts/gadde5300/2023-01-02-finner_10q_xlbr_lg_contra_stock_equity_en.md
  docs/_posts/gadde5300/2023-01-02-finner_10q_xlbr_lg_debt_en.md
  docs/_posts/gadde5300/2023-01-02-finner_10q_xlbr_lg_expense_en.md
  docs/_posts/gadde5300/2023-01-02-finner_10q_xlbr_lg_income_en.md
  docs/_posts/gadde5300/2023-01-02-finner_10q_xlbr_lg_liability_en.md
  docs/_posts/gadde5300/2023-01-02-finner_10q_xlbr_lg_revenue_en.md
Labels: new model

#13305 SPARKNLP-713 Modifies Default Values GraphExtraction
  src/main/scala/com/johnsnowlabs/nlp/annotators/GraphExtraction.scala
  src/test/scala/com/johnsnowlabs/nlp/GraphFinisherTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/GraphExtractionTest.scala
Labels: enhancement, DON'T MERGE

#13309 2023-01-04-finassertiondl_time_md_en
  docs/_posts/josejuanmartinez/2023-01-04-finassertiondl_time_md_en.md
Labels: new model

#13313 2023-01-06-redl_clinical_biobert_en
  docs/_posts/Cabir40/2023-01-06-redl_clinical_biobert_en.md
Labels: new model

#13319 Docs/nlp lab rebranding
  docs/_data/navigation.yml
  docs/_layouts/nlp_products.html
  docs/_sass/custom.scss
  docs/assets/images/annotation_lab/flower_22.png
  docs/docs.md
  docs/en/alab/install.md
  docs/en/alab/quickstart.md
Labels: documentation

#13321 Fix language of the model en => es
  docs/_posts/josejuanmartinez/2022-08-09-legclf_conventions_en_3_2.md
Labels: documentation

#13327 2023-01-11-legclf_tax_matters_md_en
  docs/_posts/josejuanmartinez/2023-01-11-legclf_affirmative_covenants_md_en.md
  docs/_posts/josejuanmartinez/2023-01-11-legclf_amendments_and_waivers_md_en.md
  docs/_posts/josejuanmartinez/2023-01-11-legclf_attorney_fees_md_en.md
  docs/_posts/josejuanmartinez/2023-01-11-legclf_choice_of_law_md_en.md
  docs/_posts/josejuanmartinez/2023-01-11-legclf_conditions_precedent_md_en.md
  docs/_posts/josejuanmartinez/2023-01-11-legclf_effect_of_termination_md_en.md
  docs/_posts/josejuanmartinez/2023-01-11-legclf_fees_and_expenses_md_en.md
  docs/_posts/josejuanmartinez/2023-01-11-legclf_miscellaneous_provisions_md_en.md
  docs/_posts/josejuanmartinez/2023-01-11-legclf_tax_matters_md_en.md
  docs/_posts/josejuanmartinez/2023-01-11-legclf_term_of_agreement_md_en.md
  docs/_posts/josejuanmartinez/2023-01-11-legclf_termination_for_cause_md_en.md
Labels: new model

#13318 SPARKNLP-715 Tokenizer Index Eerror
  src/main/scala/com/johnsnowlabs/nlp/annotators/common/SentenceSplit.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/RegexTokenizerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/TokenizerTestSpec.scala
Labels: bug-fix, DON'T MERGE

#13328 2023-01-11-ner_oncology_unspecific_posology_healthcare_en
  docs/_posts/Meryem1425/2023-01-11-ner_oncology_anatomy_general_healthcare_en.md
  docs/_posts/Meryem1425/2023-01-11-ner_oncology_biomarker_healthcare_en.md
  docs/_posts/Meryem1425/2023-01-11-ner_oncology_unspecific_posology_healthcare_en.md
Labels: new model

#13271 Added missing licensed annotators pages
  docs/_data/navigation.yml
  docs/_includes/templates/licensed_approach_model_medical_fin_leg_template.md
  docs/en/healthcare_risk_adjustments_score_calculation.md
  docs/en/licensed_annotator_entries/AnnotationMerger.md
  docs/en/licensed_annotator_entries/AssertionChunkConverter.md
  docs/en/licensed_annotator_entries/BertSentenceChunkEmbeddings.md
  docs/en/licensed_annotator_entries/ChunkConverter.md
  docs/en/licensed_annotator_entries/ChunkMapper.md
  docs/en/licensed_annotator_entries/ChunkMapperFilterer.md
  docs/en/licensed_annotator_entries/ChunkSentenceSplitter.md
  docs/en/licensed_annotator_entries/DateNormalizer.md
  docs/en/licensed_annotator_entries/Doc2ChunkInternal.md
  docs/en/licensed_annotator_entries/DocumentHashCoder.md
  docs/en/licensed_annotator_entries/ZeroShotNerModel.md
  docs/en/licensed_annotator_entries/ZeroShotRelationExtraction
  docs/en/training_entries/conll.md
  docs/en/utility_helper_modules.md
Labels: documentation

#13335 2023-01-12-bert_embeddings_legal_bert_small_uncased_en
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_Legal_heBERT_ft_he.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_Legal_heBERT_he.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_bert_small_finetuned_legal_contracts10train10val_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_bert_small_finetuned_legal_contracts_larger20_5_1_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_bert_small_finetuned_legal_contracts_larger4010_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_bert_small_finetuned_legal_definitions_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_bert_small_finetuned_legal_definitions_longer_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_bert_tiny_finetuned_legal_definitions_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_custom_legalbert_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_legal_bert_base_uncased_finetuned_RRamicus_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_legal_bert_base_uncased_finetuned_ledgarscotus7_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_legal_bert_small_uncased_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_legalbert_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_legalbert_large_1.7M_1_en.md
  docs/_posts/gadde5300/2023-01-12-bert_embeddings_legalbert_large_1.7M_2_en.md
Labels: new model, DON'T MERGE

#13337 2023-01-12-legclf_applicable_law_cuad_en
  docs/_posts/Mary-Sci/2023-01-12-legclf_applicable_law_cuad_en.md
  docs/_posts/Mary-Sci/2023-01-12-legner_applicable_law_clause_en.md
Labels: new model

#13333 2023-01-12-classifierdl_bert_news_pipeline_de
  docs/_posts/ahmedlone127/2023-01-12-classifierdl_bert_news_pipeline_de.md
  docs/_posts/ahmedlone127/2023-01-12-classifierdl_bert_sentiment_pipeline_fr.md
  docs/_posts/ahmedlone127/2023-01-12-classifierdl_berturk_cyberbullying_pipeline_tr.md
  docs/_posts/ahmedlone127/2023-01-12-classifierdl_bertwiki_finance_sentiment_pipeline_en.md
  docs/_posts/ahmedlone127/2023-01-12-classifierdl_electra_questionpair_pipeline_en.md
  docs/_posts/ahmedlone127/2023-01-12-classifierdl_use_sentiment_pipeline_tr.md
Labels: new model

#13339 2023-01-13-camembert_embeddings_Italian_Legal_BERT_SC_it
  docs/_posts/gadde5300/2023-01-13-bert_embeddings_Italian_Legal_BERT_it.md
  docs/_posts/gadde5300/2023-01-13-bert_embeddings_Legal_BERTimbau_base_pt.md
  docs/_posts/gadde5300/2023-01-13-bert_embeddings_Legal_BERTimbau_large_pt.md
  docs/_posts/gadde5300/2023-01-13-bert_embeddings_bert_large_portuguese_cased_legal_mlm_pt.md
  docs/_posts/gadde5300/2023-01-13-bert_embeddings_legal_bert_base_cased_ptbr_pt.md
  docs/_posts/gadde5300/2023-01-13-camembert_embeddings_Italian_Legal_BERT_SC_it.md
  docs/_posts/gadde5300/2023-01-13-camembert_embeddings_legal_camembert_fr.md
  docs/_posts/gadde5300/2023-01-13-camembert_embeddings_legal_distilcamembert_fr.md
  docs/_posts/gadde5300/2023-01-13-camembert_embeddings_lsg16k_Italian_Legal_BERT_SC_it.md
Labels: new model

#13341 2023-01-13-finmapper_wikipedia_parentcompanies_en
  docs/_posts/josejuanmartinez/2023-01-13-finmapper_wikipedia_parentcompanies_en.md
  docs/_posts/josejuanmartinez/2023-01-13-finmapper_wikipedia_parentcompanies_ticker_en.md
Labels: new model

#13348 2023-01-14-genericclassifier_sdoh_tobacco_usage_sbiobert_cased_mli_en
  docs/_posts/Damla-Gurbaz/2023-01-14-genericclassifier_sdoh_alcohol_usage_binary_sbiobert_cased_mli_en.md
  docs/_posts/Damla-Gurbaz/2023-01-14-genericclassifier_sdoh_alcohol_usage_sbiobert_cased_mli_en.md
  docs/_posts/Damla-Gurbaz/2023-01-14-genericclassifier_sdoh_economics_binary_sbiobert_cased_mli_en.md
  docs/_posts/Damla-Gurbaz/2023-01-14-genericclassifier_sdoh_substance_usage_binary_sbiobert_cased_mli_en.md
  docs/_posts/Damla-Gurbaz/2023-01-14-genericclassifier_sdoh_tobacco_usage_sbiobert_cased_mli_en.md
Labels: new model

#13303 SPARKNLP-607: Implement HubertForCTC
  python/sparknlp/annotator/audio/__init__.py
  python/sparknlp/annotator/audio/hubert_for_ctc.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/audio/hubert_for_ctc_test.py
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/audio/HubertForCTC.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/audio/HubertForCTCTest.scala
Labels: new-feature, new model, DON'T MERGE

#13349 2023-01-14-redl_ade_biobert_en
  docs/_posts/Meryem1425/2023-01-14-redl_ade_biobert_en.md
  docs/_posts/Meryem1425/2023-01-14-redl_bodypart_direction_biobert_en.md
  docs/_posts/Meryem1425/2023-01-14-redl_bodypart_problem_biobert_en.md
  docs/_posts/Meryem1425/2023-01-14-redl_bodypart_procedure_test_biobert_en.md
  docs/_posts/Meryem1425/2023-01-14-redl_chemprot_biobert_en.md
  docs/_posts/Meryem1425/2023-01-14-redl_clinical_biobert_en.md
  docs/_posts/Meryem1425/2023-01-14-redl_date_clinical_biobert_en.md
  docs/_posts/Meryem1425/2023-01-14-redl_drug_drug_interaction_biobert_en.md
  docs/_posts/Meryem1425/2023-01-14-redl_drugprot_biobert_en.md
  docs/_posts/Meryem1425/2023-01-14-redl_human_phenotype_gene_biobert_en.md
  docs/_posts/Meryem1425/2023-01-15-redl_nihss_biobert_en.md
  docs/_posts/Meryem1425/2023-01-15-redl_oncology_biobert_wip_en.md
  docs/_posts/Meryem1425/2023-01-15-redl_oncology_biomarker_result_biobert_wip_en.md
  docs/_posts/Meryem1425/2023-01-15-redl_oncology_granular_biobert_wip_en.md
  docs/_posts/Meryem1425/2023-01-15-redl_oncology_location_biobert_wip_en.md
  docs/_posts/Meryem1425/2023-01-15-redl_oncology_size_biobert_wip_en.md
  docs/_posts/Meryem1425/2023-01-15-redl_oncology_temporal_biobert_wip_en.md
  docs/_posts/Meryem1425/2023-01-15-redl_oncology_test_result_biobert_wip_en.md
  docs/_posts/Meryem1425/2023-01-15-redl_temporal_events_biobert_en.md
Labels: new model

#13350 2023-01-15-finner_wiki_stockexchange_en
  docs/_posts/josejuanmartinez/2023-01-15-finner_wiki_formername_en.md
  docs/_posts/josejuanmartinez/2023-01-15-finner_wiki_founding_dates_en.md
  docs/_posts/josejuanmartinez/2023-01-15-finner_wiki_nationality_en.md
  docs/_posts/josejuanmartinez/2023-01-15-finner_wiki_sector_en.md
  docs/_posts/josejuanmartinez/2023-01-15-finner_wiki_stockexchange_en.md
Labels: new model

#13331 SPARKNLP-606: Add SwinForImageClassification Annotator
  python/sparknlp/annotator/cv/__init__.py
  python/sparknlp/annotator/cv/swin_for_image_classification.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/cv/swin_for_image_classification_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/ViTClassifier.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/SwinForImageClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/feature_extractor/Preprocessor.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/util/transform/ImageResizeUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/resources/image_preprocessor/normalized_egyptian_cat.json
  src/test/resources/image_preprocessor/preprocessor_config_swin.json
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/SwinForImageClassificationTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/ViTImageClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/feature_extractor/ImageUtilsTestSpec.scala
Labels: enhancement, new-feature, new model, DON'T MERGE

#13363 2023-01-18-finel_wiki_parentorgs_en
  docs/_posts/josejuanmartinez/2023-01-18-finel_wiki_parentorgs_en.md
  docs/_posts/josejuanmartinez/2023-01-18-finel_wiki_parentorgs_ticker_en.md
Labels: new model

#13364 2023-01-18-legner_dispute_clauses_en
  docs/_posts/josejuanmartinez/2023-01-18-legner_dispute_clauses_en.md
Labels: new model

#13365 2023-01-18-legclf_dispute_clauses_cuad_en
  docs/_posts/josejuanmartinez/2023-01-18-legclf_dispute_clauses_cuad_en.md
Labels: new model

#13371 2023-01-19-finmapper_nasdaq_ticker_stock_screener_en
  docs/_posts/bunyamin-polat/2023-01-19-finmapper_nasdaq_ticker_stock_screener_en.md
Labels: new model

#13375 2023-01-19-finmapper_nasdaq_company_name_stock_screener_en
  docs/_posts/bunyamin-polat/2023-01-19-finmapper_nasdaq_company_name_stock_screener_en.md
Labels: new model

#13376 2023-01-20-finel_nasdaq_company_name_stock_screener_en
  docs/_posts/bunyamin-polat/2023-01-20-finel_nasdaq_company_name_stock_screener_en.md
Labels: new model

#13378 2023-01-20-finel_nasdaq_company_name_stock_screener_en
  docs/_posts/bunyamin-polat/2023-01-20-finel_nasdaq_company_name_stock_screener_en.md
Labels: new model

#13379 2023-01-20-finel_nasdaq_ticker_stock_screener_en
  docs/_posts/bunyamin-polat/2023-01-20-finel_nasdaq_ticker_stock_screener_en.md
Labels: new model

#13380 2023-01-20-legpipe_header_subheader_en
  docs/_posts/Mary-Sci/2023-01-20-legpipe_header_subheader_en.md
Labels: new model

#13383 2023-01-20-legpipe_header_subheader_en
  docs/_posts/Mary-Sci/2023-01-20-legpipe_header_subheader_en.md
Labels: new model

#13397 2023-01-21-legner_contract_doc_parties_lg_en
  docs/_posts/josejuanmartinez/2023-01-21-legner_contract_doc_parties_lg_en.md
Labels: new model

#13396 SPARKNLP-726 Fix metadata in XXXForSequenceClassification results
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowForClassification.scala
Labels: bug-fix, DON'T MERGE

#13402 SPARKNLP-724 Adding configuration to skip light pipeline validation
  python/sparknlp/base/embeddings_finisher.py
  python/sparknlp/base/finisher.py
  python/sparknlp/base/light_pipeline.py
Labels: enhancement, DON'T MERGE

#13415 2023-01-25-ner_eu_clinical_case_en
  docs/_posts/gpirge/2023-01-25-ner_eu_clinical_case_en.md
Labels: new model

#13418 2023-01-26-legclf_agreement_of_purchase_and_sale_bert_en
  docs/_posts/Mary-Sci/2023-01-26-legclf_agreement_of_purchase_and_sale_bert_en.md
  docs/_posts/Mary-Sci/2023-01-26-legclf_confidential_treatment_bert_en.md
  docs/_posts/Mary-Sci/2023-01-26-legclf_form_of_indemnification_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-26-legclf_independent_contractor_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-26-legclf_non_competition_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-26-legclf_principal_underwriting_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-26-legclf_settlement_agreement_and_mutual_release_bert_en.md
  docs/_posts/Mary-Sci/2023-01-26-legclf_shareholder_services_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-26-legclf_term_loan_credit_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-26-legclf_trademark_license_agreement_bert_en.md
Labels: new model

#13425 2023-01-27-legclf_termination_for_convenience_clause_en
  docs/_posts/Mary-Sci/2023-01-27-legclf_absence_of_litigation_clause_en.md
  docs/_posts/Mary-Sci/2023-01-27-legclf_application_of_trust_money_clause_en.md
  docs/_posts/Mary-Sci/2023-01-27-legclf_benefits_of_indenture_clause_en.md
  docs/_posts/Mary-Sci/2023-01-27-legclf_capital_expenditures_clause_en.md
  docs/_posts/Mary-Sci/2023-01-27-legclf_deposit_of_redemption_price_clause_en.md
  docs/_posts/Mary-Sci/2023-01-27-legclf_disclosure_of_information_clause_en.md
  docs/_posts/Mary-Sci/2023-01-27-legclf_indemnification_procedures_clause_en.md
  docs/_posts/Mary-Sci/2023-01-27-legclf_method_of_exercise_clause_en.md
  docs/_posts/Mary-Sci/2023-01-27-legclf_satisfaction_and_discharge_of_indenture_clause_en.md
  docs/_posts/Mary-Sci/2023-01-27-legclf_termination_for_convenience_clause_en.md
Labels: new model

#13352 Sparknlp 718 Zero Shot NER model annotator
  python/sparknlp/annotator/ner/__init__.py
  python/sparknlp/annotator/ner/zero_shot_ner_model.py
  python/sparknlp/internal/__init__.py
  python/sparknlp/internal/annotator_java_ml.py
  python/test/annotator/ner/zero_shot_ner_model_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/ZeroShotNerClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/ZeroShotNerModel.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/ner/dl/ZeroShotNerModelTest.scala
Labels: new-feature, models_hub, new model

#13354 Improvment for Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc_improvement.md
  .github/ISSUE_TEMPLATE/doc_improvement.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, documentation

#13369 [skip ci] SPARKNLP-725: Add PyDoc documentation for ResourceDownloader
  python/docs/reference/index.rst
  python/docs/user_guide/annotators.rst
  python/docs/user_guide/pretrained_pipelines.rst
  python/sparknlp/pretrained/resource_downloader.py
Labels: enhancement, documentation

#13420 Remove Debug Print in LP
  python/sparknlp/base/light_pipeline.py
Labels: bug-fix

#13423 SPARKNLP-728 Avoid Copying Existing Models on S3/GCP
  src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
  src/main/scala/com/johnsnowlabs/client/gcp/GCPGateway.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
Labels: enhancement, DON'T MERGE

#13427 2023-01-29-legclf_master_administrative_services_agreement_bert_en
  docs/_posts/Mary-Sci/2023-01-29-legclf_adoption_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_arrangement_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_compensation_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_investment_advisory_and_management_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_master_administrative_services_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_noncompetition_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_performance_share_award_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_retirement_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_standstill_agreement_bert_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_sublicense_agreement_bert_en.md
Labels: new model

#13428 2023-01-29-legclf_other_definitional_provisions_clause_en
  docs/_posts/Mary-Sci/2023-01-29-legclf_assignment_and_subletting_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_cusip_numbers_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_due_authorization_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_fringe_benefits_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_military_leave_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_no_material_adverse_effect_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_other_definitional_provisions_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_subcontractors_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_titles_and_subtitles_clause_en.md
Labels: new model

#13429 2023-01-29-legclf_maintenance_of_insurance_clause_en
  docs/_posts/Mary-Sci/2023-01-29-legclf_annual_bonus_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_board_of_directors_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_business_expenses_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_conditions_of_underwriters_obligations_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_maintenance_of_insurance_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_non_exclusivity_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_quiet_enjoyment_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_reimbursement_of_expenses_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_right_of_first_refusal_clause_en.md
  docs/_posts/Mary-Sci/2023-01-29-legclf_waiver_of_subrogation_clause_en.md
Labels: new model

#13430 2023-01-30-legqa_roberta_cuad_large_en
  docs/_posts/josejuanmartinez/2023-01-30-legqa_roberta_cuad_base_en.md
  docs/_posts/josejuanmartinez/2023-01-30-legqa_roberta_cuad_large_en.md
  docs/_posts/josejuanmartinez/2023-01-30-legqa_roberta_cuad_small_en.md
Labels: new model

#13431 2023-01-30-legner_roberta_zeroshot_cuad_base_en
  docs/_posts/josejuanmartinez/2023-01-30-legner_roberta_zeroshot_cuad_base_en.md
  docs/_posts/josejuanmartinez/2023-01-30-legner_roberta_zeroshot_cuad_large_en.md
  docs/_posts/josejuanmartinez/2023-01-30-legner_roberta_zeroshot_cuad_small_en.md
Labels: new model

#13441 SPARKNLP-734 Enable params argument in spark_nlp.start()
  python/sparknlp/__init__.py
Labels: enhancement

#13444 2023-01-31-legclf_bert_maud_en
  docs/_posts/gadde5300/2023-01-31-legclf_bert_maud_en.md
Labels: new model

#13446 2023-01-31-finclf_bert_broker_sentiment_analysis_en
  docs/_posts/gadde5300/2023-01-31-finclf_bert_broker_sentiment_analysis_en.md
Labels: new model

#13445 2023-01-31-finclf_bert_broker_recommendation_en
  docs/_posts/gadde5300/2023-01-31-finclf_bert_broker_recommendation_en.md
Labels: new model
