Repository JohnSnowLabs/spark-nlp, pull requests merged in 2023-05, with the labels that each got.

#13781 2023-05-04-roberta_base_zero_shot_classifier_nli_en
  docs/_posts/ahmedlone127/2023-05-04-roberta_base_zero_shot_classifier_nli_en.md
Labels: new model

#13788 2023-05-09-distilbart_xsum_6_6_en
  docs/_posts/prabod/2023-05-09-bart_large_cnn_en.md
  docs/_posts/prabod/2023-05-09-distilbart_cnn_12_6_en.md
  docs/_posts/prabod/2023-05-09-distilbart_cnn_6_6_en.md
  docs/_posts/prabod/2023-05-09-distilbart_xsum_12_6_en.md
  docs/_posts/prabod/2023-05-09-distilbart_xsum_6_6_en.md
Labels: new model

#13772 Fix Tapas bug due to exceeding the maximum rank value
  src/main/scala/com/johnsnowlabs/nlp/annotators/tapas/TapasEncoder.scala
Labels: bug-fix, DON'T MERGE

#13773 SPARKNLP-819 Adding changes to make spark-nlp 3.4.0 default version
  .github/workflows/build_and_test.yml
  project/Dependencies.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/sentencepiece/LoadSentencepiece.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/MultiDateMatcher.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/LoadsContrib.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/normalizer/MosesPunctNormalizer.scala
  src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/SparkSessionTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/norvig/NorvigSweetingBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala
Labels: new-feature, DON'T MERGE

#13782 Sparknlp 811 implement RobertaForZeroShotClassification annotator
  python/sparknlp/annotator/classifier_dl/__init__.py
  python/sparknlp/annotator/classifier_dl/roberta_bert_for_zero_shot_classification.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/classifier_dl/roberta_for_zero_shot_classification_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForZeroShotClassificationTestSpec.scala
Labels: new-feature

#13784 Fix loadSavedModel for DBFS
  src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala
Labels: bug-fix

#13787 Sparknlp 826 upload new optimized models for bart and Generate function
  python/sparknlp/annotator/seq2seq/bart_transformer.py
  python/sparknlp/internal/__init__.py
  src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTransformer.scala
Labels: enhancement, new-feature

#13779 Update XXXForSequence with multilabel and activation function
  docs/en/transformer_entries/AlbertForSequenceClassification.md
  docs/en/transformer_entries/BertForSequenceClassification.md
  docs/en/transformer_entries/CamemBertForSequenceClassification.md
  docs/en/transformer_entries/DistilBertForSequenceClassification.md
  docs/en/transformer_entries/LongformerForSequenceClassification.md
  docs/en/transformer_entries/RoBertaForSequenceClassification.md
  docs/en/transformer_entries/XlmRoBertaForSequenceClassification.md
Labels: enhancement, documentation

#13795 2023-05-11-distilbart_cnn_12_6_en
  docs/_posts/prabod/2023-05-11-bart_large_cnn_en.md
  docs/_posts/prabod/2023-05-11-distilbart_cnn_12_6_en.md
  docs/_posts/prabod/2023-05-11-distilbart_cnn_6_6_en.md
  docs/_posts/prabod/2023-05-11-distilbart_xsum_12_6_en.md
  docs/_posts/prabod/2023-05-11-distilbart_xsum_6_6_en.md
Labels: new model

#13792 SPARKNLP-825 Adding multilabel param
  examples/python/annotation/text/english/zero-shot text classification/Zero_Shot_Text_Classification_by_BERT.ipynb
  python/sparknlp/common/properties.py
  src/main/scala/com/johnsnowlabs/nlp/HasClassifierActivationProperties.scala
Labels: enhancement, DON'T MERGE

#13806 SPARKNLP-839 Fix Java Compatibility Issue
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/LoadsContrib.scala
Labels: bug-fix, DON'T MERGE

#13796 Add unzip param to downloadModelDirectly in ResourceDownloader
  python/sparknlp/internal/__init__.py
  python/sparknlp/pretrained/resource_downloader.py
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/MockResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloaderMetaSpec.scala
Labels: enhancement, new-feature, DON'T MERGE

#13827 2023-05-25-explain_document_md_fr
  docs/_posts/ahmedlone127/2023-05-25-explain_document_md_fr.md
Labels: new model

#13826 2023-05-25-distilcamembert_french_legal_fr
  docs/_posts/Mary-Sci/2023-05-25-camembert_french_legal_fr.md
  docs/_posts/Mary-Sci/2023-05-25-distilcamembert_french_legal_fr.md
Labels: new model

#13838 2023-05-28-longformer_base_english_legal_en
  docs/_posts/Mary-Sci/2023-05-28-longformer_base_english_legal_en.md
Labels: new model

#13839 2023-05-28-xlm_longformer_base_english_legal_en
  docs/_posts/Mary-Sci/2023-05-28-longformer_large_english_legal_en.md
  docs/_posts/Mary-Sci/2023-05-28-xlm_longformer_base_english_legal_en.md
Labels: new model
