Repository JohnSnowLabs/spark-nlp, pull requests merged in 2023-10, with the labels that each got.

#14009 SPARKNLP-907 Allows setting up ONNX configs through spark session
  examples/python/transformers/onnx/ONNX_Configs_in_Spark_NLP_AlbertForQuestionAnswering.ipynb
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
  src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
Labels: new-feature, DON'T MERGE

#14014 Adding ONNX support for DistilBertClassification
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DistilBertForQuestionAnswering.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DistilBertForSequenceClassification.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DistilBertForTokenClassification.ipynb
  src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForZeroShotClassification.scala
Labels: new-feature, DON'T MERGE

#14015 SPARKNLP-919: Add note for Spark Version support
  docs/en/transformer_entries/WhisperForCTC.md
  examples/python/annotation/audio/whisper/Automatic_Speech_Recognition_Whisper_(WhisperForCTC).ipynb
  examples/python/transformers/HuggingFace in Spark NLP - WhisperForCTC.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_Whisper.ipynb
  python/sparknlp/annotator/audio/whisper_for_ctc.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/audio/WhisperForCTC.scala
Labels: documentation

#14022 SPARKNLP-921: Bug Fix for BPE and RobertaForQA
  src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
  src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/GPT2Transformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BartTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2Tokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/RobertaTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/XlmTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/LongformerEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaSentenceEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForQuestionAnsweringTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizerBehaviours.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2TokenizerTestSpec.scala
Labels: bug-fix

#14024 Adding ONNX support for RobertaClassification
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_RoBertaForQuestionAnswering.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_RoBertaForSequenceClassification.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_RoBertaForTokenClassification.ipynb
  src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/ZeroShotNerClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/LongformerForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/ZeroShotNerModel.scala
Labels: new-feature, DON'T MERGE

#14028 WhisperForCTC: Fix for dynamic state tensor sizes
  src/main/scala/com/johnsnowlabs/ml/ai/Whisper.scala
Labels: bug-fix

#14031 [SPARKNLP-934] Fixing return order in computeLogitsWithTF
  src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
Labels: bug-fix, DON'T MERGE

#14035 SPARKNLP-924: DocumentCharacterTextSplitter
  docs/en/annotator_entries/DocumentCharacterTextSplitter.md
  docs/en/annotators.md
  python/sparknlp/annotator/__init__.py
  python/sparknlp/annotator/document_character_text_splitter.py
  python/test/annotator/document_character_text_splitter_test.py
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitter.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DocumentCharacterTextSplitterTest.scala
Labels: new-feature

#14034 Improving Load Model Azure Storage notebook example
  examples/util/Load_Model_from_Azure_Storage.ipynb
Labels: documentation
