Repository JohnSnowLabs/spark-nlp, pull requests merged in 2023-08, with the labels that each got.

#13901 SPARKNLP-738 Enforcing accuracy to 0 and 1 in classifiers
  src/main/scala/com/johnsnowlabs/ml/ai/SentenceDetectorDL.scala
  src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowMultiClassifier.scala
Labels: bug-fix, DON'T MERGE

#13908 SPARKNLP-873 Issue with MarianTransformers models
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
Labels: bug-fix, DON'T MERGE

#13911 BART Bug fix #13898
  src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTestSpec.scala
Labels: bug-fix, DON'T MERGE

#13917 2023-08-07-bart_large_zero_shot_classifier_mnli_en
  docs/_posts/ahmedlone127/2023-08-07-bart_large_zero_shot_classifier_mnli_en.md
Labels: new model

#13922 2023-08-15-gte_base_en
  docs/_posts/maziyarpanahi/2023-08-15-gte_base_en.md
  docs/_posts/maziyarpanahi/2023-08-15-gte_large_en.md
  docs/_posts/maziyarpanahi/2023-08-15-gte_small_en.md
Labels: new model

#13923 2023-08-15-bge_small_en
  docs/_posts/maziyarpanahi/2023-08-15-bge_base_en.md
  docs/_posts/maziyarpanahi/2023-08-15-bge_large_en.md
  docs/_posts/maziyarpanahi/2023-08-15-bge_small_en.md
Labels: new model

#13914 Adding OpenAICompletion and OpenAIEmbeddings components
  examples/util/OpenAICompletion.ipynb
  examples/util/OpenAIEmbeddings.ipynb
  python/sparknlp/annotator/__init__.py
  python/sparknlp/annotator/openai/__init__.py
  python/sparknlp/annotator/openai/openai_completion.py
  python/sparknlp/annotator/openai/openai_embeddings.py
  src/main/scala/com/johnsnowlabs/ml/ai/OpenAICompletion.scala
  src/main/scala/com/johnsnowlabs/ml/ai/OpenAIEmbeddings.scala
  src/main/scala/com/johnsnowlabs/ml/ai/model/CompletionResponse.scala
  src/main/scala/com/johnsnowlabs/ml/ai/model/TextEmbeddingResponse.scala
  src/main/scala/com/johnsnowlabs/util/ConfigHelper.scala
  src/main/scala/com/johnsnowlabs/util/ConfigLoader.scala
  src/main/scala/com/johnsnowlabs/util/JsonBuilder.scala
  src/test/scala/com/johnsnowlabs/ml/ai/OpenAICompletionTest.scala
  src/test/scala/com/johnsnowlabs/ml/ai/OpenAIEmbeddingsTest.scala
  src/test/scala/com/johnsnowlabs/util/JsonBuilderTest.scala
Labels: new-feature, DON'T MERGE

#13916 SPARKNLP-853: Introducing MPNet Sentence Embeddings like all_mpnet_base_v2
  python/sparknlp/annotator/embeddings/__init__.py
  python/sparknlp/annotator/embeddings/mpnet_embeddings.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/embeddings/mpnet_embeddings_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/MPNet.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/MPNetEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/MPNetEmbeddingsTestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#13918 [SPARKNLP-624] WhisperForCTC
  docs/en/annotators.md
  docs/en/transformer_entries/WhisperForCTC.md
  examples/python/transformers/HuggingFace in Spark NLP - WhisperForCTC.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_Whisper.ipynb
  python/sparknlp/annotator/audio/__init__.py
  python/sparknlp/annotator/audio/whisper_for_ctc.py
  python/sparknlp/common/properties.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/audio/whisper_for_ctc_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/Whisper.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/GenerationConfig.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/ForcedTokenLogitProcessor.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/SuppressLogitProcessor.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Search/BeamSearchScorer.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/TensorResources.scala
  src/main/scala/com/johnsnowlabs/ml/util/LinAlg.scala
  src/main/scala/com/johnsnowlabs/ml/util/LoadExternalModel.scala
  src/main/scala/com/johnsnowlabs/nlp/HasGeneratorProperties.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/audio/WhisperForCTC.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/audio/feature_extractor/AudioUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/audio/feature_extractor/Preprocessor.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/audio/feature_extractor/PreprocessorAttributes.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/audio/feature_extractor/WhisperPreprocessor.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/BartTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Gpt2Tokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/WhisperTokenDecoder.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/resources/audio/configs/preprocessor_config_whisper.json
  src/test/resources/audio/csv/mel_filters.csv
  src/test/resources/audio/txt/librispeech_asr_0.txt
  src/test/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitProcess/LogitProcessorTest.scala
  src/test/scala/com/johnsnowlabs/ml/util/LinAlgTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/audio/WhisperForCTCTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/audio/feature_extractor/AudioUtilsTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/audio/feature_extractor/PreprocessorTestSpec.scala
  src/test/scala/com/johnsnowlabs/util/TestUtils.scala
Labels: new-feature, DON'T MERGE

#13920 Sparknlp 821 implement bart for zero shot classification annotator
  python/sparknlp/annotator/classifier_dl/__init__.py
  python/sparknlp/annotator/classifier_dl/bart_for_zero_shot_classification.py
  python/sparknlp/annotator/classifier_dl/roberta_for_zero_shot_classification.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/classifier_dl/bart_for_zero_shot_classification_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/BartClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BartForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BartForZeroShotClassificationTestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#13927 SPARKNLP-862 Adding ONNX support for E5 Embeddings
  src/main/scala/com/johnsnowlabs/ml/ai/E5.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/E5Embeddings.scala
Labels: new-feature, DON'T MERGE

#13931 2023-08-22-asr_whisper_tiny_opt_xx
  docs/_posts/DevinTDHa/2023-08-22-asr_whisper_tiny_opt_xx.md
  docs/_posts/DevinTDHa/2023-08-22-asr_whisper_tiny_xx.md
Labels: new model

#13939 2023-08-25-e5_small_en
  docs/_posts/ahmedlone127/2023-08-25-e5_base_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_base_opt_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_base_quantized_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_base_v2_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_base_v2_opt_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_base_v2_quantized_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_large_v2_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_small_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_small_opt_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_small_quantized_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_small_v2_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_small_v2_opt_en.md
  docs/_posts/ahmedlone127/2023-08-25-e5_small_v2_quantized_en.md
Labels: new model
