Repository JohnSnowLabs/spark-nlp, pull requests merged in 2024-03, with the labels that each got.

#14186 [SPARKNLP-994] Solves ZeroShotNerClassification Issue
  docs/_posts/maziyarpanahi/2023-02-08-zero_shot_ner_roberta_en.md
  src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/ZeroShotNerClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/ner/dl/ZeroShotNerModel.scala
Labels: bug-fix, DON'T MERGE

#14202 Add MPNetEmbeddings to annotator
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
Labels: bug-fix

#14206 SPARKNLP-1026: Fix documentation for sparknlp.start()
  docs/en/install.md
  python/docs/getting_started/index.rst
Labels: documentation
