Repository JohnSnowLabs/spark-nlp, pull requests merged in 2024-05, with the labels that each got.

#14246 2024-05-06-deepa_xlmroberta_ner_large_en_panx_en
  docs/_posts/SaiDeepaPeri/2024-05-06-deepa_xlmroberta_ner_large_en_panx_en.md
  docs/_posts/SaiDeepaPeri/2024-05-06-deepa_xlmroberta_ner_large_panx_dataset_en.md
Labels: new model

#14233 Closed the S3 connection
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
Labels: bug-fix

#14255 openVINO Dependencies
  build.sbt
  project/Dependencies.scala
Labels: dependencies

#14236 [SPARKNLP-1037] Adding addFile changes to to replace broadcast in all ONNX based annotators
  src/main/scala/com/johnsnowlabs/ml/ai/M2M100.scala
  src/main/scala/com/johnsnowlabs/ml/ai/Whisper.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/audio/WhisperForCTC.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DistilBertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MPNetForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/MPNetForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/CLIPForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/LLAMA2Transformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/M2M100Transformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/MarianTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/T5Transformer.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/AlbertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BGEEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/BertSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/CamemBertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DeBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/DistilBertEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/E5Embeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/MPNetEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/RoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UAEEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/XlmRoBertaSentenceEmbeddings.scala
  src/main/scala/com/johnsnowlabs/util/ZipArchiveUtil.scala
  src/test/scala/com/johnsnowlabs/ml/onnx/OnnxWrapperTestSpec.scala
Labels: enhancement, bug-fix, DON'T MERGE

#14249 Fixing colab notebook bugs
  examples/python/transformers/HuggingFace in Spark NLP - BERT Sentence.ipynb
  examples/python/transformers/HuggingFace in Spark NLP - CamemBertForTokenClassification.ipynb
  examples/python/transformers/HuggingFace in Spark NLP - Longformer.ipynb
  examples/python/transformers/HuggingFace in Spark NLP - LongformerForQuestionAnswering.ipynb
  examples/python/transformers/HuggingFace in Spark NLP - XLNet.ipynb
  examples/python/transformers/HuggingFace in Spark NLP - XlmRoBertaForSequenceClassification.ipynb
  examples/python/transformers/HuggingFace in Spark NLP - XlmRoBertaForTokenClassification.ipynb
  examples/python/transformers/HuggingFace in Spark NLP - XlmRobertaForQuestionAnswering.ipynb
  examples/python/transformers/HuggingFace_in_Spark_NLP_BERT_Sentence.ipynb
  examples/python/transformers/HuggingFace_in_Spark_NLP_CamemBertForTokenClassification.ipynb
  examples/python/transformers/HuggingFace_in_Spark_NLP_Longformer.ipynb
  examples/python/transformers/HuggingFace_in_Spark_NLP_LongformerForQuestionAnswering.ipynb
  examples/python/transformers/HuggingFace_in_Spark_NLP_XLNet.ipynb
  src/main/scala/com/johnsnowlabs/ml/ai/Xlnet.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForTokenClassification.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForQuestionAnsweringTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForTokenClassificationTestSpec.scala
Labels: enhancement, bug-fix

#14232 Adding caching to streamlit demos
  examples/demos/streamlit/CLIPForZeroShotClassification/input/bluetick.jpg
  examples/demos/streamlit/CLIPForZeroShotClassification/input/chihuahua.jpg
  examples/demos/streamlit/CLIPForZeroShotClassification/input/egyptian_cat.jpeg
  examples/demos/streamlit/CLIPForZeroShotClassification/input/hen.JPEG
  examples/demos/streamlit/CLIPForZeroShotClassification/input/hippopotamus.JPEG
  examples/demos/streamlit/CLIPForZeroShotClassification/input/junco.JPEG
  examples/demos/streamlit/CLIPForZeroShotClassification/input/ostrich.JPEG
  examples/demos/streamlit/CLIPForZeroShotClassification/input/ox.JPEG
  examples/demos/streamlit/CLIPForZeroShotClassification/input/palace.JPEG
  examples/demos/streamlit/CLIPForZeroShotClassification/input/tractor.JPEG
  examples/demos/streamlit/CLIPForZeroShotClassification/streamlit_app.py
  examples/demos/streamlit/Question Answering Closed Book/streamlit_app.py
  examples/demos/streamlit/Question Answering Open Book/streamlit_app.py
  examples/demos/streamlit/Sentence Detector/streamlit_app.py
  examples/demos/streamlit/Sentence Grammer/streamlit_app.py
  examples/demos/streamlit/Sentence Similarity/streamlit_app.py
  examples/demos/streamlit/Sentiment Cyber Bullying/streamlit_app.py
  examples/demos/streamlit/Sentiment DA/streamlit_app.py
  examples/demos/streamlit/Sentiment DE/streamlit_app.py
  examples/demos/streamlit/Sentiment EN Emotion/streamlit_app.py
  examples/demos/streamlit/Sentiment EN Finance/streamlit_app.py
  examples/demos/streamlit/Sentiment EN Sarcasm/streamlit_app.py
  examples/demos/streamlit/Sentiment EN Toxic/streamlit_app.py
  examples/demos/streamlit/Sentiment EN/streamlit_app.py
  examples/demos/streamlit/Sentiment FR/streamlit_app.py
  examples/demos/streamlit/Sentiment SW/streamlit_app.py
  examples/demos/streamlit/Sentiment TR/streamlit_app.py
  examples/demos/streamlit/Sentiment UR/streamlit_app.py
  examples/demos/streamlit/Sentiment VI/streamlit_app.py
  examples/demos/streamlit/Speech Recognition/streamlit_app.py
  examples/demos/streamlit/Speech recognition with whisper/streamlit_app.py
  examples/demos/streamlit/Spell Checker EN/streamlit_app.py
  examples/demos/streamlit/StopWords African/streamlit_app.py
  examples/demos/streamlit/StopWords East Asain/streamlit_app.py
  examples/demos/streamlit/StopWords European/streamlit_app.py
  examples/demos/streamlit/StopWords Indian/streamlit_app.py
  examples/demos/streamlit/StopWords Middle Eastern/streamlit_app.py
  examples/demos/streamlit/T5 Active Passive/streamlit_app.py
  examples/demos/streamlit/T5 Formal Informal/streamlit_app.py
  examples/demos/streamlit/T5 Grammer/streamlit_app.py
  examples/demos/streamlit/T5 Linguistic/streamlit_app.py
  examples/demos/streamlit/T5 SQL/streamlit_app.py
  examples/demos/streamlit/Text Finder EN/streamlit_app.py
  examples/demos/streamlit/Text Preprocessing/streamlit_app.py
  examples/demos/streamlit/Text Summarization/streamlit_app.py
  examples/demos/streamlit/Text summarization with BART/streamlit_app.py
  examples/demos/streamlit/Translation Marian/streamlit_app.py
  examples/demos/streamlit/Typo Detector/streamlit_app.py
  examples/demos/streamlit/VIT Image Classification/streamlit_app.py
  examples/demos/streamlit/run_demos.ipynb
Labels: enhancement, documentation
