Repository JohnSnowLabs/spark-nlp, pull requests merged in 2024-09, with the labels that each got.

#14188 SparkNLP 997 Introducing QWEN2Transformer
  python/sparknlp/annotator/seq2seq/__init__.py
  python/sparknlp/annotator/seq2seq/qwen_transformer.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/seq2seq/qwen_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/Qwen.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/QwenTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/QwenTokenizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/QwenTestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#14205 SparkNLP 1004 - Introducing MiniCPM
  python/sparknlp/annotator/seq2seq/__init__.py
  python/sparknlp/annotator/seq2seq/cpm_transformer.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/seq2seq/cpm_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/CPM.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/CPMTransformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/CPMTestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#14209 SparkNLP 1018 - Introducing NLLB
  python/sparknlp/annotator/seq2seq/__init__.py
  python/sparknlp/annotator/seq2seq/nllb_transformer.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/seq2seq/nllb_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/NLLB.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/NLLBTransformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/NLLBTestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#14217 SparkNLP 1005 implement nomic embeddings
  python/sparknlp/annotator/embeddings/__init__.py
  python/sparknlp/annotator/embeddings/nomic_embeddings.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/embeddings/nomic_embeddings_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/Nomic.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/NomicEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/NomicEmbeddingsTestSpec.scala
Labels: new-feature, new model

#14361 [SPARKNLP-855] Introducing AlbertForZeroShotClassification
  examples/python/transformers/HuggingFace_in_Spark_NLP_AlbertForZeroShotClassification.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_AlbertForZeroShotClassification.ipynb
  python/sparknlp/annotator/classifier_dl/__init__.py
  python/sparknlp/annotator/classifier_dl/albert_for_zero_shot_classification.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/classifier_dl/albert_for_zero_shot_classification_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/AlbertForZeroShotClassificationTestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#14382 OpenVINO install instructions
  docs/en/install.md
  src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
Labels: documentation

#14364 [SPARKNLP-1027] llama.cpp integration
  build.sbt
  docs/en/annotator_entries/AutoGGUF.md
  docs/en/annotators.md
  examples/python/llama.cpp/llama.cpp_in_Spark_NLP_AutoGGUFModel.ipynb
  project/Dependencies.scala
  python/setup.py
  python/sparknlp/annotator/seq2seq/__init__.py
  python/sparknlp/annotator/seq2seq/auto_gguf_model.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/seq2seq/auto_gguf_model_test.py
  src/main/resources/log4j.properties
  src/main/resources/log4j2.properties
  src/main/scala/com/johnsnowlabs/ml/gguf/GGUFWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/HasLlamaCppProperties.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFModel.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/resources/log4j.properties
  src/test/resources/log4j2.properties
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFModelTest.scala
Labels: new-feature, dependencies, DON'T MERGE

#14390 Adding openvino support to missing annotators
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_CamemBertForQuestionAnswering.ipynb
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_CamemBertForSequenceClassification.ipynb
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_CamemBertForTokenClassification.ipynb
  python/sparknlp/annotator/classifier_dl/__init__.py
  src/main/scala/com/johnsnowlabs/ml/ai/CamemBertClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/CamemBertForQuestionAnsweringTestSpec.scala
Labels: new-feature, DON'T MERGE

#14410 2024-09-23-phi3.5_mini_4k_instruct_q4_gguf_en
  docs/_posts/DevinTDHa/2024-09-23-phi3.5_mini_4k_instruct_q4_gguf_en.md
Labels: new model

#14411 [SPARKNLP-1027] Change Default AutoGGUF pretrained model
  docs/en/annotator_entries/AutoGGUF.md
  python/sparknlp/annotator/seq2seq/auto_gguf_model.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFModel.scala
Labels: new model
