Repository JohnSnowLabs/spark-nlp, pull requests merged in 2024-06, with the labels that each got.

#14308 LLAMA2 OpenVINO Position ID Fix
  src/main/scala/com/johnsnowlabs/ml/ai/LLAMA2.scala
Labels: enhancement, bug-fix

#14313 Uploading OpenVINO example notebooks
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_BERT.ipynb
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_E5.ipynb
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_LLama2.ipynb
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_RoBERTa.ipynb
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_T5.ipynb
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_XLM_RoBERTa.ipynb
Labels: documentation

#14320 Fixed LLAMA generation bug
  src/main/scala/com/johnsnowlabs/ml/ai/LLAMA2.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/TopKLogitWarper.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Logit/LogitWarper/TopPLogitWarper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/LLAMA2Transformer.scala
Labels: enhancement, bug-fix

#14324 uploading UAEEmbeddings notebook
  examples/python/annotation/text/english/sentence-embeddings/UAEEmbeddings.ipynb
Labels: documentation, DON'T MERGE

#14334 Refactor OpenAIEmbeddings
  python/com/johnsnowlabs/ml/__init__.py
  python/com/johnsnowlabs/ml/ai/__init__.py
  python/sparknlp/__init__.py
  python/sparknlp/annotator/openai/openai_embeddings.py
  python/test/annotator/embeddings/open_ai_embeddings_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/OpenAIEmbeddings.scala
  src/test/scala/com/johnsnowlabs/ml/ai/OpenAIEmbeddingsTest.scala
Labels: bug-fix
