Repository JohnSnowLabs/spark-nlp, pull requests merged in 2024-12, with the labels that each got.

#14472 2024-12-06-bert_embeddings_sec_bert_base_en
  docs/_posts/gadde5300/2024-12-06-bert_embeddings_sec_bert_base_en.md
Labels: new model

#14422 [SPARKNLP-1068] Introducing BLIPForQuestionAnswering transformer
  examples/python/transformers/HuggingFace_in_Spark_NLP_BLIPForQuestionAnswering.ipynb
  python/sparknlp/annotator/cv/__init__.py
  python/sparknlp/annotator/cv/blip_for_question_answering.py
  python/sparknlp/base/image_assembler.py
  python/sparknlp/base/light_pipeline.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/cv/blip_for_question_answering_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/BLIPClassifier.scala
  src/main/scala/com/johnsnowlabs/nlp/AnnotationImage.scala
  src/main/scala/com/johnsnowlabs/nlp/HasBatchedAnnotateImage.scala
  src/main/scala/com/johnsnowlabs/nlp/ImageAssembler.scala
  src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/BLIPForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BertTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/PretrainedPipeline.scala
  src/test/scala/com/johnsnowlabs/nlp/AssertAnnotations.scala
  src/test/scala/com/johnsnowlabs/nlp/ImageAssemblerTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/BLIPForQuestionAnsweringTest.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/CLIPForZeroShotClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/ViTImageClassificationTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/VisionEncoderDecoderForImageCaptioningTestSpec.scala
Labels: Feature request, enhancement, DON'T MERGE

#14451 [SPARKNLP-1095] Add installation instructions for ONNX GPU on Databricks
  docs/en/install.md
Labels: documentation

#14476 SPARKNLP-1094 Adding Support to Read Word Files
  build.sbt
  docs/en/advanced_settings.md
  examples/python/reader/SparkNLP_Email_Reader_Demo.ipynb
  examples/python/reader/SparkNLP_HTML_Reader_Demo.ipynb
  examples/python/reader/SparkNLP_Word_Reader_Demo.ipynb
  project/Dependencies.scala
  python/sparknlp/reader/sparknlp_reader.py
  python/test/sparknlp_test.py
  src/main/scala/com/johnsnowlabs/reader/ElementType.scala
  src/main/scala/com/johnsnowlabs/reader/SparkNLPReader.scala
  src/main/scala/com/johnsnowlabs/reader/WordReader.scala
  src/main/scala/com/johnsnowlabs/reader/util/DocParser.scala
  src/main/scala/com/johnsnowlabs/reader/util/DocxParser.scala
  src/test/resources/reader/doc/contains-pictures.docx
  src/test/resources/reader/doc/fake_table.docx
  src/test/resources/reader/doc/page-breaks.docx
  src/test/scala/com/johnsnowlabs/reader/WordReaderTest.scala
Labels: new-feature
