Repository JohnSnowLabs/spark-nlp, pull requests merged in 2024-04, with the labels that each got.

#14196 Uploading missing notebooks from Spark NLP v 5.1.4
  examples/python/annotation/text/english/DocumentCharacterTextSplitter.ipynb
  examples/python/annotation/text/english/language-translation/Multilingual_Translation_with_M2M100.ipynb
  examples/python/annotation/text/english/question-answering/MPNetForQuestionAnswering.ipynb
  examples/python/annotation/text/english/sentence-embeddings/BGEEmbeddings.ipynb
  examples/python/annotation/text/english/sentence-embeddings/MPNetEmbeddings.ipynb
  examples/python/annotation/text/english/sequence-classification/MPNetForSequenceClassification.ipynb
  examples/python/annotation/text/english/zero-shot text classification/DeBertaForZeroShotClassification.ipynb
Labels: documentation, DON'T MERGE

#14199 SPARKNLP-962: UAEEmbeddings
  docs/en/annotators.md
  docs/en/transformer_entries/UAEEmbeddings.md
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_E5.ipynb
  python/sparknlp/annotator/embeddings/__init__.py
  python/sparknlp/annotator/embeddings/uae_embeddings.py
  python/sparknlp/internal/__init__.py
  python/sparknlp/pretrained/resource_downloader.py
  python/test/annotator/embeddings/uae_embeddings_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/UAE.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
  src/main/scala/com/johnsnowlabs/ml/util/LinAlg.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/embeddings/UAEEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/ml/util/LinAlgTest.scala
  src/test/scala/com/johnsnowlabs/nlp/embeddings/UAEEmbeddingsTestSpec.scala
Labels: bug-fix, new-feature

#14224 Cache mechanism implementation for metadata.json
  src/main/scala/com/johnsnowlabs/nlp/pretrained/RepositoryMetadata.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/S3ResourceDownloader.scala
Labels: new-feature, DON'T MERGE

#14225 [SPARKNLP-1031] Solves Dependency Parsers training issue
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserApproach.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/DependencyInstance.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/DependencyPipe.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/LocalFeatureData.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/io/ConllUReader.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/io/DependencyReader.java
  src/main/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/util/Dictionary.java
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserApproachTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserBehaviors.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/dep/DependencyParserModelTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyModelTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/parser/typdep/TypedDependencyParserApproachTestSpec.scala
Labels: bug-fix, DON'T MERGE

#14241 2024-04-22-mpnet_embeddings_biolord_2023_en
  docs/_posts/akrztrk/2024-04-22-mpnet_embeddings_biolord_2023_en.md
Labels: new model
