Repository JohnSnowLabs/spark-nlp, pull requests merged in 2024-10, with the labels that each got.

#14428 tasks-docs-integration
  docs/_data/navigation.yml
  docs/en/tasks/automatic_speech_recognition.md
  docs/en/tasks/dependency_parsing.md
  docs/en/tasks/image_captioning.md
  docs/en/tasks/image_classification.md
  docs/en/tasks/landing_page.md
  docs/en/tasks/question_answering.md
  docs/en/tasks/summarization.md
  docs/en/tasks/table_question_answering.md
  docs/en/tasks/text_classification.md
  docs/en/tasks/text_generation.md
  docs/en/tasks/text_preprocessing.md
  docs/en/tasks/token_classification.md
  docs/en/tasks/translation.md
  docs/en/tasks/zero_shot_classification.md
  docs/en/tasks/zero_shot_image_classification.md
Labels: documentation

#14435 Introducing BertForMultipleChoice transformer
  python/sparknlp/annotator/classifier_dl/__init__.py
  python/sparknlp/annotator/classifier_dl/bert_for_multiple_choice.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/classifier_dl/bert_for_multiple_choice_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/XXXForClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/PrepareEmbeddings.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForMultipleChoice.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/BertForMultipleChoiceTestSpec.scala
Labels: new-feature, DON'T MERGE

#14440 2024-10-21-bge_medembed_small_v0_1_en
  docs/_posts/Cabir40/2024-10-21-bge_medembed_base_v0_1_en.md
  docs/_posts/Cabir40/2024-10-21-bge_medembed_large_v0_1_en.md
  docs/_posts/Cabir40/2024-10-21-bge_medembed_small_v0_1_en.md
Labels: new model

#14438 Fix pretrained models not being found on dbfs systems
  src/main/scala/com/johnsnowlabs/ml/gguf/GGUFWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/AutoGGUFModel.scala
Labels: bug-fix

#14423 2024-10-03-blip_vqa_base_en
  docs/_posts/danilojsl/2024-10-03-blip_vqa_base_en.md
Labels: new model

#14432 2024-10-10-gemma_2_2b_it_iq3_m_en
  docs/_posts/ahmedlone127/2024-10-10-gemma_2_2b_it_iq3_m_en.md
  docs/_posts/ahmedlone127/2024-10-10-gemma_2_2b_it_iq4_xs_en.md
  docs/_posts/ahmedlone127/2024-10-10-gemma_2_2b_it_q3_k_l_en.md
  docs/_posts/ahmedlone127/2024-10-10-gemma_2_2b_it_q4_k_m_en.md
  docs/_posts/ahmedlone127/2024-10-10-gemma_2_2b_it_q5_k_m_en.md
  docs/_posts/ahmedlone127/2024-10-10-gemma_2_2b_it_q6_k_en.md
  docs/_posts/ahmedlone127/2024-10-10-gemma_2_2b_it_q8_0_en.md
  docs/_posts/ahmedlone127/2024-10-10-llama_3.2_3b_instruct_q3_k_l_xx.md
  docs/_posts/ahmedlone127/2024-10-10-llama_3.2_3b_instruct_q4_k_m_xx.md
  docs/_posts/ahmedlone127/2024-10-11-sent_roberta_base_en.md
  docs/_posts/ahmedlone127/2024-10-11-snowflake_artic_m_en.md
  docs/_posts/ahmedlone127/2024-10-13-uae_large_v1_en.md
  docs/_posts/ahmedlone127/2024-10-14-sent_xlm_roberta_base_xx.md
  docs/_posts/ahmedlone127/2024-10-16-asr_hubert_large_ls960_en.md
  docs/_posts/ahmedlone127/2024-10-17-asr_wav2vec2_base_960h_en.md
  docs/_posts/ahmedlone127/2024-10-18-zero_shot_classifier_clip_vit_base_patch32_en.md
  docs/_posts/ahmedlone127/2024-10-19-image_classifier_convnext_tiny_224_local_en.md
  docs/_posts/ahmedlone127/2024-10-19-image_classifier_swin_base_patch4_window7_224_en.md
  docs/_posts/ahmedlone127/2024-10-19-image_classifier_vit_base_patch16_224_en.md
  docs/_posts/ahmedlone127/2024-10-20-image_captioning_vit_gpt2_en.md
  docs/_posts/ahmedlone127/2024-10-28-image_captioning_vit_gpt2_en.md
  docs/_posts/ahmedlone127/2024-10-29-gemma_2_2b_it_iq3_m_en.md
  docs/_posts/ahmedlone127/2024-10-29-gemma_2_2b_it_iq4_xs_en.md
  docs/_posts/ahmedlone127/2024-10-29-gemma_2_2b_it_q3_k_l_en.md
  docs/_posts/ahmedlone127/2024-10-29-gemma_2_2b_it_q4_k_m_en.md
  docs/_posts/ahmedlone127/2024-10-29-llama_3.2_3b_instruct_q3_k_l_xx.md
  docs/_posts/ahmedlone127/2024-10-29-llama_3.2_3b_instruct_q4_k_m_xx.md
  docs/_posts/ahmedlone127/2024-10-29-llama_3.2_3b_instruct_q6_k_xx.md
  docs/_posts/ahmedlone127/2024-10-29-llama_3.2_3b_instruct_q8_0_xx.md
Labels: new model
