Repository JohnSnowLabs/spark-nlp, pull requests merged in 2024-01, with the labels that each got.

#14116 2024-01-01-bge_small_en
  docs/_posts/maziyarpanahi/2024-01-01-bge_base_en.md
  docs/_posts/maziyarpanahi/2024-01-01-bge_large_en.md
  docs/_posts/maziyarpanahi/2024-01-01-bge_small_en.md
Labels: new model

#14131 2024-01-10-mpnet_sequence_classifier_ukr_message_en
  docs/_posts/DevinTDHa/2024-01-10-mpnet_sequence_classifier_ukr_message_en.md
Labels: new model

#14123 HuggingFace_ONNX_in_Spark_NLP_RoBertaForTokenClassification updated
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_RoBertaForTokenClassification.ipynb
Labels: documentation

#14126 adding notebooks for onnx Deberta Import from Huggingface
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DeBertaForQuestionAnswering.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DeBertaForSequenceClassification.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_DeBertaForTokenClassification.ipynb
Labels: documentation

#14130 Sparknlp 967 add onnx support to xlm roberta classifiers
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_XlmRoBertaForQuestionAnswering.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_XlmRoBertaForSequenceClassification.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_XlmRoBertaForTokenClassification.ipynb
  src/main/scala/com/johnsnowlabs/ml/ai/AlbertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/BertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/CamemBertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/DeBertaClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/DistilBertClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/ml/ai/XlmRoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForQuestionAnswering.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForSequenceClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForTokenClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForZeroShotClassification.scala
Labels: new-feature

#14133 adding BGEEmbeddings to resource downloader
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
Labels: bug-fix

#14135 adding missing notebooks
  examples/python/transformers/HuggingFace_in_Spark_NLP_DeBertaForSequenceClassification.ipynb
  examples/python/transformers/HuggingFace_in_Spark_NLP_DeBertaForTokenClassification.ipynb
Labels: documentation

#14136 [SPARKNLP-978] Refactoring to use aws-java-sdk-s3 library
  build.sbt
  project/Dependencies.scala
  src/main/scala/com/johnsnowlabs/client/aws/AWSGateway.scala
  src/main/scala/com/johnsnowlabs/client/azure/AzureClient.scala
  src/main/scala/com/johnsnowlabs/ml/ai/OpenAICompletion.scala
  src/main/scala/com/johnsnowlabs/ml/ai/OpenAIEmbeddings.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/DateMatcherMultiLanguageTestSpec.scala
Labels: enhancement, dependencies, DON'T MERGE
