Repository JohnSnowLabs/spark-nlp, pull requests merged in 2024-02, with the labels that each got.

#14157 2024-02-01-bert_zero_shot_classifier_mnli_xx
  docs/_posts/ahmedlone127/2024-02-01-bert_zero_shot_classifier_mnli_xx.md
Labels: new model

#14132 [Issue#14129] Fix for spark.jsl.settings.storage.cluster_tmp_dir configuration
  src/main/scala/com/johnsnowlabs/storage/StorageLocator.scala
Labels: bug-fix, fixed-next-release, DON'T MERGE

#14146 2024-01-20-mpnet_base_question_answering_squad2_en
  docs/_posts/DevinTDHa/2024-01-20-mpnet_base_question_answering_squad2_en.md
Labels: new model

#14148 Sparknlp 876: Introducing LLAMA2
  python/sparknlp/annotator/seq2seq/__init__.py
  python/sparknlp/annotator/seq2seq/llama2_transformer.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/seq2seq/llama2_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/Bart.scala
  src/main/scala/com/johnsnowlabs/ml/ai/LLAMA2.scala
  src/main/scala/com/johnsnowlabs/ml/ai/VisionEncoderDecoder.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/util/LoadExternalModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/LLAMA2Transformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/LLAMA2TestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#14151 812 implement de berta for zero shot classification annotator
  examples/python/transformers/HuggingFace_in_Spark_NLP_DeBertaForZeroShotClassification.ipynb
  python/sparknlp/annotator/classifier_dl/__init__.py
  python/sparknlp/annotator/classifier_dl/deberta_for_zero_shot_classification.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/classifier_dl/deberta_for_zero_shot_classification_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/DeBertaClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotator.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForZeroShotClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/DeBertaForZeroShotClassificationTestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#14152 SPARKNLP-886: Add Fine tuned sentence bert notebook
  docs/en/transformers.md
  examples/python/transformers/Fine_Tuned_Sentence_Bert_in_Spark_NLP.ipynb
Labels: documentation

#14153 [SPARKNLP-986] Fixing optional input col validations
  python/sparknlp/annotator/er/entity_ruler.py
  python/sparknlp/base/light_pipeline.py
  python/test/annotator/er/entity_ruler_test.py
  src/main/scala/com/johnsnowlabs/nlp/LightPipeline.scala
  src/test/resources/entity-ruler/url_regex.json
Labels: bug-fix, DON'T MERGE

#14154 [SPARKNLP-984] Fixing Deberta notebooks URIs
  examples/python/transformers/HuggingFace_in_Spark_NLP_DeBertaForSequenceClassification.ipynb
  examples/python/transformers/HuggingFace_in_Spark_NLP_DeBertaForTokenClassification.ipynb
Labels: documentation, DON'T MERGE

#14155 SparkNLP 933: Introducing M2M100 : multilingual translation model
  python/sparknlp/annotator/seq2seq/__init__.py
  python/sparknlp/annotator/seq2seq/m2m100_transformer.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/seq2seq/m2m100_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/M2M100.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/M2M100Transformer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/M2M100TestSpec.scala
Labels: new-feature, new model, DON'T MERGE

#14167 [SPARKNLP-940] Adding changes to correctly copy cluster index storage…
  build.sbt
  examples/util/Load_Model_from_GCP_Storage.ipynb
  src/main/scala/com/johnsnowlabs/storage/RocksDBConnection.scala
  src/main/scala/com/johnsnowlabs/storage/StorageHelper.scala
Labels: bug-fix, DON'T MERGE

#14170 2024-02-11-bge_m3_xx
  docs/_posts/ahmedlone127/2024-02-11-bge_m3_xx.md
Labels: new model

#14177 SPARKNLP-1000: Fix No Operation named [init_all_tables] for GPT2
  src/main/scala/com/johnsnowlabs/ml/ai/GPT2.scala
Labels: bug-fix, DON'T MERGE
