Repository JohnSnowLabs/spark-nlp, pull requests merged in 2025-03, with the labels that each got.

#14242 SPARKNLP-1006: Introducing OLMo
  docs/en/transformer_entries/OLMoTransformer.md
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_OLMO.ipynb
  python/sparknlp/annotator/seq2seq/__init__.py
  python/sparknlp/annotator/seq2seq/olmo_transformer.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/seq2seq/olmo_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/OLMo.scala
  src/main/scala/com/johnsnowlabs/ml/ai/util/Generation/Generate.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxSerializeModel.scala
  src/main/scala/com/johnsnowlabs/ml/onnx/OnnxWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/OLMoTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeSpecialTokens.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/OLMoTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/OLMoTestSpec.scala
Labels: new-feature, DON'T MERGE

#14444 Sparknlp 1060 implement phi 3.5 vision
  docs/en/transformer_entries/Phi3Vision.md
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_Phi3Vision.ipynb
  python/sparknlp/annotator/cv/__init__.py
  python/sparknlp/annotator/cv/phi3_vision_for_multimodal.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/cv/phi3_vision_for_multimodal_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/Phi3V.scala
  src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/util/LoadExternalModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/Phi3Vision.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/util/transform/Phi3vUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Phi3VisionTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/Phi3VisionTestSpec.scala
Labels: new-feature, DON'T MERGE

#14450 SparkNLP 1033: Introducing LLAVA
  docs/en/transformer_entries/LLAVAForMultiModal.md
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_LLAVA.ipynb
  python/sparknlp/annotator/cv/__init__.py
  python/sparknlp/annotator/cv/llava_for_multimodal.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/cv/llava_for_multimodal_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/LLaVA.scala
  src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/LLAVAForMultiModal.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/LLAVATokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/LLAVAForMultiModalTestSpec.scala
Labels: new-feature, DON'T MERGE

#14457 SparkNLP 1032: Introducing CoHere
  docs/en/transformer_entries/CoHereTransformer.md
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_CoHere.ipynb
  python/sparknlp/annotator/seq2seq/__init__.py
  python/sparknlp/annotator/seq2seq/cohere_transformer.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/seq2seq/cohere_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/CoHere.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/seq2seq/CoHereTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/seq2seq/CoHereTestSpec.scala
Labels: new-feature, DON'T MERGE

#14474 SparkNLP 1077- Introducing Qwen2 - VL
  docs/en/transformer_entries/Qwen2VLTransformer.md
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_Qwen2VL.ipynb
  python/sparknlp/annotator/cv/__init__.py
  python/sparknlp/annotator/cv/qwen2vl_transformer.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/cv/qwen2vl_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/Qwen2VL.scala
  src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/util/LoadExternalModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/Qwen2VLTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/feature_extractor/Preprocessor.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/util/transform/Qwen2VLUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/Qwen2VLTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/Qwen2VLTransformerTestSpec.scala
Labels: new-feature, DON'T MERGE

#14489 [SPARKNLP-1102] Adding support to read Excel files
  examples/python/reader/SparkNLP_Email_Reader_Demo.ipynb
  examples/python/reader/SparkNLP_Excel_Reader_Demo.ipynb
  examples/python/reader/SparkNLP_HTML_Reader_Demo.ipynb
  examples/python/reader/SparkNLP_Word_Reader_Demo.ipynb
  python/sparknlp/reader/sparknlp_reader.py
  python/test/sparknlp_test.py
  src/main/scala/com/johnsnowlabs/reader/EmailReader.scala
  src/main/scala/com/johnsnowlabs/reader/ExcelReader.scala
  src/main/scala/com/johnsnowlabs/reader/HTMLReader.scala
  src/main/scala/com/johnsnowlabs/reader/SparkNLPReader.scala
  src/main/scala/com/johnsnowlabs/reader/WordReader.scala
  src/main/scala/com/johnsnowlabs/reader/util/XlsxParser.scala
  src/test/resources/reader/xls/2023-half-year-analyses-by-segment.xlsx
  src/test/resources/reader/xls/vodafone.xlsx
  src/test/scala/com/johnsnowlabs/reader/EmailReaderTest.scala
  src/test/scala/com/johnsnowlabs/reader/ExcelReaderTest.scala
  src/test/scala/com/johnsnowlabs/reader/HTMLReaderTest.scala
  src/test/scala/com/johnsnowlabs/reader/WordReaderTest.scala
Labels: new-feature, DON'T MERGE

#14491 [SPARKNLP-1103] Adding support to read power point files
  examples/python/reader/SparkNLP_PowerPoint_Reader_Demo.ipynb
  python/sparknlp/reader/sparknlp_reader.py
  python/test/sparknlp_test.py
  src/main/scala/com/johnsnowlabs/reader/ExcelReader.scala
  src/main/scala/com/johnsnowlabs/reader/PowerPointReader.scala
  src/main/scala/com/johnsnowlabs/reader/SparkNLPReader.scala
  src/main/scala/com/johnsnowlabs/reader/WordReader.scala
  src/main/scala/com/johnsnowlabs/reader/util/PptParser.scala
  src/test/resources/reader/ppt/fake-power-point-table.pptx
  src/test/resources/reader/ppt/fake-power-point.pptx
  src/test/scala/com/johnsnowlabs/reader/ExcelReaderTest.scala
  src/test/scala/com/johnsnowlabs/reader/PowerPointTest.scala
Labels: new-feature, DON'T MERGE

#14495 [SPARKNLP-1107] Introducing RoBertaForMultipleChoice
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_RoBERTaForMultipleChoice.ipynb
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_RoBERTaForMultipleChoice.ipynb
  python/sparknlp/annotator/classifier_dl/__init__.py
  python/sparknlp/annotator/classifier_dl/roberta_for_multiple_choice.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/classifier_dl/roberta_for_multiple_choice_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/RoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RoBertaForMultipleChoice.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/RobertaForMultipleChoiceTestSpec.scala
Labels: new-feature, DON'T MERGE

#14497 [SPARKNLP-1108] Introducing XlmRoBertaForMultipleChoice Transformer
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_XlmRoBERTaForMultipleChoice.ipynb
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_XLMRoBERTaForMultipleChoice.ipynb
  python/sparknlp/annotator/classifier_dl/__init__.py
  python/sparknlp/annotator/classifier_dl/xlm_roberta_for_multiple_choice.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/classifier_dl/xlm_roberta_for_multiple_choice_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/XlmRoBertaClassification.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForMultipleChoice.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/XlmRoBertaForMultipleChoiceTestSpec.scala
Labels: new-feature, DON'T MERGE

#14499 [SPARKNLP-1098] Adding PDF reader support
  build.sbt
  examples/python/reader/SparkNLP_PDFToText_Annotator_Demo.ipynb
  examples/python/reader/SparkNLP_PDF_Reader_Demo.ipynb
  project/Dependencies.scala
  python/sparknlp/reader/pdf_to_text.py
  python/sparknlp/reader/sparknlp_reader.py
  python/test/reader/pdf_to_text_test.py
  src/main/scala/com/johnsnowlabs/reader/PdfToText.scala
  src/main/scala/com/johnsnowlabs/reader/SparkNLPReader.scala
  src/main/scala/com/johnsnowlabs/reader/util/pdf/BinaryFile.scala
  src/main/scala/com/johnsnowlabs/reader/util/pdf/HasInputValidator.scala
  src/main/scala/com/johnsnowlabs/reader/util/pdf/HasLocalProcess.scala
  src/main/scala/com/johnsnowlabs/reader/util/pdf/OcrText.scala
  src/main/scala/com/johnsnowlabs/reader/util/pdf/PageNum.scala
  src/main/scala/com/johnsnowlabs/reader/util/pdf/PdfUtils.scala
  src/test/resources/reader/pdf/image_3_pages.pdf
  src/test/resources/reader/pdf/pdf-title.pdf
  src/test/resources/reader/pdf/text_3_pages.pdf
  src/test/scala/com/johnsnowlabs/reader/PdfToTextTest.scala
  src/test/scala/com/johnsnowlabs/reader/SparkNLPReaderTest.scala
Labels: new-feature, DON'T MERGE

#14501 2025-01-18-llava_v1.5_7b_Q4_0_gguf_en
  docs/_posts/DevinTDHa/2025-01-18-llava_v1.5_7b_Q4_0_gguf_en.md
Labels: new model

#14502 Sparknlp 1078 Introducing llama 3.2 vision models
  docs/en/transformer_entries/MLLamaForMultimodal.md
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_MLLama.ipynb
  python/sparknlp/annotator/cv/__init__.py
  python/sparknlp/annotator/cv/mllama_for_multimodal.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/cv/mllama_for_multimodal_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/MLLama.scala
  src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/MLLamaForMultimodal.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/util/transform/MllamaUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/MLLamaTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/resources/images/demo.jpeg
  src/test/resources/images/image1.jpg
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/MLLamaForMultimodalTestSpec.scala
Labels: new-feature, DON'T MERGE

#14512 2025-01-30-starcoder2_3b_int8_en
  docs/_posts/prabod/2025-01-30-starcoder2_3b_int4_en.md
  docs/_posts/prabod/2025-01-30-starcoder2_3b_int8_en.md
  docs/_posts/prabod/2025-02-12-olmo_1b_int4_en.md
  docs/_posts/prabod/2025-02-13-llava_1_5_7b_hf_en.md
  docs/_posts/prabod/2025-02-13-phi_3_vision_128k_instruct_en.md
  docs/_posts/prabod/2025-02-14-qwen2_vl_2b_instruct_int4_en.md
Labels: new model

#14519 SPARKNLP-1109 Adding Extractor to Sparknlp
  examples/python/data-preprocessing/SparkNLP_Cleaner_Demo.ipynb
  examples/python/data-preprocessing/SparkNLP_Email_Data_Preparation.ipynb
  examples/python/data-preprocessing/SparkNLP_Extractor_Demo.ipynb
  python/sparknlp/annotator/cleaners/__init__.py
  python/sparknlp/annotator/cleaners/cleaner.py
  python/sparknlp/annotator/cleaners/extractor.py
  python/test/annotator/cleaners/__init__.py
  python/test/annotator/cleaners/cleaner_test.py
  python/test/annotator/cleaners/extractor_test.py
  src/main/scala/com/johnsnowlabs/nlp/annotators/cleaners/Cleaner.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cleaners/Extractor.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cleaners/util/CleanerHelper.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cleaners/CleanerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cleaners/ExtractorTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cleaners/util/CleanerHelperTestSpec.scala
Labels: new-feature, DON'T MERGE

#14524 [SPARKNLP-1113] Adding Text Reader
  examples/python/reader/SparkNLP_TXT_Reader_Demo.ipynb
  python/sparknlp/reader/sparknlp_reader.py
  python/test/sparknlp_test.py
  src/main/scala/com/johnsnowlabs/reader/SparkNLPReader.scala
  src/main/scala/com/johnsnowlabs/reader/TextReader.scala
  src/test/resources/reader/txt/simple-text.txt
  src/test/scala/com/johnsnowlabs/reader/TextReaderTest.scala
Labels: new-feature, DON'T MERGE

#14532 SparkNLP 1088 - Introducing Deepseek Janus
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_Janus.ipynb
  python/sparknlp/annotator/cv/__init__.py
  python/sparknlp/annotator/cv/janus_for_multimodal.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/cv/janus_for_multimodal_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/Janus.scala
  src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
  src/main/scala/com/johnsnowlabs/ml/util/LoadExternalModel.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/JanusforMultiModal.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/util/io/ImageIOUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/JanusTokenizer.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/JanusForMultiModalTestSpec.scala
Labels: new-feature, DON'T MERGE

#14533 Improved Error Handling for AutoGGUF models
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_MPNetForQuestionAnswering.ipynb
  examples/python/transformers/onnx/HuggingFace_ONNX_in_Spark_NLP_XlmRoBertaSentenceEmbeddings.ipynb
Labels: bug-fix

#14537 2025-03-25-janus_1_3b_int4_en
  docs/_posts/prabod/2025-03-25-janus_1_3b_int4_en.md
Labels: new model
