Repository JohnSnowLabs/spark-nlp, pull requests merged in 2025-05, with the labels that each got.

#14552 Sparknlp 1115 Introducing SmolVLM
  docs/en/transformer_entries/JanusForMultiModal.md
  docs/en/transformer_entries/SmolVLMTransformer.md
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_SmolVLMTransformer.ipynb
  python/sparknlp/annotator/cv/__init__.py
  python/sparknlp/annotator/cv/smolvlm_transformer.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/cv/smolvlm_transformer_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/SmolVLM.scala
  src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/HasImageFeatureProperties.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/SmolVLMTransformer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/feature_extractor/Preprocessor.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/util/transform/SmolVLMUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/SmolVLMTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/SmolVLMTransformerTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/util/transform/SmolVLMUtilsTest.scala
Labels: on-hold, new-feature, DON'T MERGE

#14551 SparkNLP 1121 Introducing PaliGemma
  docs/en/transformer_entries/PaliGemmaForMultiModal.md
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_PaliGemmaForMultiModal.ipynb
  python/sparknlp/annotator/cv/__init__.py
  python/sparknlp/annotator/cv/paligemma_for_multimodal.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/cv/paligemma_for_multimodal_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/PaliGemma.scala
  src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/PaliGemmaForMultiModal.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/PaliGemmaTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/PaliGemmaForMultimodalTestSpec.scala
Labels: on-hold, new-feature, new model, DON'T MERGE

#14550 2025-04-11-smolvlm_instruct_int4_en
  docs/_posts/prabod/2025-04-11-smolvlm_instruct_int4_en.md
  docs/_posts/prabod/2025-04-14-paligemma_3b_pt_224_int4_en.md
  docs/_posts/prabod/2025-04-15-paligemma2_3b_mix_224_int4_en.md
  docs/_posts/prabod/2025-04-15-paligemma2_3b_pt_448_int4_en.md
  docs/_posts/prabod/2025-04-15-paligemma_3b_ft_vqav2_448_int4_en.md
  docs/_posts/prabod/2025-04-15-paligemma_3b_pt_224_int4_en.md
  docs/_posts/prabod/2025-04-28-gemma_3_4b_it_int4_en.md
  docs/_posts/prabod/2025-04-28-gemma_3_4b_pt_int4_en.md
Labels: new model

#14578 SparkNLP - 1123 Introducing InternVL
  docs/en/transformer_entries/InternVLForMultiModal.md
  examples/python/transformers/openvino/HuggingFace_OpenVINO_in_Spark_NLP_InternVLForMultiModal.ipynb
  python/sparknlp/annotator/cv/__init__.py
  python/sparknlp/annotator/cv/internvl_for_multimodal.py
  python/sparknlp/internal/__init__.py
  python/test/annotator/cv/internvl_for_multimodal_test.py
  src/main/scala/com/johnsnowlabs/ml/ai/InternVL.scala
  src/main/scala/com/johnsnowlabs/ml/openvino/OpenvinoWrapper.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/InternVLForMultiModal.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/cv/util/transform/InternVLUtils.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/BpeTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/annotators/tokenizer/bpe/InternVLTokenizer.scala
  src/main/scala/com/johnsnowlabs/nlp/pretrained/ResourceDownloader.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/InternVLForMultiModalTestSpec.scala
  src/test/scala/com/johnsnowlabs/nlp/annotators/cv/feature_extractor/InternVLUtilsTestSpec.scala
Labels: new-feature

#14581 Documentation for SparkNLP Readers and Partition class
  conda/meta.yaml
  python/docs/reference/index.rst
  python/sparknlp/partition/__init__.py
  python/sparknlp/partition/partition.py
  python/sparknlp/partition/partition_transformer.py
  python/sparknlp/reader/pdf_to_text.py
  python/sparknlp/reader/sparknlp_reader.py
  src/main/scala/com/johnsnowlabs/partition/Partition.scala
  src/main/scala/com/johnsnowlabs/partition/PartitionTransformer.scala
  src/main/scala/com/johnsnowlabs/reader/EmailReader.scala
  src/main/scala/com/johnsnowlabs/reader/ExcelReader.scala
  src/main/scala/com/johnsnowlabs/reader/HTMLReader.scala
  src/main/scala/com/johnsnowlabs/reader/PdfToText.scala
  src/main/scala/com/johnsnowlabs/reader/PowerPointReader.scala
  src/main/scala/com/johnsnowlabs/reader/SparkNLPReader.scala
  src/main/scala/com/johnsnowlabs/reader/TextReader.scala
  src/main/scala/com/johnsnowlabs/reader/WordReader.scala
Labels: documentation, DON'T MERGE
